### ISSUE TITLE
prepare_model_for_training() should work for existing PeFT/LoRA models for further finetuning

### ISSUE THREAD

**Issue by minimaxir** [huggingface/peft#102]
I see that a new utility function `prepare_model_for_training()` was added, however this won't work for previously trained LoRA models for two reasons:

1. The LoRA adapters will be frozen as well (fixable by adding a `if 'lora' not in name` conditional to the param freezing)
2. PEFT adds an extra wrapper around the model, so additional getters are needed for things like the `LayerNorm`.

On my own testing I can confirm further finetuning does work after these are down.

**Comment by pacman100** [comment]
Hello, `prepare_model_for_training ` is only for training with PEFt-LoRA + INT8 as explained below and it is before converting the model to PeftModel. A b
<img width="1002" alt="Screenshot 2023-02-17 at 8 20 23 AM" src="https://user-images.githubusercontent.com/13534540/219537643-9abaabd8-d042-47cb-b54f-b744e87b370e.png">
etter name would help in avoiding confusion, @younesbelkada could we change the function name to have `intt8` to help avoid confusion?

**Comment by younesbelkada** [comment]
Thanks for the feedback @minimaxir !
In https://github.com/huggingface/peft/pull/105 we have updated the name of the method to avoid confusion

**Comment by minimaxir** [comment]
The current implementation of `prepare_model_for_int8_training()` now works for further finetuning, so all good on my end.
