### ISSUE TITLE
using peft with autogptq and gpt2 model causes "RuntimeError: self and mat2 must have the same dtype"

### ISSUE THREAD

**Issue by drimeF0** [huggingface/peft#1026]
### System Info

Python 3.10.12
transformers 4.34.0
triton 2.0.0
torch 2.0.1+cu118
peft 0.5.0
auto-gptq 0.4.2

ubuntu from google colab 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

https://colab.research.google.com/drive/1pHeX2w4ksYSPu6fHF1IqVjRednYThCJI

### Expected behavior

I expected to work without errors, however, instead I get an error related to dtype

**Comment by BenjaminBossan** [comment]
Just to give you an update, I can reproduce the error and I'm looking into it. My current understanding is that what happens is that PEFT does not recognize the model to be a GPTQ-quantized model and treats it as a vanilla PyTorch model, which results in the wrong layer type being used, which in turn results in the error.
