### ISSUE TITLE
'PeftModelForCausalLM' object has no attribute 'merge_and_unload' when attempting to merge (BloomForCausalLM)

### ISSUE THREAD

**Issue by gmanlan** [huggingface/peft#1030]
### System Info

peft=0.3.0
accelerate=0.20.3
transformers=4.30.2
platform=debian.amd64
python=3.7.12

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### Tasks

- [x] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

The following minimum script shows a typical prompt tuning workflow based on bloomz-3b. At a later time, we attempt to merge the base model with the adapter but it fails with an error stating that 'merge_and_unload' doesn't exist. It doesn't matter if we attempt to merge_and_unload right after the fine-tuning or at a later time by re-loading the artifacts, the error is the same.
```
## ----------------------------------------
## ----- Fine-tuning (just for reference)
## ----------------------------------------

peft_config = PromptTuningConfig(
     task_type=TaskType.CAUSAL_LM,
     prompt_tuning_init=PromptTuningInit.TEXT,
     num_virtual_tokens=8,
     prompt_tuning_init_text="What is the sentiment of this text?",
     tokenizer_name_or_path="bigscience/bloomz-3b"
)
model = AutoModelForCausalLM.from_pretrained("bigscience/bloomz-3b")
model = get_peft_model(model, peft_config)
# -- Finetuning would happen here --
model.save_pretrained("my_finetuned_model")

## ---------------------------------------------------------------
## ----- Now attempting to merge base model with adapter
## ---------------------------------------------------------------

config = PeftConfig.from_pretrained('./my_finetuned_model/')

>> PeftConfig(peft_type='PROMPT_TUNING', base_model_name_or_path='bigscience/bloomz-3b', task_type='CAUSAL_LM', inference_mode=True)

model = AutoModelForCausalLM.from_pretrained(config.base_model_name_or_path)
model = PeftModel.from_pretrained(model, './my_finetuned_model')

model.eval()

merged_model = model.merge_and_unload()

>> AttributeError: 'PeftModelForCausalLM' object has no attribute 'merge_and_unload'
>> AttributeError: 'BloomForCausalLM' object has no attribute 'merge_and_unload'
```

### Expected behavior

I would expect merge_and_unload() to be a valid object attribute which can merge the base model with the prompt tuned adapter weights, as documented in various sources, including the official documentation: https://huggingface.co/docs/peft/package_reference/tuners#peft.LoraModel.merge_and_unload

**Comment by BenjaminBossan** [comment]
Hi, note that you say you want to use LoRA but you're actually using prompt-tuning.

**Comment by gmanlan** [comment]
Right. Prompt-tuning is being used to create an adapter to fine-tune the model. After that, the intention is to merge the prompt tuned model weights with the base model. I've assumed that PromptTuning and LoRA would be "equivalent" (both producing adapters at the end of the day) and hence I have expected merge_and_unload to work generically... If my understanding is incorrect... what's the method by which you get to merge the PromptTuned adapter with the base model so that you can deal with a single model artifact?

**Comment by BenjaminBossan** [comment]
Merging is not possible with prompt-tuning, which is why you got the error. You'd have to use LoRA or IA³ to get the ability to merge.

**Comment by gmanlan** [comment]
That's a useful piece of information! Hopefully this helps somebody else. Thanks @BenjaminBossan for your guidance.
