### ISSUE TITLE
Conv2d.forward() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by hoang1007** [huggingface/peft#1037]
### System Info

peft==0.6.0dev
diffusers==0.21.4

### Information

- [ ] The official example scripts
- [x] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

Sorry, but I don't know how to provide a simple code snippet because it's happend when I training diffusion. It require several steps like prepare data, training code...
```python
LORA_TARGET_MODULES = [
        "to_q",
        "to_k",
        "to_v",
        "proj",
        "proj_in",
        "proj_out",
        "conv",
        "conv1",
        "conv2",
        "conv_shortcut",
        "to_out.0",
        "time_emb_proj",
        "ff.net.2",
    ]

unet = get_peft_model(
  model=unet,
  peft_config=LoraConfig(
      target_modules=LORA_TARGET_MODULES,
  )
)
```

### Expected behavior

I think the reason is:
- ResnetBlock2D used in Unet module has conv1 layer as type `LoRACompatibleConv` and it take 2 arguments
![Screenshot from 2023-10-19 10-22-13](https://github.com/huggingface/peft/assets/78253878/8b942734-3949-417b-b27c-6e023d6f69b2)
- But when I passed unet into `get_peft_model()`. the conv1 layer has changed to type `peft.tuners.lora.layer.Conv2d` and it take only 1 argument
![Screenshot from 2023-10-19 10-25-52](https://github.com/huggingface/peft/assets/78253878/0c17a9cf-13c6-49c1-93fb-0c6a17a514a6)

**Comment by kovalexal** [comment]
@hoang1007 hi!

I faced the same issue and it is caused by the `LoRACompatibleConv` layer that was introduced in `diffusers>=0.21.0`.

See https://github.com/huggingface/peft/pull/916 https://github.com/huggingface/peft/issues/879 https://github.com/huggingface/peft/pull/937#issuecomment-1723141571 for more detail.

If you downgrade your diffusers version to `diffusers<0.21.0"` everything should work fine.

**Comment by hoang1007** [comment]
Okei, thank u

**Comment by Xynonners** [comment]
> As far as I can tell, the fix is on their to-do list [#937 (comment)](https://github.com/huggingface/peft/pull/937#issuecomment-1723159367) #936

Hi, after installing diffusers upstream the mentioned issue was fixed, but now I seem to be getting a different issue also related to diffusers>0.21.0.

```
  File "/vol/zraid1/Projects/AI/Self/mofusp/mofusp/new/UpDraft/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return self._call_impl(*args, **kwargs)
           ^^^    return forward_call(*args, **kwargs)
^^^ ^   ^  ^   ^  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^  File "/vol/zraid1/Projects/AI/Self/mofusp/mofusp/new/UpDraft/venv/lib/python3.11/site-packages/peft/peft_model.py", line 488, in forward
^^^^^^^^^
  File "/vol/zraid1/Projects/AI/Self/mofusp/mofusp/new/UpDraft/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return self.get_base_model()(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^    ^^return forward_call(*args, **kwargs)^^^
^^^
  File "/vol/zraid1/Projects/AI/Self/mofusp/mofusp/new/UpDraft/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/vol/zraid1/Projects/AI/Self/mofusp/mofusp/new/UpDraft/venv/lib/python3.11/site-packages/peft/peft_model.py", line 488, in forward
return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/vol/zraid1/Projects/AI/Self/mofusp/mofusp/new/UpDraft/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return self.get_base_model()(*args, **kwargs)
           ^^^^    return forward_call(*args, **kwargs)^
^^ ^  ^  ^  ^   ^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^  File "/vol/zraid1/Projects/AI/Self/mofusp/mofusp/new/UpDraft/venv/lib/python3.11/site-packages/diffusers/models/unet_2d_condition.py", line 1158, in forward
^^^^^^^^^^^^^^^
  File "/vol/zraid1/Projects/AI/Self/mofusp/mofusp/new/UpDraft/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    unscale_lora_layers(self, lora_scale)
    return self._call_impl(*args, **kwargs)
  File "/vol/zraid1/Projects/AI/Self/mofusp/mofusp/new/UpDraft/venv/lib/python3.11/site-packages/diffusers/utils/peft_utils.py", line 112, in unscale_lora_layers
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/vol/zraid1/Projects/AI/Self/mofusp/mofusp/new/UpDraft/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
          module.unscale_layer(weight)
     TypeError: ^LoHaLayer.unscale_layer() takes 1 positional argument but 2 were given^
```

**Comment by kovalexal** [comment]
@Xynonners hi! Thanks for bringing this up!

As far as I can tell, this issue may be related to the recent changes in diffusers+peft compatibility (#1029,  #1034).

I have a PR for the LoKr adapter #978 (but it is not in the upstream right now) and it also should fix the LoHa adapter with my recent changes https://github.com/huggingface/peft/pull/978#discussion_r1371856547 (as they share a lot of common code).

While we are almost at the finish line with this PR, could you please try out the version from PR #978?

**Comment by Xynonners** [comment]
> @Xynonners hi! Thanks for bringing this up!
> 
> As far as I can tell, this issue may be related to the recent changes in diffusers+peft compatibility (#1029, #1034).
> 
> I have a PR for the LoKr adapter #978 (but it is not in the upstream right now) and it also should fix the LoHa adapter with my recent changes [#978 (comment)](https://github.com/huggingface/peft/pull/978#discussion_r1371856547) (as they share a lot of common code).
> 
> While we are almost at the finish line with this PR, could you please try out the version from PR #978?

Alrighty, tested and it seems to work. Waiting for merge now :grin:

**Comment by kovalexal** [comment]
Hmmm, that seems strange.

Are you still using the latest version from #978 PR?

According to [that code](https://github.com/huggingface/peft/blob/f6e73352197d309382b964c28fa764d8caec2a2f/src/peft/tuners/lycoris_utils.py#L175C9-L175C9), `unscale_layer` should accept 2 arguments - the first one is `self` and the second one is `scale`.

Here is also a small code that demonstrates that we are able to pass scale value to `unscale_layer` layers in #978 branch:

```python
import torch
from peft.tuners.loha.model import Linear

lin = Linear(
    in_features=10, out_features=10, bias=False,
    device="cpu", dtype=torch.float32, r=4, alpha=4, adapter_name="default"
)


lin.scale_layer(2.0)
lin.unscale_layer(2.0)
```

I am not sure, maybe there are some missing parts in diffusers + peft integration for LoHa adapters, do you happen to have some code snippet + library versions you are using for me to investigate what is happening here?

**Comment by Xynonners** [comment]
> Hmmm, that seems strange.
> 
> Are you still using the latest version from #978 PR?
> 
> According to [that code](https://github.com/huggingface/peft/blob/f6e73352197d309382b964c28fa764d8caec2a2f/src/peft/tuners/lycoris_utils.py#L175C9-L175C9), `unscale_layer` should accept 2 arguments - the first one is `self` and the second one is `scale`.
> 
> Here is also a small code that demonstrates that we are able to pass scale value to `unscale_layer` layers in #978 branch:
> 
> ```python
> import torch
> from peft.tuners.loha.model import Linear
> 
> lin = Linear(
>     in_features=10, out_features=10, bias=False,
>     device="cpu", dtype=torch.float32, r=4, alpha=4, adapter_name="default"
> )
> 
> 
> lin.scale_layer(2.0)
> lin.unscale_layer(2.0)
> ```
> 
> I am not sure, maybe there are some missing parts in diffusers + peft integration for LoHa adapters, do you happen to have some code snippet + library versions you are using for me to investigate what is happening here?

ah sorry, it seems like the pip cache was screwing with the install from git+, checked the site-packages and it was missing stuff.

updated correctly this time and it works :+1:
