### ISSUE TITLE
Add VeRA (Vector Based Random Matrix Adaption)

### ISSUE THREAD

**Issue by vvvm23** [huggingface/peft#1038]
### Feature request

A recent paper by Qualcomm AI Research proposed a new parameter efficient finetuning method called VeRA. This uses two projection matrices (as in LoRA) that are randomly initialised, frozen, and shared between all layers. Two scaling vectors are created and are trained. This reduces the number of training parameters while offering comparable results to LoRA.
![image](https://github.com/huggingface/peft/assets/44398246/6e3c093d-e99e-4d6b-ba15-95647e05b9a8)

### Motivation

The method is similar to LoRA and offers comparable performance with less trainable parameters, particularly for large rank adaption. In addition, the projection matrices do not need to be saved as they can be regenerated by storing the PRNG key. Overall, I think these properties would make this method useful to the community.

![image](https://github.com/huggingface/peft/assets/44398246/1ea20890-a36a-4136-b41e-864f9cea2e10)

### Your contribution

I would be happy to contribute code for this. The authors have not made their code available, however the method is similar enough to LoRA that this shouldn't be an issue.

One caveat is that this method has not been peer-reviewed or verified by the community yet. I'm in the process of trying it myself. If the method turns out to not work as well as reported, then it should not be integrated into `peft`.

Thanks :hugs:

**Comment by BenjaminBossan** [comment]
_not stale :)_

**Comment by mehrdad-es** [comment]
@vvvm23 have you been able to test out the performance of VERA?
