### ISSUE TITLE
Multiple Adapters merging question

### ISSUE THREAD

**Issue by AlbertoZerbinati** [huggingface/peft#1040]
### Feature request

I'm experimenting with merging multiple different Lora adapters into a single model.

This is the code I'm using:
```python
# load the model
model = AutoModelForCausalLM.from_pretrained(
    "model_path",
    device_map="auto",
    torch_dtype=torch.float16,
)

# apply and merge adapter 1
model = PeftModel.from_pretrained(
    model,
    "adapter_1_path",
    torch_dtype=torch.float16,
)
model = model.merge_and_unload()

# apply and merge adapter 2
model = PeftModel.from_pretrained(
    model,
    "adapter_2_path",
    torch_dtype=torch.float16,
)
model = model.merge_and_unload()
```
The two adapters were obtained via fine-tuning with `peft`.
`adapter 1` was obtained by fine-tuning `model 1`, while `adapter 2` was obtained by fine-tuning `model + adapter 1`.

My approach seems to be working, in the sense that there are no execution errors, the model seems to behave correctly, and `model + adapter 1 + adapter 2` performs better than `model + adapter 1` according to some metrics I'm using.

What sparked the question is that the code above generates the following INFO message:
```
INFO:peft.tuners.tuners_utils:Already found a `peft_config` attribute in the model. This will lead to having multiple adapters in the model. Make sure to know what you are doing!
```

So I'd like to ask: is this the proper way to merge multiple Lora adapters into the same model? Is there a reference to follow? I didn't find one.

### Motivation

I think there's potential in merging multiple Lora adapters, for instance adding two distinct, independent behaviors to a base model...
I'm curious to know if there's a recommended way of doing it.

### Your contribution

See code above.

**Comment by LuciferianInk** [comment]
The `PeftModel` class does have a method called `add_weighted_adapter()`, which is apparently used for merging adapters: https://huggingface.co/docs/peft/main/en/package_reference/tuners#peft.LoraModel.add_weighted_adapter

That said, I've been unable to use it, and [I'm here to report a similar issue as yours](https://github.com/huggingface/peft/issues/1045).

I suspect adapter merging is unsupported and/or in early development right now, since it doesn't appear to be well-documented anywhere. "adapter-transformers" does, apparently, support "adapter fusion", but I've never used it, and I'm hoping it will come to PEFT at some point.

**Comment by BenjaminBossan** [comment]
As @LuciferianInk mentions, using [`add_weighted_adapter`](https://huggingface.co/docs/peft/main/en/package_reference/tuners#peft.LoraModel.add_weighted_adapter) is the direct way to go, as it gives you more control about how to merge the adapters. There is indeed a bug on `main` right now but it should be fixed very soon.

The approach described by @AlbertoZerbinati should also work as long as the adapters have the same rank and you're fine with both adapters being assigned the same weight.

**Comment by beingdutta** [comment]
> As @LuciferianInk mentions, using [`add_weighted_adapter`](https://huggingface.co/docs/peft/main/en/package_reference/tuners#peft.LoraModel.add_weighted_adapter) is the direct way to go, as it gives you more control about how to merge the adapters. There is indeed a bug on `main` right now but it should be fixed very soon.
> 
> The approach described by [@AlbertoZerbinati](https://github.com/AlbertoZerbinati) should also work as long as the adapters have the same rank and you're fine with both adapters being assigned the same weight.

I can't see any such method, `add_weighted_adapter()`, in the docs. Is it deprecated?

**Comment by BenjaminBossan** [comment]
> I can't see any such method, `add_weighted_adapter()`, in the docs. Is it deprecated?

It's here: https://huggingface.co/docs/peft/v0.18.0/en/package_reference/lora#peft.LoraModel.add_weighted_adapter
