### ISSUE TITLE
Peft is not working with stabilityai/stablelm-3b-4e1t

### ISSUE THREAD

**Issue by apcameron** [huggingface/peft#1044]
### System Info

pip install git+https://github.com/huggingface/peft.git

Finethining fails with

-------

<pre> File &quot;/home/andrew/Downloads/finetune/env/lib/python3.11/site-packages/trl/trainer/sft_trainer.py&quot;, line 143, in __init__
    model = get_peft_model(model, peft_config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File &quot;/home/andrew/Downloads/finetune/env/lib/python3.11/site-packages/peft/mapping.py&quot;, line 108, in get_peft_model
    return MODEL_TYPE_TO_PEFT_MODEL_MAPPING[peft_config.task_type](model, peft_config, adapter_name=adapter_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File &quot;/home/andrew/Downloads/finetune/env/lib/python3.11/site-packages/peft/peft_model.py&quot;, line 916, in __init__
    super().__init__(model, peft_config, adapter_name)
  File &quot;/home/andrew/Downloads/finetune/env/lib/python3.11/site-packages/peft/peft_model.py&quot;, line 116, in __init__
    self.base_model = cls(model, {adapter_name: peft_config}, adapter_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File &quot;/home/andrew/Downloads/finetune/env/lib/python3.11/site-packages/peft/tuners/lora/model.py&quot;, line 110, in __init__
    super().__init__(model, config, adapter_name)
  File &quot;/home/andrew/Downloads/finetune/env/lib/python3.11/site-packages/peft/tuners/tuners_utils.py&quot;, line 90, in __init__
    self.inject_adapter(self.model, adapter_name)
  File &quot;/home/andrew/Downloads/finetune/env/lib/python3.11/site-packages/peft/tuners/tuners_utils.py&quot;, line 214, in inject_adapter
    peft_config = self._prepare_adapter_config(peft_config, model_config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File &quot;/home/andrew/Downloads/finetune/env/lib/python3.11/site-packages/peft/tuners/lora/model.py&quot;, line 386, in _prepare_adapter_config
    raise ValueError(&quot;Please specify `target_modules` in `peft_config`&quot;)
ValueError: Please specify `target_modules` in `peft_config`
</pre>

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

Finetune a Stabilityai based model using peft

### Expected behavior

Finetuning does not fail with a message from peft.

**Comment by BenjaminBossan** [comment]
As the error message suggests, you have to specify the `target_modules` argument in the config. For some models, we have a [predefined list](https://github.com/huggingface/peft/blob/56556faa17263be8ef1802c172141705b71c28dc/src/peft/utils/other.py#L406) of these target layers, but StableLM has not been added yet. Assuming you want to use LoRA, you probably want to target the `q` and `v` layers, possibly also `k`. Check their names in the StableLM module (e.g. using `[key for key, _ in model.named_parameters()]`) and add them to the `target_modules` argument.

**Comment by apcameron** [comment]
Thank you. I have added
target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],

**Comment by BenjaminBossan** [comment]
Great. Good luck training. If you run into any more issues, feel free to re-open.
