### ISSUE TITLE
RuntimeError: "svd_cuda_gesvdj" not implemented for 'BFloat16'

### ISSUE THREAD

**Issue by LuciferianInk** [huggingface/peft#1052]
### System Info

- `transformers` version: 4.34.0
- Platform: Linux-6.5.6-arch2-1-x86_64-with-glibc2.35
- Python version: 3.10.12
- Huggingface_hub version: 0.17.3
- Safetensors version: 0.4.0
- Accelerate version: 0.23.0
- Accelerate config:    not found
- PyTorch version (GPU?): 2.1.0+cu121 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: False
- Using distributed or parallel set-up in script?: False

### Who can help?

@pacman100 @younesbelkada 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

Simply load the PeftModel class in half precision (BFloat16), and try to use `model.add_weighted_adapter()` with the 'svd' `combination_type`. It will fail with the following error:
```
vtx-lab-1   | Traceback (most recent call last):
vtx-lab-1   |   File "/src/lab/aigen/aigen/aigen.py", line 220, in __init__
vtx-lab-1   |     self.model.add_weighted_adapter(
vtx-lab-1   |   File "/usr/local/lib/python3.10/dist-packages/peft/tuners/lora/model.py", line 586, in add_weighted_adapter
vtx-lab-1   |     target_lora_A.data, target_lora_B.data = self._svd_weighted_adapter(
vtx-lab-1   |   File "/usr/local/lib/python3.10/dist-packages/peft/tuners/lora/model.py", line 635, in _svd_weighted_adapter
vtx-lab-1   |     U, S, Vh = torch.linalg.svd(delta_weight, full_matrices=full_matrices, driver=driver)
vtx-lab-1   | RuntimeError: "svd_cuda_gesvdj" not implemented for 'BFloat16'
```
None of the other `svd_driver`s work either.

### Expected behavior

Given that the entire purpose of this library is to reduce memory consumption, it seems strange that half precision (BFloat16) would be unsupported in the `model.add_weighted_adapter()` method. I'm sure this is tricky to implement, and I am in no rush; the "cat" `combination_type` works fine for my needs, today. Just putting this here for posterity.

**Comment by BenjaminBossan** [comment]
Since we rely on `torch.linalg.svd` and it doesn't support bf16 (nor fp16), there isn't much we can do here short of writing our own SVD function. Maybe SVD support for half precision is a feature you could raise with the PyTorch devs.
