### ISSUE TITLE
Fine tune models in the exl2 format

### ISSUE THREAD

**Issue by psych0v0yager** [huggingface/peft#1055]
### Feature request

This request is based on the following colab https://colab.research.google.com/drive/1_TIrmuKOFhuRRiTWN94iLKUFu6ZX4ceb?usp=sharing#scrollTo=RkU58PaRjMXC and following pages in the docs https://huggingface.co/docs/transformers/main_classes/quantization

Specifically huggingface offers a way to finetune a GPTQ model with the GPTQ config. You are able to use exllama as a backend if you want to run inference.

However, exllamav2 was released recently and uses the new exl2 format. This format has several advantages over GPTQ. In addition, there have been some perplexity issues using GPTQ with exllamav2 shown in the following reddit post https://www.reddit.com/r/LocalLLaMA/comments/16i6a83/we_should_use_exllama1_for_gptq_and_exllama2_for/. The reddit post is 1 month old, and the issue may have been fixed already; regardless the exl2 format is considered an upgrade over GPTQ

The requested feature would be: an EXL2Config class that allows us to fine tune an exl2 model using PEFT.

### Motivation

Provide finetuning support for the new exl2 format. This should provide better performance with exllamav2.

### Your contribution

I do not have too much experience in backend work, but I am willing to learn if needed.

**Comment by younesbelkada** [comment]
cc @SunMarc what do you think about this?

**Comment by SunMarc** [comment]
Hi @psych0v0yager, we've haven't added yet the exl2 format since it is still in development. 
If you are looking for inference speed, I would recommend you looking at AWQ with fused modules. If you are thinking about finetuning, I would recommend QLORA.
