### ISSUE TITLE
For a multi-adapter model save_pretrained saves all adapters, from_pretrained only loads one

### ISSUE THREAD

**Issue by denizyuret** [huggingface/peft#1059]
When save_pretrained is called on a multi-adapter model it saves all the adapters.
When from_pretrained is called on the resulting directory, only the default adapter is loaded.
Is there a recommended way to get back the same multi-adapter model when loading?

**Comment by younesbelkada** [comment]
I think for now you need to load them one by one, we could definitely enhance the `from_pretrained` method by adding a flag to load multi-adapters

**Comment by denizyuret** [comment]
I think it would be consistent for save and load to be compatible in this sense. On the other hand I see that there is no record that contains the list of adapters a model has -- each adapter is saved independently in its own directory and their config file only knows about that one adapter. Are you thinking of putting all the adapter names in a config.json, or do a directory search for all adapter_config.json files?

**Comment by denizyuret** [comment]
With the new `PeftAdapterMixin`, the situation is has become a bit more inconsistent: `save_pretrained` saves multiple adapters in their own directories with a `PeftModel`, but only a single (active) adapter in the root directory with a model with `PeftAdapterMixin`. There is still no standard way to load the model back with multiple adapters.
