### ISSUE TITLE
Clarifications on merge_and_unload() as well as load_adapter() and add_adapter().

### ISSUE THREAD

**Issue by yousenwang** [huggingface/peft#1064]
I fine-tuned two PeftModel using LoraConfig on two different datasets.

What should I do to achieve the incremental effect?

Case 1:

```py
base_model.load_adapter("./my_first_peft_model_local_path")
## and then 
base_model.add_adapter("./my_second_peft_model_local_path")
```
Is case 1 not what I want since it seems like `set_adapter()` can switch back and forth from one adapter to another (without reloading the based model)?

OR

Case 2
```py
base_model.load_adapter("./my_first_peft_model_local_path")

merged_model = base_model.merge_and_unload() 
## why do we need unload() after merge() changes the weights of the based model?

merged_model.load_adapter("./my_second_peft_model_local_path")
```
why do we need unload() after merge() changes the weights of the based model?

Is it possible to unmerge()?

Thank you for clarifying for me.

### Reference

https://huggingface.co/docs/transformers/main/peft#load-a-peft-adapter
https://huggingface.co/docs/peft/package_reference/tuners#peft.LoraModel.merge_and_unload
https://huggingface.co/docs/peft/conceptual_guides/lora

**Comment by BenjaminBossan** [comment]
> What should I do to achieve the incremental effect?

IIUC, what you want is for the two adapters to be active at the same time, is that right?

In that case, as you mention, method 1 does not work. Method 2 can work (your code is not quite complete), but as you wrote, after `merge_and_unload`, it is no longer possible to unmerge.

There is another method, although it is not yet documented and it requires the latest PEFT: You can set multiple active adapters at once (at least for LoRA). It would work like this:

```python
# load the first adapter, which is called "default" by default
model = PeftModel.from_pretrained(<path-to-first-adapter>)
# load the second adapter, let's call it "other"
model.load_adapter(<path-to-second-adapter>, adapter_name="other")
# make both adapters active at the same time
model.base_model.set_adapter(["default", "other"])
```

We will have to document this better, for now it's a kind of "hidden" feature. Let us know if it works or if you run into any issues.

**Comment by dwraco** [comment]
Somewhat related to this topic, can someone please explain the behavior of merge_and_unload() when multiple adapters are loaded? Does it just merge in the active adapter and leave the rest of the adapters alone? Does it merge in all the loaded adapters? Does it merge in just the active adapter and then unloads all the other adapters without merging them?

Let's say I had the following code:
```
model = PeftModelForCausalLM.from_pretrained(model, main_lora, adapter_name=main_lora, **device_arg)
for lora in ['secondary_lora', 'tertiary_lora']:
    model.load_adapter(lora, adapter_name=f"{lora}")

model.set_adapter(main_lora)
model = model.merge_and_unload()
```

What happens to the other adapters, 'secondary_lora' and 'tertiary_lora?' Can I follow up the initial merge with a section of code like the one below to merge in the other two adapters?

```
model.set_adapter("secondary_lora")
model = model.merge_and_unload()
model.set_adapter("tertiary_lora")
model = model.merge_and_unload()
```

Or do I need to load them up again?

```
model = PeftModelForCausalLM.from_pretrained(model, "secondary_lora", adapter_name="secondary_lora", **device_arg)
model = model.merge_and_unload()
model = PeftModelForCausalLM.from_pretrained(model, "tertiary_lora", adapter_name="tertiary_lora", **device_arg)
model = model.merge_and_unload()
```

Thank you for any guidance you can provide here.

**Comment by younesbelkada** [comment]
Currently it will indeed merge only active adapters, I believe you need to load them up again as `merge_and_unload()` will also unload the peft model.
In https://github.com/huggingface/peft/pull/1132 I am working on a feature where you can specify the list of adapters you want to merge

**Comment by dwraco** [comment]
Thanks, younesbelkada! I appreciate your answer and the work you're doing on that pull request.

**Comment by younesbelkada** [comment]
Thanks very much @dwraco !

**Comment by younesbelkada** [comment]
Closing as #1132 has been merged, feel free to re-open the issue or create a new one if you think that's not the case
