### ISSUE TITLE
Huge performance hit adding in a LoRA 

### ISSUE THREAD

**Issue by praguepride** [huggingface/peft#1067]
### System Info

I am running BLIP-2 on an AWS CPU ECS instance: (16 vGPU, 64 GB of ram). Having BLIP-2 caption images comes out to about 1 image every 3 seconds given the code I am running.

I was able to train a LoRA very quickly however when I run this section of code (taken from the sample google colab): 

https://github.com/huggingface/notebooks/blob/main/peft/Fine_tune_BLIP2_on_an_image_captioning_dataset_PEFT.ipynb
```

from transformers import Blip2ForConditionalGeneration, AutoProcessor
from peft import PeftModel, PeftConfig

device = "cuda" if torch.cuda.is_available() else "cpu"

peft_model_id = "path/to/my/lora/folder"
config = PeftConfig.from_pretrained(peft_model_id)

model = Blip2ForConditionalGeneration.from_pretrained(config.base_model_name_or_path, device_map="auto")
model = PeftModel.from_pretrained(model, peft_model_id)

processor = AutoProcessor.from_pretrained("Salesforce/blip2-opt-2.7b")
```
     
The model performance goes from 3sec per image to 1 minute per image. I have tested this out on other larger AWS machines and I still see this huge decrease in performance.

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

Run a BLIP-2 caption for ~50 images and then test adding in a LoRA does to that same throughput.

### Expected behavior

A LoRA should have minimal impact on processing time, right?

**Comment by BenjaminBossan** [comment]
Thanks for reporting. Could you please monitor your available memory? One suspicion is that since `device_map="auto"` is being used, some weights are offloaded to CPU or disk, making the whole inference process using the newly loaded model much slower. If you run the inference in the same notebook, it could be that some earlier memory is not freed. So using the same code in a completely new process would be a possible solution if memory is indeed the issue.

**Comment by younesbelkada** [comment]
Note also that you are running your model in full-precision according to your script. Loading your model in half-precision + as @BenjaminBossan stated forcing the model to be on GPU could probably help.

```diff
+ import torch
from transformers import Blip2ForConditionalGeneration, AutoProcessor
from peft import PeftModel, PeftConfig

device = "cuda" if torch.cuda.is_available() else "cpu"

peft_model_id = "path/to/my/lora/folder"
config = PeftConfig.from_pretrained(peft_model_id)

- model = Blip2ForConditionalGeneration.from_pretrained(config.base_model_name_or_path, device_map="auto")
+ model = Blip2ForConditionalGeneration.from_pretrained(config.base_model_name_or_path, device_map={"" : 0}, torch_dtype=torch.float16)
model = PeftModel.from_pretrained(model, peft_model_id)

processor = AutoProcessor.from_pretrained("Salesforce/blip2-opt-2.7b")
```

`device_map={"" : 0}` simply means to put the entire model on the GPU0.
You could also consider merging the adapter weights into your model, please refer to my message here: https://huggingface.co/Salesforce/codegen2-7B/discussions/1#6543f4eb2996405c23882b03 for more details
