### ISSUE TITLE
Add docs on how to merge adapters after 4bit QLoRA with PEFT 0.6

### ISSUE THREAD

**Issue by geronimi73** [huggingface/peft#1080]
### Feature request

there has been some controversy on how to correctly **merge the adapters with the base model after 4bit LoRA** training. 

to me it seems there are two ways to merge and save:

- ChrisHayduk https://gist.github.com/ChrisHayduk/1a53463331f52dca205e55982baf9930
- TheBloke https://github.com/TheBlokeAI/AIScripts/blob/main/merge_peft_adapters.py

What is the correct way to merge the adapters now (with PEFT 0.6 and [PR 851](https://github.com/huggingface/peft/pull/851) merged) after training a 4-bit quantized model ?

### Motivation

no docs, at least i haven't found any

### Your contribution

example:

**quantize and train**
```
modelpath="models/Mistral-7B-v0.1"

model = AutoModelForCausalLM.from_pretrained(
    modelpath,    
    load_in_4bit=True,
    quantization_config=BitsAndBytesConfig(
        load_in_4bit=True,
        llm_int8_threshold=6.0,
        llm_int8_has_fp16_weight=False,
        bnb_4bit_compute_dtype=torch.bfloat16,
        bnb_4bit_use_double_quant=True,
        bnb_4bit_quant_type="nf4",
    ),
    torch_dtype=torch.bfloat16,
)

model = prepare_model_for_kbit_training(model)
config = LoraConfig(
    r=64, 
    lora_alpha=16, 
    target_modules =
        ['q_proj', 
        'k_proj', 
        'down_proj', 
        'v_proj', 
        'gate_proj', 
        'o_proj', 
        'up_proj'],
    lora_dropout=0.1, 
    bias="none", 
    task_type="CAUSAL_LM"
)
model = get_peft_model(model, config)

train ...
```

**merge and save** 
```
base_model = AutoModelForCausalLM.from_pretrained(
    "models/Mistral-7B-v0.1",
    return_dict=True,
    torch_dtype=torch.bfloat16,
)

model = PeftModel.from_pretrained(base_model, "some-checkpoint")
model = model.merge_and_unload()

model.save_pretrained(args.out, safe_serialization=True)
```

is this the proper way to do it? if yes/no, it would be nice to have this documented somwhere! 🤗

**Comment by BenjaminBossan** [comment]
In general, the code you posted looks good, if you run into any trouble, let us know.

I haven't read the full sources, what is the "controversy" about merging? AFAICT, both scripts use `merge_and_unload`, which is also mentioned in the [docs](https://huggingface.co/docs/peft/v0.6.0/en/conceptual_guides/lora#merge-lora-weights-into-the-base-model). Let us know what is unclear to you, so that we can improve the docs.

**Comment by geronimi73** [comment]
Thank you for your answer Benjamin!

Let me elaborate on what I meant by controversy.

The script by TheBloke does exactly what I posted above:
```
base_model = AutoModelForCausalLM.from_pretrained(..)
model = PeftModel.from_pretrained(..)
model = model.merge_and_unload(..)
```

The [other script](https://gist.github.com/ChrisHayduk/1a53463331f52dca205e55982baf9930#file-merge_qlora_with_quantized_model-py-L32) however **loads in 4bit** and then **dequantizes** and then merges:
```
model = LlamaForCausalLM.from_pretrained(load_in_4bit=True)
model = dequantize_model(..)
model = PeftModel.from_pretrained(..)
model = model.merge_and_unload(..)
```
which is also the way @TimDettmers [suggested](https://twitter.com/Tim_Dettmers/status/1695352747694919931) to do it, noting that "_I think I have seen a PR on PEFT, so this will soon come to PEFT by default, but for now, its better to merge it in this way._"

My question is: with PEFT 0.6, do we still need to `dequantize_model` before merging or was this taken care of?

**Comment by BenjaminBossan** [comment]
I see, thanks for explaining. The word "controversy" is a bit strong IMO ;) it's just two different approaches.

Yes, merging LoRA with 4bit models is now supported directly by PEFT thanks to #851 (use the latest PEFT release v0.6.0, which includes these changes). Tim's comment was from before the PR was merged. So the first suggestion should work fine.

**Comment by jaredquekjz** [comment]
Actually I am not sure it's really closed. Can I clarify - will the Peft library now auto-detect whether the training is on qLora and merge correctly a model in 4 bit to an adapter? In the above code - the model is loaded in torch.bfloat16 after all: ```base_model = AutoModelForCausalLM.from_pretrained(
    "models/Mistral-7B-v0.1",
    return_dict=True,
    torch_dtype=torch.bfloat16,
)

model = PeftModel.from_pretrained(base_model, "some-checkpoint")
model = model.merge_and_unload()

model.save_pretrained(args.out, safe_serialization=True)```
