### ISSUE TITLE
PEFT with quantized LLMa

### ISSUE THREAD

**Issue by Sai-Ashish** [huggingface/peft#1081]
### Feature request

I would like to inquire if prompt tuning feature is available with 4-bit quantized LLAMA-2 model.

### Motivation

4-bit quantization makes the models easy to use and hardware friendly. Can they be used along with prompt tuning using this library?

### Your contribution

I believe it should be compatible since full precision LLAMA-2 (CausalLM) is compatible with prompt-tuning.

**Comment by SumanthRH** [comment]
Not a maintainer, but I will chime in: Prompt tuning with 4-bit quantization should work! Prompt tuning simply modifies the input embeddings into the transformer, so all appropriate dtype casting necessary should happen. If you're interested, you can have a look at the exact changes for a causal LM [here](https://github.com/huggingface/peft/blob/cfe35a7878b44e017836f0b0c0c3b3e9e0cb738b/src/peft/peft_model.py#L1024C1-L1025C1). Locally, I'm able to run the [example notebook for causal language modelling](https://github.com/huggingface/peft/blob/main/examples/causal_language_modeling/peft_prompt_tuning_clm.ipynb) with 4-bit quantization enabled (just added `load_in_4bit=True` at init and `model = prepare_model_for_kbit_training(model)` before calling  `get_peft_model`).  The notebook uses BLOOMz-560M, but Llama-2 should also work.

**Comment by Sai-Ashish** [comment]
Thanks a lot for an elaborate answer @SumanthRH !
