### ISSUE TITLE
Error when loading Lora weights in example notebook.

### ISSUE THREAD

**Issue by kelsey-um** [huggingface/peft#1087]
### System Info

Running on Colab using T4 GPU but I've run into this issue aswell on a RTX4090 with other models. Using the example found in _examples/int8_training/Finetune_flan_t5_large_bnb_peft.ipynb_, specifically the cell where the adapters are loaded from the hub.

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

```
import torch
from peft import PeftModel, PeftConfig
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer

peft_model_id = "ybelkada/flan-t5-large-financial-phrasebank-lora"
config = PeftConfig.from_pretrained(peft_model_id)

model = AutoModelForSeq2SeqLM.from_pretrained(config.base_model_name_or_path, torch_dtype="auto", device_map="auto")
tokenizer = AutoTokenizer.from_pretrained(config.base_model_name_or_path)

# Load the Lora model
model = PeftModel.from_pretrained(model, peft_model_id)
```

Getting the following error:

```
TypeError                                 Traceback (most recent call last)
[<ipython-input-2-b64e9cbc4a96>](https://localhost:8080/#) in <cell line: 6>()
      4 
      5 peft_model_id = "ybelkada/flan-t5-large-financial-phrasebank-lora"
----> 6 config = PeftConfig.from_pretrained(peft_model_id)
      7 
      8 model = AutoModelForSeq2SeqLM.from_pretrained(config.base_model_name_or_path, torch_dtype="auto", device_map="auto")

[/usr/local/lib/python3.10/dist-packages/peft/config.py](https://localhost:8080/#) in from_pretrained(cls, pretrained_model_name_or_path, subfolder, **kwargs)
    132 
    133         kwargs = {**class_kwargs, **loaded_attributes}
--> 134         config = config_cls(**kwargs)
    135         return config
    136 

TypeError: LoraConfig.__init__() got an unexpected keyword argument 'enable_lora'
```

### Expected behavior

Model weights should load.

**Comment by BenjaminBossan** [comment]
Hi, this notebook is kinda old and the generated files stored on `https://huggingface.co/ybelkada/flan-t5-large-financial-phrasebank-lora` don't work anymore. However, if you run the notebook yourself and save the weights on your own Hugging Face repo or locally, it will work fine.

**Comment by BenjaminBossan** [comment]
There is no direct support for loading those old adapters. One thing you could do which may work: Download the repo to a  local folder, edit the `adapter_config.json` and remove the line `"enable_lora": null,`, then try to load the model from your local folder instead of from HF. If that works, you can create your own HF repo and upload the "fixed" version there for the future.

**Comment by kelsey-um** [comment]
This solved the issue. I also had to remove a few other parameters that were giving the same error. Thank you so much for your help! :)

**Comment by zchenyu** [comment]
+1 we ran into this issue as well. There are a lot of (old) adapters in the wild that still have this parameter. e.g. https://huggingface.co/hfl/chinese-llama-2-lora-7b/blob/main/adapter_config.json#L4
Would be great if we can make this a backwards compatible change

**Comment by OfficerChul** [comment]
https://huggingface.co/tloen/alpaca-lora-7b/discussions/8

The issue also has arisen from this repo, but it seems like it's not yet merged.
