### ISSUE TITLE
Possible issue with prompt tuning with left padding

### ISSUE THREAD

**Issue by SumanthRH** [huggingface/peft#1093]
### System Info

peft version 0.7.0

### Who can help?

@pacman100 @BenjaminBossan 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

I believe the current implementation for prompt tuning is suboptimal for causal language models, because of left padding. In the original paper from [Lester _et al_](https://arxiv.org/abs/2104.08691), prompt tuning is proposed as a method to prepend prompt tokens $P$ to an input $X$ to get the best performance for the task of generating $Y$. Note that the paper only implemented prompt tuning for seq2seq models, specifically for T5. Now with causal language models, you typically have a decoder-only architecture and thus left padding. For example, for the example notebook on prompt tuning for BLOOM (`examples/causal_language_modeling/peft_prompt_tuning_clm.ipynb`), here is how one input looks like: 

`<pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>Tweet text : Couples wallpaper, so cute. :) #BrothersAtHome Label : no complaint</s>`

The current prompt tuning code simply prepends prompt embeddings to the input sequence after padding, so this is equivalent to having something like: 

`Prompt<pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>Query`

This seems very sub-optimal. Also, this leads to a different kind of prompt conditioning for training time and test time inputs, so it might even be wrong. I was wondering if this has been investigated. I'm happy to take up benchmarking to see what performance you might get if you can somehow prepend the prompt embeddings after padding. I believe PEFT should atleast add a warning right now that prompt tuning with causal LM is not the same as prompt tuning with seq2seq. 

### Expected behavior

Prompt tokens should be prepended right before input query, or PEFT should atleast provide a warning that prompt tuning for causal LMs is suboptimal with padding.

**Comment by BenjaminBossan** [comment]
I haven't worked with prompt tuning yet, so only have theoretical knowledge. In general, the token ids are already padded when they are passed to the PEFT model, right? So we would have to identify the right place to inject the prompt tokens, thinking about edge cases like max token count.

I tried to jump into the debugger to where I thought this is happening and ran the decoder code but the debugger was not reached, so I think our tests don't even cover this case yet. If you have some idea how to work on this, it would be great. If the best feasible solution is a warning or an entry in the docs, that would also be fine.

**Comment by SumanthRH** [comment]
Yes, the token ids are already padded, so we'd need an ad-hoc implementation that needs to use padding token id (maybe passed through kwargs?) and then navigate to the first instance of a non-padding token for each sequence in the mini-batch. If PEFT is supporting prompt tuning in PeftModelForCausalLM, I feel like this is an important feature to have (almost zero chance that training is done without padded sequences). I'll see how this looks and make a PR. If it ends up being too ugly, then we can just add the warning.

**Comment by BenjaminBossan** [comment]
_not stale_
