### ISSUE TITLE
ValueError: Target module QuantLinear() is not supported.

### ISSUE THREAD

**Issue by manideep-paa** [huggingface/peft#1097]
### System Info

Hi,I was able to finetune a GPTQ model till 2 days back, but suddenly I have been getting the following error when executing the line: model = get_peft_model(model, config)
ERROR:
ValueError: Target module QuantLinear() is not supported. Currently, only the following modules are supported: `torch.nn.Linear`, `torch.nn.Embedding`, `torch.nn.Conv2d`, `transformers.pytorch_utils.Conv1D`.

platform: aws sagemaker
bitsandbytes: 0.41.0
torch:  2.1.0+cu121
peft:  0.6.0
transformers:  4.35.0
accelerate:  0.24.1
auto_gptq:  0.5.0
python: p310

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

```python
from peft import prepare_model_for_kbit_training
from transformers import AutoModelForCausalLM, AutoTokenizer, GPTQConfig,LlamaForCausalLM,LlamaTokenizer
model_id = "TheBloke/CodeLlama-7B-Instruct-GPTQ"

tokenizer = AutoTokenizer.from_pretrained(model_id,padding_side="left", add_eos_token= True,return_tensors="pt",use_auth_token ="...")
#tokenizer.pad_token = tokenizer.eos_token  # Llama has no pad token by default
tokenizer.pad_token = '[PAD]'

quantization_config_loading = GPTQConfig(bits=4, use_exllama=True)
model = AutoModelForCausalLM.from_pretrained(model_id,
                                             #load_in_4bit=True,
                                             quantization_config=quantization_config_loading,
                                             device_map="auto")

model.gradient_checkpointing_enable()
model = prepare_model_for_kbit_training(model)

from peft import LoraConfig, get_peft_model
config = LoraConfig(
    r=4,
    lora_alpha=32,
    target_modules=["k_proj","o_proj","q_proj","v_proj"],
    #modules_to_save=["embed_tokens", "lm_head"],
    lora_dropout=0.2, #0.05 worked fine
    bias="none",
    task_type="CAUSAL_LM"
)

model = get_peft_model(model, config)
model.print_trainable_parameters()
```

### Expected behavior

I would expect the model to load.

**Comment by BenjaminBossan** [comment]
Thanks for reporting. I could not reproduce the error, your code passed for me. What versions of PEFT, auto-gptq etc. are you using? If not the latest, could you try updating?

**Comment by BenjaminBossan** [comment]
@manideep-paa I just saw that your original code contained a HF token. I have edited your post and deleted it, but note that this token is now compromised. If it is your personal token or from your company, I would recommend to invalidate it and create a new one.
