### ISSUE TITLE
Support for Ladder Side Tuning (LST)

### ISSUE THREAD

**Issue by yeshwanthv5** [huggingface/peft#1098]
### Feature request

Hello 

Are there any plans for integrating Ladder Side Tuning (LST) into this library? 

References
Repo: https://github.com/ylsung/Ladder-Side-Tuning/tree/main
Paper: https://arxiv.org/abs/2206.06522

### Motivation

The paper proposes a method that is more efficient in terms of GPU memory and shows competitive results compared to LoRA and IA3. It would be a valuable addition to this repository.

### Your contribution

I am very interested in understanding the challenges and discussing an implementation plan. Unfortunately, I don't have the bandwidth to work on this at the moment.

**Comment by BenjaminBossan** [comment]
Thanks for bringing this to our radar, the method looks interesting indeed. Right now, we don't have it on our roadmap. To the community: Please let us know if you are interested in having this method in PEFT (or even better, if you are interested in adding it).
