### ISSUE TITLE
AttributeError: module 'numpy.linalg._umath_linalg' has no attribute '_ilp64'

### ISSUE THREAD

**Issue by gunaxprofessional** [huggingface/peft#1119]
### System Info

Google Colab Free Version

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

`from peft import PeftModel`

### Expected behavior

AttributeError: module 'numpy.linalg._umath_linalg' has no attribute '_ilp64'

**Comment by younesbelkada** [comment]
Hi @gunaxprofessional 
What is your numpy version?
Can you try `pip install --upgrade numpy `?

**Comment by gunaxprofessional** [comment]
Hi @younesbelkada 
I'm pretty sure that I'm using the latest version of NumPy (1.26.2). I also checked the version of NumPy that I'm currently using against the latest version available on the PyPI website.

**Comment by younesbelkada** [comment]
Hi @gunaxprofessional 
Hmmm I just installed numpy==1.26.2 and was not able to repro, perhaps can you try to install PEFT on a fresh new env?

**Comment by younesbelkada** [comment]
Do you still face this issue @gunaxprofessional ? Closing the issue for now, feel free to re-open or create a new issue with a reproducer

**Comment by KlevertonSilva** [comment]
It worked here using pip install numpy==1.24.4

**Comment by amwen0614** [comment]
降低numpy的版本就能运行了
