### ISSUE TITLE
Request for compatibility with simpletransformers

### ISSUE THREAD

**Issue by abhi1nandy2** [huggingface/peft#112]
There are many downstream tasks (especially in NLP) that use the [simpletransformers](https://simpletransformers.ai/) package. Is there any way to use PEFT in that package?

**Comment by pacman100** [comment]
Hello @abhi1nandy2, I don't have experience with [simpletransformers](https://simpletransformers.ai/) package and the required effort for getting PEFT working with it. Currently, our focus is on adding more real world applications of PEFT, few more seminal PEFT methods and making sure whatever is supported to work well with the 🤗 ecosystem of Transformers, Accelerate and Hub. 

We welcome PRs that enable PEFT to work with [simpletransformers](https://simpletransformers.ai/) package.
