### ISSUE TITLE
Prompt distillation loss in MPT

### ISSUE THREAD

**Issue by junzhang-zj** [huggingface/peft#1124]
I have trouble positioning the **distillation process** in the source training of MPT. I observed in the test that the output loss is only the classification loss of the T5 model. I want to confirm whether this part has not been implemented or if I have missed it. Thank you very much!

**Comment by SumanthRH** [comment]
Hi. Not a maintainer, but I can chime in.  I assume you're talking about the distillation loss in multitask prompt tuning (MPT)? 

PEFT only implements adapters and modifications at the model architecture layer and does not maintain custom losses for different PEFT methods. So adding a loss function is upto the user really. With multitask-prompt-tuning (MPT), PEFT implements addition of prompt embeddings (as seen [here](https://github.com/huggingface/peft/blob/18a09101132473200a68f5b7f2cbe00a6932c2bf/src/peft/tuners/multitask_prompt_tuning/model.py#L28)) and so the output loss is not changed - it's the default loss for that model/architecture. From what I can tell with `examples`, there's [only one for multitask prompt tuning](https://github.com/huggingface/peft/blob/main/examples/conditional_generation/multitask_prompt_tuning.ipynb) and the distillation loss isn't implemented there as well yet. Hope that helps!

**Comment by junzhang-zj** [comment]
@SumanthRH  Yes, this is my question, because the code of the article is officially stated here, so I thought MPT implemented all the functions of the article. Thank you for your answer confirming my observation 😭.
