### ISSUE TITLE
AttributeError: 'DataParallel' object has no attribute 'config' when call get_peft_model.

### ISSUE THREAD

**Issue by hjsg1010** [huggingface/peft#114]
Hi, I am trying to fine-tuning GPT-based model using multiple gpus.
I wrap the base-model using torch.nn.DataParallel.

However, when I try to fine-tune the base-model using peft-LoRA by 
`peft_model = get_peft_model(model,config)`

I get AttributeError: 'DataParallel' object has no attribute 'config'  Error.

How can I solve this problem?

**Comment by minimaxir** [comment]
In general it seems like `peft` doesn't support multiple GPUs yet, which is likely the reason for the `os.environ["CUDA_VISIBLE_DEVICES"]="0"` line at the beginning of the example notebooks.

**Comment by pacman100** [comment]
Hello @minimaxir, for those examples it is limitation with INT8 training. For normal training, it does support any distributed setup, checkout the DeepSpeed example scripts which should work on torch DDP by changing accelerate config without any change to the code. And DeepSpeed example can be run of multiple nodes and multiple GPUs. 

@hjsg1010, make sure to first wrap the base model by calling `get_peft_model` before wrapping it in PyTorch DP, DDP or DeepSpeedEngine ...

**Comment by wxyzjp123** [comment]
Hi bro, I am fine-tuning a bert-based model using LORA, I have no problem with single GPU. However I got an error when I use multiple GPUs(the same as u), when I try to calling get_peft_model first and then using PyTorch DP (if n_gpu > 1:model = torch.nn.DataParallel(model)), it gives an error AttributeError: 'DataParallel' object has no attribute 'encoder'

**Comment by mostafaelhoushi** [comment]
When initializing the model with `pretrained()` function, try adding `device_map="auto"` argument.
This will require having the `accelerate` library installed, so if it is not installed, run `pip install accelerate`.
