### ISSUE TITLE
A (possible) bug in lora merging method: add_weighted_adapter

### ISSUE THREAD

**Issue by jihuishan** [huggingface/peft#1155]
### System Info

peft 0.6.1

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

In both line 565 and 578 of add_weighted_adapter from, peft/tuners/lora/model.py, lora_A and lora_B are upgraded by
 target_lora_A.data += current_adapter_lora_A.data * weight * target.scaling[adapter]
target_lora_B.data += current_adapter_lora_B.data
It is quite confusing (and performance degrading) that the upgrade of target_lora_B is not relevant with the weight, although this seems like a delibrate design (as target_lora_A is upgraded correctly). 

### Expected behavior

When using add_weighted_adapter, me expect all params of each adapter is weightedly combined, instead of weightedly averaging across lora_A while evenly averaging for lora_B. 
During my experiments on merging several loras for a unified model, the performance drops signicantly if the problem above is not solved. For example, lets say there are five adapters with same configs are trained individually on five datasets, and when using a set of weights: [1,0,0,0,0] for add_weighted_adapter to merge these adatpers, me expect the result to be the same of using the first adapter without averaging, which is how weighted averaging works, right? But actually, there is a huge gap between the performance of these two implementations, which should have been almost the same. 
A simple fix is to change both line 565 and 578 by adding the weight: 
target_lora_B.data += current_adapter_lora_B.data ---> target_lora_B.data += current_adapter_lora_B.data * weight
And it works. Assigning a set of weights of [1,0,0,0,0] for five adapters works nearly the same as merely using the first adapter now.
Thank you for your amazing work for the community, and the patience reading this.

**Comment by jihuishan** [comment]
@BenjaminBossan Thank you for your response and patience in reproducing the results, and I'm sorry for the confusing way of referring the codes (me've never issued a question before.)
There may be an explanation about the problem. When merging LoRA adapters, we hope that: $W = W_0 + αB_1A_1 + βB_2A_2 + ……$
Therefore, it is understandable that it was implemented with no weights on B, because due to the formula above, simply putting a weight on A is enough. 

However, this will be a little bit different due to the way we merge adapters. Lets say the weights are $[1,0,0]$ for three adapters, then:
$$W = W_0 + BA = W_0 + (B_1 + B_2 + B_3)(αA_1 + βA_2 + γA_3) = W_0 +(B_1 + B_2 + B_3)(1\times A_1 + 0\times A_2 + 0\times A_3) = W_0 + (B_1 + B_2 + B_3)A_1$$
In another word, the problem is that the B here is being averaged before multiplying with A. Therefore, no matter how the weights are, the arithmetic mean of B_1, B_2 and B_3 is actually used, instead of the intended one. 

From another perspective,  any $B_i$ and $A_i$ of an adatper for merging are coupling with other adapters like $B_j$ and $A_j$, which are not independent, and not what it looks like in the first formula above. 

Due to reasons above, my fix of adding weight to B works and merely works for extreme cases where weights are like [0,1,0], and it seems quite tough to produce a merging that is truely independent. Still, adding a weight to B is of some help, making the performance much better than without it when merging adapters in my experiments, though it is not identical to the literal meaning of "average".

**Comment by BenjaminBossan** [comment]
Thanks for explaining. Indeed, the two formulas are not equivalent and there is in fact no way to combine `lora_A` and `lora_B` to make the two equivalent, except for trivial cases (like weights 0 or 1). Therefore, when using that method, we have to accept that we will only get an approximation of what we would get when adding the LoRAs one after another. SVD might be the preferred method.

That being said, I can still see an argument for applying the `weight` to both `lora_A` and `lora_B` so that we can get identical results for edge cases like `weights=[1, 0, 0]`. However, let's say we have weights `[0.5, 0.5]`. If we apply 0.5 to both sides, we actually shrink the total weight norm because it is applied twice, right? So I wonder if we should actually apply `sqrt(weight)` to both sides instead. WDYT @jihuishan and @pacman100?

**Comment by pacman100** [comment]
Hello, for exact equivalence, please use `cat` and for approx equivalence use `svd`. `linear` is a way of combining LoRAs which doesn't confirm to merging them and is a simple weighted linear combination.

**Comment by pacman100** [comment]
> However, this will be a little bit different due to the way we merge adapters. Lets say the weights are 
 for three adapters, then:

> In another word, the problem is that the B here is being averaged before multiplying with A. Therefore, no matter how the weights are, the arithmetic mean of B_1, B_2 and B_3 is actually used, instead of the intended one.

Thank you for the detailed explanation, makes sense

**Comment by jihuishan** [comment]
>  So I wonder if we should actually apply `sqrt(weight)` to both sides instead. 

That's a good idea,  I presume.

> Hello, for exact equivalence, please use `cat` and for approx equivalence use `svd`. `linear` is a way of combining LoRAs which doesn't conform to merging them and is a simple weighted linear combination.

Thank you! I will try 'svd'.

**Comment by pacman100** [comment]
My go-to setting is `cat` as it is exact and faster when ranks are small and you are not merging many adapters.

**Comment by jihuishan** [comment]
> My go-to setting is `cat` as it is exact and faster when ranks are small and not merging many adapters.

Indeed, `cat` seems more convenient and stable here.
