### ISSUE TITLE
MoLoRA on PEFT

### ISSUE THREAD

**Issue by alexrs** [huggingface/peft#1156]
### Feature request

The paper ["Pushing Mixture of Experts to the Limit: Extremely Parameter Efficient MoE for Instruction Tuning
"](https://arxiv.org/abs/2309.05444) introduced MoLoRA, a Mixutre-of-Experts approach using LoRA adapters. I am using it to conduct some research for my MSc thesis, and have implemented it in peft. I was wondering if this method is interesting and would be worth it to clean up my code and submit a PR.

### Motivation

The motivation is to include more PEFT methods that the community can benefit from.

### Your contribution

I can contribute a PR with the implementation of MoLoRA.

**Comment by BenjaminBossan** [comment]
Thanks for bringing this paper to our attention.

At first glance, it looks similar to AdaMix (Wang et al. 2022, #719) which unfortunately has gone stale, but maybe we can revive.

The Cohere paper cites that method as follows:

> Several studies have explored PEFT in the context of MoE or in a similar fashion, albeit with
certain distinctions. For instance, Wang et al. (2022) focused on single-task fine-tuning employing a
mixture of adapters for BERTbase with 110M parameters (Devlin et al., 2019) and RoBERT alarge
with 355M parameters (Liu et al., 2019), incorporating random routing, and adopting a few-shot
evaluation. In divergence from this, our work centers on instruction-tuning with multiple tasks
present during fine-tuning.

If the main difference is the training process, which is not part of PEFT, I wonder if the two methods are different enough to justify separate implementations.

However, if you found the new paper to work really well and if the other PR cannot be easily salvaged, we could give MoE another shot. One nice thing about the new paper seems to be that it was also applied to IA³. Maybe we can implement it in such a generic way that it can be applied to all (non prompt-learning) adapters.

**Comment by abhinav-kashyap-asus** [comment]
They reopened #719 . 
It requires review before being merged. Can you check with them. I think it will be useful for a lot of people

**Comment by BenjaminBossan** [comment]
There are a bunch of merge conflicts by now, so it would need to be updated and then re-reviewed.

**Comment by abhinav-kashyap-asus** [comment]
I also see that it has been implemented in a way that differs from the current repository. 
For Mixture of Experts in general, we can follow a different route. Would it be okay if I can contribute an initial model for this and we can work on integrating this here?

**Comment by BenjaminBossan** [comment]
> Would it be okay if I can contribute an initial model for this and we can work on integrating this here?

Feel free to propose a solution. You can create a draft PR to share your work early, so that we can give quick feedback.

**Comment by abhinav-kashyap-asus** [comment]
Awesome. Sure. Let me work on this and propose a simple Mixture of Adapters work. 
We can work on it after the initial PR

**Comment by DumoeDss** [comment]
Thank you for your work ~ Can you please provide an example of how MoLoRA is used in finetune? About processing dataset and training configuration.

**Comment by tgaddair** [comment]
Worth pointing out that Scale published a blog showing how they applied MoV (similar to MoLoRA but for IA^3): https://scale.com/blog/fine-tuning-mixture-of-experts-peft

Also worth mentioning the official implementation of MoLoRA (from the paper) for reference: https://github.com/for-ai/parameter-efficient-moe

**Comment by LiuNull** [comment]
Mark

**Comment by thakur-nandan** [comment]
I also found this related repository: https://github.com/liuqidong07/MOELoRA-peft, an official implementation of MoELoRA (https://arxiv.org/abs/2310.18339). 

I am sharing it for reference.

**Comment by DumoeDss** [comment]
Hey, may I ask how it's going now?
I saw a similar solution:
https://github.com/huggingface/peft/issues/1472
