### ISSUE TITLE
Any support for masked language modeling?

### ISSUE THREAD

**Issue by ryan-caesar-ramos** [huggingface/peft#116]
I see that there's support for causal language modeling, and that models trained with MLM objectives are supported for sequence and token classification tasks, but could I ask if there's anything I missed/any hacky way to get PEFT to work for masked language modeling?

**Comment by pacman100** [comment]
Hello, you could make the current examples to work for MLM pre-training by just converting the model to the PEFT model. Please try it out and let us know if you face any issues.

**Comment by ryan-caesar-ramos** [comment]
Thanks! Will do

**Comment by bkopin-quinten** [comment]
@ryan-caesar-ramos Did it worked for you?

**Comment by ryan-caesar-ramos** [comment]
Hello @bkopin-quinten I can't remember why but I did not push through with trying this. Sorry!

**Comment by Bachstelze** [comment]
@pacman100 Which PEFT type and task would you use for masked language modeling?
