### ISSUE TITLE
add token for phi-1.5 tokenizer

### ISSUE THREAD

**Issue by lastrei** [huggingface/peft#1173]
### System Info

sentencepiece                0.1.99
bitsandbytes                 0.41.1
cryptography                 40.0.2
peft                         0.4.0
transformers                 4.30.2

### Who can help?

@pacman100 @younesbelkada 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

i add 20000 vocab for phi-1.5 
begin len(phi_tokenizer.get_vocab())) 50295
after len(phi_tokenizer.get_vocab())  69151

after that i use qlora to finetune phi 1.5

```
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16
)

model = AutoModelForCausalLM.from_pretrained(
    "microsoft/phi-1_5",
    device_map={"": 0},
    trust_remote_code=True,
    quantization_config=bnb_config
)
model.resize_token_embeddings(len(tokenizer))

lora_config = LoraConfig(
    r=8,
    lora_alpha=16,
    target_modules=["wte","Wqkv", "out_proj"],
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
)
model = get_peft_model(model, lora_config)

model.print_trainable_parameters()

training_arguments = TrainingArguments(
    output_dir="phi-1_5-finetuned-zh-text",
    per_device_train_batch_size=1,
    gradient_accumulation_steps=4,
    learning_rate=2e-4,
    lr_scheduler_type="cosine",
    save_strategy="epoch",
    logging_steps=20,
    max_steps=10,
    num_train_epochs=1
)
```

after that i got the peft model

```
model = AutoModelForCausalLM.from_pretrained("microsoft/phi-1_5", trust_remote_code=True, torch_dtype=torch.float32)
model.resize_token_embeddings(len(tokenizer))
peft_model = PeftModel.from_pretrained(model, "phi-1_5-finetuned-zh-text", from_transformers=True)
model = peft_model.merge_and_unload()

# model
model.save_pretrained("phi-1_5-finetuned-zh-text")
```
in lora model 
the config.json shows:
"vocab_size": 69151

but when i use the lora model to inference 
it's shows that:
```
size mismatch for transformer.embd.wte.weight: copying a param with 
shape torch.Size([69151, 2048]) from checkpoint, the shape in current model is 
torch.Size([69184, 2048]).
        size mismatch for lm_head.linear.weight: copying a param with shape 
torch.Size([69151, 2048]) from checkpoint, the shape in current model is 
torch.Size([69184, 2048]).
        size mismatch for lm_head.linear.bias: copying a param with shape 
torch.Size([69151]) from checkpoint, the shape in current model is 
torch.Size([69184]).
```

why the emb shape is  [69184,2048] ?? 

### Expected behavior

why after merge peft model,the emb shape change,69184>vocab_size in config.json
if peft will add special token for model?
how should i to fix that?

**Comment by BenjaminBossan** [comment]
Thank you for reporting. How exactly are you using the model for inference? Do you load it from the saved checkpoint? If so, how?

**Comment by lastrei** [comment]
> Thank you for reporting. How exactly are you using the model for inference? Do you load it from the saved checkpoint? If so, how?
here is my merge code for adapter model and base model
```
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
from peft import set_peft_model_state_dict, LoraConfig, get_peft_model
import os

lora_config = LoraConfig(
    r=16,
    lora_alpha=16,
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
    target_modules=["wte"],
    base_model_name_or_path="./phi-1_5-finetuned-zh-text/",
)

tokenizer = AutoTokenizer.from_pretrained("./phi-1_5-finetuned-zh-text")
model = AutoModelForCausalLM.from_pretrained("microsoft/phi-1_5", trust_remote_code=True,)
model.resize_token_embeddings(len(tokenizer))

model = get_peft_model(model, lora_config)

orig_tokenizer_vocab = len(tokenizer)
# Resize token embeddings
model.resize_token_embeddings(len(tokenizer))

# Load the finetuned Lora PEFT model
model.eval()
model = model.merge_and_unload()
model.save_pretrained("./outputs/lora")
```

# the code load lora model 

```
from transformers import AutoModelForCausalLM, AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("./phi-1_5-finetuned-zh-text", trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained("./outputs/lora", trust_remote_code=True)
# 打印模型emb层的shape
for name, p in model.named_parameters():
    if name == "transformer.embd.wte.weight":
        print(name, p.shape)
```

# error code

```
RuntimeError: Error(s) in loading state_dict for PhiForCausalLM:
        size mismatch for transformer.embd.wte.weight: copying a param with 
shape torch.Size([69151, 2048]) from checkpoint, the shape in current model is 
torch.Size([69184, 2048]).
        size mismatch for lm_head.linear.weight: copying a param with shape 
torch.Size([69151, 2048]) from checkpoint, the shape in current model is 
torch.Size([69184, 2048]).
        size mismatch for lm_head.linear.bias: copying a param with shape 
torch.Size([69151]) from checkpoint, the shape in current model is 
torch.Size([69184]).
        You may consider adding `ignore_mismatched_sizes=True` in the model 
`from_pretrained` method.
```

**Comment by BenjaminBossan** [comment]
Thanks for providing more context. One question: Is it necessary for you to `merge_and_unload` before calling `save_pretrained`? That way, you save all the model weights, not just the adapters, which should result in a huge checkpoint. Would it also work for you to save just the PEFT adapters and load them using `PeftModel.from_pretrained`, as documented [here](https://huggingface.co/docs/peft/quicktour#save-and-load-a-model)? You can still `merge_and_unload` after that. Note that when you load your base model, you should of course resize the embedding layer in the same fashion as before (seeding might be required to ensure reproducibility).

I'm not sure if this will resolve your problem, but it's worth a try.

**Comment by lastrei** [comment]
thanks sir , i have try it :
i just load the adapter model and the basemodel,then the shape is right
```
for name, p in model.named_parameters():
    if "wte" in name:
        print(name, p.shape)

base_model.model.transformer.embd.wte.weight torch.Size([69151, 2048])
base_model.model.transformer.embd.wte.lora_embedding_A.default torch.Size([16, 69151])
base_model.model.transformer.embd.wte.lora_embedding_B.default torch.Size([2048, 16])
```

i dont konw if PEFT has change some thing , i have finetune a bloom model months ago, The whole process is like my code above，qlora finetune , merge_upload save_pretrain and predict,There is no problem。The only difference is that there is no expansion of the vocabulary for tokenizer。

i still dont konw why the wte shape changes after  merge_and_unload and save_pretrained.

but its works with PeftModel.from_pretrain.
```
model = PeftModel.from_pretrained(model, finetune_model_path)

# print wte shape
for name, p in model.named_parameters():
    if "wte" in name:
        print(name, p.shape)
```

thanks,sir
