### ISSUE TITLE
Inquiry about the initialization method of adaption_prompt

### ISSUE THREAD

**Issue by callanwu** [huggingface/peft#1175]
In current repo, adaption_prompt initializes the tokens with standard normal values by using `nn.Parameter()`
https://github.com/huggingface/peft/blob/dd4771b2f42a72b9d7a54fbf9815530659305718/src/peft/tuners/adaption_prompt/layer.py#L52-L54
The comments about these code is https://github.com/huggingface/peft/blob/dd4771b2f42a72b9d7a54fbf9815530659305718/src/peft/tuners/adaption_prompt/layer.py#L45-L47
It said `we follow the official repo which used an Embedding`. The referenced official repo'page is not found now. Dose current code is consitent with the `LLaMA-Adapter`.
In new [`LLaMA-Adapter`](https://github.com/OpenGVLab/LLaMA-Adapter/tree/main) repo, the initialization code is 
https://github.com/OpenGVLab/LLaMA-Adapter/blob/b82e90bd31dc75d6fdca0a35b53ff00d1b96bc47/llama/model.py#L214-L216
It truly uses `nn.Embedding()`
# Question
- Is the current implementation consistent with the official code? `nn.Parameter(torch.empty(1, adapter_len, self.model.hidden_size).normal_()` vs `nn.Embedding(self.adapter_len, self.model.hidden_size)`
- Are there any issues with the current comments?

And I will later modify the comments here and submit a pull request.

### Who can help?

@pacman100 @younesbelkada @sayakpaul

**Comment by callanwu** [comment]
And here is author's reply about `Zero-init Attention`:
https://github.com/OpenGVLab/LLaMA-Adapter/issues/9#issuecomment-1529047043

**Comment by BenjaminBossan** [comment]
Thanks for bringing this up. According to the [docs for Embedding](https://pytorch.org/docs/stable/generated/torch.nn.Embedding.html), its weight is:

> initialized from N(0,1)

So wouldn't this amount to the same outcome? Or do I misunderstand something?

**Comment by callanwu** [comment]
Thank you for your reply and helping me review my knowledge of tensor initialization:)
