### ISSUE TITLE
Toggle inference_mode during training

### ISSUE THREAD

**Issue by LuciferianInk** [huggingface/peft#1182]
### Feature request

After loading a model for training with `get_peft_model()`, I would like to have the ability to temporarily put that model into `inference_mode=True` - so I can test generations while actively training.

### Motivation

As part of my training process, I like to periodically log test generations to the console every X iterations.

However, a  `PeftModel` - loaded with `get_peft_model()` - does not use the training weights for inference. And thus, generations during training are useless - because they're coming from the base model (and not the adapter).

So far as I can tell, an adapter is only usable after it has been saved to-disk, and loaded again via one of the supported methods. This is somewhat painful and expensive, and it would be better if I could just "toggle" inference_mode in some way. I had hoped to use `model.set_adapter()` for this - but `model.active_adapters()` indicates that the "default" adapter is already active!

I tried to call something like this every 50 steps, but the model never uses the adapter:
```
if hasattr(model, "active_peft_config"):
    setattr(model.active_peft_config, "inference_mode", True)

outputs = model.generate(
    inputs=None,
    do_sample=True,
    temperature=0.7
)

gen_texts = tokenizer.batch_decode(outputs, skip_special_tokens=True)

if hasattr(model, "active_peft_config"):
    setattr(model.active_peft_config, "inference_mode", False)
```
Is there a "proper" way to run inference on a model that's actively being trained, or is this a feature we might consider adding?

### Your contribution

Depending on the complexity of the problem, I might be capable of writing the code. But I would prefer for a maintainer to 1) tell me if there's already a way to do this, or 2) the best way to approach the development of such a feature.

**Comment by BenjaminBossan** [comment]
> However, a `PeftModel` - loaded with `get_peft_model()` - does not use the training weights for inference. And thus, generations during training are useless - because they're coming from the base model (and not the adapter).

I wouldn't say this is true :) You should be able to treat the model like any PyTorch model, so 'model.eval()` should be enough to put it into inference mode. Do you have some code that shows that the adapter weights are not being used for inference?

**Comment by LuciferianInk** [comment]
I'm sorry; you're right, false alarm. I just went through a major refactor, and was testing with a IA^3 adapter... which apparently isn't as expressive as other methods. Just after posting this, I switched to LoRA - and could immediately see its influence on the output generations. All is good, now.

I appreciate the quick response.
