### ISSUE TITLE
prefix tuning for encoder-decoder models in peft different from original implementation?

### ISSUE THREAD

**Issue by mickeymickeymonkey** [huggingface/peft#1188]
### System Info

peft==0.6.2

### Who can help?

@pacman @younesbelkada @BenjaminBossan 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

```
model = AutoModelForSeq2SeqLM.from_pretrained('t5-base')
config = PrefixTuningConfig(
    task_type=TaskType.SEQ_2_SEQ_LM,
    num_virtual_tokens=20,
    prefix_projection = False, )
peft_model = get_peft_model(model, config)
```

### Expected behavior

the paper for prefix tuning (https://aclanthology.org/2021.acl-long.353.pdf) show that in encoder-decoder models, the encoder and decoder get different prefixes (look at figure 2 of the paper). also look at Line 218-233 of the original implementation: https://github.com/XiangLi1999/PrefixTuning/blob/cleaned/seq2seq/prefixTuning.py

it seem the current version of prefix tuning in the peft library only add the trainable prefixes to the decoder? (by calling get_prompt and then passing its as past_key_values into the seq2seq model. look at line 1204 https://github.com/huggingface/peft/blob/main/src/peft/peft_model.py). in the t5 script  past_key_values only enters the decoder.  do I understand this correctly? or am I misunderstanding something?

if so, are you planning to add support for the original encoder-decoder implementation? thank you very much.

**Comment by aldakata** [comment]
I was looking at the same thing myself and I believe that the implementation follows this other paper https://github.com/THUDM/P-tuning-v2/tree/main

I don't know how big of an implementation it would be, but I am considering adding the support myself
