### ISSUE TITLE
model_kwargs["input_ids"].shape[0], peft_config.num_virtual_tokens KeyError: 'input_ids'

### ISSUE THREAD

**Issue by mengqianshuang** [huggingface/peft#1192]
### System Info

peft 0.6.2
pytorch 2.0.1
transformers 4.35.2
python 3.11

### Information

- [x] The official example scripts
- [x] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

    device = "cuda:6"
    model_name_or_path = "./Model/t5-base"

    peft_config = PromptTuningConfig(
        task_type=TaskType.CAUSAL_LM,
        prompt_tuning_init=PromptTuningInit.TEXT,
        num_virtual_tokens=8,
        prompt_tuning_init_text="Generate a title for the bug report:",
        tokenizer_name_or_path=model_name_or_path
    )

    T5_tokenizer = T5TokenizerFast.from_pretrained(model_name_or_path)
    plm = T5ForConditionalGeneration.from_pretrained(model_name_or_path)
    plm = get_peft_model(plm, peft_config)

    inputs = T5_tokenizer(
        f'When I tried to open the window, a crash happen. Title : ',
        return_tensors="pt",
    )

    plm.to(device)

    with torch.no_grad():
        inputs = {k: v.to(device) for k, v in inputs.items()}
        outputs = plm.generate(
            input_ids=inputs["input_ids"], attention_mask=inputs["attention_mask"], max_new_tokens=10, eos_token_id=3
        )
        print(T5_tokenizer.batch_decode(outputs.detach().cpu().numpy(), skip_special_tokens=True))

### Expected behavior

I followed the guide to do prompt tuning. https://huggingface.co/docs/peft/task_guides/clm-prompt-tuning 

Instead of using the "bigscience/bloomz-560m" model in the guide, I used T5-base and modified the script slightly to fit in my task.

The training process was fine, as the loss decreased slowly. However, when I tried to use the model to GENERATE, something went wrong. This may be related to the process of passing parameters.
Here is the stack trace.
```
Traceback (most recent call last):
  File "/data/mqs/KeyTitle2/eval2.py", line 223, in <module>
    outputs = plm.generate(
              ^^^^^^^^^^^^^
  File "/data/anaconda3/envs/mpt/lib/python3.11/site-packages/peft/peft_model.py", line 1060, in generate
    outputs = self.base_model.generate(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/mpt/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/mpt/lib/python3.11/site-packages/transformers/generation/utils.py", line 1673, in generate
    return self.greedy_search(
           ^^^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/mpt/lib/python3.11/site-packages/transformers/generation/utils.py", line 2518, in greedy_search
    model_inputs = self.prepare_inputs_for_generation(input_ids, **model_kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/mpt/lib/python3.11/site-packages/peft/peft_model.py", line 1074, in prepare_inputs_for_generation
    model_kwargs["input_ids"].shape[0], peft_config.num_virtual_tokens
    ~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'input_ids'
```
I referred to the peft/peft_model.py file and found nothing quite special.

I wrote a simple code sample to use the model to generate something(shown above). It produced the same issue.

**Comment by BenjaminBossan** [comment]
I haven't checked in detail, but note that T5 is not a causal LM, could you please try `task_type=TaskType.SEQ_2_SEQ_LM`?

**Comment by mengqianshuang** [comment]
> I haven't checked in detail, but note that T5 is not a causal LM, could you please try `task_type=TaskType.SEQ_2_SEQ_LM`?

Thank you! I think that is the point! The model in the code sample generated a word after changing the task_type.

I was a little confused by the task_type when reading the guide. Because I thought the parameter was meant to choose from different downstream tasks, such as prefix tuning, prompt tuning and semantic segmentation. 

Thanks a lot!!!

**Comment by BenjaminBossan** [comment]
Great that it worked. I'll close the issue for now, feel free to re-open if you encounter more issues.
