### ISSUE TITLE
Figure out failing stable diffusion tests

### ISSUE THREAD

**Issue by BenjaminBossan** [huggingface/peft#1194]
### System Info

Tests may only fail on Windows, only with CPU, or only for specific PyTorch versions.

### Who can help?

Anyone.

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

Currently, the merging test for LoHa is being skipped:

https://github.com/huggingface/peft/blob/f0fb9516d8ebc4fed1bacaa11b789be023f003f8/tests/test_stablediffusion.py#L122-L124

Testing on Linux, the test passes with GPU and PyTorch 2.1, but fails on CPU.

Furthermore, the same test causes issues for OFT as well when using CPU:

https://github.com/huggingface/peft/pull/1160#issuecomment-1829890240

### Expected behavior

Merging should work on CPU for LoHa and OFT.

**Comment by lukaskuhn-lku** [comment]
I invested some hours but didn't find the exact point where it goes wrong but I can for sure say that it is only the text-encoder merging that does not produce correct results. The merging of the unet does not result in any differences in outputs.

**Comment by BenjaminBossan** [comment]
Thanks for the info, this helps a lot.
