### ISSUE TITLE
Potentially a bug

### ISSUE THREAD

**Issue by ngocbh** [huggingface/peft#1198]
https://github.com/huggingface/peft/blob/2b901ee57230559aaf39867c7698f6aca3617162/src/peft/tuners/tuners_utils.py#L260C32-L260C32

inject_adapters have its own `model` argument but, in line 260 and 263, it accesses model parameters using `self.model`. I guess it's not a safe choice.

**Comment by BenjaminBossan** [comment]
Thanks for bringing this up. The `model` and `self.model` are indeed the same object (check `model is self.model`), so the code works correctly when used as intended. I agree, however, that this is confusing and it would be better if `model` was used throughout. If you want to create a PR to fix that, we'd be happy to merge it.
