### ISSUE TITLE
ModulesToSaveWrapper has no 'weight' attritude

### ISSUE THREAD

**Issue by zhangsheng377** [huggingface/peft#1225]
### System Info

peft=0.4.0
model=Megatron's GPTModel

### Who can help?

@BenjaminBossan 
We are recently using peft=0.4.0+Megatron to run GPTModel. There is a code of the model `self.language_model.output_layer.weight`, which directly takes the weight of the output_layer, but the output_layer has already been `modules_to_save`, so it reported  "ModulesToSaveWrapper has no 'weight' attribute" error.

We now solve the problem with the following code:
```python
def modules_to_save_getattr_hook(self, name: str):
    try:
        return super(ModulesToSaveWrapper, self).__getattr__(name)  # defer to nn.Module's logic
    except AttributeError:
        if self.active_adapter not in self.modules_to_save:
            return getattr(self.original_module, name)
        return getattr(self.modules_to_save[self.active_adapter], name)


setattr(ModulesToSaveWrapper, '__getattr__', modules_to_save_getattr_hook)
```

But I'm not sure if the new version of peft code still has this problem, so I'm here to consult you.

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

self.language_model.output_layer.weight

### Expected behavior

ModulesToSaveWrapper can obtain the "weight" attribute normally

**Comment by zhangsheng377** [comment]
@BenjaminBossan

**Comment by BenjaminBossan** [comment]
Thanks for reporting. Where does the snippet `self.language_model.output_layer.weight` come from, it would be easiest to make a change there to accommodate for `ModulesToSaveWrapper`.

> But I'm not sure if the new version of peft code still has this problem

Newer PEFT versions will display the same issue. I think we could add an attribute to `ModulesToSaveWrapper` that returns the weight of the currently active adapter or of the original module of the adapter is deactivated. But I'm not sure if having that attribute could have some unwanted side-effects.

**Comment by zhangsheng377** [comment]
> Thanks for reporting. Where does the snippet `self.language_model.output_layer.weight` come from, it would be easiest to make a change there to accommodate for `ModulesToSaveWrapper`.

https://github.com/NVIDIA/Megatron-LM/blob/bcce6f54e075e3c3374ea67adefe54f3f2da2b07/megatron/model/gpt_model.py#L94
It comes from here, but the Megatron-LM has not received PR for a long time.


> Newer PEFT versions will display the same issue. I think we could add an attribute to `ModulesToSaveWrapper` that returns the weight of the currently active adapter or of the original module of the adapter is deactivated. But I'm not sure if having that attribute could have some unwanted side-effects.

Yeap, although there is no problem with our current training, I am not 100% sure.

**Comment by BenjaminBossan** [comment]
I think your solution should be fine.
