### ISSUE TITLE
Any plan for pipeline parallel to suit larger model?

### ISSUE THREAD

**Issue by zhuzilin** [huggingface/peft#124]
Hi, I wonder if you have any plan on adding pipeline parallel to this library so that we could fine-tune larger model across multiple gpus? The reason for mentioning pipeline parallel particularly is that it may be easier to implement a general version comparing to tensor parallel or other model parallel strategies. If you have such plan, I'd love to help :)

**Comment by pacman100** [comment]
Hello @zhuzilin, as PEFT relies on 🤗 Accelerate for all distributed training needs, it would be great if you can help us in supporting pipeline parallelism in generic fashion in 🤗 Accelerate itself: https://github.com/huggingface/accelerate
