### ISSUE TITLE
About the dtype of trainable params

### ISSUE THREAD

**Issue by hiyouga** [huggingface/peft#1249]
### System Info

peft 0.7.0
transformers 4.34.0
torch 2.0.1

### Who can help?

@pacman100 @younesbelkada @sayakpaul 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

```python
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
from peft import PeftModel, TaskType, LoraConfig, get_peft_model

tok = AutoTokenizer.from_pretrained("llama2-7b")
model = AutoModelForCausalLM.from_pretrained("llama2-7b", torch_dtype=torch.float16, low_cpu_mem_usage=True)

lora_config = LoraConfig(
    task_type=TaskType.CAUSAL_LM,
    inference_mode=False,
    r=8,
    lora_alpha=16,
    lora_dropout=0.05,
    target_modules=["q_proj", "v_proj"],
    modules_to_save=["embed_tokens", "lm_head"]
)
peft_model = get_peft_model(model, lora_config)

for name, param in peft_model.named_parameters():
    print(name, param.dtype)
"""
base_model.model.model.layers.31.self_attn.q_proj.base_layer.weight torch.float16
base_model.model.model.layers.31.self_attn.q_proj.lora_A.default.weight torch.float16
base_model.model.model.layers.31.self_attn.q_proj.lora_B.default.weight torch.float16
base_model.model.model.layers.31.self_attn.k_proj.weight torch.float16
base_model.model.model.layers.31.self_attn.v_proj.base_layer.weight torch.float16
base_model.model.model.layers.31.self_attn.v_proj.lora_A.default.weight torch.float16
base_model.model.model.layers.31.self_attn.v_proj.lora_B.default.weight torch.float16
...
base_model.model.lm_head.original_module.weight torch.float16
base_model.model.lm_head.modules_to_save.default.weight torch.float16
"""
```

### Expected behavior

If we load the model with half-precision and use fp16 mixed precision training, it will throw "ValueError: Attempting to unscale FP16 gradients."

Should we manually cast them in float32?

**Comment by BenjaminBossan** [comment]
Could you please provide the training code and the full error?

**Comment by hiyouga** [comment]
I use a modified version of https://github.com/huggingface/transformers/blob/main/examples/pytorch/language-modeling/run_clm.py

Here is the training code: https://gist.github.com/hiyouga/361bc114960672115446050857895dbb

We run this script by: CUDA_VISIBLE_DEVICES=0 python run_clm.py --model_name_or_path llama2-7b --low_cpu_mem_usage True --train_file wikipedia.json --block_size 512 --do_train --fp16 --output_dir test

Full error:
```
[INFO|trainer.py:593] 2023-12-11 19:41:42,620 >> Using auto half precision backend
[INFO|trainer.py:1723] 2023-12-11 19:41:42,780 >> ***** Running training *****
[INFO|trainer.py:1724] 2023-12-11 19:41:42,780 >>   Num examples = 963
[INFO|trainer.py:1725] 2023-12-11 19:41:42,780 >>   Num Epochs = 3
[INFO|trainer.py:1726] 2023-12-11 19:41:42,780 >>   Instantaneous batch size per device = 1
[INFO|trainer.py:1729] 2023-12-11 19:41:42,780 >>   Total train batch size (w. parallel, distributed & accumulation) = 1
[INFO|trainer.py:1730] 2023-12-11 19:41:42,780 >>   Gradient Accumulation steps = 1
[INFO|trainer.py:1731] 2023-12-11 19:41:42,780 >>   Total optimization steps = 2,889
[INFO|trainer.py:1732] 2023-12-11 19:41:42,782 >>   Number of trainable parameters = 1,033,895,936
  0%|                                                                                                        | 0/2889 [00:00<?, ?it/s]Traceback (most recent call last):
  File "xx/training/run_clm.py", line 681, in <module>
    main()
  File "xx/training/run_clm.py", line 629, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "xxlib/python3.10/site-packages/transformers/trainer.py", line 1555, in train
    return inner_training_loop(
  File "xxlib/python3.10/site-packages/transformers/trainer.py", line 1904, in _inner_training_loop
    self.accelerator.clip_grad_norm_(
  File "xxlib/python3.10/site-packages/accelerate/accelerator.py", line 2120, in clip_grad_norm_
    self.unscale_gradients()
  File "xxlib/python3.10/site-packages/accelerate/accelerator.py", line 2083, in unscale_gradients
    self.scaler.unscale_(opt)
  File "xxlib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 284, in unscale_
    optimizer_state["found_inf_per_device"] = self._unscale_grads_(optimizer, inv_scale, found_inf, False)
  File "xxlib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 212, in _unscale_grads_
    raise ValueError("Attempting to unscale FP16 gradients.")
ValueError: Attempting to unscale FP16 gradients.
```

**Comment by BenjaminBossan** [comment]
Thanks for providing the example. I could reproduce the error, but it was not related to PEFT. Using the normal script, without PEFT, and only with `torch_dtype=torch.float16`, causes the same issue. I'm not familiar with `Trainer`, but I assume this is not the correct way to handle mixed precision training. Please check the relevant documentation.

**Comment by hiyouga** [comment]
Got it. This problem is also not related to Trainer. Generally, we should make the trainable params in float32 in order to perform mixed precision training. The default dtype of PEFT adapters remains float16 if the base model was loaded in float16. So we cannot directly use these adapters in fp16 training (but we can use them in bf16 training).
https://github.com/huggingface/peft/blob/21c304f6f6ea62c7dcbef8e201d178a7575b471d/src/peft/tuners/lora/layer.py#L96-L102

Coincidently, if we use `prepare_model_for_kbit_training` to perform QLoRA, the adapter weights can be cast in float32 that solves this problem.
https://github.com/huggingface/peft/blob/21c304f6f6ea62c7dcbef8e201d178a7575b471d/src/peft/utils/other.py#L99-L103

**Comment by BenjaminBossan** [comment]
Yes, you are correct. What I meant is that when using `Trainer`/accelerate, they should handle the dtypes, so explicitly requiring `float16` should not be necessary.

> Coincidently, if we use `prepare_model_for_kbit_training` to perform QLoRA, the adapter weights can be cast in float32 which solves the problem.

Yes, good point, this function is not only useful for QLoRA, but the name might suggest so.

**Comment by hiyouga** [comment]
I thought the trainer could not handle the model dtype for LoRA training. By default, the model is loaded with 32-bit precision, which consumes a high amount of GPU memory. (e.g. a 7B model requires 28GB GRAM)

```python
from transformers import AutoModelForCausalLM
model = AutoModelForCausalLM.from_pretrained("llama2-7b", low_cpu_mem_usage=True, device_map="cuda")
print(model.dtype)
# torch.float32
```

However, during PEFT training, we want the model to be loaded directly in 16 bits or lower precision, in this case, it is necessary to explicitly specify the precision type in order to save more GPU memory. (e.g. a 7B model requires 16GB GRAM)

### Reproduction

Training code: https://gist.github.com/hiyouga/5b139f3d4d41a6cc49382c9e79e177ea
Diff checker (with the main example): https://www.diffchecker.com/Tp1MqOPq/

Without `torch_dtype=float16`
```bash
CUDA_VISIBLE_DEVICES=0 python run_clm.py --model_name_or_path llama2-7b --low_cpu_mem_usage True --train_file wikipedia.json --block_size 128 --output_dir test --do_train --per_device_train_batch_size 1 --fp16
```

**GRAM used: 33GB**


With torch_dtype=float16
```bash
CUDA_VISIBLE_DEVICES=0 python run_clm.py --model_name_or_path llama2-7b --low_cpu_mem_usage True --train_file wikipedia.json --block_size 128 --output_dir test --do_train --per_device_train_batch_size 1 --fp16 --torch_dtype float16
```

**GRAM used: 17GB**

**Comment by KCFindstr** [comment]
I was able to do float16 finetuning with peft==0.6.2. Are there any dependency changes that might lead to this issue?

**Comment by hiyouga** [comment]
> I was able to do float16 finetuning with peft==0.6.2. Are there any dependency changes that might lead to this issue?

Yes, there is. In PEFT 0.6.2, they used `self.weight` to determine the dtype and device for the adapter weight. However, there isn't any weight after `torch.nn.Module.__init__()`, so this logic was invalid, and the adapter weight was not cast in the same dtype as the model.

https://github.com/huggingface/peft/blob/v0.6.2/src/peft/tuners/lora/layer.py#L63-L89
https://github.com/huggingface/peft/blob/32357c2dd2bab768da554d0b1b7dc15825689eb2/src/peft/tuners/lora/layer.py#L82-L89

Instead, in PEFT 0.7.0, they implemented `self.get_base_layer()` and used the weight of the base layer to achieve this, ensuring that the adapter weight was correctly cast in the same dtype as the model.

https://github.com/huggingface/peft/blob/v0.7.0/src/peft/tuners/lora/layer.py#L74-L103
https://github.com/huggingface/peft/blob/2665f80a1738b315dce42da8f1a9c7fe793aa9ca/src/peft/tuners/lora/layer.py#L96-L103

**Comment by KCFindstr** [comment]
@hiyouga Thanks for the explanation! So the float16 finetuning capability in peft 0.6.2 is actually a bug that got fixed in 0.7.0 🥲

**Comment by hiyouga** [comment]
A related issue: https://github.com/huggingface/peft/issues/1090 
I closed it because of the above findings.

**Comment by BenjaminBossan** [comment]
Could you try if applying this to the PEFT model would work after loading the model in 16bit:

```python
def cast_lora_to_float(model):
    for name, mod in model.named_modules():
        if ("lora_" in name) and hasattr(mod, "weight"):
            mod.weight.data = mod.weight.data.float()
        if ("lora_" in name) and hasattr(mod, "bias") and (mod.bias is not None):
            mod.bias.data = mod.bias.data.float()
```

**Comment by hiyouga** [comment]
@BenjaminBossan It works when `modules_to_save` is None, but it cannot handle the params in `modules_to_save`

**Comment by BenjaminBossan** [comment]
Yes, I forgot about it:

```python
def cast_lora_to_float(model):
    for name, mod in model.named_modules():
        if ("lora_" in name) and hasattr(mod, "weight"):
            mod.weight.data = mod.weight.data.float()
        if ("lora_" in name) and hasattr(mod, "bias") and (mod.bias is not None):
            mod.bias.data = mod.bias.data.float()
        if ("modules_to_save" in name) and isinstance(mod, nn.Linear):
            mod.weight.data = mod.weight.data.float()
            if mod.bias is not None:
                mod.bias.data = mod.bias.data.float()
```

**Comment by hiyouga** [comment]
@BenjaminBossan It gives
```
base_model.model.model.embed_tokens.original_module.weight torch.float16
base_model.model.model.embed_tokens.modules_to_save.default.weight torch.float16
base_model.model.model.layers.0.self_attn.q_proj.base_layer.weight torch.float16
base_model.model.model.layers.0.self_attn.q_proj.lora_A.default.weight torch.float32
base_model.model.model.layers.0.self_attn.q_proj.lora_B.default.weight torch.float32
base_model.model.model.layers.0.self_attn.k_proj.weight torch.float16
base_model.model.model.layers.0.self_attn.v_proj.base_layer.weight torch.float16
base_model.model.model.layers.0.self_attn.v_proj.lora_A.default.weight torch.float32
base_model.model.model.layers.0.self_attn.v_proj.lora_B.default.weight torch.float32
```

Because I use `nn.Embedding` as `modules_to_save`
It could also be a norm layer

**Comment by BenjaminBossan** [comment]
Ah yes, please add an `isinstance` check to include the layer types you want to add to `modules_to_save`. Depending on the type, the attribute names could also be different from `weight` and `bias` but the idea should be the same.

**Comment by hiyouga** [comment]
I prefer to use
```python
for param in filter(lambda p: p.requires_grad, model.parameters()):
    param.data = param.data.to(torch.float32)
```

**Comment by BenjaminBossan** [comment]
That should work too. It is a bit more coarse-grained, so there could be model architectures where this modifies data that it shouldn't, but for most cases it should be fine.

**Comment by hiyouga** [comment]
A similar discussion here: https://github.com/huggingface/transformers/pull/28142
It seems we couldn't use float16 model loading in PEFT training?
