### ISSUE TITLE
Retraining Fine tune model

### ISSUE THREAD

**Issue by AliHaider20** [huggingface/peft#1253]
### System Info

Model saving:

```
base_model_reload = AutoModelForCausalLM.from_pretrained(
    base_model, low_cpu_mem_usage=True, trust_remote_code=True,
    return_dict=True,torch_dtype=torch.bfloat16,
    device_map= {"": 0})
model = PeftModel.from_pretrained(base_model_reload, new_model)
model = model.merge_and_unload()
print("Model merged")
tokenizer = AutoTokenizer.from_pretrained(base_model, trust_remote_code=True)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

# os.chdir("codegood")
model.push_to_hub(new_model, check_pr=True)
tokenizer.push_to_hub(new_model, check_pr=True)
```

Fine tune model reading:
```
# Fine tuned model
from peft import PeftConfig
PEFT_MODEL_ID = "codegood/MPhi_Latest"
# PEFT_MODEL_ID = "codegood/Mistral_instruct_latest"


config = PeftConfig.from_pretrained(PEFT_MODEL_ID)
model = AutoModelForCausalLM.from_pretrained(
    config.base_model_name_or_path,
    load_in_4bit = True,
    return_dict=True,
    quantization_config=bnb_config,
    device_map= "auto",
    trust_remote_code=True
)

model = PeftModel.from_pretrained(model, PEFT_MODEL_ID)

tokenizer = AutoTokenizer.from_pretrained(config.base_model_name_or_path,  device_map="auto")
tokenizer.pad_token = tokenizer.eos_token
model = prepare_model_for_kbit_training(model, use_gradient_checkpointing=False)

for i in range(10):
    torch.cuda.empty_cache()

```

I'm getting the below error: 
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn.

I'm using all the latest libraries:
```
%pip install -U bitsandbytes
%pip install -U transformers
# %pip install transformers==4.30
%pip install -U peft
%pip install -U accelerate einops
%pip install -U trl 
%pip install rouge_score rouge
%pip install datasets==2.11
%pip install -U flash-attn --no-build-isolation
```

### Who can help?

@pacman100 @younesbelkada @sayakpaul 

### Information

- [X] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [x] My own task or dataset (give details below)

### Reproduction

trainer.train()

### Expected behavior

Start training the fine tune model.

**Comment by BenjaminBossan** [comment]
Could you please try:

```python
- model = PeftModel.from_pretrained(model, PEFT_MODEL_ID)
+ model = PeftModel.from_pretrained(model, PEFT_MODEL_ID, is_trainable=True)
```

**Comment by AliHaider20** [comment]
@BenjaminBossan I tried, but it's giving the same error.

**Comment by BenjaminBossan** [comment]
> After removing `model = prepare_model_for_kbit_training(model, use_gradient_checkpointing=False)`
> 
> It works, is it the correct way? Can you explain what's going on?

Ah yes, this function should be called on the base model, not on the PEFT model, this is why it wasn't working for you.

> Also, I'm expecting the model evaluate to be near 1 or less than 1.

This is super hard to say, there can be innumerable reasons for that and based on the provided code, it's impossible to say. Did you evaluate the model after training and then after loading without any further LoRA adapter? Could it be the quantization itself?

**Comment by pacman100** [comment]
Hello @AliHaider20, as Benjamin mentioned, please prepare the base model before loading the adapter weights for further finetuning. Also, please provide a minimal example which can clearly reproduce the issue for us to deep dive.

**Comment by AliHaider20** [comment]
@pacman100  I've provided the sample code I'm trying to run. 
@BenjaminBossan I was able to run the same code previously. 

![image](https://github.com/huggingface/peft/assets/42317018/9b83a803-59ed-47ef-bbeb-1be49e5cbde7)
I'm getting the above results with and w/o applying kbit training function.
I'm also tried using merge and unload.

**Comment by BenjaminBossan** [comment]
> I'm getting the above results with and w/o applying kbit training function.

Could you please paste the exact code that you ran, otherwise it's hard for us to help you.

> I'm also tried using merge and unload.

You shouldn't use that for the purpose of training.

**Comment by AliHaider20** [comment]
Sure, here is the code.
```
# # Fine tuned model
# from peft import PeftConfig
# PEFT_MODEL_ID = "codegood/MPhi_Latest"
PEFT_MODEL_ID = "codegood/MPhi_40_epochs"
# PEFT_MODEL_ID = "codegood/MistralLite_SCQA"
# PEFT_MODEL_ID = "codegood/Mistral_instruct_latest"


config = PeftConfig.from_pretrained(PEFT_MODEL_ID)
model = AutoModelForCausalLM.from_pretrained(
    config.base_model_name_or_path,
    load_in_4bit = True,
    return_dict=True,
    quantization_config=bnb_config,
    torch_dtype=torch.bfloat16,
    device_map= "auto",
    trust_remote_code=True
)

model = PeftModel.from_pretrained(model, PEFT_MODEL_ID)

tokenizer = AutoTokenizer.from_pretrained(config.base_model_name_or_path,trust_remote_code=True, device_map="auto")
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = 'left'

model = prepare_model_for_kbit_training(model, use_gradient_checkpointing=False)

for i in range(10):
    torch.cuda.empty_cache()
    gc.collect()

```

**Comment by BenjaminBossan** [comment]
> `model = PeftModel.from_pretrained(model, PEFT_MODEL_ID)`

As mentioned above, you should pass `is_trainable=True` if you plan on training this adapter further.

> `model = prepare_model_for_kbit_training(model, use_gradient_checkpointing=False)`

Also, as mentioned above, this should be called on the base model, not the PEFT model, i.e. on the `model` _before_ passing it to `PeftModel.from_pretrained`.

**Comment by AliHaider20** [comment]
Thanks it works now, but still the model is incorrectly loaded I guess as I'm getting very high eval results as if I'm loading the base model.

```
from transformers import DataCollatorForLanguageModeling
per_device_train_batch_size = 10 # reduce batch size by 2x if out-of-memory error
per_device_eval_batch_size = 10
gradient_accumulation_steps = 3  # increase gradient accumulation steps by 2x if batch size is reduced
optim = "paged_adamw_32bit" # activates the paging for better memory management
save_strategy="steps" # checkpoint save strategy to adopt during training
save_steps = 10 # number of updates steps before two checkpoint saves
logging_steps = 200 # number of update steps between two logs if logging_strategy="steps"
learning_rate = 2e-4  # learning rate for AdamW optimizer
max_grad_norm = 0.3 # maximum gradient norm (for gradient clipping)
max_steps = -1      # training will happen for 320 steps
warmup_ratio = 0.05 # number of steps used for a linear warmup from 0 to learning_rate
lr_scheduler_type = "cosine"  # learning rate scheduler


training_arguments = TrainingArguments(
    output_dir="./results",
    per_device_train_batch_size=per_device_train_batch_size,
    per_device_eval_batch_size=per_device_eval_batch_size,
    gradient_accumulation_steps=gradient_accumulation_steps,
    optim=optim,
    save_steps=save_steps,
    learning_rate=learning_rate,
    max_grad_norm=max_grad_norm,
    max_steps=max_steps,
    save_total_limit = 3,
#     accelerator = accelerator,
    num_train_epochs=3,
    warmup_ratio=warmup_ratio,
    group_by_length=True,
    lr_scheduler_type=lr_scheduler_type,
    evaluation_strategy='steps',
    eval_steps=save_steps,
    metric_for_best_model="eval_loss",
    logging_steps=logging_steps,
    weight_decay=0.001,
    fp16=False,
    bf16=False,
#     hub_model_id="HF_AWS_Mistral_SC",
    report_to="wandb",
#     load_best_model_at_end=True,
)
# Setting sft parameters
trainer = SFTTrainer(
    model=model,
    eval_dataset= test_qa,
#     eval_dataset = combined_test,
    train_dataset=train_qa,
#     train_dataset = combined_train,
    neftune_noise_alpha=5,
    peft_config=peft_config,
    max_seq_length= 256,
    dataset_text_field="text",
    tokenizer=tokenizer,
    args=training_arguments,
    packing= False,
    data_collator  = DataCollatorForLanguageModeling(tokenizer, mlm=False)
)

for _ in range(15):
    torch.cuda.empty_cache()
    gc.collect()
for name, module in trainer.model.named_modules():
    if "norm" in name:
        module = module.to(torch.float32)
if torch.cuda.device_count() > 1: # If more than 1 GPU
    model.is_parallelizable = True
    model.model_parallel = True

```

![image](https://github.com/huggingface/peft/assets/42317018/a8c50db7-93db-45d6-9896-0ba3f374cc02)

**Comment by AliHaider20** [comment]
There was issue with pushing the model to the HF. I'm now pushing it using the trainer.push_to_hub but it just pushes the safetensors which I don't think is the model. Can someone let me know a better way to upload the model with the pth file to the hub? I'm using dev version of transformers.

**Comment by BenjaminBossan** [comment]
> but it just pushes the safetensors which I don't think is the model.

Safetensors is an alternative to using pickle (i.e. "checkpoint" files aka `.bin` files, also sometimes `.pt`, `.pickle`, or `.pkl`). It has various advantages over pickle and should not cause any problem.
