### ISSUE TITLE
PEFT Model returns same results like original model after fine tuning using LORA. 

### ISSUE THREAD

**Issue by SachinLimbachiya** [huggingface/peft#1259]
### System Info

I have fine tune the FlanT5 with target module Q and V base model using my data but during inference, it returns exact same results as the original model. Upon checking the weight in these target modules before and after, they are same which means during fine tuning weight is not updated.  Does anyone else find a similar issue?  Shared the link of Kaggle for the code, for ref

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

https://www.kaggle.com/code/paultimothymooney/fine-tune-flan-t5-with-peft-lora-deeplearning-ai/notebook

### Expected behavior

Different output after fine tuning.

**Comment by BenjaminBossan** [comment]
I tried to understand what's going on but the notebook is quite long and it's unclear where things are going wrong. Ideally, if you could provide a minimal example to reproduce the error, that would be much better.

One thing I saw is that the path you use to save the PEFT model and to load it again are not identical.

> Upon checking the weight in these target modules before and after

Do you mean immediately before and after training, or before and after saving and loading the model?

**Comment by steveepreston** [comment]
I faced same issue
