### ISSUE TITLE
Serialize and load method seems not compatible cross device.

### ISSUE THREAD

**Issue by svjack** [huggingface/peft#126]
If I try to train the peft model in "cuda", and use save_pretrained to save it to local.
the pickled weight in .bin files can not be loaded successfully in a cpu environment
because in the definition of from_pretrained method in peft model, only use torch.load 
without map_location setting.
This seems should be corrected. 

peft version: '0.2.0.dev0'

**Comment by sujithjoseph** [comment]
I am also facing the same situation. save_pretrained was used to save it on 8 GPUs. I dont have an issue to load it up for inference on those 8 GPUs. but if I load it up on 1 GPU or 2 GPUs, it gives an error 
```
RuntimeError: Attempting to deserialize object on CUDA device 7 but torch.cuda.device_count() is 2. Please use 
torch.load with map_location to map your storages to an existing device.
```

**Comment by svjack** [comment]
> I am also facing the same situation. save_pretrained was used to save it on a VM with 8 GPUs. I dont have an issue to load it up for inference on that VM with 8 GPUs. but if I load it up on another VM with 1 GPU or 2 GPUs, it gives an error 
> ```
> RuntimeError: Attempting to deserialize object on CUDA device 7 but torch.cuda.device_count() is 2. Please use 
> torch.load with map_location to map your storages to an existing device.
> ```
> How can I fix it? @pacman100 

![Screenshot_2023-02-24-17-52-39-75_320a9a695de7cdce83ed5281148d6f19.jpg](https://user-images.githubusercontent.com/27874014/221148306-6d032c03-a972-4595-87c9-7bfcd5c4f9e2.jpg)

**Comment by gabinguo** [comment]
Same issue... fine-tuned on 1 `GPU` and save only the adapter model using `.save_pretrained(...)` of `PeftModelForCausalLM` ... I tried to test it locally on `cpu` but it failed with:

> RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map
your storages to the CPU.

Potential Issue:
`peft/peft_model.py:158`
```python3
adapters_weights = torch.load(filename)
```
Switch to this temporarily fixed my problem...
```python3
adapters_weights = torch.load(filename, map_location=torch.device("cuda" if torch.cuda.is_available() else "cpu"))
```

**Comment by pacman100** [comment]
Hello @gabinguo, what you suggested is the fix, it would be great if you could raise PR with the fix! 🤗

**Comment by gabinguo** [comment]
Sure thing! Here it is #134 : )
