### ISSUE TITLE
This regex is confusing

### ISSUE THREAD

**Issue by s-k-yx** [huggingface/peft#1260]
https://github.com/huggingface/peft/blob/c9df262d69b41d36c7e199219605420be03dfbca/src/peft/tuners/tuners_utils.py#L502
It works now, but seems has a wrong format.
`r".*\.{pattern}\.(\d+)\..*".format(pattern=pattern)` this is a better format, if only layer_index is needed `r".*\.{pattern}\.(\d+)".format(pattern=pattern)` is enough.

module name examples:
...
model.layers.0.post_attention_layernorm
model.layers.1  # first expression will escape this
model.layers.1.self_attn
model.layers.1.self_attn.q_proj
model.layers.1.self_attn.k_proj
...

**Comment by BenjaminBossan** [comment]
Do you mean specifically that the 2nd `.` is not escaped and the `*` at the end? I agree that those looks suspicious. We have an extensive test suite here:

https://github.com/huggingface/peft/blob/main/tests/test_tuners_utils.py

Some test cases have dubious results (see the comments). If you want to, feel free to create a PR with a better regex and we can check how the tests are affected.

**Comment by s-k-yx** [comment]
ok, i've made a PR, and  this test case should be false?  https://github.com/huggingface/peft/blob/0f1e9091cc975eb5458cc163bf1843a34fb42b76/tests/test_tuners_utils.py#L65

**Comment by BenjaminBossan** [comment]
Fixed via #1263
