### ISSUE TITLE
Adding LoRA like additional trainable parameters for nn.Parameter() or nn.Embedding()

### ISSUE THREAD

**Issue by lawrence-cj** [huggingface/peft#1272]
### Feature request

When training LoRA with PEFT, if there is a learnable embedding or parameter variables in the model, PEFT won't add additional trainable parameters for them. Maybe trainable parameter for nn.embedding() and nn.Parameter() data should be added for model fine-tuning.

### Motivation

When I use LoraConfig for finetuning a model, modules with `.weight` will be added new LoRA trainable parameters for fine-tuning. However, there are still some nn.Parameter() variables in the model. I haven't got a decent way for adding trainable parameters for them.

### Your contribution

Cc: @sayakpaul

**Comment by sayakpaul** [comment]
Cc: @BenjaminBossan

**Comment by BenjaminBossan** [comment]
> modules with `.weight` will be added new LoRA trainable parameters for fine-tuning

This is not quite right. Depending on the model architecutre, we may auto-detect the layers that LoRA should be applied to, but those are not automatically all layers with a `weight` attribute.

In general, if you want to control which layers LoRA should be applied to, this is done via the `target_modules` argument of the `LoraConfig`. Note that this also supports `nn.Embedding`, so if you include the embedding layer there, it should be updated.

As for general `nn.Parameter`s, we do not support them. It would be very difficult to do so, as we would have to ensure that LoRA is added each time that parameter is being used, i.e. we would have to mess with Python's `__getattribute__` or descriptors.

**Comment by lawrence-cj** [comment]
Thank you so much for the quick reply. Yeah, the non.Embedding truly will be added a trainable parameter, is it more like a LoRA encode decode, or a same size variable will be created.

**Comment by BenjaminBossan** [comment]
> is it more like a LoRA encode decode, or a same size variable will be created.

Sorry, I did not understand this, could you please rephrase?

**Comment by lawrence-cj** [comment]
Oh sry, I mean, is the trainable parameter added for `embedding_ori = nn.Embedding(x)` is `embedding_lora=nn.Embedding(x)` or just like LoRA for linear layers `embedding_lora = nn.Linear()(nn.Linear()(x))`.
Since we have some variables in the model, which are initialized as nn.Parameter() and there is no input for them. I wanna ask what is the best to implement an additional trainable layer for them.

**Comment by BenjaminBossan** [comment]
Ah I see. For `Embedding`, we indeed add `nn.Parameter`s, so not like what we do for `Linear`:

https://github.com/huggingface/peft/blob/55c37e9c0b48c6e937ccc46a5f05b8f341701694/src/peft/tuners/lora/layer.py#L156-L159

> I wanna ask what is the best to implement an additional trainable layer for them.

In general, it's not possible to add new trainable layers to PEFT (of course, unless you create a PR and add them). It's hard to say, without knowing more details, what the best approach for you should be. You could try to manually add your custom adapter, but this might still cause trouble, e.g. when trying to merge layers or saving the adapter.

**Comment by lawrence-cj** [comment]
Well, it seems more easier for us to change the nn.Parameter to nn.Embedding, no? If so, since we don’t have an input for nn.Embedding, would it be possible to work normally?

**Comment by lawrence-cj** [comment]
Change the module from torch.nn.Parameter to torch.nn.Embedding for peft.Lora
