### ISSUE TITLE
[SpeechToText] Wav2vec2 Support

### ISSUE THREAD

**Issue by omarsou** [huggingface/peft#128]
Hello,

Thanks a lot for the great project.

I noticed that there are no examples/tutorials on speech2text model. But since one of them ([wav2vec2](https://arxiv.org/abs/2006.11477)) is based on the transformer encoder architecture, I want to know if there is a way to use your package for wav2vec2 model.

Thank you :)

**Comment by pacman100** [comment]
Hello, Whisper model example of ASR, i.e., speech-to-text is available here: https://github.com/huggingface/peft/blob/main/examples/int8_training/peft_bnb_whisper_large_v2_training.ipynb

**Comment by pacman100** [comment]
It would be great if you can try adapting it to wav2vec2 and let us know if you face any issues with it

**Comment by DavraYoung** [comment]
hello, any updates on this? Do anyone has any clue how can we accomplish lora tuning in wav2vec training?

**Comment by younesbelkada** [comment]
Hi @DavraYoung,
If my understanding is correct, there is no need to integrate anything on `peft` side to accomplish this. You can just identify the modules you want to adapt by specifying their names in `target_modules` when defining `LoraConfig`. 
```python
peft_config = LoraConfig(
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    bias="none",
   target_modules=["k_proj", "q_proj"]
)
```
As you can see from here: https://github.com/huggingface/transformers/blob/main/src/transformers/models/wav2vec2/modeling_wav2vec2.py#L510 for the name of the modules to adapt

**Comment by gau-nernst** [comment]
> Hi @DavraYoung, If my understanding is correct, there is no need to integrate anything on `peft` side to accomplish this. You can just identify the modules you want to adapt by specifying their names in `target_modules` when defining `LoraConfig`.
> 
> ```python
> peft_config = LoraConfig(
>     r=16,
>     lora_alpha=32,
>     lora_dropout=0.05,
>     bias="none",
>     target_modules=["k_proj", "q_proj"]
> )
> ```
> 
> As you can see from here: https://github.com/huggingface/transformers/blob/main/src/transformers/models/wav2vec2/modeling_wav2vec2.py#L510 for the name of the modules to adapt

Can this be added to a tutorial / quicktour somewhere, especially the `target_modules` argument? This is not mentioned anywhere obvious, and facing the error

```
ValueError: Please specify `target_modules` in `peft_config`
```

is not very helpful. Thank you!

**Comment by BenjaminBossan** [comment]
This page contains a bit more info in `target_modules`: https://huggingface.co/docs/peft/developer_guides/custom_models

**Comment by gau-nernst** [comment]
@BenjaminBossan Thank you, that's good to see. I think it will be better if there is more visibility to that page? Or at least the quickstart instruction should mention `target_modules`? Wav2Vec2.0 is a very popular audio model on HF, and using the quickstart instructions fails immediately is a bit discouraging. Whisper also has the same problem.

**Comment by BenjaminBossan** [comment]
If the only issue is how to correctly set the `target_modules` config for wav2vec and whisper, they could also be added to the [`TRANSFORMERS_MODELS_TO_LORA_TARGET_MODULES_MAPPING`](https://github.com/huggingface/peft/blob/6e783780ca9df3a623992cc4d1d665001232eae0/src/peft/utils/other.py#L367), so that they work out of the box. ping @pacman100 @younesbelkada

**Comment by geoffvdr** [comment]
Hi, has anyone of you been able to save and load wav2vec2+peft model?
This is an open issue: https://github.com/huggingface/peft/issues/1569
