### ISSUE TITLE
What's the default setting for "target_modules" for TaskType.CAUSAL_LM (LoraConfig)

### ISSUE THREAD

**Issue by suchunxie** [huggingface/peft#1289]
Hi, I'm fine-tuning Llama with Lora, and today I found my code didn't specify the `target_modules` parameter when training, which makes me a bit worried. I would appreciate your help.
My code is as follows:
```    
model = create_hf_model(LlamaForCausalLM, args.model_name_or_path, tokenizer) 
peft_config = LoraConfig(task_type=TaskType.CAUSAL_LM, inference_mode=False, r=args.lora_dim, lora_alpha=args.lora_alpha, lora_dropout=args.lora_dropout)
```
Is it that because I didn't set the target module, it actually processed a full-parameter training? (if so, in that case, what the Peft library function on?)

ps. I checked your example [here](https://github.com/huggingface/peft/blob/3714aa2fff158fdfa637b2b65952580801d890b2/src/peft/peft_model.py#L641) in the source code, I noticed that in the sample the  `target_modules`  is also not set.

**Comment by BenjaminBossan** [comment]
Don't worry, everything should work as expected. When `target_modules` is not specified, PEFT will look up the model architecture and choose the appropriate ones:

https://github.com/huggingface/peft/blob/1c9679ac7177bf9bde6f884612fb279567f77206/src/peft/utils/constants.py#L49

If we cannot detect any target modules for your model, we will raise an error, so that you'll know.

**Comment by suchunxie** [comment]
@BenjaminBossan Big thanks for the quick confirmation! I'm quite relieved. 
Also although It's a bit late, for those who may come to the same question, I found in the trained model, within the `adapter_config.json` file, there's a description about the updated `target_modules` info, in the case for`TaskType.CAUSAL_LM` for llama the default setting is as expected just like below:
```  
 "target_modules": [
    "q_proj",
    "v_proj"
  ],
  "task_type": "CAUSAL_LM"
```

**Comment by suchunxie** [comment]
That's very considerable! Thanks very much & best wishes.
