### ISSUE TITLE
Selecting LoRA layers from PeftModel

### ISSUE THREAD

**Issue by PCanavelli** [huggingface/peft#1292]
Hi everyone,

I've been strunggling with what may just be an API usage issue as of late.

The use case is a follows: I am training a diffusion model with LoRA adapters in both the text encoder and UNet. I would like to selectively change the dtype and activate/deactivate the gradients of the LoRA layers, without impacting the base model. What would be the cleanest way to go about it?

Cheers

**Comment by BenjaminBossan** [comment]
Could you show a little bit of code, like how you create the model? That way, it's easier to point you to a solution.
