### ISSUE TITLE
using LORA with multi-gpu

### ISSUE THREAD

**Issue by wxyzjp123** [huggingface/peft#1296]
### System Info

Pytorch DP

### Who can help?

@pacman100 @younesbelkada @sayakpaul

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

model = AutoModel.from_pretrained(checkpoint, config=config, trust_remote_code=True)
model = CreateModel(model, config, tokenizer)
model = get_peft_model(model, peft_config)
model.print_trainable_parameters()
model.to(device)
if n_gpu > 1:
        model = torch.nn.DataParallel(model)

### Expected behavior

model = AutoModel.from_pretrained(checkpoint, config=config, trust_remote_code=True)
model = CreateModel(model, config, tokenizer)
model.to(device)
if n_gpu > 1:
        model = torch.nn.DataParallel(model)
model = get_peft_model(model, peft_config)
model.print_trainable_parameters()
I am fine-tuning a bert-based model using LORA, I have no problem with single GPU, I get an error when I use multiple GPUs (Pytorch DP): AttributeError: 'DataParallel' object has no attribute 'config'. 

When I try to call get_peft_model first and then use Pytorch DP (if n_gpu > 1:model = torch.nn.DataParallel(model)), it also gives an error AttributeError: 'DataParallel' object has no attribute 'encoder'
model = AutoModel.from_pretrained(checkpoint, config=config, trust_remote_code=True)
model = CreateModel(model, config, tokenizer)
model = get_peft_model(model, peft_config)
model.print_trainable_parameters()
model.to(device)
if n_gpu > 1:
        model = torch.nn.DataParallel(model)

**Comment by sayakpaul** [comment]
IIUC you need to unwrap the actual model from data-parallel model.

**Comment by wxyzjp123** [comment]
Thanks for your reply, I changed it as I understood your reply (I'm not sure if I understood it correctly) and although it did run successfully, it may only used single gpu, not multiple gpus.

modified code is as follows：
model.to(device)
if n_gpu > 1:
        model = torch.nn.DataParallel(model)
model = model.module
model = get_peft_model(model, peft_config)
model.print_trainable_parameters()

**Comment by wxyzjp123** [comment]
> IIUC you need to unwrap the actual model from data-parallel model.

Thanks for your reply, I changed my code as I understood your reply (I'm not sure if I understood it correctly) and although it did run successfully, it actually only used single gpu, not multiple gpus.

The modified code is as follows:

model.to(device)
if n_gpu > 1:
         model = torch.nn.DataParallel(model)
model = model.module
model = get_peft_model(model, peft_config)
model.print_trainable_parameters()

**Comment by wxyzjp123** [comment]
> [<img alt="@wxyzjp123" width="40" height="40" src="https://avatars.githubusercontent.com/u/59395733?s=80&amp;v=4">](/wxyzjp123)
> 
> 
> #### Add a comment
> Comment



> IIUC you need to unwrap the actual model from data-parallel model.

Thank you for your reply, I changed the code as I understood your reply (I'm not sure I understood it correctly) and although it did run successfully, only single gpu was actually used, not multiple gpus.

<img width="535" alt="截屏2023-12-25 14 55 33" src="https://github.com/huggingface/peft/assets/59395733/0e483d21-9d53-46fe-869f-c1513e47292e">

**Comment by wxyzjp123** [comment]
> IIUC you need to unwrap the actual model from data-parallel model.

Thanks for your reply, I changed the code as I understood your reply (I'm not sure if I understood it correctly), and although it did run successfully, only single gpu was actually used, not multiple gpus.
<img width="535" alt="截屏2023-12-25 14 55 33" src="https://github.com/huggingface/peft/assets/59395733/05531496-504a-4f63-a7fe-481f72fb4629">

**Comment by younesbelkada** [comment]
Hi @wxyzjp123 
You need to wrap your model in a DDP after creating the PeftModel. Can you try to call `model = torch.bb.DataParallel(model)` after `model.print_trainable_parameters()` ?

**Comment by wxyzjp123** [comment]
> Hi @wxyzjp123 You need to wrap your model in a DDP after creating the PeftModel. Can you try to call `model = torch.bb.DataParallel(model)` after `model.print_trainable_parameters()` ?

Thanks for the reply, it worked. By the way, I was wondering why using lora didn't shorten the time per epoch (even slightly more), is this normal? And is there anything else I can focus on for lora to take effect besides training time?
