### ISSUE TITLE
[Question] What is the main difference between "modules_to_save" and "target_modules"?

### ISSUE THREAD

**Issue by SatireY** [huggingface/peft#1298]
Hi, in my work I need to add some special token to LLAMA, so I need to train the parameter of ["embed_tokens", "lm_head"] for both layers, what confuses me is that should I add this parameter to LoraConfig's "modules_to_save " or "target_modules"? Looking forward to your reply!

**Comment by SatireY** [comment]
@BenjaminBossan I noticed that you have answered relevant questions before, could you give me some help? Thank you

**Comment by younesbelkada** [comment]
Hi @SatireY 
Thanks for the issue, please refer to this specific example: https://github.com/huggingface/peft/blob/main/examples/causal_language_modeling/peft_lora_clm_with_additional_tokens.ipynb from @pacman100 when doing CLM + training on additional tokens

**Comment by SatireY** [comment]
> Hi @SatireY Thanks for the issue, please refer to this specific example: https://github.com/huggingface/peft/blob/main/examples/causal_language_modeling/peft_lora_clm_with_additional_tokens.ipynb from @pacman100 when doing CLM + training on additional tokens

Thank you for your quick reply. I have checked this ipynb notebook. The configuration used by the author is as follows:
"config = LoraConfig(
r=64, lora_alpha=128, lora_dropout=0.0, target_modules=["embed_tokens", "lm_head", "q_proj", "v_proj"]
)"
He uses "target_modules" but doesn't explain why he doesn't use "modules_to_save ", which doesn't answer my question.

**Comment by BenjaminBossan** [comment]
`target_modules` is for modules that should get LoRA applied to, `modules_to_save` is for modules that should be fine-tuned normally, without LoRA (all other modules will be kept frozen).

For your use case, you should add the `lm_head` to `modules_to_save` and try if fine-tuning the embeddings (i.e. adding them to `target_modules`) is sufficient for good training results.
