### ISSUE TITLE
prepare_model_for_int8_training assumes layernorm layers contain the string"layer_norm"

### ISSUE THREAD

**Issue by edbeeching** [huggingface/peft#130]
prepare_model_for_int8_training assumes layernorm layers contain the string "layer_norm"
This is not always the case. Some models call this "ln", some "layernorm". Perhaps make this an argument?

**Comment by pacman100** [comment]
Hello @edbeeching, please let us know if the above PR resolves the issue

**Comment by edbeeching** [comment]
@pacman100 That solution looks perfect. Thank you.
