### ISSUE TITLE
Regarding bugs generated by tasks that require the addition of custom tokens.

### ISSUE THREAD

**Issue by SatireY** [huggingface/peft#1300]
### System Info

peft==0.7.1

### Who can help?

@BenjaminBossan 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

This is my raw code, I need to fine-tune the LLAMA model on my dataset, and I need to add some dedicated tokens ，（token_{i}As input, i as label).
```
# LLAMA Tokenizer and model
tokenizer = LlamaTokenizer.from_pretrained(config.checkpoints.path)
model = LlamaForCausalLM.from_pretrained(
    config.checkpoints.path,
    load_in_8bit=True,
    device_map="auto",
    torch_dtype=torch.float16,
)

tokenizer.add_tokens([f"<token_{i}>" for i in range(1025)])

tokenizer.add_tokens([f"{i}" for i in range(257)])

model.resize_token_embeddings(len(tokenizer))

eval_prompt = """
Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.
### Instruction:
task name

### Input:
Front:<token_796><token_301><token_559><token_801><token_272><token_514><token_87><token_272>

### Response:
"""

model_input = tokenizer(eval_prompt, return_tensors="pt").to(model.device)
model.eval()
    with torch.no_grad():
        print("before train")
        print(
            tokenizer.decode(
                model.generate(**model_input, max_new_tokens=100)[0],
                skip_special_tokens=True,
            )
        )
peft_config = LoraConfig(
        task_type=TaskType.CAUSAL_LM,
        inference_mode=False,
        r=8,
        lora_alpha=32,
        lora_dropout=0.05,
        target_modules=["q_proj", "v_proj"],
    )
model = prepare_model_for_kbit_training(model)
model = get_peft_model(model, peft_config)
train_config = {
        "lora_config": peft_config,
        "learning_rate": 1e-4,
        "num_train_epochs": config.train.num_train_epochs,
        "gradient_accumulation_steps": 2,
        "per_device_train_batch_size": 2,
        "gradient_checkpointing": False,
    }
training_args = TrainingArguments(
        output_dir=output_dir,
        # report_to=config.train.report_to,
        overwrite_output_dir=True,
        bf16=True,  # Use BF16 if available
        # logging strategies
        logging_dir=f"{output_dir}/logs",
        logging_strategy="steps",
        logging_steps=10,
        save_strategy="no",
        # optim="adamw_torch_fused",
        optim="paged_adamw_32bit",
        max_steps=total_steps if enable_profiler else -1,
        **{k: v for k, v in train_config.items() if k != "lora_config"},
    )
trainer = Trainer(
            model=model,
            args=training_args,
            train_dataset=train_dataset,
            data_collator=default_data_collator,
            callbacks=[profiler_callback] if enable_profiler else [],
        )

        # Start training
        trainer.train()
model.eval()
    with torch.no_grad():
        print("After train")
        print(
            tokenizer.decode(
                model.generate(**model_input, max_new_tokens=100)[0],
                skip_special_tokens=True,
            )
        )
model.save_pretrained(output_dir)
tokenizer.save_pretrained(output_dir)
```
The above is the code I trained. After the training, I first called generate method to check whether the model was successfully fine-tuned (it could be called normally in the training script). Then I called save_pretrained(output_dir) method to save the model. I found that the save_pretrained(output_dir) method did not hold ["embed_tokens" and "lm_head"] by default. When I tried to use a trained model for inference, I got an cuda error:
```
# This is another file
tokenizer = LlamaTokenizer.from_pretrained("tmp/llama-output")

model = LlamaForCausalLM.from_pretrained(
    "tmp/llama-output",
    load_in_8bit=True,
    device_map="auto",
    torch_dtype=torch.float16,
)
eval_prompt = """
Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.
### Instruction:
task name

### Input:
Front:<token_796><token_301><token_559><token_801><token_272><token_514><token_87><token_272>

### Response:
"""

model_input = tokenizer(eval_prompt, return_tensors="pt").to(model.device)
model.eval()
with torch.no_grad():
    print("After train")
    print(
        tokenizer.decode(
            model.generate(**model_input, max_new_tokens=100)[0],
            skip_special_tokens=True,
        )
    )
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:09<00:00,  1.65s/it]
After train
../aten/src/ATen/native/cuda/Indexing.cu:1141: indexSelectLargeIndex: block: [78,0,0], thread: [32,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1141: indexSelectLargeIndex: block: [78,0,0], thread: [33,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
```
adapter_config.json:
```
{
  "alpha_pattern": {},
  "auto_mapping": null,
  "base_model_name_or_path": "checkpoints/llama2",
  "bias": "none",
  "fan_in_fan_out": false,
  "inference_mode": true,
  "init_lora_weights": true,
  "layers_pattern": null,
  "layers_to_transform": null,
  "loftq_config": {},
  "lora_alpha": 32,
  "lora_dropout": 0.05,
  "megatron_config": null,
  "megatron_core": "megatron.core",
  "modules_to_save": null,
  "peft_type": "LORA",
  "r": 8,
  "rank_pattern": {},
  "revision": null,
  "target_modules": [
    "v_proj",
    "q_proj"
  ],
  "task_type": "CAUSAL_LM"
}
```

### Expected behavior

model.resize_token_embeddings(len(tokenizer)) is usually performed to add custom tokens to the initial LLM. The default save_pretrained() behavior is not saved. I think this is logically missing. The save_pretrained() method should be able to save ["embed_tokens", "lm_head"] by default,That's the first question.

**Comment by SatireY** [comment]
After that, I added the parameters modules_to_save=["embed_tokens", "lm_head"] in LoraConfig, which made the checkpoint do hold both layers of parameters, but again ran into problems when I tried to load them. 
```
RuntimeError: Error(s) in loading state_dict for LlamaForCausalLM:
        size mismatch for model.embed_tokens.modules_to_save.default.weight: copying a param with shape torch.Size([33272, 4096]) from checkpoint, the shape in current model is torch.Size([32000, 4096]).
        size mismatch for lm_head.modules_to_save.default.weight: copying a param with shape torch.Size([33272, 4096]) from checkpoint, the shape in current model is torch.Size([32000, 4096]).
```
The weight of the model loaded from adapter_model is still only 32000 token embedding size. I have to load it from the base model checkpoint and then execute the following code to properly reason with the trained model:
```
tokenizer = LlamaTokenizer.from_pretrained("tmp/llama-output")

model = LlamaForCausalLM.from_pretrained(
    "tmp/llama-output",
    load_in_8bit=True,
    device_map="auto",
    torch_dtype=torch.float16,
)
model = LlamaForCausalLM.from_pretrained(
    config.checkpoints.path,
    load_in_8bit=True,
    device_map="auto",
    torch_dtype=torch.float16,
)
# redo resize
model.resize_token_embeddings(len(tokenizer))
model = PeftModel.from_pretrained(model, "tmp/llama-output/logs_test")
```
Although my problem was eventually solved, I think it was missing in the implementation logic of the peft library, which was confusing for tasks that needed to add custom tokens. I could reason directly in the training script, and I didn't realize that the saved model didn't record my changes to the embedded layer. Being a peft newbie might not be too friendly, and I spent the day reading about related issues to solve my problems. Look forward to improvements.

**Comment by SatireY** [comment]
By the way, I tried to save after calling Model.merge_and_unload () during the process of solving the problem, which I think can save all model weights including ["embed_tokens" and "lm_head"] layers, I added the code as follows:
```
model = model.merge_and_unload()
    model.save_pretrained(output_dir)
    tokenizer.save_pretrained(output_dir)
    with torch.no_grad():
        print("After merge")
        print(
            tokenizer.decode(
                model.generate(**model_input, max_new_tokens=100)[0],
                skip_special_tokens=True,
            )
        )
```
This saves the entire model weight directly in the save directory, which gives normal results in my training script:
```
before train

Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.
### Instruction:
task name

### Input:
Front:<token_796><token_301><token_559><token_801><token_272><token_514><token_87><token_272>

### Response:
"""
    
    <token_123>......
    ms
    182 

    mis（messy output）
```

```
After train

    Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.
### Instruction:
task name

### Input:
Front:<token_796><token_301><token_559><token_801><token_272><token_514><token_87><token_272>

### Response:
 217 115 32 51 39 128 180 0 (right output)
```
```
After merge

    Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.
### Instruction:
task name

### Input:
Front:<token_796><token_301><token_559><token_801><token_272><token_514><token_87><token_272>

### Response:
  217 115 32 51 39 128 180 0 (right output)
```
But when I used another inference script to load the saved model, I got confused output. I thought the problem was with the Model.save_pretrained (output_dir) method.

**Comment by BenjaminBossan** [comment]
Thanks for reporting this. As you mention, we indeed offer a solution but it could be better documented. Do you have a suggestion where in the documentation we could best put that information?

> By the way, I tried to save after calling Model.merge_and_unload () during the process of solving the problem

Note that if you do that, you will save the _whole model_, not only the adapter, resulting in a much larger file. Depending on your use case, you may want to avoid that. Also, it means that you cannot disable the adapter anymore after loading, which could also be something you may need.

**Comment by SatireY** [comment]
> Thanks for reporting this. As you mention, we indeed offer a solution but it could be better documented. Do you have a suggestion where in the documentation we could best put that information?
> 
> > By the way, I tried to save after calling Model.merge_and_unload () during the process of solving the problem
> 
> Note that if you do that, you will save the _whole model_, not only the adapter, resulting in a much larger file. Depending on your use case, you may want to avoid that. Also, it means that you cannot disable the adapter anymore after loading, which could also be something you may need.

Thanks for your reply, I think you can explain some of the fine-tuning scenarios that require changes to the vocabulary in the documentation, which may be more friendly to peft newobs. Specifically, you and I think we can add instructions for this scenario here（https://huggingface.co/docs/peft/v0.7.1/en/tutorial/peft_model_config）.
