### ISSUE TITLE
training a multi-adapter model

### ISSUE THREAD

**Issue by denizyuret** [huggingface/peft#1303]
Based on https://huggingface.co/docs/transformers/v4.36.1/en/peft I used to be able to train a multi-adapter model with:
```
trainer = Trainer(...)
trainer.model.add_adapter(lora_config, adapter_name='adapter1')
trainer.model.add_adapter(lora_config, adapter_name='adapter2')
trainer.model.set_adapter('adapter1')
trainer.train()
trainer.model.set_adapter('adapter2')
trainer.train()
```
This used to work with peft-0.5.0 but stopped working with peft-0.6.0 (the second adapter does not train). Did something change with set_adapter after 0.5.0? Am I using the interface wrong?

**Comment by younesbelkada** [comment]
Hi @denizyuret 
Hmm this should work .. Can you try with peft==0.7.1?

**Comment by denizyuret** [comment]
peft 0.7.1 is also broken.

**Comment by younesbelkada** [comment]
Hmm I need to investigate then, does temporarly setting `requires_grad=True` to the adapters fixes the issue?

**Comment by BenjaminBossan** [comment]
Yes, could you please check that the correct parameters have `requires_grad` set to `True` when you switch the active adapter?

**Comment by denizyuret** [comment]
`requires_grad` seems to be correctly set for the active adapter after the switch.

I don't know if this will help: if I keep switching back and forth between the two adapters, only the first adapter which went through training gets modified when it is active, nothing gets modified when the other is active.

**Comment by younesbelkada** [comment]
@denizyuret how your base model is loaded? if you use accelerate perhaps something is off with forward hooks but really not sure

**Comment by denizyuret** [comment]
Here is a minimal example: https://github.com/denizyuret/peft-debug
Usage: ./train.py --output_dir=out --num_train_epochs=1 --gradient_checkpointing=True --per_device_train_batch_size=1
Should show that the second adapter does not train (unless using peft==0.5.0)

**Comment by denizyuret** [comment]
Also, please re-open https://github.com/huggingface/peft/issues/1059 -- we still have no consistent way to save/load multi-adapter models from disk or from hub.

**Comment by BenjaminBossan** [comment]
I ran your script with a few modifications. Just to be sure, is the error you're getting:

> AssertionError: No inf checks were recorded for this optimizer.

The following line fixed the error for me:

```python
    ...
    trainer.model.set_adapter('adapter1')
    [mod.requires_grad_(True) for n, mod in trainer.model.named_modules() if "lora" in n]
    trainer.train()
    ...
```

I also checked the weights for both adapters to confirm that only the correct adapter is being updated. Could you please confirm whether the error is the same that you're getting and whether the extra lines fixes the error?

**Comment by denizyuret** [comment]
@BenjaminBossan (1) I do not get the error you get, everything runs ok, adapter2 just doesn't train in the original script. (2) After adding your modification adapter2 started training for me, it seems to have fixed the problem. I checked in a couple of extra files in https://github.com/denizyuret/peft-debug to help:
- conda.list and pip.list have the package versions I am using.
- train.out and train2.out show the output I get from the original and modified versions of the script.

**Comment by BenjaminBossan** [comment]
> After adding your modification adapter2 started training for me, it seems to have fixed the problem

Okay, great. My suspicion of what's happening is that `Trainer` somehow out parameters without `requires_grad=True` when initializing the optimizer:

https://github.com/huggingface/transformers/blob/5be46dfc094a5028efdb7ca13a04f35a0323259c/src/transformers/trainer.py#L940-L953

This is why the second adapter, which is inactive at the beginning, does not train after switching. In earlier versions of PEFT, we didn't bother to set `requires_grad=False` correctly when the adapter was inactive. This has now been fixed, but it causes the issue you described.

I think another way could be to initialize the optimizer manually, including all parameters, then passing that to `Trainer`:

```python
optimizer = torch.optim.AdamW(model.parameters(), ...)
trainer = Trainer(..., optimizers=(optimizer, <scheduler or None>))
```

I don't have experience with `Trainer`, so this is just a guess. Anyway, if this works, it would be preferable, as my code snippet would activate gradients on all adapters, even if inactive. Theoretically, this should not cause trouble, as those inactive adapters don't participate in the forward pass. But it's better to be safe and also PyTorch DDP doesn't like that.

> I checked in a couple of extra files in https://github.com/denizyuret/peft-debug to help:

Thanks, but I think we've identified the issue. I had to make some changes to make it run on my machine with little GPU memory :)

**Comment by BenjaminBossan** [comment]
@denizyuret Just a small update. We discussed this internally and the filter for the parameters in `Trainer` that I referenced above are necessary for it to work correctly with DeepSpeed, so this cannot be changed.

If my solution of manually enabling gradients works for you, then it should be good (it could cause issues with DDP though). Alternatively, you could instantiate a separate optimizer for the 2nd adapter and pass that to the `Trainer` instance when you want to train the 2nd adapter, that could be a cleaner solution.
