### ISSUE TITLE
Does peft support to save and load lora weights for a customed model

### ISSUE THREAD

**Issue by stardusts-hj** [huggingface/peft#1306]
### System Info

peft transformers diffusers

### Who can help?

@pacman100 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

lora_state_dict =  get_peft_model_state_dict(accelerator.unwrap_model(model), adapter_name="default")
accelerator.save(lora_state_dict,lora_path)

### Expected behavior

When I have my own model like this
`
from peft import LoraConfig, get_peft_model, get_peft_model_state_dict
model = My_model()   
lora_config = LoraConfig(
        r=64,
        target_modules=[
            "to_q",
            "to_k",
            "to_v",])
model = get_peft_model(model, lora_config)
`
,then I trained lora weights,
for saving, is it correct to use the following
`
lora_state_dict =  get_peft_model_state_dict(accelerator.unwrap_model(model), adapter_name="default")
accelerator.save(lora_state_dict,lora_path)
`
**However**, while I load the lora to models, I didn't find a simple way to load lora weights to a new model

**Comment by younesbelkada** [comment]
Hi @stardusts-hj 
Thanks for the issue, you need to design your own weight loading logic
You can check out what we do in transformers: https://github.com/huggingface/transformers/blob/main/src/transformers/integrations/peft.py#L206 we use `set_peft_model_state_dict` method

**Comment by BenjaminBossan** [comment]
Did you try just doing `model.save_pretrained(...)` on the PEFT model, and later loading with `PeftModel.load_pretrained(my_custom_model, ...)`? If you're using accelerate, you may also have to check on the accelerator object if it's the main process to avoid possible clashes.

**Comment by stardusts-hj** [comment]
> get_peft_model_state_dict(accelerator.unwrap_model(model), adapter_name="default")

Thanks, I will check that in accelerator

**Comment by stardusts-hj** [comment]
> younesbelkada

Thanks, 'set_peft_model_state_dict' method real solves my problems to load lora weights to my customed models.

**Comment by younesbelkada** [comment]
Awesome, thanks @stardusts-hj @BenjaminBossan !
