### ISSUE TITLE
AdaLora SVDLayer dtype error in inference

### ISSUE THREAD

**Issue by yileld** [huggingface/peft#1309]
### System Info

peft==0.6.2
transformers==4.32.0

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

I trained AdaLora with Qwen model, and load the model in inference using AutoModelForCausalLM.from_pretrained().

```
  self.model = AutoModelForCausalLM.from_pretrained(path, **model_kwargs)
  if peft_path is not None:
      from peft import PeftModel
      self.model = PeftModel.from_pretrained(self.model,
                                             peft_path,
                                             is_trainable=False)
```

But encountered the problem.

```
File "/usr/local/lib/python3.10/dist-packages/peft/tuners/adalora/layer.py", line 175, in forward
    result += (dropout(x) @ (lora_A * lora_E).T @ lora_B.T) * scaling / ranknum
RuntimeError: expected mat1 and mat2 to have the same dtype, but got: c10::BFloat16 != float
```

I read the code of peft/tuners/adalora/layer.py and found the code annotation 

```
line 163
# TODO: SVDLinear does not convert dtype, unlike lora linear, is that correct?
```

It seems not converting dtype is the reason.

### Expected behavior

I fix the bug by adding

`self.model.to(torch.bfloat16)`

Is it in the todo list to convert dtype like lora?

**Comment by BenjaminBossan** [comment]
What is your intent? Do you want to run the model with bfloat16 or using float? If the former, your fix should be okay.
