### ISSUE TITLE
Lora converted with convert_peft_sd_lora_to_kohya_ss is unusable

### ISSUE THREAD

**Issue by Dentoty** [huggingface/peft#1329]
### System Info

Google Colab
ftfy-6.1.3
accelerate-0.25.0 
datasets-2.16.1 
diffusers-0.25.0 
dill-0.3.7 
evaluate-0.4.1 
multiprocess-0.70.15 
peft-0.7.1 
pyarrow-hotfix-0.6 
responses-0.18.0

### Who can help?

@kovalexal

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

**Train an example lora:**

```
MODEL_NAME="runwayml/stable-diffusion-v1-5"
INSTANCE_DIR=""
OUTPUT_DIR=""

!accelerate launch train_dreambooth.py \
  --pretrained_model_name_or_path=$MODEL_NAME  \
  --instance_data_dir=$INSTANCE_DIR \
  --output_dir=$OUTPUT_DIR \
  --instance_prompt="2h749hf0j24f" \
  --resolution=512 \
  --train_batch_size=1 \
  --prior_loss_weight=1.0 \
  --train_text_encoder \
  --train_batch_size=1 \
  --sample_batch_size=4 \
  --num_train_epochs=1 \
  --use_lora \
  --max_train_steps=800 \
  --gradient_checkpointing \
  --learning_rate=1e-4 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --lr_num_cycles=1 \
  --lr_power=1.0
```
  
**Convert the end result - it converts successfully:**
```
MODEL_NAME="runwayml/stable-diffusion-v1-5"
LORA_DIR=""
SAFETENSOR_OUTPUT_DIR="pytorch_lora_weights.safetensors"

!accelerate launch convert_peft_sd_lora_to_kohya_ss.py \
  --sd_checkpoint=$MODEL_NAME \
  --peft_lora_path=$LORA_DIR \
  --dump_path=$SAFETENSOR_OUTPUT_DIR
```
  
  
**Test the end result:**
```python
import torch
from diffusers import StableDiffusionPipeline, DPMSolverMultistepScheduler

pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    safety_checker=None,
    torch_dtype=torch.float16,
    token=""
    ).to("cuda")
pipe.scheduler = DPMSolverMultistepScheduler.from_config(pipe.scheduler.config, num_train_timesteps=1000, beta_start=0.00085, beta_end=0.012, use_karras_sigmas=True, beta_schedule="scaled_linear", solver_order=2, steps_offset=1, clip_sample=False, algorithm_type="sde-dpmsolver++")

pipe.load_lora_weights("path/to/lora/folder", weight_name="pytorch_lora_weights.safetensors")

prompt = "2h749hf0j24f"
image = pipe(prompt=prompt, num_inference_steps=30, guidance_scale=8).images[0]
display(image)
```

The lora saves and loads successfully but the trained character is missing after using the conversion script.
This happens while using the code above and also when using Automatic1111 to try out the converted lora.

### Expected behavior

From what I undestand the original PEFT lora has 2 folders, unet and text_encoder, which the script will merge into a single .safetensors file but the end result is that the trained character/concept ends up missing even when using the correct keyword and loading the lora properly.

**Comment by BenjaminBossan** [comment]
Thanks for reporting. Could you share the LoRA adapter you're trying to load (before and after conversion)? Also, do you see any warnings when running the script that indicate what may have gone wrong?

**Comment by kovalexal** [comment]
@Dentoty, hi!

Thanks for bringing it in. This script is currently a bit outdated, I'll update it soon.

**Comment by Dentoty** [comment]
@BenjaminBossan 

Here you go - https://file.io/nAPrQ8EtmYIm

As I prepared the files I also noticed the .safetensors file is only 16B which means that there was a faliure or something that might have not been handled or supressed.

There is one warning during loading the lora:
pipe.load_lora_weights("/path", weight_name="pytorch_lora_weights.safetensors")

/usr/local/lib/python3.10/dist-packages/diffusers/loaders/lora.py:407: FutureWarning: `unet.unet keys` is deprecated and will be removed in version 0.27. Keys starting with 'unet.unet' are deprecated.
  deprecate("unet.unet keys", "0.27", deprecation_message)

**Comment by kovalexal** [comment]
@Dentoty I tried to replicate this issue (with the LoRA you've provided), but the conversion went fine. The output checkpoint size is around 17MB in fp32.

I used the following environment:

- cuda:11.8.0-devel-ubuntu22.04
- transformers==4.27.3
- accelerate==0.21.0
- peft==0.7.1
- diffusers==0.25.0

The following code was used for conversion:
```bash
python3 /workspaces/peft/examples/lora_dreambooth/convert_peft_sd_lora_to_kohya_ss.py \
--sd_checkpoint="runwayml/stable-diffusion-v1-5" \
--peft_lora_path=/workspaces/peft/sample_networks/failed_lora/Original \
--dump_path=my_conversion.safetensors
```

```console
(peft) root@klg-gpu-003:/workspaces/peft# du -hs sample_networks/failed_lora/safetensors/my_conversion.safetensors 
17M     sample_networks/failed_lora/safetensors/my_conversion.safetensors
(peft) root@klg-gpu-003:/workspaces/peft# du -hs sample_networks/failed_lora/safetensors/pytorch_lora_weights.safetensors 
4.0K    sample_networks/failed_lora/safetensors/pytorch_lora_weights.safetensors
```

Apparently, there was some error during conversion in your case (the `.safetensors` file you've provided contains no tensors). Could you try to convert it again?

**Comment by Dentoty** [comment]
@kovalexal you are correct, the issue was a misspelling of the peft_lora_path. 
The script still works as expected.
