### ISSUE TITLE
Training a PeftModel loaded with `from_pretrained` causes a grad-related RuntimeError

### ISSUE THREAD

**Issue by EricLBuehler** [huggingface/peft#1340]
Hello everybody,

I am continuing to experiment with LoRA adapters, and ran into an issue when trying to train with multiple adapters. I also inject trainable parameters into the output of each LoRA layer, which necessarily means they have gradients.

I have boiled the error down to the following code:

```python
from peft.peft_model import PeftModel

model = AutoModelForCausalLM.from_pretrained(...)

model = PeftModel.from_pretrained(model,
                                       './Mistral_v120Zephyr/checkpoint-30780/',
                                       'Bioinspired', False)

# Code to inject trainable parameters
...

# Setup the trainer
...

trainer.train()
```

This results in the following error:
`RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn`.
The traceback occurs when the trainer initiates the `backward` pass on the weights.

Adding a Pytorch forward hook with `register_forward_hook` that prints the output gives:
```python
output=CausalLMOutputWithPast(loss=tensor(2.3833, device='cuda:0'), logits=tensor([[[-5.8750, -5.8125, -0.2158,  ..., -4.1562, -3.6719, -3.8906],
         [-8.9375, -8.0625,  1.8359,  ..., -8.0625, -7.2188, -4.4062],
         [-3.5000, -3.0625,  2.8594,  ..., -2.6562, -2.1250, -1.5391],
         ...,
         [-4.0625,  5.7812,  2.9531,  ..., -3.8906, -4.3750, -1.7188],
         [-6.6250, -5.5000,  2.6719,  ..., -6.4688, -4.5312, -3.9219],
         [-6.3750, -4.0938, 15.0000,  ..., -3.7656, -4.3750, -3.5312]]],
       device='cuda:0'), past_key_values=None, hidden_states=None, attentions=None)
```

I note that there is no `grad_fn`, and `requires_grad` is not `True`.  To me, this seems to indicate that the gradient from the trainable parameters being injected into the LoRA layers is not propagating through the layers and as such the output has no gradient graph.

Ultimately, my question is the following: Am I using the `.from_pretrained` method incorrectly, or is this problem related to my injection of trainable parameters? Thank you for any help!

**Comment by BenjaminBossan** [comment]
When you called `from_pretrained`, you passed `False` as 4th argument, which is the `is_trainable` parameter. Could you please retry with `is_trainable=True`?

**Comment by EricLBuehler** [comment]
Thank you, that helped to point me in the direction of fixing it! The issue was actually in the way I injected the trainable parameter, which caused the same affect as setting that parameter to False.

**Comment by HGGshiwo** [comment]
disable gradient_checkpoint solve the error for me
