### ISSUE TITLE
the generation results contain some null samples

### ISSUE THREAD

**Issue by FayeXXX** [huggingface/peft#1345]
### System Info

torch==2.1.2
transformers==4.31.0.dev0
bitsandbytes==0.39.1
peft==0.5.0
accelerate==0.25.0
datasets==2.15.0

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction
```
def generate_prompt(source, target=None, eos_token="</s>", ):
    input = f"{source}\n"
    if args.transfer == "infor2form":
        instruction = "Rewrite the following sentence, maintain the content and change the style from informality to formality:\n"
        output = f"Rewrite: {target + ' ' + eos_token if target else ''} "
    prompt = (" ").join([instruction, input, output])
    return prompt

def formatting_func(prompt):
    output = []
    for d, s in zip(prompt["source"], prompt["target"]):
        op = generate_prompt(d, s)
        output.append(op)
    return output

quant_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_use_double_quant=True
)

lora_config = LoraConfig(
        r=16,
        lora_alpha=8,
        lora_dropout=0.05,
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
        bias="none",
        task_type="CAUSAL_LM",
    )
```
### Expected behavior

I finetune Llama-2 with LORA bf16, after the  finetuning process, I load the checkpoint and do the test with 500 samples, but get almost 30 samples reply nothing or '\n'. Do you have any ideas how to fix it?

**Comment by BenjaminBossan** [comment]
Honestly these types of issues are super hard to debug. It doesn't sound like a LoRA issue per se, maybe the model was not trained well enough or some training samples are empty for some reason? Are these 30 empty generations always for the same samples or random? Can you get a result when you try the same prompt multiple times?
