### ISSUE TITLE
'PeftModelForCausalLM' object has no attribute 'base_model' for a deepspeed stage 3 model

### ISSUE THREAD

**Issue by olegsinavski** [huggingface/peft#1349]
### System Info

```
peft==0.7.1
transformers==4.36.2
deepspeed==0.12.4
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

Hello! I'm facing the issue with `deepspeed==0.12.4`, stage3, `transformers==4.36.2` and `peft==0.7.1`:
```
AttributeError: 'PeftModelForCausalLM' object has no attribute 
'_ds_child_entered'
....
....
  File ".../site-packages/peft/peft_model.py", line 528, in __getattr__
    return super().__getattr__(name)  # defer to nn.Module's logic
  File ".../torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'PeftModelForCausalLM' object has no attribute 'base_model'
``` 
and eventually
```
RecursionError: maximum recursion depth exceeded while calling a Python object
```

I'm using `pytorch lightning`:
```python
trainer = Trainer(
    ...
    strategy = DeepSpeedStrategy(stage=3)
)

class Module(LightningModule):
    def configure_model(self) -> None:
        deepspeed_config = self.trainer.strategy.config
        self.dschf = HfDeepSpeedConfig(deepspeed_config)
        model = AutoModelForCausalLM.from_pretrained(...)
        model = get_peft_model(
            model,
            LoraConfig(
                task_type=TaskType.CAUSAL_LM,
                inference_mode=False,
                target_modules=target_modules,
                r=48,
                lora_alpha=16,
                lora_dropout=0.0,
            ),
        )

```

When deepspeed 3 is activated, transformers use some custom hooks to init the model differently. Apparently, that doesn't go well with `peft` assumptions.

### Expected behaviour

get_peft_model succeeds without an error

**Comment by BenjaminBossan** [comment]
Yeah, DS 3 might not work well with the added adapter layers. Still, could you show more code and the full error message, maybe it helps digging deeper.

**Comment by ret-1** [comment]
Hi @olegsinavski ,

I found this problem is due to the implementation of `PeftModel`:
https://github.com/huggingface/peft/blob/7ffa43b16e4625322c9f157db12c9358f2f54cdf/src/peft/peft_model.py#L664-L669

Here is the explaination:
In deepspeed, it uses a decorator to wrap the `__init__` function of models, and in the decorator it will call `hasattr` function, which will cause the recursion. 
```python
# a simple code to show what happened
class PeftModel:
    def __init__(self, model):
        self.base_model = model
    
    def __getattr__(self, name):
        try:
            return super().__getattr__(name)
        except AttributeError:
            # recursion error
            return getattr(self.base_model, name)
        
import functools
def d(f):
    # this decorator is used in deepspeed
    @functools.wraps(f)
    def wrapper(module, *args, **kwargs):
        if not hasattr(module, 'abc'):
            print('abc')
        f(module, *args, **kwargs)
    return wrapper

class PeftModelForCausalLM(PeftModel):
    @d
    def __init__(self, model):
        super().__init__(model)

a = PeftModelForCausalLM(1)
```

I think we could try to modify the implementation of `__getattr__`, but I found the easiest way is to modify the code of deepspeed:
https://github.com/ret-1/DeepSpeed/commit/87fab6683027041345afaf017676e216f7fb7729
this works out for me.

**Comment by SunVictor23** [comment]
pip install unsloth==2025.2.2     is ok
