### ISSUE TITLE
is there a reason why generate with Prompt Tuning would be different for Seq2Seq_LM?

### ISSUE THREAD

**Issue by aldopareja** [huggingface/peft#135]
I'm trying to use prompt tuning for conditional generation but it's still not there, I'm wondering if the same modifications done [here](https://github.com/huggingface/peft/commit/bdeb3778d0a35d0fd66f87f884e6f8fe32ecf705) would be alright.

Thank you!

**Comment by djaym7** [comment]
+1

**Comment by djaym7** [comment]
@pacman100

**Comment by wise-east** [comment]
+1

**Comment by fateme-hshm96** [comment]
I have the same question. @pacman100 🙏🏻
