### ISSUE TITLE
ImportError: cannot import name 'is_g2p_en_available' from 'transformers.utils' (/usr/local/lib/python3.10/dist-packages/transformers/utils/__init__.py)

### ISSUE THREAD

**Issue by kli017** [huggingface/peft#1351]
### System Info

platform: colab
python=3.10
trasformers=4.37.0.dev0
accelerate=0.26.1
peft=0.7.2.dev0

### Who can help?

@younesbelkada Hi, I was run the peft_bnb_whisper_large_v2_training.ipynb from example. Everything is good till I met the error. When I run the code `import evaluate`, the error happen. I also try transformers=4.27.4, 4.33,1 and 4.36.2 and get the same error.
![1705041152061](https://github.com/huggingface/peft/assets/14877573/7ecb36a9-52fa-4750-b403-36dd78907965)

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

Run the peft_bnb_whisper_large_v2_training.ipynb in colab.

### Expected behavior

Anyone can help?

**Comment by BenjaminBossan** [comment]
This appears to be an issue with [evaluate](https://github.com/huggingface/evaluate/issues), please report it there. Please check that you have the latest evaluate version too.
