### ISSUE TITLE
AttributeError: 'LoraModel' object has no attribute 'prepare_inputs_for_generation'

### ISSUE THREAD

**Issue by belegubesa** [huggingface/peft#1358]
### System Info

Python 3.8.0 torch peft==0.4.0 bitsandbytes==0.40.2 transformers==4.31.0 trl==0.4.7 accelerate

### Who can help?

@pacman100 @younesbelkada 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

# LoRA Config
peft_parameters = LoraConfig(
    lora_alpha=16,
    lora_dropout=0.1,
    r=8,
    bias="none",
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
    task_type="CAUSAL_LM"
)

# Training Params
train_params = TrainingArguments(
    output_dir="./results_modified",
    num_train_epochs=1,
    per_device_train_batch_size=4,
    gradient_accumulation_steps=1,
    optim="paged_adamw_32bit",
    save_steps=25,
    logging_steps=25,
    learning_rate=2e-4,
    weight_decay=0.001,
    fp16=False,
    bf16=False,
    max_grad_norm=0.3,
    max_steps=-1,
    warmup_ratio=0.03,
    group_by_length=True,
    lr_scheduler_type="constant",
    report_to="tensorboard"
)

# Trainer
fine_tuning = SFTTrainer(
    model=base_model,
    train_dataset=train_dataset_final,
    peft_config=peft_parameters,
    dataset_text_field="concatenated_text",
    tokenizer=llama_tokenizer,
    args=train_params
)

# Training
fine_tuning.train()

# Save Model
fine_tuning.model.save_pretrained(refined_model)

### Expected behavior

'LoraModel' object has no attribute 'prepare_inputs_for_generation'

I;m using the LoraConfig and the SFTTrainer classes from the PEFT library. The LoraModel class is a part of the library, and I'm using it as-is. The prepare_inputs_for_generation method should be implemented within the LoraModel class itself. 

P.S. using base_model_name = "NousResearch/Llama-2-7b-chat-hf"
and base_model = AutoModelForCausalLM.from_pretrained

**Comment by younesbelkada** [comment]
hi @belegubesa 
can you try to update peft / trl ? `pip install -U peft trl`

**Comment by hanan9m** [comment]
if anyone got a similar error when using "awq" and "peft". I had a problem with converting model that i loaded with
```
model = AutoAWQForCausalLM.from_quantized(model_id)
model = get_peft_model(model, peft_config)
```
and got a similar error.

apparently you need to use the `get_peft_model` function like this:
`model = get_peft_model(model.model, peft_config)`

**Comment by adibMosharrof** [comment]
I am receiving the same errors... has there been any progress on this?

**Comment by ret-1** [comment]
Maybe this is similar to #1349

**Comment by jxmorris12** [comment]
This happened to me when I accidentally loaded a model using `AutoModel.from_pretrained(...)` instead of `AutoModelForCausalLM.from_pretrained(...)`.
