### ISSUE TITLE
Potentially a bug? Dimension mismatch when using adaption_prompt in Llama2

### ISSUE THREAD

**Issue by LEE94-1** [huggingface/peft#1362]
### System Info

peft==0.7.1
transformers==4.31.0

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Code Information

Group Query Attention has been used in LlamaAttention (transformers==4.31.0).
The module `k_proj` and `v_proj` is defined as
```
self.k_proj = nn.Linear(self.hidden_size, self.num_key_value_heads * self.head_dim, bias=config.attention_bias)
self.v_proj = nn.Linear(self.hidden_size, self.num_key_value_heads * self.head_dim, bias=config.attention_bias)
```
So, the output of `k_proj` and `v_proj` is `num_key_value_heads * head_dim`.
But in `adaption_prompt.layer.py`, `adapter_k` and `adapter_v` is calculated by
```
key = getattr(self.model, k_proj_layer)(self.adaption_prompt)
value = getattr(self.model, v_proj_layer)(self.adaption_prompt)

adapter_k = (
    key.view(1, self.adapter_len, self.model.num_heads, self.model.head_dim)
        .repeat(bsz, 1, 1, 1)
        .transpose(1, 2)
    )

adapter_v = (
    value.view(1, self.adapter_len, self.model.num_heads, self.model.head_dim)
        .repeat(bsz, 1, 1, 1)
       .transpose(1, 2)
)
```
The dimension in `key` and `value` is `1, adapter_len, model.num_key_value_heads * model.head_dim`,
and it doesn't match `1, adapter_len, model.num_heads, model.head_dim`.
Maybe it can be fixed by adding an attribute to fit both GQA and MHA. 
The demo is
```
def __init__(...):
    ...
    if hasattr(self.model, num_key_value_heads):
        self.kv_num_heads = getattr(self.model, num_key_value_heads)
    else:
        self.kv_num_heads = getattr(self.model, head_dim)
    ...
```

Also, in `adaption_prompt.utils.py`, the method `llama_compute_query_states` needs to be fixed.

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

```
model = AutoModelForCausalLM.from_pretrained(model_path)
model = get_peft_model(model, adaption_prompt_config)
output = model(**batch)
print(output)
```

### Expected behavior

```
tensor([...])
```

**Comment by BenjaminBossan** [comment]
It's quite possible that there is a bug there. Could you please provide a more complete reproducer so that I can double-check?

**Comment by LEE94-1** [comment]
I'm sorry about that I can't provide the src code. I can't push them online becasuse of my work.  But I think change the `examples/causal_language_modeling
/peft_lora_clm_accelerate_ds_zero3_offload.py:110-113` to 
`
    accelerator = Accelerator()

    model_name_or_path = "meta-llama/Llama-2-7b-chat-hf"

    dataset_name = "twitter_complaints"

    peft_config = AdaptionPromptConfig(task_type=TaskType.CAUSAL_LM, inference_mode=False, target_modules='self_attn', adapter_len=24, adapter_layers=8)`
may reproduce this error.
And my solution is 
In `layer.py`:
```
    def forward(self, **kwargs):
        """
        Forward pass for the adapter which wraps the original LlamaAttention module.

        "Official" paper implementation:
        https://github.com/ZrrSkywalker/LLaMA-Adapter/blob/41c3546fe1997ab8a65809dc8d8f9252b19d9faf/llama/model.py#L141

        Args:
            kwargs: See the original LlamaAttention module.
        """
        if kwargs.get("output_attention", False):
            raise NotImplementedError("output_attention is not currently supported.")

        output, _, past_key_value = self.model(**kwargs)
        bsz = output.shape[0]
        q_len = output.shape[1]
        embed_dim = output.shape[2]
        k_proj_layer = TRANSFORMERS_MODEL_CONFIG[self.model_type].k_proj_layer
        v_proj_layer = TRANSFORMERS_MODEL_CONFIG[self.model_type].v_proj_layer
        o_proj_layer = TRANSFORMERS_MODEL_CONFIG[self.model_type].o_proj_layer

        if k_proj_layer == v_proj_layer:
            _, key, value = getattr(self.model, k_proj_layer)(self.adaption_prompt).split(embed_dim, dim=2)
        else:
            key = getattr(self.model, k_proj_layer)(self.adaption_prompt)
            value = getattr(self.model, v_proj_layer)(self.adaption_prompt)

        # @LEE94-1
        adapter_k = (
            key.view(1, self.adapter_len, self.model.num_key_value_heads, self.model.head_dim)
            .repeat(bsz, 1, 1, 1)
            .transpose(1, 2)
        )

        # @LEE94-1
        adapter_v = (
            value.view(1, self.adapter_len, self.model.num_key_value_heads, self.model.head_dim)
            .repeat(bsz, 1, 1, 1)
            .transpose(1, 2)
        )

        # Recompute query states.
        compute_query_states = TRANSFORMERS_MODEL_CONFIG[self.model_type].compute_query_states
        # (bsz, num_heads, q_len, head_dim)
        query_states = compute_query_states(model=self.model, **kwargs)

        previous_dtype = query_states.dtype

        # @LEE94-1
        mqa_adapter_k = repeat_kv(adapter_k, self.model.num_key_value_groups)
        mqa_adapter_v = repeat_kv(adapter_v, self.model.num_key_value_groups)

        scores = torch.matmul(query_states, mqa_adapter_k.transpose(2, 3).to(previous_dtype)) / math.sqrt(
            self.model.head_dim
        )
        # Upcast attention to fp32
        # (bsz, num_heads, q_len, adapter_len)
        scores = self.adaption_gate * F.softmax(scores, dim=-1, dtype=torch.float32).to(previous_dtype)
        # (bsz, q_len, num_heads * head_dim)
        adapter_output = torch.matmul(scores, mqa_adapter_v).transpose(1, 2).reshape(bsz, q_len, -1)
        # (bsz, q_len, hidden_size)
        if o_proj_layer is not None:
            adapter_output = getattr(self.model, o_proj_layer)(adapter_output)

        # Add adaption prompt output to original output.
        output = output + adapter_output

        # Restore original dtype.
        output = output.to(previous_dtype)
        return output, None, past_key_value
```
In `utils.py`:
```
def llama_compute_query_states(model: nn.Module, **kwargs) -> torch.Tensor:
    """
    Compute query states for Llama models specifically.

    They need to be recomputed as the forward() method of the original LlamaModel in the transformers library does not
    return them. See the related discussion in the PR: https://github.com/huggingface/peft/pull/268
    """
    hidden_states = kwargs.get("hidden_states")
    position_ids = kwargs.get("position_ids")
    past_key_value = kwargs.get("past_key_value")
    bsz, q_len, _ = hidden_states.size()
    query_states = model.q_proj(hidden_states).view(bsz, q_len, model.num_heads, model.head_dim).transpose(1, 2)

    # @LEE94-1
    value_states = model.v_proj(hidden_states).view(bsz, q_len, model.num_key_value_heads, model.head_dim).transpose(1, 2)

    seq_len = q_len
    if past_key_value is not None:
        if isinstance(past_key_value, tuple):
            # for transformers <= 4.35
            seq_len += past_key_value[0].shape[-2]
        else:
            # since transformers 4.36, this is a DynamicCache instance
            seq_len += past_key_value.get_seq_length(model.layer_idx)
    cos, sin = model.rotary_emb(value_states, seq_len=seq_len)

    return llama_apply_rotary_pos_emb(query_states, cos, sin, position_ids)
```
If you want to use these code, please do double-check them first. Because I write them by my memory and can't debug them on my PC.

**Comment by BenjaminBossan** [comment]
Hi, I tried reproducing the error using `peft_lora_clm_accelerate_ds_zero3_offload.py` but it ran fine for me. I did the following modifications to the script:

- `peft_config = AdaptionPromptConfig(task_type=TaskType.CAUSAL_LM, inference_mode=False, target_modules='self_attn', adapter_len=24, adapter_layers=8)`
- `model_name_or_path = "meta-llama/Llama-2-7b-chat-hf"`
- Used bnb 4bit quantization because of memory constraints
- Ran without parallelism, no DeepSpeed

**Comment by LEE94-1** [comment]
Oh, it's my fault.

**Comment by LEE94-1** [comment]
Oh, it's my fault. Llama2 use gqa in 34B and 70B. I found this problem when using 70B llama. It can be reproduced by building a new small model. Here:
'''
from transformers import LlamaForCausalLM, LlamaConfig
from peft.tuners.adaption_prompt import AdaptionPromptModel, AdaptionPromptConfig
from peft import get_peft_model, TaskType
import torch

if __name__ == '__main__':
    model_config = LlamaConfig(
            vocab_size=32000,
            hidden_size=128,
            intermediate_size=11008,
            num_hidden_layers=8,
            num_attention_heads=4,
            num_key_value_heads=2,
            hidden_act="silu",
            max_position_embeddings=2048,
            initializer_range=0.02,
            rms_norm_eps=1e-6,
            use_cache=True,
            pad_token_id=None,
            bos_token_id=1,
            eos_token_id=2,
            pretraining_tp=1,
            tie_word_embeddings=False,
            rope_theta=10000.0,
            rope_scaling=None,
            attention_bias=False
    )

    model = LlamaForCausalLM(config=model_config)

    adaption_config = AdaptionPromptConfig(task_type=TaskType.CAUSAL_LM, inference_mode=False,
                                           target_modules='self_attn', adapter_len=16,
                                           adapter_layers=4)
    peft_model = get_peft_model(model, adaption_config)

    input_ids = torch.tensor([[0 for _ in range(12)] for _ in range(4)])
    output = model(input_ids=input_ids)
    print(output)

'''
![image](https://github.com/huggingface/peft/assets/38997878/b30ca153-8191-444b-8c24-d0c8cbef0add)

**Comment by BenjaminBossan** [comment]
Thanks a lot. Indeed, with this setup, I could reproduce the error and also your solution seems to fix it. Thanks! Would you be interested in creating a PR?

**Comment by BenjaminBossan** [comment]
> But I failed to run `make test` in the `main` branch.

Hmm, not sure, the error message is not helpful and I'm no Windows expert. But let's not worry about that too much, we can let the CI run the tests. Does it work if you just run your test: `pytest tests/ -k test_llama_gqa`?

**Comment by LEE94-1** [comment]
> pytest tests/ -k test_llama_gqa

Failed with the same error with `unrecognized`, `inifile` and `rootdir`. So I think it maybe a error for my env. I reinstalled it tested it by myself.
```
from transformers import LlamaForCausalLM, LlamaConfig
from peft.tuners.adaption_prompt import AdaptionPromptModel, AdaptionPromptConfig
from peft import get_peft_model, TaskType
import torch

if __name__ == '__main__':
    model_config = LlamaConfig(
        vocab_size=16,
        hidden_size=8,
        intermediate_size=8,
        num_hidden_layers=8,
        num_attention_heads=4,
        num_key_value_heads=2,
        hidden_act="silu",
        max_position_embeddings=2048,
        initializer_range=0.02,
        rms_norm_eps=1e-6,
        use_cache=True,
        pad_token_id=None,
        bos_token_id=1,
        eos_token_id=2,
        pretraining_tp=1,
        tie_word_embeddings=False,
        rope_theta=10000.0,
        rope_scaling=None,
        attention_bias=False
    )
    model = LlamaForCausalLM(config=model_config)
    adaption_config = AdaptionPromptConfig(
        task_type=TaskType.CAUSAL_LM,
        inference_mode=False,
        target_modules='self_attn', adapter_len=16,
        adapter_layers=4
    )
    peft_model = get_peft_model(model, adaption_config)
    input_ids = torch.LongTensor([[1, 1, 1], [2, 1, 2]])
    output = peft_model(input_ids=input_ids)
    print(output.logits.shape)

    model_config = LlamaConfig(
        vocab_size=16,
        hidden_size=8,
        intermediate_size=8,
        num_hidden_layers=8,
        num_attention_heads=4,
        num_key_value_heads=2,
        hidden_act="silu",
        max_position_embeddings=2048,
        initializer_range=0.02,
        rms_norm_eps=1e-6,
        use_cache=True,
        pad_token_id=None,
        bos_token_id=1,
        eos_token_id=2,
        pretraining_tp=1,
        tie_word_embeddings=False,
        rope_theta=10000.0,
        rope_scaling=None,
        attention_bias=False
    )
    model = LlamaForCausalLM(config=model_config)
    adaption_config = AdaptionPromptConfig(
        task_type=TaskType.CAUSAL_LM,
        inference_mode=False,
        target_modules='self_attn', adapter_len=16,
        adapter_layers=4
    )
    peft_model = get_peft_model(model, adaption_config)
    input_ids = torch.LongTensor([[1, 1, 1], [2, 1, 2]])
    output = peft_model(input_ids=input_ids)
    print(output.logits.shape)
```
The result is:
```
PS E:\code> & D:/anaconda/anaconda/python.exe e:/code/test_model.py
torch.Size([2, 3, 16])
torch.Size([2, 3, 16])
```
