### ISSUE TITLE
Error while fetching adapter layer from huggingface library

### ISSUE THREAD

**Issue by Muskanb** [huggingface/peft#1363]
### System Info

```
        pa_extractor = LlamaForCausalLM.from_pretrained(LLAMA_MODEL_NAME,
                                                        token=HF_ACCESS_TOKEN,
                                                        max_length=LLAMA2_MAX_LENGTH,
                                                        pad_token_id=cls.tokenizer.eos_token_id,
                                                        device_map="auto",
                                                        quantization_config=bnb_config)
        pa_extractor.load_adapter(PEFT_MODEL_NAME, token=HF_ACCESS_TOKEN, device_map="auto")
```

   # getting the below error while executing :
   401 client error, Repository Not Found for url: https://huggingface.co/muskan/llama2/resolve/main/adapter_model.safetensors. 
 Please make sure you specified the correct `repo_id` and `repo_type`. 
If you are trying to access a private or gated repo, make sure you are authenticated. Invalid username or password

 This error occurs while calling  pa_extractor.load_adapter
 

### Who can help?

@pacman100 @younesbelkada @sayakpaul

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

The model is present in my private repo, should be replicable if you will try to use load_adapter to fetch any adapter layer from hf directly.

### Expected behavior

Should be able to download the peft adapter layer successfully

**Comment by BenjaminBossan** [comment]
Hi, I could not reproduce the error, I could load an adapter pushed to the HF Hub without trouble. I tried both private and public repos and it worked. Could it be that when you try to load the adapter, the correct token is not provided, so that the authentication fails?
