### ISSUE TITLE
deepspeed zero3 context is not invoked when creating new layers, so adapter layers are not wrapped by deepspeed

### ISSUE THREAD

**Issue by haixpham** [huggingface/peft#1366]
### System Info

torch 2.1
transformers 4.36.2
accelerate 0.26.0
deepspeed 0.12.6
peft 0.7.1

### Who can help?

@pacman100 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

This is when using `transformers.Trainer` and `TrainingArguments` with `--deepspeed=ds_config_zero3.json `. 

The base model is wrapped by deepspeed (adding `ds_shape`, `ds_tensor`, etc.), within a `deepspeed.zero.Init()` context.

But calling `peft_model = get_peft_model(base_model, peft_config)` is not wrapped in deepspeed context, so all new adapter layers are not wrapped by deepspeed at all (no partitioning on those layers).

Is it intended by design or a bug?

### Expected behavior

New adapter layers, such as `lora_A`, `lora_B` are wrapped in deepspeed zero3 context. This can be done at multiple points:
- in `get_peft_model()`
- in `PeftModel.from_pretrained()`
- or in each Peft model type

Have to handle initialization and loading/saving/merging (same as in `transformers`)
- initialization: wrap in `deepspeed.zero.Init(config_dict_or_path=deepspeed_config())`. The proper place is in `get_peft_model()` IMO, but I may be wrong.
- loading: wrap in `deepspeed.zero.GatheredParameters()`, in `PeftModel.from_pretrained()`.
- saving: deepspeed state_dict not handled in `get_peft_model_state_dict()` if PEFT model's adapter layers are fully wrapped by deepspeed. In `transformers.Trainer` saving is taken care of with `Trainer.save_model()`, but calling `model.save_pretrained()` doesn't handle deepspeed wrapper. It's assumed that the model has already been unwrapped. But this is the same as `transformers.PretrainedModel.save_pretrained() so I assume it's intended by design
- merging: I'm not sure, but I assume this PR addresses the problem: https://github.com/huggingface/peft/pull/1267

**Comment by haixpham** [comment]
It's actually a lot more complicated, because `deepspeed.zero.Init()` must be placed right before module initialization call. So expect a lot of changes in the code base. I modified the part of PEFT for LoRA and it works as I expect.

**Comment by haixpham** [comment]
There's also problems with `ModulesToSaveWrapper`, because deepspeed partitioning state cannot be deepcopied. So my modification only support one adapter (the active one).

**Comment by schwarzwalder93** [comment]
Facing the same issue. LoRA adapter weights are not getting saved properly when using deepspeed launcher.

**Comment by BenjaminBossan** [comment]
@haixpham Great that you could get PEFT to work with DS Zero 3. Would you be interested in adding this change to PEFT?

**Comment by haixpham** [comment]
@BenjaminBossan 

I'm tested it extensively in different use cases to make sure it works 100% correctly. My usecase includes using Deepspeed in training and not using Deepspeed in inference. The changes I made work as I want for what I'm doing, but there may be bugs somewhere or globally unintended behavior that I'm not certain about.
