### ISSUE TITLE
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

### ISSUE THREAD

**Issue by PetroMaslov** [huggingface/peft#137]
Hi!

I tried to use peft model with Seq2SeqTrainer, got the next error:
```
Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
```

Code:

```
tokenizer = AutoTokenizer.from_pretrained(args.model_id)
model = AutoModelForSeq2SeqLM.from_pretrained(
        "google/flan-t5-large",
        use_cache=False if args.gradient_checkpointing else True, 
)

lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    target_modules=["q", "v"],
    lora_dropout=0.05,
    bias="none",
    task_type="SEQ_2_SEQ_LM"
)

model = get_peft_model(model, lora_config)


trainer = Seq2SeqTrainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=eval_dataset,
    )
```

**Comment by JamesDConley** [comment]
I've been hitting this same issue whenever I try to use gradient checkpointing with Lora. Not sure what the underlying problem is but seems to be tied to that.

**Comment by younesbelkada** [comment]
Hi !
Can you call `model.enable_input_require_grads()` ? You have to use the `main` branch of `transformers` though (`pip install --upgrade git+https://github.com/huggingface/transformers`

**Comment by JamesDConley** [comment]
> Hi ! Can you call `model.enable_input_require_grads()` before `get_peft_model` ? You have to use the `main` branch of `transformers` though (`pip install --upgrade git+https://github.com/huggingface/transformers`)

This worked for me, thanks!

**Comment by psinger** [comment]
@younesbelkada 

Thanks, your suggestion fixes this issue.
Unfortunately, if I additionally run `torch.compile(model)` I get this error again. Any idea?

**Comment by totaltube** [comment]
Same error if opening lora adapter for additional training. Also seq2seq model flan-t5
```python
config = PeftConfig.from_pretrained(peft_model_id)
tokenizer = AutoTokenizer.from_pretrained(config.base_model_name_or_path)
model = AutoModelForSeq2SeqLM.from_pretrained(config.base_model_name_or_path)
model = PeftModel.from_pretrained(model, peft_model_id).to(device)
model.print_trainable_parameters()
```
And model.print_trainable_parameters() will output 0 trainable parameters.

**Comment by pacman100** [comment]
Hello,  `is_trainable=True` is required to load the pretrained adapter and have them in trainable mode.
Please pass `PeftModel.from_pretrained(model, peft_model_id, is_trainable=True).to(device)` and let us know if that solves the issue

**Comment by totaltube** [comment]
> Hello, `is_trainable=True` is required to load the pretrained adapter and have them in trainable mode. Please pass `PeftModel.from_pretrained(model, peft_model_id, is_trainable=True).to(device)` and let us know if that solves the issue

Yes, it works with this parameter. Thank you! And no need to do  'enable_input_require_grads()'

**Comment by duanyiqun** [comment]
@psinger  
Same here, I have the same problem when additionally run compile command, have you found anything related to this?

**Comment by AayushSameerShah** [comment]
@younesbelkada Hell yeah, it works!

**Comment by ManuSinghYadav** [comment]
> Hi ! Can you call `model.enable_input_require_grads()` before `get_peft_model` ? You have to use the `main` branch of `transformers` though (`pip install --upgrade git+https://github.com/huggingface/transformers`)

This worked for me, thanks!! @younesbelkada

**Comment by dengchengxifrank** [comment]
This problem may exit if you don't add the external model in to forward. Maybe you can check your forward function in your model.

**Comment by tuanlda78202** [comment]
> This problem may exit if you don't add the external model in to forward. Maybe you can check your forward function in your model.

That's work for my case

**Comment by jacklanda** [comment]
> Hi ! Can you call `model.enable_input_require_grads()` before `get_peft_model` ? You have to use the `main` branch of `transformers` though (`pip install --upgrade git+https://github.com/huggingface/transformers`)

This method is also workable for the scenario that you want to freeze some parts of the model and optimize the other parts on parameters. It'd be better to set the same thing for it.

**Comment by han-shanshan** [comment]
> model.enable_input_require_grads()


> Hi ! Can you call `model.enable_input_require_grads()` before `get_peft_model` ? You have to use the `main` branch of `transformers` though (`pip install --upgrade git+https://github.com/huggingface/transformers`)

You saved a soul.

**Comment by ashishbamania** [comment]
I used the following: 

training_args = TrainingArguments(
    # other arguments 
    label_names=["labels"],  # Explicitly set the label names
)

and this fixed the error for me

**Comment by ashishbamania** [comment]
I used the following:

from transformers import TrainingArguments

training_args = TrainingArguments(
    #other args 
    label_names=["labels"], #add this 
)

**Comment by abubakr380** [comment]
In my case, I was using unsloth.FastLanguageModel.pretrained to load the model and the model didn't have the `enable_input_require_grads()` (I think becxause it's a Causal_LM). Instead I enabled `requires_grad` by registering a forward hook:

```
def make_inputs_require_grad(module, input, output):
    output.requires_grad_(True)
model.get_input_embeddings().register_forward_hook(make_inputs_require_grad)
```
Creadits to https://discuss.huggingface.co/t/peft-lora-gpt-neox-backward-pass-failing/35641/2
