### ISSUE TITLE
How to set a predefined weight for LoRA and the linear layer

### ISSUE THREAD

**Issue by quqxui** [huggingface/peft#1382]
Hi,

Thanks for your great job! 

I have a question: When adding LoRA on a linear layer, how to set a predefined weight for LoRA and the linear layer, instead of just 0.5 : 0.5 ?

**Comment by BenjaminBossan** [comment]
> When adding LoRA on a linear layer, how to set a predefined weight for LoRA and the linear layer, instead of just 0.5 : 0.5 ?

I did not understand your question, could you please explain it further? Where do we set weights of 0.5, could you please link to that part of the code?

**Comment by quqxui** [comment]
I have implemented my need with lora_alpha and alpha_pattern. Thanks.
