### ISSUE TITLE
Softprompt broken with use_cache=True

### ISSUE THREAD

**Issue by Rallio67** [huggingface/peft#1391]
### System Info

I am using transformers 4.37 and peft 0.7.1

Quite simply, generate is broken with use_cache = True. 

Probably it has something to do with this error:
https://github.com/kipgparker/soft-prompt-tuning/issues/7

This was working in previous versions, but broke recently. I am not sure what version it was working on.

To replicate, train a softprompt, then test it with use_cache = False and use_cache = True. Only the first token generated is correct, after that the outputs are garbled and messed up.

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction
```
from transformers import MistralForCausalLM, LlamaTokenizer
from peft import PeftModel, PeftConfig
import torch

# Hugging Face model id
peft_model_id = "mis_7b_sp_f"
model_id = "mistralai/Mistral-7B-v0.1" 

# Load models and tokenizer
config = PeftConfig.from_pretrained(peft_model_id)
model = MistralForCausalLM.from_pretrained(model_id, torch_dtype=torch.bfloat16, device_map={"":0}, use_cache=False)
model = PeftModel.from_pretrained(model, peft_model_id)
tokenizer = LlamaTokenizer.from_pretrained(model_id)

def generate_from_model(text):
    encoded_input = tokenizer(text, return_tensors='pt')
    output_sequences = model.generate(
                                    input_ids=encoded_input['input_ids'].cuda(0),
                                    do_sample=False,
                                    max_new_tokens=35,
                                    num_return_sequences=1,
                                    output_scores=True,
                                    return_dict_in_generate=True,
                                    pad_token_id=0,
                                    eos_token_id=2,
                                    use_cache= True #change this to False to get correct output
                                  )
    gen_sequences = output_sequences.sequences[:, :]
    for sequence in gen_sequences:
        print(tokenizer.decode(sequence, skip_special_tokens=False))
```
### Expected behavior

By switching the use_cache off the problem is fixed. The generation should be the same whether use_cache is turned on or off, but it is different and when cache is turned on the output is garbled and broken.

**Comment by vikram71198** [comment]
yep, I faced the same exact issue while soft prompt tuning as well. Switching ```use_cache``` to False did the trick. This needs to be looked into & fixed.

**Comment by BenjaminBossan** [comment]
> This was working in previous versions, but broke recently. I am not sure what version it was working on.

Just to be sure, you mean previous versions of PEFT? To be sure, could you please also try the most recent version of PEFT?

> To replicate, train a softprompt, then test it with use_cache = False and use_cache = True.

Could you please give more details here? What PEFT method did you use? What was the specific config?

**Comment by Rallio67** [comment]
> > This was working in previous versions, but broke recently. I am not sure what version it was working on.
> 
> Just to be sure, you mean previous versions of PEFT? To be sure, could you please also try the most recent version of PEFT?
> 
> > To replicate, train a softprompt, then test it with use_cache = False and use_cache = True.
> 
> Could you please give more details here? What PEFT method did you use? What was the specific config?

I posted this bug 2 weeks ago when the most recent version of peft was 0.7.1. As mentioned in the original post, it is with a softprompt using the PROMPT_TUNING config.

I didn't know the current version has been updated 3 times since my post. 

I just checked the same code that failed with 
transformers==4.37.0 and peft==0.7.1
and can verify with these versions it still fails with use_cache=True and works with use_cache=False

I updated to 
transformers==4.37.2 and peft==0.8.2
and the error is gone, so somehow it has been fixed with the newer versions.
