### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for PeftModelForCausalLM: size mismatch...

### ISSUE THREAD

**Issue by achangtv** [huggingface/peft#1396]
I am trying to .merge_and_unload() a Llama 2 peft model to use it for inference in Databricks.
Here is my code for training the model; I do add a pad token which I think is the cause of the error.
```
target_modules = ['q_proj','k_proj','v_proj','o_proj','gate_proj','down_proj','up_proj','lm_head']

lora_config = LoraConfig(
    r=4,
    lora_alpha=8,
    lora_dropout=0.05,
    bias="none",
    target_modules = target_modules,
    task_type="CAUSAL_LM",
)

per_device_train_batch_size = 1
gradient_accumulation_steps = 4
optim = 'adamw_hf'
learning_rate = 1e-5
max_grad_norm = 0.3
warmup_ratio = 0.03
lr_scheduler_type = "linear"

from transformers import TrainingArguments
training_args = TrainingArguments(
    output_dir=base_dir,
    save_strategy="epoch",
    evaluation_strategy="epoch",
    num_train_epochs = 1.0,
    per_device_train_batch_size=per_device_train_batch_size,
    gradient_accumulation_steps=gradient_accumulation_steps,
    optim=optim,
    learning_rate=learning_rate,
    fp16=True,
    max_grad_norm=max_grad_norm,
    warmup_ratio=warmup_ratio,
    group_by_length=True,
    lr_scheduler_type=lr_scheduler_type,
    logging_steps=100,
)

nf4_config = BitsAndBytesConfig(
  load_in_4bit=True,
  bnb_4bit_quant_type="nf4",
  bnb_4bit_use_double_quant=True,
  bnb_4bit_compute_dtype=torch.bfloat16
)

model_path = 'meta-llama/Llama-2-7b-hf'

tokenizer = LlamaTokenizer.from_pretrained(model_path)
tokenizer.add_special_tokens({'pad_token': '[PAD]'})

model = LlamaForCausalLM.from_pretrained(
    model_path, device_map='auto', quantization_config=nf4_config,
)
model.resize_token_embeddings(len(tokenizer))

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

trainer = SFTTrainer(
    model,
    train_dataset=to_train_dataset,
    eval_dataset = test_dataset,
    dataset_text_field=text_field,
    max_seq_length=2048,
    args=training_args,
)
#Upcast layer norms to float 32 for stability
for name, module in trainer.model.named_modules():
  if "norm" in name:
    module = module.to(torch.float32)

with mlflow.start_run(run_name='tft'):
    trainer.train()
```

And here is my code for merging the weights:
```
model = AutoPeftModelForCausalLM.from_pretrained(qlora_path, device_map="auto", torch_dtype=torch.bfloat16)
model = model.merge_and_unload()

output_merged_dir = "/dbfs/$folder"
os.makedirs(output_merged_dir, exist_ok=True)
model.save_pretrained(output_merged_dir, safe_serialization=True)

# save tokenizer for easy inference
tokenizer = AutoTokenizer.from_pretrained(qlora_path)
tokenizer.save_pretrained(output_merged_dir)
```

Right on that first line, I get this error:

`RuntimeError: Error(s) in loading state_dict for PeftModelForCausalLM: size mismatch for base_model.model.lm_head.lora_B.default.weight: copying a param with shape torch.Size([32001, 4]) from checkpoint, the shape in current model is torch.Size([32000, 4]).`

I will say, after initializing the SFTTrainer I did get this, info message? `Using pad_token, but it is not set yet.` The thing is, I did set the pad token above that, so it should have been set. Did I forget to do something somewhere that it added the token in one place but not another, so things are all wonky now? Is there a way I can somehow add that pad token to the base model? Not really sure where to go from here.

**Comment by mehrdad-es** [comment]
@achangtv could you try modifying your local repo for the `AutoPeftModelForCausalLM.from_pretrained` method to make tokenzier modifications just like you did for your first code block and then see if that'll fix the problem?

**Comment by epicmouse667** [comment]
@achangtv I‘ve met the same problem when loading the lora parameters. Then I've found the solution [here](https://discuss.huggingface.co/t/having-trouble-loading-a-fine-tuned-peft-model-codellama-13b-instruct-hf-base/52880/2).It says that you need to add the special tokens and resize the token embeddings before loading lora.
`for token in special_tokens:
            if token not in self.tokenizer.get_vocab():
                logger.info(f"Add special unit tokens {token} to tokenizer.vocab")
                self.tokenizer.add_tokens([token])
        #resize embedding
        embedding_size = self.model.get_input_embeddings().weight.shape[0]
        if len(self.tokenizer) > embedding_size:
            self.model.resize_token_embeddings(len(self.tokenizer))

        if lora_weights is not None:
            self.model = PeftModel.from_pretrained(
                self.model,
                lora_weights,
                torch_dtype=torch.float16,
                device_map="auto",
                use_safetensors=True
            )`

**Comment by BenjaminBossan** [comment]
@epicmouse667 IIUC, with the solution you linked, the issue could be resolved? In that case, I'll close this issue. Feel free to re-open if there are still questions.

**Comment by epicmouse667** [comment]
@BenjaminBossan Yeh, at least the solution works for me. Thanks for your feedback.

**Comment by achangtv** [comment]
Works for me, thanks @epicmouse667!
