### ISSUE TITLE
Why huggingface only support relative local path? 

### ISSUE THREAD

**Issue by yzeng58** [huggingface/peft#1397]
### System Info

peft: 0.4.0

### Who can help?

@pacman100 @younesbelkada @sayakpaul

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

from peft import PeftModel
model = PeftModel.from_pretrained(model, '/data/yzeng58/micl/results/models')

Here '/data/yzeng58/micl/results/models' is the output directory. 

### Expected behavior

Load the model from the local path.

However, it can only support the relative path, instead of an absolute path.

**Comment by simon-lund** [comment]
Not super helpful ^^ but it should support absolute paths by default.

What error do you get?

**Comment by younesbelkada** [comment]
HI @yzeng58 
As stated by @simon-lund I think it should support both scenarios, can you share a reproducible snippet? Also could you try out with the latest pypi release? `pip install -U peft`

**Comment by BenjaminBossan** [comment]
I could not reproduce the error of loading a local PEFT model with absolute paths (on Linux machine, using the latest PEFT version):

```python
from peft import LoraConfig, get_peft_model, PeftModel
from transformers import AutoModelForCausalLM

config = LoraConfig(task_type="CAUSAL_LM")
model = AutoModelForCausalLM.from_pretrained("bigscience/bloomz-560m")
peft_model = get_peft_model(model, config)
peft_model.save_pretrained("/tmp/peft/issue-1397")

model = AutoModelForCausalLM.from_pretrained("bigscience/bloomz-560m")
loaded = PeftModel.from_pretrained(model, "/tmp/peft/issue-1397")  # works
# contents of /tmp/peft/issue-1397: adapter_config.json  adapter_model.safetensors	README.md
```
