### ISSUE TITLE
New pypi version please

### ISSUE THREAD

**Issue by YLGH** [huggingface/peft#1400]
### Feature request

Hi, would it be possible to push a new stable version of PEFT on PyPI? https://pypi.org/project/peft/ It looks like the last release is from over a month ago. 

### Motivation

There are some new features I'd like to use (without having to install from source).

### Your contribution

Help test

**Comment by younesbelkada** [comment]
Hi @YLGH , it is coming soon: https://github.com/huggingface/peft/pull/1406
