### ISSUE TITLE
Where is `self.generation_config`coming from?

### ISSUE THREAD

**Issue by simon-lund** [huggingface/peft#1401]
https://github.com/huggingface/peft/blob/1c1c7fdaa6e6abaa53939b865dee1eded82ad032/src/peft/peft_model.py#L1136

`self.generation` variable is not initialized in the model, it is also not part of a class up in the inheritance hierarchy.
So I assume it is retrieved from the base model via the implemented `\_\_getattr\_\_` method.

If that's the case, doesn't this make the code redundant? Also, how could this code work if we have to go down 1 level deeper? The only reason I can imagine doing this if `generation_config` is set after the model was initialized, but why would you need to do this?

Could you help me with this and explain how `generation_config` is supposed to be initialized and used?  

Thank you :) Best
Simon

**Comment by simon-lund** [comment]
Also, how is generate called when, for example, the LoRA model does not implement a generate method?

**Comment by simon-lund** [comment]
Also, in this line the "prepare_inputs_for_generation" are stored but at this point, the base_model has already been replace with a PEFT tuner, which does not have this method implmented :thinking: 

https://github.com/huggingface/peft/blob/0769587a3cd80ad2ae508cc06efbf54ddca821b3/src/peft/peft_model.py#L894

**Comment by simon-lund** [comment]
Same question for this line:

https://github.com/huggingface/peft/blob/bfc102c0c095dc9094cdd3523b729583bfad4688/src/peft/peft_model.py#L259

**Comment by younesbelkada** [comment]
Hi Simon
Thanks for the issue
`self.generation_config` is directly retrieved from the base model through the `getattr` method. To preserve consistency with the `PreTrainedModel` class from transformers, we also store that attribute, that is also used by prompt tuning methods. With respect to generate, it directly uses `generate` from `PreTrainedModel` that inherits from `GenerationMixin`, and `prepare_inputs_for_generation` is used under the hood by `generate`, hence the need to re-write that method

**Comment by simon-lund** [comment]
https://github.com/huggingface/peft/blob/189a9a666dc90f335b6a4db77f4b856b6a8bbdfd/src/peft/peft_model.py#L1135-L1138

Thank you for your time and response :)
So, I think I was confused by the `else` block then, because one doesn't need it, right?

If `self.generation_config` is resolved via `__getattr__` to `self.base_model.generation_config`, this results in:

```python
...
else:
    self.base_model.generation_config = self.base_model.generation_config
....
````
So one could just leave it out?


--------------

Regarding all the methods and variables accessed via `self.base_model`, could you please let me know what I am missing? Because from the looks of it, `self.base_model` is set to a tuner, e.g.,  `LoraModel` which is derived from `BaseTuner` and neither one implements `__getattr__` to access attributes of the wrapped `PreTrainedModel`. 

https://github.com/huggingface/peft/blob/5e4aa7eb92c2004ee07a1682800ab19b1af7c873/src/peft/peft_model.py#L120-L128

So my question here is how is an access, e.g., `prepare_inputs_for_generation` possible with this setup?  
I think I missed a `__getattr__` or a parent class somewhere :shrug:

**Comment by BenjaminBossan** [comment]
> So, I think I was confused by the `else` block then, because one doesn't need it, right?

The `else` block you cite is not about resolving `generation_config`, but about resolving `self.base_model.model` vs `self.base_model`. For prompt tuning methods, we need the latter, else we need the former (e.g. for LoRA, the `PeftModel`'s `base_model` is wrapped again as `LoraModel`, which references the true base model).

> So my question here is how is an access, e.g., `prepare_inputs_for_generation` possible with this setup?

This is only used for prompt tuning, so the case where `base_model = model`, i.e. it's not a `LoraModel` or anything like that.

**Comment by simon-lund** [comment]
Thank you for clarification.
