### ISSUE TITLE
Simplify `PeftModel.save_pretrained`

### ISSUE THREAD

**Issue by simon-lund** [huggingface/peft#1403]
https://github.com/huggingface/peft/blob/0769587a3cd80ad2ae508cc06efbf54ddca821b3/src/peft/peft_model.py#L121-L203

If I understand this correctly, this method does nothing when `is_main_process=False`.
So, instead of checking this multiple times in various places while executing some other code, one could simplify this by adding a guard at the top of the method:

```python
def save_pretrained(..., is_main_process=True):
    if not is_main_process:
        warnings.warn("Called `save_pretrained` on non-main process. Skipping saving.")
        return
```

**Comment by younesbelkada** [comment]
Hi @simon-lund 
Thanks! Just to understand, in the code you pointed out you said:

> If I understand this correctly, this method does nothing when is_main_process=False.

It seems `is_main_process` is never used no?

**Comment by simon-lund** [comment]
I am so sorry, I referenced the method on the wrong branch.

https://github.com/huggingface/peft/blob/189a9a666dc90f335b6a4db77f4b856b6a8bbdfd/src/peft/peft_model.py#L162
Am 29. Jan. 2024, 23:31 +0100 schrieb Younes Belkada ***@***.***>:

**Comment by BenjaminBossan** [comment]
Thanks Simon for your suggestion. I did a quick check on the method and it looks like indeed your suggestion could simplify the method. It wouldn't be 100% identical, e.g. this line creates a folder even if not on the main process:

https://github.com/huggingface/peft/blob/ce925d844a0bc54b951fcb69229dfe740c9afa45/src/peft/peft_model.py#L223

But AFAICT, all those side effects are unnecessary if not on the main process, so it should be fine to add an early return. Therefore, if you're interested, we would welcome the suggested change. We just need to ensure that nothing important is lost by the change.
