### ISSUE TITLE
[Documentation] Compatibility between lora + deepspeed + bitsandbytes

### ISSUE THREAD

**Issue by nathan-az** [huggingface/peft#1418]
### Feature request

Additional details in the [peft + deepspeed documentation](https://huggingface.co/docs/peft/accelerate/deepspeed-zero3-offload) and/or the [peft quantization documentation](https://huggingface.co/docs/peft/developer_guides/quantization) clarifying `peft` + `deepspeed` + `bitsandbytes` compatibility.

A table/compatibility matrix would be useful (e.g. columns being zero2, zero3, zero3 with CPU offloading and rows being standard precision, 4bit, 8bit, etc.). It would provide a central spot to confirm compatibility rather than trawling github issues, as well as a location to update if compatibility changes.

### Motivation

It's very common for users of `peft` to use it with `bitsandbytes` to load the base model in 4bit/8bit and only perform compute in higher precision. Separately, it's very popular to use `deepspeed` (or `fsdp`) for scalable full parameter training.

It's not particularly clear whether it's possible to use both a quantized base model, and model sharding with zero3. I originally supposed that you could use zero3 for parameter sharding, and potentially CPU offloading.

The [documentation](https://huggingface.co/docs/peft/accelerate/deepspeed-zero3-offload) makes it clear that `peft` is compatible with `deepspeed`, but makes no note of its compatibility with `deepspeed` AND `bitsandbytes`.

Including a section (or a warning box) on this in the documentation would be great for reducing ambiguity, particularly if it's updated as things change (e.g. if it is not supported now, but becomes supported).

### Your contribution

I'm happy to actually submit the PR containing the docs (maybe the relevant notes on both the quantization and deepspeed pages) and make them look pretty, but would need someone to clarify the current level of compatibility, or whether `peft` + `deepspeed` + `bitsandbytes` simply does not work right now.

**Comment by BenjaminBossan** [comment]
Hi Nathan, thanks for the suggestion. I agree that it would be useful to have this type of information to avoid confusion. If you provide a PR to add this, it would be very welcome.

When it comes to what combination does and does not work, I think it can be tricky, as it may depend on specific details. Maybe @pacman100 can provide some further details.

**Comment by nathan-az** [comment]
Bumping, this would be valuable for the community and I've seen the question come up more than once without clear answers.

**Comment by BenjaminBossan** [comment]
We made some recent updates to the [DS](https://huggingface.co/docs/peft/accelerate/deepspeed) and [FSDP](https://huggingface.co/docs/peft/accelerate/fsdp) part of the docs, though it's still not explicitly mentioned if it works with bnb (which it doesn't AFAIK). Maybe we can add mention that there, not sure if a table/matrix is needed.

**Comment by younesbelkada** [comment]
@nathan-az we just shipped some clarification on PEFT main docs, can you have a look ?

**Comment by nathan-az** [comment]
Looks great, thanks @younesbelkada! Great to have that clarification (and maybe one day an update if ZeRO3 becomes compatible with bitsandbytes' 4bit!)

**Comment by younesbelkada** [comment]
Hi @nathan-az 
Actually it turns out Zero-3 is supported if you don't use zero-init, see @pacman100 's findings here: https://github.com/microsoft/DeepSpeed/issues/4295#issuecomment-1978737326

**Comment by younesbelkada** [comment]
I will update the docs accordingly
