### ISSUE TITLE
ValueError: Tokenizer class XXXXXXXX does not exist or is not currently imported

### ISSUE THREAD

**Issue by Sun-Shiqi** [huggingface/peft#1438]
### System Info

if i use peft==0.8.2,  i will get this error, but when  i only change the version to 0.7.1 , the error will be sovled.

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

when using use peft==0.8.2, the error like this :
File "*****/test_Qwen_aes_tag.py", line 9, in <module>
    model = AutoPeftModelForCausalLM.from_pretrained(
  File "/home/tiger/.local/lib/python3.9/site-packages/peft/auto.py", line 124, in from_pretrained
    tokenizer = AutoTokenizer.from_pretrained(pretrained_model_name_or_path)
  File "/home/tiger/.local/lib/python3.9/site-packages/transformers/models/auto/tokenization_auto.py", line 724, in from_pretrained
    raise ValueError(
ValueError: Tokenizer class QWenTokenizer does not exist or is not currently imported.

### Expected behavior

Maybe a  bug in  the new version .

**Comment by younesbelkada** [comment]
@Sun-Shiqi hmm interesting, I think we could fix that by passing `trust_remote_code` to the peft model's from_pretrained, can you share the full traceback and a minimal snippet to repro?

**Comment by Sun-Shiqi** [comment]
> @Sun-Shiqi hmm interesting, I think we could fix that by passing `trust_remote_code` to the peft model's from_pretrained, can you share the full traceback and a minimal snippet to repro?

I have already set "trust_remote_code=True" , but this error will still occur under peft==0.8.2. My simple code is as follows：

`model = AutoPeftModelForCausalLM.from_pretrained(
    "./checkpoint/qwen-14B-chat_lora_aes_tag_prediction_artist_pretrain_0204/checkpoint-14000", # path to the output directory
    device_map="auto",
    trust_remote_code=True
).eval()`

**Comment by younesbelkada** [comment]
@Sun-Shiqi thanks ! can you share a minimal reproducible snippet with a model that is currently on HuggingFace Hub?

**Comment by lzhmarkk** [comment]
Same problem.
Fixed by adding `trust_remote_code=True` in `src/peft/auto.py` line 123 to `tokenizer = AutoTokenizer.from_pretrained(pretrained_model_name_or_path, trust_remote_code=True)`, *when trying to load a tokenizer from local path.*
