### ISSUE TITLE
Size mismatch error when loading model with added tokens using peft_model.save_pretrained

### ISSUE THREAD

**Issue by Rizvanov-Rinat** [huggingface/peft#1457]
### System Info

peft: 0.8.2
accelerate: 0.27.0
transformers: 4.37.2
torch: 2.2.0+cu118
python: 3.10.6

### Who can help?

@pacman100 @younesbelkada

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

```python
from transformers import AutoTokenizer, AutoModel
from peft import PeftModel, LoraConfig, TaskType, get_peft_model

BASE_MODEL_NAME = 'roberta-base'
DST_MODEL_DIR = './models/roberta-test'

tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL_NAME)
model = AutoModel.from_pretrained(BASE_MODEL_NAME)

# Add special tokens and resize embeddings
add_tokens=['<TOK1>', '</TOK1>', '<TOK2>', '</TOK2>']
tokenizer.add_tokens(add_tokens, special_tokens=True)
model.resize_token_embeddings(len(tokenizer))

# PEFT model configuration and initialization
lora_config = LoraConfig(task_type=TaskType.FEATURE_EXTRACTION, r=2, lora_alpha=32, lora_dropout=0.1, bias="none")
peft_model = get_peft_model(model, lora_config)

# Save tokenizer and PEFT model
tokenizer.save_pretrained(DST_MODEL_DIR)
peft_model.save_pretrained(DST_MODEL_DIR, save_embedding_layers=True)

# Load the model and PEFT model to check if embeddings are preserved
model = AutoModel.from_pretrained(DST_MODEL_DIR)  # <-- This is where the size mismatch error occurs
peft_model = PeftModel.from_pretrained(model, DST_MODEL_DIR)
```

### Expected behavior

After saving PEFT model with special tokens using `peft_model.save_pretrained`, I expect that when loading them back, the embeddings would reflect the new size with added tokens. Instead, the embeddings revert to the original size, indicating that the special tokens were not preserved.

### Additional Context

This error suggests that the model saved with `peft_model.save_pretrained` does not retain the new token embeddings.

```bash
RuntimeError: Error(s) in loading state_dict for RobertaModel:
size mismatch for embeddings.word_embeddings.weight: copying a param with shape torch.Size([50269, 768]) from checkpoint, the shape in current model is torch.Size([50265, 768]).
```

Also, when saving and loading the model configuration separately with the model loads successfully with the correct embeddings size reflecting the added tokens:

```python
...
peft_model.config.save_pretrained(DST_MODEL_DIR)

config = AutoConfig.from_pretrained(DST_MODEL_DIR)
model = AutoModel.from_config(config)
...
```

Using this alternative approach, the loaded model's embeddings correctly account for the new token sizes (50269, 768).

Initially, I considered that this might be a problem related to the transformers library. I performed the same steps of adding tokens, resizing embeddings, saving, and loading the model using only the transformers. But this process worked as expected. 

For reference, the same problem has been documented in [Issue #838](https://github.com/huggingface/peft/issues/838).

**Comment by BenjaminBossan** [comment]
The issue is that you're trying to load the base model from `DST_MODEL_DIR`, but this directory only contains the tokenizer and the adapter files. You should load the base model just as you normally would:

```diff
- model = AutoModel.from_pretrained(DST_MODEL_DIR)
+ model = AutoModel.from_pretrained(BASE_MODEL_NAME)
+ model.resize_token_embeddings(len(tokenizer))
```

**Comment by Rizvanov-Rinat** [comment]
> The issue is that you're trying to load the base model from `DST_MODEL_DIR`, but this directory only contains the tokenizer and the adapter files. You should load the base model just as you normally would:
> 
> ```diff
> - model = AutoModel.from_pretrained(DST_MODEL_DIR)
> + model = AutoModel.from_pretrained(BASE_MODEL_NAME)
> + model.resize_token_embeddings(len(tokenizer))
> ```

Yes, this approach allows loading the base model and then adding new tokens. However, if these new tokens were finetuned in the original model or initialized randomly, simply resizing without transferring the weights for these tokens would not preserve their modifications. Thus, after resizing, we would not retain the weights corresponding to training or initialization, potentially impacting the model's performance.

**Comment by BenjaminBossan** [comment]
Indeed. That's why the embedding layer should be saved and loaded too in that case, which you did correctly. More on this can be found in the [docs](https://huggingface.co/docs/peft/v0.8.2/en/developer_guides/troubleshooting#extending-the-vocabulary).

**Comment by Rizvanov-Rinat** [comment]
Thank you for the clarification. It seems I've understood how the embedding layer should be managed with new tokens.

**Comment by AaronZLT** [comment]
In this way, the new trained embedding from peft adapter will be added to the resized embedding when merging? Should we use mean_resizing=False

**Comment by BenjaminBossan** [comment]
> In this way, the new trained embedding from peft adapter will be added to the resized embedding when merging? Should we use mean_resizing=False

Most of the time, LoRA is not applied to the embedding layer, only the linear layers, so there is nothing to merge into the embeddings. When adding new tokens, you'd generally want to fully train the embedding layer. But it is possible to apply LoRA to embeddings, which, depending on your task, may be enough to train the newly added tokens. In that case, as long as you resize before calling `get_peft_model`, LoRA should take into account the new vocabulary size. Thus merging should work as expected.

Whether you use `mean_resizing` or not should not matter (one exception being that it can cause issues with FSDP, in which case you should set it to `False`).
