### ISSUE TITLE
Whisper Training int8 PEFT

### ISSUE THREAD

**Issue by javilonso** [huggingface/peft#146]
This issue goes to @younesbelkada !!!
I was trying your [notebook for training Whisper based on int8](https://github.com/huggingface/peft/blob/main/examples/int8_training/peft_bnb_whisper_large_v2_training.ipynb), however I am wondering which version of transformers were you using.

In 4.26.1, I am getting an error at trainer.py, line 362
https://github.com/huggingface/transformers/blob/v4.26.1/src/transformers/trainer.py

```
        if getattr(model, "is_loaded_in_8bit", False):
            raise ValueError(
                "The model you want to train is loaded in 8-bit precision. "
                "Training an 8-bit model is not supported yet. "
            )

```

Thanks in advance!

**Comment by younesbelkada** [comment]
Hello @javilonso 
Thanks for the ping! 
To solve this issue, please use the latest changes of `transformers`, `pip install git+https://github.com/huggingface/transformers.git` as this change has not been upstream yet on the public package!

**Comment by javilonso** [comment]
> Hello @javilonso Thanks for the ping! To solve this issue, please use the latest changes of `transformers`, `pip install git+https://github.com/huggingface/transformers.git` as this change has not been upstream yet on the public package!

Thanks for your reply!
Just to confirm, do you have transformers 4.27.0-dev0?

**Comment by younesbelkada** [comment]
hi @javilonso 
Yes

**Comment by javilonso** [comment]
Thanks @younesbelkada, training now in progress!
