### ISSUE TITLE
[BUG] Unexpected GPU memory consumption when using transformers PEFT in Zero3

### ISSUE THREAD

**Issue by alekseymalakhov11** [huggingface/peft#1470]
### System Info

transformers = "4.35.0"
peft = "0.7.1"
torch = ">=2.0.0"
accelerate = "^0.24.1"
deepspeed = "^0.9.5"

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Description

Llama30B with Lora adapters cannot fit into 8 x A100 (80GB).

### Demonstration of Problem and Experiment Setups

I will illustrate this issue using various experiment setups on smaller models:

1. 7b+lora+stage 3
![image](https://github.com/huggingface/peft/assets/131314005/5d30fd07-2b4f-4da2-a2fb-3b9434fbb6c8)
2. 7b+stage 3
![image](https://github.com/huggingface/peft/assets/131314005/b9453c69-a576-40a4-8e9c-0a4bd47bb4ab)
3. 7b+lora+stage 2
![image](https://github.com/huggingface/peft/assets/131314005/4a754f4d-d89b-4bc9-bf19-bcd02710a2a7)
4. 7b + stage 2
![image](https://github.com/huggingface/peft/assets/131314005/5e5bfa69-99d7-4918-9b0b-9c432ef02bef)

All other parameters remain consistent in the experiments below.

### Suspected Cause

The possible reason for this issue might be that Zero3 does not partition non-trainable weights across GPUs. The basis for this assumption is:

- The memory consumption is consistent with predicted values when Lora is not used.
- When training the model with both Zero2 and Zero3 using Lora, I observe nearly the same memory consumption.
- A [code examination](https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/runtime/zero/stage3.py#L318C14-L318C58) of the Zero Runtime sources also suggests this could be the case.

### Expected behavior

Training the model with Zero3 while using Lora should consume significantly less memory than Zero2 with Lora.

We also opened an [issue in Deepspeed](https://github.com/microsoft/DeepSpeed/issues/5109), but no one has assisted us. Additionally, you might have more experience with PEFT and Deepspeed integration in the Transformers trainer.

**Comment by BenjaminBossan** [comment]
Yes, there are issues with using PEFT with DS. @pacman100 knows more about this. We plan to add documentation on this soon.

**Comment by alekseymalakhov11** [comment]
Thank you for your response! I have also opened an [issue in transformers](https://github.com/huggingface/transformers/issues/29047), where I attached snippets of our training code.
