### ISSUE TITLE
HF Pipeline support for PeftModelForSequenceClassification

### ISSUE THREAD

**Issue by ddofer** [huggingface/peft#1488]
### Feature request

 'PeftModelForSequenceClassification' is not supported for text-classification when using huggingface pipeline. 
Request: add support.

### Motivation

Huggingface best practice for inference (their pipeline) doesn't support PEFT trained models.

```
    from transformers import pipeline
model_checkpoint =  "facebook/esm2_t12_35M_UR50D"
peft_config = LoraConfig(base_model_name_or_path=model_checkpoint,task_type= "SEQ_CLS", bias="all", target_modules=  "all-linear")
[...]
### model training, using HF trainer etc'] 

    trained_model = AutoModelForSequenceClassification.from_pretrained(MODEL_DRIVE_SAVE_PATH,
                                                                  num_labels=num_labels,problem_type="single_label_classification")
    
    # trained_model = PeftModel.from_pretrained(trained_model, MODEL_DRIVE_SAVE_PATH) # same output when using this istead of below
    trained_model = PeftModelForSequenceClassification.from_pretrained(trained_model, MODEL_DRIVE_SAVE_PATH,
                                                                       config=peft_config)
  tokenizer = AutoTokenizer.from_pretrained(model_checkpoint,
                                            padding= False#True # orig
  #                                           padding= True# alt
                                            ,truncation=True,max_length=model_max_len)
  
  pipe = pipeline("text-classification", model=trained_model, tokenizer=tokenizer)
```

This results in the error "The model 'PeftModelForSequenceClassification' is not supported for text-classification."
Note - raw underlying model was trained with peft, lora, sequence classification task. 

Is there a workaround for this?

### Your contribution

I'm unfamiliar with the setup (and have been having many many issues getting PEFT to work with ESM2), I can't help much.

**Comment by ddofer** [comment]
Update: 
`merged_model = trained_model.merge_and_unload()`
 -> results in being able to use HF pipeline. 
Still, it would be good to have a warning/error message so users know this is required (or to handle this automatically)

**Comment by BenjaminBossan** [comment]
Hey, I get the same log message as you did. However, I don't think it's an actual error, it's a false alarm. The model should run correctly after this message is shown. Could you please check that?

Of course, you can `merge_and_unload` the model and it should also work. As long as you have only one LoRA adapter, this should work fine.

**Comment by ddofer** [comment]
Doing merge_and_unload  is screwed up. 
In the same notebook where I run the code, it saves and loads ok/ 
In  a seperate notebook/runtime, exact same code, it gives and error when trying to load the saved model/adapters (identity/ dropout not supported). No idea why, and it doesn't seem to save the sequence classification head correctly. 
I'm kinda going nuts on this, been spending 2 weeks messing with getting esm to work with peft/lora :(

**Comment by BenjaminBossan** [comment]
I see. If there are details you can share, like a description of the individual steps, configs, error message, etc., please do so and I can take a look.
