### ISSUE TITLE
ModulesToSaveWrapper not working with ModulesDict dictionary methods

### ISSUE THREAD

**Issue by SamGalanakis** [huggingface/peft#1492]
### System Info

transformers 4.37.2
peft 0.8.2
accelerate 0.27.2
torch  2.2.0

        

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

Error:
```
Exception has occurred: TypeError
'ModulesToSaveWrapper' object is not subscriptable
  File "/home/sam_work/code/tag_classification/test.py", line 14, in forward
    return self.foo_dict["foo"](torch.rand(1,10))
           ~~~~~~~~~~~~~^^^^^^^
  File "/home/sam_work/code/tag_classification/test.py", line 25, in <module>
    lora_model()
TypeError: 'ModulesToSaveWrapper' object is not subscriptable
```

```python
from peft import *
from torch import nn, Tensor
import torch


class ModelFoo(nn.Module):
    def __init__(self) -> None:
        super().__init__()
        self.other_layer = nn.Linear(10, 10)
        self.foo_dict = nn.ModuleDict({"foo": nn.Linear(10, 10)})

    def forward(self) -> Tensor:
        return self.foo_dict["foo"](torch.rand(1, 10))


model = ModelFoo()

peft_config = LoraConfig(
    target_modules=["other_layer"],
    modules_to_save=["foo_dict"],
)
model()
lora_model = get_peft_model(model=model, peft_config=peft_config)

lora_model()
```

### Expected behavior

The dictionary methods are promoted to wrapper - can use modulesdict without modifying code.

Seems like only forward is getting promoted to the wrapper and treating the modulesdict as a dictionary doesn't work. . Similar errors for items keys values indexing with key etc. Also same issues with iterating over ModulesList. Can look into working on it myself if there isn't some reason this hasn't been implemented,

**Comment by SamGalanakis** [comment]
Ok, would be nice to add a warning when initializing or at least documentation for ModuleDicta nd ModuleList

**Comment by BenjaminBossan** [comment]
We now raise an error directly when initializing the model.

**Comment by SamGalanakis** [comment]
> We now raise an error directly when initializing the model.

Nice thanks!

**Comment by function2-llx** [comment]
@BenjaminBossan Hello, may I ask some questions about the usage for `ModulesToSaveWrapper` here? I'm sorry if it is inappropriate to ask here, and I'll open a new issue in that case. 

First, in the comment above and the related PR it is mentioned that:

> Even if `__getitem__` etc. were exposed, I'm not sure if it would work correctly, e.g. `forward` would also fail IIUC.

> The reason why `ModulesToSaveWrapper` cannot support `ModuleDict` et al. is because it tries to call forward on the original or copied module, but these modules don't implement a forward method.

Could you please explain why does `ModulesToSaveWrapper` have to ensure that its `forward` should work? In my opinion, a `ModulesToSaveWrapper` object is a "wrapper" of the original module and derived modules for adapters, and users will use it as if it was the wrapped module. If the original module does not support methods like `forward`, users will not call those unsupported methods either on the corresponding `ModulesToSaveWrapper` object. Thus, it makes sense to me `ModulesToSaveWrapper` does not have to support `forward` all the time.

Second, can we make `ModulesToSaveWrapper` support getting attributes of the wrapped module? As mentioned by the first question, I feel like using the `ModulesToSaveWrapper` as if it was the inner module. Overwriting `__getattr__` seems plausible to achieve this, just like what `LoraModel` does:

https://github.com/huggingface/peft/blob/bc9426f10b584a895082ec18ccfd1d56211b0dfa/src/peft/tuners/lora/model.py#L268-L273

I have checked this comment (https://github.com/huggingface/peft/pull/1238#pullrequestreview-1772299804), it was mentioned that overwriting `__getattr__` was less preferred. However, currently, only the `weight` attribute is supported, which restricts my use case.

My last question may not be that closely related to this issue: Is there a way to make an `nn.Parameter` trainable (e.g., the embedding for the [CLS] token)? Currently, `modules_to_save` in the `PeftConfig` only supports `nn.Module`. 

Thank you in advance!

**Comment by BenjaminBossan** [comment]
Thanks @function2-llx for raising these concerns. You're right that it would probably be possible to make `ModulesToSaveWrapper` work with `ModuleDict` if the appropriate methods are exposed. I'm still not too happy about using `__getattr__` but maybe we could live with that.

Just one thing I wonder: Would it be possible to target the individual modules within the `ModuleDict` with `modules_to_save` instead of targeting the whole `ModuleDict`?

Anyway, I'd be open to exploring this further in a separate PR if you're interested.

> Is there a way to make an `nn.Parameter` trainable (e.g., the embedding for the [CLS] token)? Currently, `modules_to_save` in the `PeftConfig` only supports `nn.Module`.

Could you please give an example where this currently fails?

Again, in general I think this could be possible but it could require some extra work because right now, we're not matching parameters when we check for targets to replace, only modules. If we want to change that logic, we have to be careful not to break anything.

**Comment by function2-llx** [comment]
@BenjaminBossan Thanks for the reply. I agree that we must be very careful when introducing new stuffs, especially when working with some fundamental methods like `__getattr__`, more discussions, especially suggestions from other members and users, are necessary. The good news is that such practice is not that uncommon and we can learn many experience from many widely used libraries if we finally decided to do so. 

> Just one thing I wonder: Would it be possible to target the individual modules within the `ModuleDict` with ·modules_to_save` instead of targeting the whole `ModuleDict`?

Yes, I believe this is possible. Here's a simple example to achieve this:

```python
from peft.utils import ModulesToSaveWrapper
from torch import nn

class MyWrapper(ModulesToSaveWrapper):
    @property
    def active_module(self):
        if self.active_adapter not in self.modules_to_save:
            return self.original_module
        return self.modules_to_save[self.active_adapter]

    def __getitem__(self, item):
        return self.active_module.__getitem__(item)

def main():
    wrapper = MyWrapper(
        nn.ModuleDict({
            '1': nn.Linear(10, 10),
            '2': nn.Conv2d(10, 10, 1),
        }),
        'default',
    )
    print(wrapper['1'])
    print(wrapper['2'])

if __name__ == '__main__':
    main()
```

The executing output of the script is as follows, which should

```
Linear(in_features=10, out_features=10, bias=True)
Conv2d(10, 10, kernel_size=(1, 1), stride=(1, 1))
```

If we call the wrapper with `wrapper()`, the error message is also quite informative, a user will easily understand that a mistake was made to call `forward` on a (wrapped) `ModuleDict` object.

```
NotImplementedError: Module [ModuleDict] is missing the required "forward" function
```


> > Is there a way to make an `nn.Parameter` trainable (e.g., the embedding for the [CLS] token)? Currently, `modules_to_save` in the `PeftConfig` only supports `nn.Module`.
> 
> Could you please give an example where this currently fails?

This will happen when both submodules and parameters are registered under the same module. For example, in the following code, the position embedding `self.pos_embed` is registered as an `nn.Parameter` under the `SamVisionEncoder`, while there are also other submodules registered (e.g., `self.patch_embed`). In this case, I find it impossible to use `modules_to_save` to make `self.pos_embed` trainable. 



https://github.com/huggingface/transformers/blob/c8d98405a8f7b0e5d07391b671dcc61bb9d7bad5/src/transformers/models/sam/modeling_sam.py#L982-L1000

```python
class SamVisionEncoder(nn.Module):
    def __init__(self, config: SamVisionConfig):
        super().__init__()
        self.config = config
        self.image_size = config.image_size

        self.patch_embed = SamPatchEmbeddings(config)

        self.pos_embed = None
        if config.use_abs_pos:
            # Initialize absolute positional embedding with pretrain image size.
            self.pos_embed = nn.Parameter(
                torch.zeros(
                    1,
                    config.image_size // config.patch_size,
                    config.image_size // config.patch_size,
                    config.hidden_size,
                )
            )
```

**Comment by function2-llx** [comment]
But I don't think these are issues totally prevent my usage though. In my opinion, it seems that the modules that a PEFT model works with (including both `modules_to_save` and `target_modules` for LoRA) are "leaf modules", that is, modules without any submodules but parameters. Here are my workarounds accordingly:

1. Search all leaf modules of a model and classify each of them. For example, if I want to fully fine-tune some module when working with LoRA, I use the following function to generate `target_modules` and `modules_to_save`:

```python
def get_lora_modules_finetune_all(module: nn.Module, prefix: str):
    target_modules, modules_to_save = [], []

    # noinspection PyShadowingNames
    def dfs(m: nn.Module, prefix: str):
        if len(named_children := list(m.named_children())) == 0:
            # is leaf module
            modules_to_save.append(prefix)
        else:
            for name, child in named_children:
                dfs(child, apply_prefix(prefix, name))

    dfs(module, prefix)
    return target_modules, modules_to_save

def apply_prefix(prefix: str, name: str):
    return f'{prefix}{name}' if prefix.endswith('.') or not prefix else f'{prefix}.{name}'
```

2. When necessary, wrap the parameter in the `nn.Module`.

```python
class ParameterWrapper(nn.Module):
    def __init__(self, weight: nn.Parameter):
        super().__init__()
        # use "weight" as the name for the wrapped parameter because `ModulesToSaveWrapper` supports it
        self.weight = weight
```

**Comment by BenjaminBossan** [comment]
> Yes, I believe this is possible. Here's a simple example to achieve this:

What I meant is that this should already be possible without any modifications to `ModulesToSaveWrapper`:

```python
class MyModule(nn.Module):
    def __init__(self):
        super().__init__()
        self.md = nn.ModuleDict({"foo": nn.Linear(1, 2), "bar": nn.Conv2d(3, 2, 1)})
        self.baz = nn.Linear(3, 4)

config = LoraConfig(modules_to_save="foo", target_modules=["baz"])
get_peft_model(MyModule(), config)

# returns:
PeftModel(
  (base_model): LoraModel(
    (model): MyModule(
      (md): ModuleDict(
        (foo): ModulesToSaveWrapper(
          (original_module): Linear(in_features=1, out_features=2, bias=True)
          (modules_to_save): ModuleDict(
            (default): Linear(in_features=1, out_features=2, bias=True)
          )
        )
        (bar): Conv2d(3, 2, kernel_size=(1, 1), stride=(1, 1))
      )
      (baz): lora.Linear(
        (base_layer): Linear(in_features=3, out_features=4, bias=True)
        (lora_dropout): ModuleDict(
          (default): Identity()
        )
        (lora_A): ModuleDict(
          (default): Linear(in_features=3, out_features=8, bias=False)
        )
        (lora_B): ModuleDict(
          (default): Linear(in_features=8, out_features=4, bias=False)
        )
        (lora_embedding_A): ParameterDict()
        (lora_embedding_B): ParameterDict()
      )
    )
  )
)
```

So we can already target a specific module within a `ModuleDict`. If we want to target all modules in the `ModuleDict`, as long as we know the names of the keys, we can do that without having to target the `ModuleDict` itself. It's not quite as comfortable maybe, but also not that hard.

> This will happen when both submodules and parameters are registered under the same module. For example, in the following code, the position embedding `self.pos_embed` is registered as an `nn.Parameter` under the `SamVisionEncoder`, while there are also other submodules registered (e.g., `self.patch_embed`). In this case, I find it impossible to use `modules_to_save` to make `self.pos_embed` trainable.

Thanks for providing an example. This is indeed not possible at the moment. I'm not sure how easy it would be to add this feature, since we go through the `named_modules`, which does not include pure `nn.Parameter`s. Trying to match individual parameters could be quite hard, as we don't really have control about how they're being used.
