### ISSUE TITLE
TypeError: LoraConfig.__init__() got an unexpected keyword argument 'use_original_init'

### ISSUE THREAD

**Issue by moghadas76** [huggingface/peft#1511]
### System Info

TypeError: LoraConfig.__init__() got an unexpected keyword argument 'use_original_init'

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] My own task or dataset (give details below)
- [ ] An officially supported task in the `examples` folder

### Reproduction

config = LoraConfig(
                r=16,
                lora_alpha=16,
                target_modules=["query", "value"],
                lora_dropout=0.1,
                use_original_init=False,
                bias="none",
                modules_to_save=["classifier"],
            )

### Expected behavior

done!

**Comment by BenjaminBossan** [comment]
`use_original_init` is not a valid argument, please remove it.

**Comment by JessicaLopezEspejel** [comment]
> use_original_init

It does not work , do you have any idea about it? I am calling the model as follows:
```
model_id = "jessicalopez/FT_CodeTrans_db"
model = AutoPeftModelForCausalLM.from_pretrained(model_id)
```
Thank you in advance.

**Comment by BenjaminBossan** [comment]
@JessicaLopezEspejel What PEFT version are you using? Probably your version is too low.
