### ISSUE TITLE
Tinyllama with Lora consumes more memory than full-finetuning

### ISSUE THREAD

**Issue by rohitgr7** [huggingface/peft#1514]
### System Info

peft==0.8.2
transformers==4.36.2
torch==2.1.0

python: 3.10
GPU: A100
CUDA: 12.3

### Who can help?

@pacman100 @younesbelkada @sayakpaul 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

```py
from peft import PeftModel
from transformers import AutoModelForCausalLM
import torch
from tqdm.auto import tqdm


def train(with_lora=False):
    model = AutoModelForCausalLM.from_pretrained(
        "TinyLlama/TinyLlama-1.1B-intermediate-step-1431k-3T",
        torch_dtype=torch.bfloat16,
        attn_implementation='flash_attention_2',
        device_map='cuda:2'
    )

    if with_lora:
        model = PeftModel.from_pretrained(model, "TinyPixel/tinyllama-lora", is_trainable=True)
    
    model = model.train()
    input_ids = torch.randint(0, 10000, (2, 8192)).cuda(2)
    attention_mask = torch.randint(1, 2, (2, 8192)).cuda(2)
    optimizer = AdamW(model.parameters(), lr=1e-4)
    for _ in tqdm(range(1000), total=1000):
        res = model(input_ids=input_ids, attention_mask=attention_mask, labels=input_ids)
        res.loss.backward()
        optimizer.step()
        optimizer.zero_grad()


if __name__ == '__main__':
    train(with_lora=False)
```

### Expected behavior

With Lora it's using ~57GB and with full-finetuning it is using ~53GB, which is weird. Ideally it should consume less memory when using lora.

**Comment by BenjaminBossan** [comment]
I believe the issue here is that you're only performing inference, not fine-tuning. For pure inference, LoRA is expected to consume more memory, since we're adding the LoRA parameters on top of the base model. Could you check if calling `model = model.merge_and_unload()` after loading the LoRA weights helps with getting the same memory?

When it comes to memory savings with LoRA, they are only materialized during training. I ran your scripts (with a few variations) and added training with AdamW. Without LoRA, I ran out of memory with 16GB but with LoRA, I could train with ~7GB being used.

**Comment by BenjaminBossan** [comment]
> can you share those variations? It'd be very helpful for me.

This won't be very useful for you:

- turned off flash attention (because of cuda driver)
- turned off bf16 (not supported)
- switched to device 0
- added optimizer (AdamW)
- called `res.loss.backward()` and stepped the optimizer inside the loop

> Yeah I didn't add backward and optimizer to make it minimal by just enabling the train mode in lora

That's commendable but I think in this case, you removed a bit too much :) Did you observe the memory increase when you performed actual training?

**Comment by rohitgr7** [comment]
turning of flash attn is just going OOM.
```py
from peft import PeftModel
from transformers import AutoModelForCausalLM
import torch
from tqdm.auto import tqdm
from torch.optim import AdamW


def train(with_lora=False):
    model = AutoModelForCausalLM.from_pretrained(
        "TinyLlama/TinyLlama-1.1B-intermediate-step-1431k-3T",
        # torch_dtype=torch.bfloat16,
        # attn_implementation='flash_attention_2',
        device_map='cuda:0'
    )

    if with_lora:
        model = PeftModel.from_pretrained(model, "TinyPixel/tinyllama-lora", is_trainable=True)
    
    model = model.train()
    input_ids = torch.randint(0, 10000, (1, 8192)).cuda(0)
    attention_mask = torch.randint(1, 2, (1, 8192)).cuda(0)
    optimizer = AdamW(model.parameters(), lr=1e-4)
    for _ in tqdm(range(1000), total=1000):
        res = model(input_ids=input_ids, attention_mask=attention_mask, labels=input_ids)
        res.loss.backward()
        optimizer.step()
        optimizer.zero_grad()


if __name__ == '__main__':
    train(with_lora=True)
```

**Comment by BenjaminBossan** [comment]
That's why I mentioned this won't be very useful for you: I only made these changes out of necessity. Please go ahead and use flash attention and bf16.

**Comment by rohitgr7** [comment]
@BenjaminBossan you mentioned `I could train with ~7GB being used.`. Just need to know how do did that? was it with the same context length? maybe I am missing something.

**Comment by BenjaminBossan** [comment]
> was it with the same context length

Much reduced context length, sorry I forgot to mention that.

But regardless of all of that, the essence is that inference (without `merge_and_unload`) is expected to take a bit _more_ memory with LoRA, the memory saving is for training.

**Comment by rohitgr7** [comment]
I see. but still no memory saving with `merge_and_upload`. I literally can't call loss.backward

```py
model = model.merge_and_unload()
```
returns a LlamaModel (without lora)

```py
model.merge_and_unload()
```
disable requires_grad for all the parameters.

I think `merge_and_unload` is meant for inference only.

**Comment by BenjaminBossan** [comment]
Yes, `merge_and_unload` is for getting the same memory usage for inference, which the snippet you posted tests. It does not work for training.

Using LoRA for training (without any kind of merging) should result in lower memory usage, though. If you find this not to be the case, let us know.

**Comment by rohitgr7** [comment]
> Using LoRA for training (without any kind of merging) should result in lower memory usage, though. If you find this not to be the case, let us know.

yes, this is not the case. It is taking more memory.  I have shared the code-snippet in the my issue as well.

**Comment by BenjaminBossan** [comment]
Which one? [Here](https://github.com/huggingface/peft/issues/1514#issuecomment-1969482523) you just mention that you get OOM, not that LoRA requires more memory than full fine-tuning.

**Comment by rohitgr7** [comment]
I meant with flash-attn (code in issue description) this is not the case. Lora is taking a little bit more memory than full-finetuning.

**Comment by BenjaminBossan** [comment]
I see. Unfortunately, I cannot currently test this, as I don't have an Ampere GPU. What is the memory usage of that script with vs without LoRA when using FA2?

**Comment by rohitgr7** [comment]
> With Lora it's using ~57GB and with full-finetuning it is using ~53GB, which is weird. Ideally it should consume less memory when using lora.

**Comment by BenjaminBossan** [comment]
Again, I tried to reproduce the issue but couldn't, LoRA reduces the memory requirements when I test it. The changes that I made:

- No flash attention
- float16 instead of bfloat16
- smaller input size (1024 instead of 8192)

I don't think any of these should make a difference.

Could you try calling `model.print_trainable_parameters()` right before the training loop starts to ensure that we're really only training the LoRA parameters and not somehow all parameters?

**Comment by rohitgr7** [comment]
it says 4% trainable parameters or something. I noticed that with long context length the difference in memory usage is kind of same. With low context length, I see the major difference. So probably somewhere in that direction we need to explore?

**Comment by BenjaminBossan** [comment]
> I noticed that with long context length the difference in memory usage is kind of same. With low context length, I see the major difference. So probably somewhere in that direction we need to explore?

Could you please give some numbers: Trying out a few different context lengths, what is the memory usage with PEFT vs without PEFT.

**Comment by rohitgr7** [comment]
```
trainable params: 50,462,720 || all params: 1,150,511,104 || trainable%: 4.386113252149889
```

| context length | Lora (GB) | Without Lora (GB) |
|----------------|-----------|-------------------|
| 512            | 12.3      | 6.6               |
| 1024           | 13.4      | 10                |
| 2048           | 18.7      | 16.9              |
| 4096           | 31.7      | 30.5              |
| 8192           | 54.2      | 57.8              |

**Comment by rohitgr7** [comment]
ah! sorry. The error was in the column name. Updated it.

```
trainable params: 50,462,720 || all params: 1,150,511,104 || trainable%: 4.386113252149889
```

| context length | Without Lora (GB) | Lora (GB) |
|----------------|-----------|-------------------|
| 512            | 23.9      | 12.4               |
| 1024           | 29.1      | 22.1                |
| 1536           | 42.4      | 35.4              |
| 2048           | 58.2      | 52.2              |
| 4096           | OOM      | OOM              |
| 8192           | OOM      | OOM              |


This is the script btw:
```py
def train(with_lora=False):
    model = AutoModelForCausalLM.from_pretrained(
        "TinyLlama/TinyLlama-1.1B-intermediate-step-1431k-3T",
        device_map='cuda:2'
    )

    if with_lora:
        model = PeftModel.from_pretrained(model, "TinyPixel/tinyllama-lora", is_trainable=True)
        model.print_trainable_parameters()
    
    model = model.train()
    input_ids = torch.randint(0, 10000, (2, 4096)).cuda(2)
    attention_mask = torch.randint(1, 2, (2, 4096)).cuda(2)
    optimizer = AdamW(model.parameters(), lr=1e-4)
    for _ in tqdm(range(20), total=20):
        res = model(input_ids=input_ids, attention_mask=attention_mask, labels=input_ids)
        res.loss.backward()
        optimizer.step()
        optimizer.zero_grad()
```

**Comment by rohitgr7** [comment]
could be. This is the behavior I noticed only with small models, not with ~7B models.
