### ISSUE TITLE
add pre-commit for better formatting?

### ISSUE THREAD

**Issue by mayank31398** [huggingface/peft#152]
Can we have a pre-commig-config in this repo?
for better formatting?

**Comment by pacman100** [comment]
Hello, as of now, one needs to do the following before raising the PR:
1. make style
2. make quality

There aren't CI tests to ensure that is being done at present though. Will be adding those CI tests eventually. This would keep PEFT in sync with all the other HF libraries. I don't think pre-commig-config is used in other HF libraries, hence won't be exploring this at present.

**Comment by mayank31398** [comment]
I see thanks. It is used in this [library](https://github.com/huggingface/transformers-bloom-inference).
But I maintain it, so maybe its just me :) 🤗

**Comment by mayank31398** [comment]
closing this.
Thanks
