### ISSUE TITLE
integrate ResLoRA

### ISSUE THREAD

**Issue by hllj** [huggingface/peft#1520]
### Feature request

Integrate ResLoRA into PEFT.
Paper: https://arxiv.org/abs/2402.18039
Code from Microsoft: https://github.com/microsoft/LMOps/tree/main/reslora

### Motivation

I find interesting in this paper from Microsoft about Identity Residual Mapping between LoRA.

### Your contribution

Yes, I can contribute by submitting a PR. Working on it.

**Comment by madstuntman11** [comment]
Hello @hllj  Did you had a chance to move forward with the integration?
