### ISSUE TITLE
AQLM with LORA too slow

### ISSUE THREAD

**Issue by DavidAkinpelu** [huggingface/peft#1536]
### System Info

transformers: git+https://github.com/huggingface/transformers@4fc708f98c9c8d5cb48e8a2639e3f7a21c65802f
Platform: Ubuntu 22.04.3 LTS
GPU: RTX GeForce 3090
Python version: 3.10.13
Aqlm: 1.0.3
Huggingface_hub version: 0.20.3
Accelerate version: git+https://github.com/huggingface/accelerate@63cfd9efdc29eb1f87e949fda341ccec0bc9baed
PyTorch version (GPU?): 2.2.1+cu122 (True)
Using GPU in script?: yes
Using distributed or parallel set-up in script?: no
Peft version: git+https://github.com/huggingface/peft@c43cc5028ea6779dd885a664dcd6e0327ed99551

### Who can help?

@younesbelkada @pac

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

```
base_model_flavor = "BlackSamorez/Llama-2-7b-AQLM-2Bit-1x16-hf"

model = AutoModelForCausalLM.from_pretrained(base_model_flavor,
                                      trust_remote_code=trust_remote_code,
                                      torch_dtype=torch.float16,
                                      device_map="auto",
                                      low_cpu_mem_usage=True)
 model = model.model

peft_config = LoraConfig(
            r=32,
            lora_alpha=64,
            bias="none",
            lora_dropout=0.1,
            task_type=TaskType.FEATURE_EXTRACTION,
            target_modules=l["q_proj", "o_proj", "v_proj", "k_proj"],
            inference_mode=False
        )

  model = get_peft_model(model, peft_config)
```

### Expected behavior

I am trying to use AQLM with LORA for a feature extraction task. Unfortunately the training is really slow i.e 74 forward passes in 11 minutes. I don't know what I am doing wrong.

**Comment by younesbelkada** [comment]
Hi @DavidAkinpelu 
Thanks for the issue ! Can you confirm with us the model is entirely loaded on GPU? `print(model.hf_device_map)` Also what is your AQLM version?
cc @BlackSamorez as well

**Comment by BlackSamorez** [comment]
Hi @DavidAkinpelu !
It's, sadly, not properly documented yet, but you should do:
```python
import aqlm

with aqlm.optimize_for_training():
    model = AutoModelForCausalLM.from_pretrained(base_model_flavor,
                                      trust_remote_code=trust_remote_code,
                                      torch_dtype=torch.float16,
                                      device_map="auto",
                                      low_cpu_mem_usage=True)
```

The thing is, there a few ways to compute a forward pass and some of them work better for very small number of tokens (e.g. generation), and some are optimized for large batch sizes (e.g. training). We're hoping to be able to determine which kernels to use dynamically in later versions of `aqlm`, but, for now, please add that wrapped explicitly. Also, keep in mind, that a model loaded under that wrapper will be very slow on generation. We're working on making it a more pleasant experience!

**Comment by younesbelkada** [comment]
Thanks very much @BlackSamorez !!
It would be great if we can mention that context manager in the docs: https://huggingface.co/docs/peft/main/en/developer_guides/quantization#aqlm-quantizaion - the file that needs to be modified is this one: https://github.com/huggingface/peft/blob/main/docs/source/developer_guides/quantization.md would you like to open a PR for it? Otherwise happy to do it !

**Comment by DavidAkinpelu** [comment]
Thanks. It's working now!

**Comment by BlackSamorez** [comment]
@younesbelkada I've replaced it with an automatic selection and deprecated the `optimize_for_training` wrapper in `aqlm` version `1.1.0`.
That's why I didn't want to document it: it wasn't meant to last long. We were planning to make everything more ready for a second series of PR posts we're planning to run within a few days.

**Comment by younesbelkada** [comment]
Awesome, thank you so much @BlackSamorez ! Great work !
