### ISSUE TITLE
[Feature request] Support LoftQ with CPU offloading

### ISSUE THREAD

**Issue by peterjc123** [huggingface/peft#1538]
### Feature request

When GPU memory is limited, we have to use QLoRA. With LoftQ, we could probably get better results. But it doesn't seem to be supported when cpu offloading is on at the time, since it throws an error `cannot copy params on the meta device`.

### Motivation

Have something to try when GPU memory is limited

### Your contribution

I can try out the changes if this is supported

**Comment by BenjaminBossan** [comment]
I think that there are some usability issues with LoftQ in general, as it requires quite a few steps to set up correctly and basically requires to create a copy of the base model. Therefore, I'll be thinking about how to improve usability in the future, which hopefully includes the issue you mentioned.
