### ISSUE TITLE
Fail to use multi-GPUs with peft model

### ISSUE THREAD

**Issue by TheoDpPro** [huggingface/peft#1544]
### System Info

transformers version: 4.38.1
accelerate version: 0.26.1
peft version: 0.8.2
pytorch version: 2.1.2

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

    compute_dtype = getattr(torch, "bfloat16")
    bnb_config = BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_quant_type="nf4",
            bnb_4bit_compute_dtype=compute_dtype,
            bnb_4bit_use_double_quant=True,)
    
    model = AutoModelForCausalLM.from_pretrained(path_base_model, quantization_config=bnb_config, device_map='auto')
    tokenizer = AutoTokenizer.from_pretrained(path_base_model, padding_side="right", add_eos_token=True, add_bos_token=True)
  
    model.gradient_checkpointing_enable()
    model = prepare_model_for_kbit_training(model)
    config = LoraConfig(r=32, lora_alpha=64,
                        target_modules = ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj", "lm_head",], 
                        bias="none", lora_dropout=0.05, task_type="CAUSAL_LM",)
    model = get_peft_model(model, config)
  
    fsdp_plugin = FullyShardedDataParallelPlugin(state_dict_config=FullStateDictConfig(offload_to_cpu=True, rank0_only=False),
                                                optim_state_dict_config=FullOptimStateDictConfig(offload_to_cpu=True, rank0_only=False),)
    accelerator = Accelerator(fsdp_plugin=fsdp_plugin)
    model = accelerator.prepare_model(model, device_placement=True)

    train_args = transformers.TrainingArguments(
                    output_dir=output_dir,
                    warmup_steps=1,
                    per_device_train_batch_size=batch_size,
                    gradient_accumulation_steps=1,
                    gradient_checkpointing=True,
                    num_train_epochs=num_train_epochs,
                    learning_rate=2.5e-5, 
                    bf16=False,
                    optim="paged_adamw_8bit",
                    logging_dir = './logs',
                    ddp_backend = "gloo"
                )

    trainer = transformers.Trainer(
        model = model,
        train_dataset = dataset_train_tokenized,
        eval_dataset  = dataset_test_tokenized,
        args = train_args,
        data_collator = transformers.DataCollatorForLanguageModeling(tokenizer, mlm=False),
    )

    model.config.use_cache = False  # silence the warnings. Please re-enable for inference!
    trainer.train()

### Expected behavior

Trying to fine-tune on 2 GPUs.

Memory usage of these 2 GPUs is :
GPU0 : 20 216 / 32 768
GPU1 : 23 220 / 32 768

However, GPU utilization is :   
GPU0: 0%
GPU1: 100%

Sometimes, it switches such that GPU0 utilization is 100% and GPU1 0%.

But, they are never used at the same time.

Note that model parallelism with my custom PyTorch models work normally.

I do not know if it's a bug, or an implementation mistake. Please, do you have any idea ?

**Comment by younesbelkada** [comment]
Hi @TheoDpPro 
Yes this is expected, in this specific case, you are performing naive pipeline parallelism through `device_map="auto"`. Your model is loaded evenly across the two GPUs but the hidden states are computed in a sequential manner on each GPU. 
If you want to maximize your GPU usage, you should perform DP (Data Parallelism), by reducing the batch_size and making sure you are loading two copies of the model on each GPU by forcing the `device_map` to load the model on the GPU `i`:

```diff
+ from accelerate import PartialState

compute_dtype = getattr(torch, "bfloat16")
bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=compute_dtype,
        bnb_4bit_use_double_quant=True,)

- model = AutoModelForCausalLM.from_pretrained(path_base_model, quantization_config=bnb_config, device_map='auto')
+ model = AutoModelForCausalLM.from_pretrained(path_base_model, quantization_config=bnb_config, device_map={'': PartialState().process_index})
tokenizer = AutoTokenizer.from_pretrained(path_base_model, padding_side="right", add_eos_token=True, add_bos_token=True)

model.gradient_checkpointing_enable()
model = prepare_model_for_kbit_training(model)
config = LoraConfig(r=32, lora_alpha=64,
                    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj", "lm_head",], 
                    bias="none", lora_dropout=0.05, task_type="CAUSAL_LM",)
model = get_peft_model(model, config)

fsdp_plugin = FullyShardedDataParallelPlugin(state_dict_config=FullStateDictConfig(offload_to_cpu=True, rank0_only=False),
                                            optim_state_dict_config=FullOptimStateDictConfig(offload_to_cpu=True, rank0_only=False),)
accelerator = Accelerator(fsdp_plugin=fsdp_plugin)
model = accelerator.prepare_model(model, device_placement=True)

train_args = transformers.TrainingArguments(
                output_dir=output_dir,
                warmup_steps=1,
                per_device_train_batch_size=batch_size,
                gradient_accumulation_steps=1,
                gradient_checkpointing=True,
                num_train_epochs=num_train_epochs,
                learning_rate=2.5e-5, 
                bf16=False,
                optim="paged_adamw_8bit",
                logging_dir = './logs',
                ddp_backend = "gloo"
            )

trainer = transformers.Trainer(
    model = model,
    train_dataset = dataset_train_tokenized,
    eval_dataset  = dataset_test_tokenized,
    args = train_args,
    data_collator = transformers.DataCollatorForLanguageModeling(tokenizer, mlm=False),
)

model.config.use_cache = False  # silence the warnings. Please re-enable for inference!
trainer.train()
```

```python
PartialState().process_index
```
Will return `0` for the GPU 0 and will return `1` for the GPU 1. Then you need to make sure `accelerate` is configured properly for multi-GPU by running `accelerate config` and selecting "multi-gpu" and run your script with `accelerate run xxx.py`

**Comment by younesbelkada** [comment]
Very nice @TheoDpPro ! Thanks so much !
