### ISSUE TITLE
/usr/local/lib/python3.8/dist-packages/peft/tuners/lora.py:167: UserWarning: fan_in_fan_out is set to True but the target module is not a Conv1D. Setting fan_in_fan_out to False.  

### ISSUE THREAD

**Issue by imrankh46** [huggingface/peft#155]
what are the targed modules for BLOOM or any other model in text generattion category ?
i got the following error,

> /usr/local/lib/python3.8/dist-packages/peft/tuners/lora.py:167: UserWarning: fan_in_fan_out is set to True but the target module is not a Conv1D. Setting fan_in_fan_out to False.  

```
from peft import LoraConfig, get_peft_model, TaskType, get_peft_config

config = LoraConfig(
    r=8,
    lora_alpha=32,
    #target_modules=["q_proj", "v_proj"],
    lora_dropout=0.2,
    task_type=TaskType.CAUSAL_LM, 
    inference_mode=False,
   
)

model = get_peft_model(model, config)
print_trainable_parameters(model)
```

**Comment by pacman100** [comment]
Hello @imrankh46, target modules differ from model to model. You can safely ignore the above warning. FPlease find the mappings for popular models here: https://github.com/huggingface/peft/blob/main/src/peft/mapping.py#L41-L58

**Comment by imrankh46** [comment]
> Hello @imrankh46, target modules differ from model to model. You can safely ignore the above warning. FPlease find the mappings for popular models here: https://github.com/huggingface/peft/blob/main/src/peft/mapping.py#L41-L58

Thank you for this. The one issues is solve.
