### ISSUE TITLE
Base Model Revision

### ISSUE THREAD

**Issue by mnoukhov** [huggingface/peft#1567]
### Feature request

Currently, the `adapter_config` only stores the `base_model_name_or_path` but not the `revision`. This means that if a `PeftModel` is trained on top of a model with a `revision` then loading `PeftModel.from_pretrained` will load the `main` revision of the base model, not the correct revision. 

We should add a `base_model_revision` to the `adapter_config` so that we can correctly load the base model 

### Motivation

This will cause a bug if using `PeftModel.from_pretrained` when the base model has a revision.  

### Your contribution

I can try to submit a PR if I have time in 2-3 weeks

**Comment by BenjaminBossan** [comment]
Thanks for this suggestion, it sounds good. A PR would be great, but no need to rush it.

**Comment by mnoukhov** [comment]
I looked into it and found that there's already actually a `revision` parameter 
https://github.com/huggingface/peft/blob/56773b9a92b141111d65fe3548d0c30233358868/src/peft/config.py#L235

It's just not being used when calling `from_pretrained` here https://github.com/huggingface/peft/blob/56773b9a92b141111d65fe3548d0c30233358868/src/peft/auto.py#L104

I've opened the PR #1658 but in order to do unit tests, I need a model with a base model with revision. If you don't mind this not being on `hf-internal-testing`, I can upload it to my personal account, but maybe you'd prefer the former. Let me know @BenjaminBossan

**Comment by BenjaminBossan** [comment]
_not stale_

**Comment by mnoukhov** [comment]
resolved by #1658
