### ISSUE TITLE
PP or TP supported for multi-node training?

### ISSUE THREAD

**Issue by mxjyst** [huggingface/peft#1572]
### System Info

deepspeed
accelerate

### Who can help?

@pacman100 @younesbelkada @sayakpaul 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

Do pipeline parallel and tensor parallel are supported for multi-node fine-tuning(lora and QLora)? Is there doc or any suggestions on these？

### Expected behavior

--

**Comment by BenjaminBossan** [comment]
QLoRA should work with [DeepSpeed](https://huggingface.co/docs/peft/main/en/accelerate/deepspeed#deepspeed). [FSDP](https://www.answer.ai/posts/2024-03-06-fsdp-qlora.html) should also work but may require the latest versions of the respectively involved libraries (bitsandbytes, transformers, trl, peft).

**Comment by mxjyst** [comment]
Agree with you. But deepspeed ad FSDP are all data parallel. If I  want to fine-tune much large model, like 130B llm, there will be OOM with 80G 4xA100. I think pipeline or tensor parallel is needed in this case.

**Comment by BenjaminBossan** [comment]
DS and FSDP are not just data parallel but model parallel. Regarding PP and TP, I'm not aware of working examples. This doesn't mean it can't work, but I wouldn't suspect it to run out of the box.
