### ISSUE TITLE
Error in LoraModel docstring

### ISSUE THREAD

**Issue by brynhayder** [huggingface/peft#1586]
https://github.com/huggingface/peft/blob/78daa4cf7624ec9c2c38fe73b0317b61428ca26b/src/peft/tuners/lora/model.py#L71

Not possible to default because written as a positional argument

**Comment by brynhayder** [comment]
There is also no mention in the docs that this modifies the `model` argument as a side effect.

**Comment by BenjaminBossan** [comment]
> Not possible to default because written as a positional argument

I agree that it's confusing but it is accurate. `LoraModel` is not called directly by users but indirectly via `PeftModel`, which uses `"default"` as default for the adapter name.

> There is also no mention in the docs that this modifies the `model` argument as a side effect.

We do document it sporadically (e.g. [here](https://huggingface.co/docs/peft/package_reference/peft_model#peft.PeftModel.from_pretrained)) but I agree that we should mention it in more places. If you're interested, feel free to open a PR and add a mention where you think it's most relevant.
