### ISSUE TITLE
TaskType attribute in Lora config for question answering is wrong 

### ISSUE THREAD

**Issue by aryangoyal7** [huggingface/peft#1589]
### System Info

in documentation it is "QUESTION_ANS = "QUESTION_ANS"" but it doesnt work, i test the same code for CASUAL_LM , it works, hence needs to be fixed, I tried "QUESTION_ANSWERING" that does work as wellthe 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

```python
from peft import LoraConfig, get_peft_model, TaskType

config = LoraConfig(
    r=32,
    lora_alpha=64,
    target_modules=[
        "q_proj",
        "k_proj",
        "v_proj",
        "o_proj",
        "gate_proj",
        "up_proj",
        "down_proj",
        "lm_head",
    ],
    bias="none",
    lora_dropout=0.05,  # Conventional
    task_type=TaskType.QUESTION_ANSWERING,
)
print("task_type")
model = get_peft_model(model, config)
print_trainable_parameters(model)



print(model)
```

### Expected behavior

the model shouldnt have an attribute error or anything

**Comment by BenjaminBossan** [comment]
Your snippet worked for me with some minor modifications:

```diff
model  = AutoModelForQuestionAnswering.from_pretrained("facebook/opt-125m")

config = LoraConfig(
    r=32,
    lora_alpha=64,
    target_modules=[
        "q_proj",
        "k_proj",
        "v_proj",
        "o_proj",
        "gate_proj",
        "up_proj",
        "down_proj",
        "lm_head",
    ],
    bias="none",
    lora_dropout=0.05,  # Conventional
-     task_type=TaskType.QUESTION_ANSWERING,
+     task_type=TaskType.QUESTION_ANS,
)
print("task_type")
model = get_peft_model(model, config)
- print_trainable_parameters(model)
+ model.print_trainable_parameters()
# prints trainable params: 1,771,010 || all params: 127,011,844 || trainable%: 1.3943660246362537
```

This was tested with the latest PEFT version.

**Comment by aryangoyal7** [comment]
what is the specified format for questionn answering dataset then? 
![image](https://github.com/huggingface/peft/assets/98456095/c5143aba-3377-4223-bf2f-aa024f8d1b7c)
I am getting this error.

**Comment by BenjaminBossan** [comment]
Could you please share the code that results in this error? Also, please paste the error message as text, not as image. Thanks.
