### ISSUE TITLE
NotImplementedError: Saving is not supported for PeftMixedModel (yet).

### ISSUE THREAD

**Issue by mickeymickeymonkey** [huggingface/peft#1590]
### Feature request

I trained a peftmixedmodel with different adapters but can't save the adapter weights. any idea what why it is not possible to save_pretrained like normal? any idea when this can be possible?

### Motivation

being able to save the adapter weights only is a massive save on storage

### Your contribution

.

**Comment by BenjaminBossan** [comment]
So the intent of this class is to use different adapter types, like LoRA and LoHa, at inference time. Training of these adapters should be done separately. Therefore, it is assumed that these adapters have already been saved and there is no need to save them again. The reason why it's not supported is that it is not straightforward to implement this with different adapter types.

**Comment by mickeymickeymonkey** [comment]
ok I see, thank you for the explanations
