### ISSUE TITLE
model.print_trainable_parameters() is incomplete.

### ISSUE THREAD

**Issue by Minami-su** [huggingface/peft#1594]
model:ISTA-DASLab/Mixtral-8x7B-Instruct-v0_1-AQLM-2Bit-1x16-hf
peft:0.10.0
```
model = AutoModelForCausalLM.from_pretrained(base_model,
                                             trust_remote_code=True,
                                             attn_implementation="flash_attention_2",
                                             torch_dtype=torch.bfloat16,
                                             device_map="auto",
                                             low_cpu_mem_usage=True)
model = prepare_model_for_kbit_training(model)
config = LoraConfig(
        r=lora_r,
        lora_alpha=lora_alpha,
        target_modules=modules,
        lora_dropout=lora_dropout,
       # modules_to_save=modules_to_save,
        bias="none",
        task_type="CAUSAL_LM",
    )

model = get_peft_model(model, config)

model.print_trainable_parameters()  # Be more transparent about the % of trainable params.
print(model.get_nb_trainable_parameters())
print(model.num_parameters(only_trainable=False))
```
output:
trainable params: 242,225,152 || all params: 6,789,079,040 || trainable%: 3.5678646628335615
(242225152, 6789079040)
6789079040

**Comment by BenjaminBossan** [comment]
Sorry, could you please explain further what is missing?

**Comment by Minami-su** [comment]
> Mixtral-8x7B-Instruct



> Mixtral-8x7B-Instruct-v0_1

Mixtral-8x7B-Instruct-v0_1 has approximately 46 billion parameters, obviously the number of parameters being output here is incorrect

**Comment by Minami-su** [comment]
model:ISTA-DASLab/Mixtral-8x7B-Instruct-v0_1-AQLM-2Bit-1x16-hf
```
model = AutoModelForCausalLM.from_pretrained(base_model,
                                             trust_remote_code=True,
                                             attn_implementation="flash_attention_2",
                                             torch_dtype=torch.bfloat16,
                                             device_map="auto",
                                             low_cpu_mem_usage=True)
total_parameters = sum(p.numel() for p in model.parameters())

print(f"Total number of parameters: {total_parameters}")
```
output:
Total number of parameters: 6546853888

**Comment by BenjaminBossan** [comment]
So if I understand you correctly, the number of parameters you see when loading Mixtral 8x7B is not what you expect. This is not only when using `print_trainable_parameters()` from PEFT but also when counting the parameters directly. This means it's not a PEFT-specific issue. I would therefore suggest to go to transformers and open an issue there or open a discussion on the Hugging Face forums.
