### ISSUE TITLE
[Feature Request] Support `torch.nn.Conv1d` layers for LoRA

### ISSUE THREAD

**Issue by dg845** [huggingface/peft#1604]
### Feature request

I would like [`torch.nn.Conv1d`](https://pytorch.org/docs/stable/generated/torch.nn.Conv1d.html) layers to be supported by LoRA. Currently, if I try to include a `torch.nn.Conv1d` layer in `LoraConfig.target_modules`, I get the following error:

```bash
ValueError: Target module Conv1d(...) is not supported. Currently, only the following modules are supported: `torch.nn.Linear`, `torch.nn.Embedding`, `torch.nn.Conv2d`, `transformers.pytorch_utils.Conv1D`.
```

I see that [`transformers.pytorch_utils.Conv1D`](https://github.com/huggingface/transformers/blob/5ad7f17002f304b1e880fe2333c7deba95d12f4e/src/transformers/pytorch_utils.py#L83) is supported but it would be nice to be able to use non-`transformers` models with LoRA as well. [Edit: also, `transformers.pytorch_utils.Conv1D` is not as feature-ful as `torch.nn.Conv1d` (for example, it doesn't support different `kernel_size`s) because it's intended to essentially be a linear layer with weights transposed for following the OpenAI GPT-2 implementation.]

### Motivation

Audio models often use `torch.nn.Conv1d` layers so it would be easier to use LoRA with audio models if it is supported.

### Your contribution

I would be willing to open a PR for this, not sure if it can supported in the same way `torch.nn.Conv2d` is supported or if there are any specific difficulties with `torch.nn.Conv1d`.

**Comment by BenjaminBossan** [comment]
Yes, thanks, it would be good to have `nn.Conv1d` support for LoRA. Feel free to open a draft PR early and we can give quick feedback. Take a look for instance at #1324, which also adds a new module type, for inspiration.
