### ISSUE TITLE
Is there a choice to use `ignore_mismatch_sizes` in PeftModel.from_pretrained like AutoModel in Transformers?

### ISSUE THREAD

**Issue by gary-young** [huggingface/peft#1605]
### Feature request

Add ignore_mismatch_sizes in PeftModel.from_pretrained.

### Motivation

When I try to add some special tokens into an LM and use an adapter, I find though I can set ignore_mismatch_sizes = True when I load the base model, I have no similar choice to ignore the mismatch parameters when I load the adapter.
I have searched a possible way to first load the adapter and then add the base model. However, in my case, my base model has been some trained parameters that I cannot resize the parameters after loading the adapter.
Have I miss some args? Or is it a necessary choice?

### Your contribution

I don't know what can I do.

**Comment by BenjaminBossan** [comment]
Do you have some simple reproducer for the error you mentioned? Then we can check if there is something we can do on the PEFT side.

From what I understand, this shouldn't require a trained adapter, so it you could just show how you created and saved the adapter, then tried to load it, it should be sufficient.

**Comment by gary-young** [comment]
@BenjaminBossan Sorry, my statement was unclear. I did not encounter a bug, but I wish to submit a **feature request**. When I try to add new tokens to a pre-trained model **as well as** a corresponding adapter (which means the size of lm_head and token embed needs to change), I find that the `from_pretrained` function in transformers can conveniently ignore those modules with the same name but mismatched size by using the ignore_mismatch_size option. (See [here](https://huggingface.co/docs/transformers/v4.39.3/en/main_classes/model#transformers.PreTrainedModel.from_pretrained))

This is useful when I want to further fine-tune these models. However, I noticed that peft does not offer this option, meaning I cannot load a partially matched adapter into a base model that has loaded some parameters through the above method (with another part of the parameters being reinitialized due to size change). I hope Peft could offer a similar functionality.

In my case, I have trained a Llama with an adapter on my task, I use the `trainer.train` to automatically save the adapter, and the adapter has been saved successfully. But I want to use this model as well as the trained adpater to finetune on another task, which requires two special tokens, so I resize the base model (here, it means the Llama), and I can successfully load the pretrained Llama (except for the resized lm_head and embed_layer, which I will manually process them). However, I find I cannot load the adapter because I have changed the size of these two modules. I hope I have an option to just ignore them.

**Comment by gary-young** [comment]
I forgot to mention that for these two layers, I set them in `modules_to_save`, so they are both fully trained and saved in the adapter.

**Comment by BenjaminBossan** [comment]
Thanks you for clarifying, I think I got it now. So you would like something like this to work:

```python
import torch
from transformers import AutoModelForCausalLM
from peft import LoraConfig, PeftModel, get_peft_model
from peft.utils.other import ModulesToSaveWrapper

model_id = "facebook/opt-125m"
model0 = AutoModelForCausalLM.from_pretrained(model_id)
peft_config0 = LoraConfig(
    task_type="CAUSAL_LM", target_modules=["q_proj", "v_proj"], modules_to_save=["embed_tokens"], init_lora_weights=False
)
peft_model0 = get_peft_model(model0, peft_config0)

# embedding layer uses ModulesToSave:
[module for module in peft_model0.modules() if isinstance(module, ModulesToSaveWrapper)]

peft_model0.save_pretrained("/tmp/peft/issue-1605")

model1 = AutoModelForCausalLM.from_pretrained(model_id)
model1.resize_token_embeddings(50272 + 2)
# this currently raises an error:
peft_model1 = PeftModel.from_pretrained(model1, "/tmp/peft/issue-1605", ignore_mismatched_sizes=True)
# RuntimeError: Error(s) in loading state_dict for PeftModelForCausalLM:
# 	size mismatch for base_model.model.model.decoder.embed_tokens.modules_to_save.default.weight: copying a param with shape torch.Size([50272, 768]) from checkpoint, the shape in current model is torch.Size([50274, 768]).
```

Is that right?

**Comment by BenjaminBossan** [comment]
@gary-young I created a PR: #1620. Maybe you can check if it works with your use case.
