### ISSUE TITLE
Configuration issue

### ISSUE THREAD

**Issue by AswiniNLP** [huggingface/peft#1608]
### Feature request

When ever I am using 

```python
peft_config = PrefixTuningConfig(
    peft_type="PREFIX_TUNING",
    inference_mode=False,
    task_type=TaskType.SEQ_2_SEQ_LM,
    num_virtual_tokens=20,
    token_dim=768,
    num_transformer_submodules=1,
    num_attention_heads=12,
    num_layers=12,
    encoder_hidden_size=768,
)
```

 this setting in the flan T5 XXL model, while training I am getting in forward

> ValueError: There should be 4 past states. 2 (past / key) for cross attention. Got 2 past key / value states

Could you please help me to resolve this

**Comment by AswiniNLP** [comment]
The issue like when ever I give the configuration I am getting :
ValueError: There should be 4 past states. 2 (past / key) for cross attention. Got 2 past key / value states
This error I am getting during training.

**Comment by BenjaminBossan** [comment]
The error message must be longer than this, please copy the whole error message and paste it here.

Also, just initializing the config as you did above works, so there must be more code involved that leads to the error. Please share as much of that as you can, otherwise we won't be able to help you.

**Comment by AswiniNLP** [comment]
![Screenshot from 2024-04-03 21-20-22](https://github.com/huggingface/peft/assets/132350955/ff12eb8f-217a-46e8-ae42-edc641264e79)

Please find the attachment, Also I am not able to find the propose behind using token_dim=768,
    num_transformer_submodules=1,
    num_attention_heads=12,
    num_layers=12,
    encoder_hidden_size=768,
These parameters are inside the config. Because if I do not give these parameters then also my model works well, Please help me to explain this along with the solution for the error.

**Comment by BenjaminBossan** [comment]
Hi, I tried to reproduce your issue. Since you haven't shared all the code, I had to guess some parts. Also, I used flan-t5-base because of its size. The resulting code works for me:

```python
from peft import PrefixTuningConfig, TaskType, get_peft_model
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer

model_id = "google/flan-t5-base"
tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForSeq2SeqLM.from_pretrained(model_id)
peft_config = PrefixTuningConfig(
    peft_type="PREFIX_TUNING",
    inference_mode=False,
    task_type=TaskType.SEQ_2_SEQ_LM,
    num_virtual_tokens=20,
    token_dim=768,
    num_transformer_submodules=1,
    num_attention_heads=12,
    num_layers=12,
    encoder_hidden_size=768,
)
peft_model = get_peft_model(model, peft_config)
input_ids = tokenizer("Explain tea making", return_tensors="pt").input_ids
model.generate(input_ids=input_ids)  # works
tokenizer.decode(model.generate(input_ids=input_ids)[0])  # '<pad> Tea making is a process that involves brewing tea, brewing tea, and brewing'
```

Could you please check if this also works for you? Do you do anything different in your code that could be the cause of your code breaking but not this one? Please share as much as possible.

**Comment by BenjaminBossan** [comment]
Can you change `num_transformer_submodules=1` to `num_transformer_submodules=2` and try again?

**Comment by AswiniNLP** [comment]
Yes It is working for transformer sub module as 2 , can you please explain
the reason? Also can you please tell me the reason why should we use prompt
encoder in prefix tuning?

**Comment by BenjaminBossan** [comment]
> Yes It is working for transformer sub module as 2 , can you please explain the reason?

Since you have a seq2seq model, i.e. a model with an encoder block and a decoder block, you have to indicate 2 submodules. If you have a pure decoder model (a "causal LM" like Llama), there is only the decoder block.

> Also can you please tell me the reason why should we use prompt encoder in prefix tuning?

Not sure what you mean exactly. In PEFT, the usage of a prompt encoder is an implementation detail of prefix tuning.

**Comment by AswiniNLP** [comment]
Thank you for your reply.

**Comment by BenjaminBossan** [comment]
You're welcome. Feel free to re-open the issue if new questions come up.

**Comment by AswiniNLP** [comment]
Dear Benjamin,

 I created a PEFT adapter for prefix tuning on say (7 x number of trainable
parameters) where 7 is my virtual token length on adapter 1 and I saved the
model, now on top of adapter 1, I want to use another Prefix tuning PEFT
adapter, say adapter 2. I am getting an error on that case.

Could you please suggest how can I do this type of set, Now I want to
freeze the entire Peft model and train another set of virtual tokens on
adapter 2 on the top of the first adapter Peft model.

(prefix adapter2(prefix adapter1(base model))).... and so on.

**Comment by BenjaminBossan** [comment]
> Now I want to freeze the entire Peft model and train another set of virtual tokens on adapter 2 on the top of the first adapter Peft model.
(prefix adapter2(prefix adapter1(base model))).... and so on.

Sorry, I don't think that we currently support this.
