### ISSUE TITLE
AttributeError: ModulesToSaveWrapper has no attribute layers

### ISSUE THREAD

**Issue by pxy963** [huggingface/peft#1609]
### System Info

accelerate                0.28.0
peft                      0.10.0
torch == 2.2.1
transformer==4.39.2
flash-attn==2.5.6
python == 3.10

### Who can help?

 @BenjaminBossan

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

We use peft==0.10.0 to finetune the openbmb/MiniCPM-2B-sft-bf16. 
When run this code,  the error occurs.
`model = get_peft_model(model, peft_config)`

### Expected behavior

AttributeError: ModulesToSaveWrapper has no attribute layers

**Comment by BenjaminBossan** [comment]
Could you please provide more context? Ideally, that is all the code that leads up to the line that causes the error, as well as the full error message.

**Comment by pxy963** [comment]
Thank you. I have solved the problem.

**Comment by PulkitAgr113** [comment]
Hi, I am facing a similar issue with another model. How did you solve this error?

**Comment by BenjaminBossan** [comment]
@PulkitAgr113 The more information you can provide about your error, the more likely it is that someone can help you.
