### ISSUE TITLE
replace_lora_weights_loftq seems not present in transformers

### ISSUE THREAD

**Issue by RonanKMcGovern** [huggingface/peft#1617]
### System Info

transformers==4.38.1
bitsandbytes==0.42.0
peft==0.8.2

### Who can help?

@BenjaminBossan 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

```
from peft import replace_lora_weights_loftq

replace_lora_weights_loftq(model)
```

Error:
```
from peft import replace_lora_weights_loftq
ImportError: cannot import name 'replace_lora_weights_loftq' from 'peft'
```

### Expected behavior

Expecting this to replace the weights

**Comment by BenjaminBossan** [comment]
Hi Ronan, this function was added in PEFT v0.10.0. If you want to use it, please upgrade your PEFT install.

**Comment by RonanKMcGovern** [comment]
thanks, appreciate it
