### ISSUE TITLE
Documentation Clarification for loading PEFT models with AutoModelForCausalLM.from_pretrained

### ISSUE THREAD

**Issue by RonanKMcGovern** [huggingface/peft#1619]
### System Info

- `transformers` version: 4.40.0.dev0
- Platform: Linux-5.4.0-150-generic-x86_64-with-glibc2.35
- Python version: 3.10.12
- Huggingface_hub version: 0.20.3
- Safetensors version: 0.4.2
- Accelerate version: 0.29.0.dev0
- Accelerate config:    not found
- PyTorch version (GPU?): 2.2.2+cu121 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed

### Who can help?

@stevhliu

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

There are multiple ways to load peft models. For example:
```
model = AutoModelForCausalLM.from_pretrained(local_path_to_model_adapter)
```
or
```
peft_model = PeftModel.from_pretrained(base_model,local_path_to_model_adapter)
```

It would be helpful to describe both within peft documentation. More specifically:
1. Highlight that `merge_and_unload` does not work with AutoModelforCausalLM.
2. Clarify how AutoModelforCausalLM actually loads the adapter (I assume it keeps the adapter weights unmerged with the base model, hence slower inference?). [btw, it's useful that this can be used to load models because you can put in a path that can be either an adapter model OR a full model. However, this doesn't then work for merging, so one needs to know in advance if the path is to an adapter or full model before deciding how to load if one might need to use merge_and_unload).
3. Clarify that PeftModel requires the base and the adapter model to be specified (although, in principle it would seem there should be a way to allow loading by only specifying the adapter model).

### Expected behavior

See notes above

**Comment by younesbelkada** [comment]
Makes sense, I agree this is a bit confusing, will work on that in the next couple of days!

**Comment by RonanKMcGovern** [comment]
Unstale
