### ISSUE TITLE
Support EETQ QLoRA

### ISSUE THREAD

**Issue by thincal** [huggingface/peft#1643]
### Feature request

EETQ: https://github.com/NetEase-FuXi/EETQ

EETQ quantization is with great performance during inference supported by TGI and LoRAX already, so that if it could be supported by finetuning that would be great for QLoRA training and inference.

### Motivation

Achieve good inference performance for QLoRA-ed model.

### Your contribution

May be preparing PR, but depends on the complexity.

**Comment by younesbelkada** [comment]
Hi @thincal 
Yes that would be awesome, we are already in touch with the authors: https://github.com/NetEase-FuXi/EETQ/issues/13 I think the plan forward would be to first integrate it in transformers then we would go for a PEFT integration

**Comment by thincal** [comment]
> Hi @thincal 
> 
> Yes that would be awesome, we are already in touch with the authors: https://github.com/NetEase-FuXi/EETQ/issues/13 I think the plan forward would be to first integrate it in transformers then we would go for a PEFT integration

It is supported in transformers now, when to start with peft? Thanks.

**Comment by younesbelkada** [comment]
Hi @thincal thanks ! @SidaZh I saw you added `False` to `is_trainable` when integrating EETQ in transformers, is there any reason why LoRA might not be supported with EETQ? Essentially to support PEFT you need to support backprop in the EETQ 8-bit linear layers, e.g: https://github.com/casper-hansen/AutoAWQ/commit/29ee66d9e77f3e443d48a17b4838d00a76bc6f5e for autoawq / will run some tests and get back to you

**Comment by SidaZh** [comment]
> Hi @thincal thanks ! @SidaZh I saw you added `False` to `is_trainable` when integrating EETQ in transformers, is there any reason why LoRA might not be supported with EETQ? Essentially to support PEFT you need to support backprop in the EETQ 8-bit linear layers, e.g: [casper-hansen/AutoAWQ@29ee66d](https://github.com/casper-hansen/AutoAWQ/commit/29ee66d9e77f3e443d48a17b4838d00a76bc6f5e) for autoawq / will run some tests and get back to you

Great work! We will test this backward example. There is a problem that dequantization may not work correctly in EETQ.

**Comment by dtlzhuangz** [comment]
Hi @younesbelkada. We have implemented backprop for EETQ. We implemented the dequantization via multiplying an identity matrix with qweight using the dequantize-gemm interface. We had a simple test and it seems to work. Could you have a review on the code and we will merge it into main of EETQ if there is no problem.

**Comment by younesbelkada** [comment]
Thanks so much @dtlzhuangz ! I left one comment there, let me know what do you think

**Comment by dtlzhuangz** [comment]
> Thanks so much @dtlzhuangz ! I left one comment there, let me know what do you think

The modification LGTM. BTW, I forgot to ask you if the training results look good to you. So, is the result good?

**Comment by younesbelkada** [comment]
Hi @dtlzhuangz @SidaZh 
I tried your branch and had to come up with a fix: https://github.com/NetEase-FuXi/EETQ/pull/16 let me know what do you think!

**Comment by dtlzhuangz** [comment]
Hi @younesbelkada. The new fix LGTM and has been merged. However, I have another question. How does tensor parallelism work in peft? If EETQ is quantized under TP=1, it should not be used in TP>1, because layouts of quantized weights will be processed. If peft directly splits the TP-1 weights into parallellinears, it will output wrong hidden_states. So I want to know if such potential bug exists.

**Comment by younesbelkada** [comment]
hi @dtlzhuangz , thanks for bringing up this concern, I understand the issue ! 
I think people will less likely use PEFT + quantized models + TP as we never encountered such usecase in our issues. For using PEFT + TP, people use the PEFT TP layers: https://github.com/huggingface/peft/blob/main/src/peft/tuners/lora/tp_layer.py with megatron

**Comment by dtlzhuangz** [comment]
> hi @dtlzhuangz , thanks for bringing up this concern, I understand the issue ! I think people will less likely use PEFT + quantized models + TP as we never encountered such usecase in our issues. For using PEFT + TP, people use the PEFT TP layers: https://github.com/huggingface/peft/blob/main/src/peft/tuners/lora/tp_layer.py with megatron

So, if I understand correctly, it's not allowed to use both quantized models and TP in peft. Thank you for your answer!
