### ISSUE TITLE
[doc] issues with rendering docs in FF

### ISSUE THREAD

**Issue by stas00** [huggingface/peft#1644]
There are doc rendering issues in FF, at least for: https://huggingface.co/docs/peft/main/en/accelerate/deepspeed

Fine in chrome:
![snapshot_724](https://github.com/huggingface/peft/assets/10676103/50a05784-12a2-4a61-a065-fbff9a0e81ed)

Broken in FF 124.0.1 (Ubuntu)
![snapshot_725](https://github.com/huggingface/peft/assets/10676103/2792315f-00b1-4538-a143-331e368f5604)

**Comment by stas00** [comment]
Very odd. I have even rechecked with incognito mode, with all extensions turned off, it's not there.

And since chrome renders it fine on the same account, then this is not system-font related either.

**Comment by BenjaminBossan** [comment]
Very strange. I tried another Ubuntu machine with Firefox and it renders fine there as well. Incognito mode has no effect.

**Comment by stas00** [comment]
By trying incognito I meant to signal that it's not due to an impact of some FF extension, since incognito disables them all.

But if it's just me, and you can't reproduce it - we can close this

**Comment by BenjaminBossan** [comment]
> By trying incognito I meant to signal that it's not due to an impact of some FF extension, since incognito disables them all.

Got it.

> But if it's just me, and you can't reproduce it - we can close this

Let's leave this open to wait and see if anyone else can or cannot reproduce this issue.
