### ISSUE TITLE
`bitsandbytes` is imported eagerly in `peft/utils/loftq_utils.py`

### ISSUE THREAD

**Issue by function2-llx** [huggingface/peft#1665]
https://github.com/huggingface/peft/pull/1230 makes the import of `bitsandbytes` lazy, however, the fix seems to be imcomplete.
https://github.com/huggingface/peft/blob/5a4b9cade64bac8afdff5006ee9dd815c90b5469/src/peft/utils/loftq_utils.py#L34-L35
Perhaps there can be a test case ensuring that the CUDA context is not initialized after importing `peft`, e.g.:
```python
import torch
import peft
assert not torch.cuda.is_initialized()
```
@BenjaminBossan

**Comment by BenjaminBossan** [comment]
Thanks for pointing this out, we can surely work on this, as it's a valid concern. Let us know if you're interested in creating a PR to fix this.

**Comment by function2-llx** [comment]
Hello, I can make a PR, but perhaps one month layer. Is that okay?

**Comment by BenjaminBossan** [comment]
Thanks! I'll hopefully have time to fix this earlier, as it's a bit annoying and should only require a few extra lines for the fix and test. If I don't find the time by then, I'll be happy to accept your PR.

**Comment by function2-llx** [comment]
@BenjaminBossan Thank you so much for your PR and explanation! Your explanation makes sense to me. The side effect of importing seems to be a common issue, and I'll definitely pay attention to related issues and solutions, and share my ideas when available.
