### ISSUE TITLE
DoRA support for Embedding

### ISSUE THREAD

**Issue by ShayekhBinIslam** [huggingface/peft#1677]
### Feature request

Supporting DoRA with Embedding to allow seamless integration with the LoRA framework.

### Motivation

I need to finetune a model where additional tokens have to be trained. But getting the "Embedding does not support DoRA yet, please set it to False" error.

### Your contribution

No

**Comment by bezir** [comment]
We're eager to receive a PR from the community 🤗! I am also having this issue.

**Comment by ariG23498** [comment]
Hey @BenjaminBossan I would like to try my hand at this.

As I understand it, I would need to build the DoRA Embedding layer in [`dora.py`](https://github.com/huggingface/peft/blob/main/src/peft/tuners/lora/dora.py) and then link that implementation in [`lora/layer.py`](https://github.com/huggingface/peft/blob/main/src/peft/tuners/lora/layer.py).

**Comment by BenjaminBossan** [comment]
Thanks a lot for offering to take this @ariG23498. Yes, you got it exactly right on how to add the layer. In case you need more context on why DoRA is implemented as it is (which looks more complicated than needed), you can check #1806, but this background info should not be needed to work on this.
