### ISSUE TITLE
Errors with flan-t5 in conditional_generation-peft_prefix_tuning while training and inference

### ISSUE THREAD

**Issue by djaym7** [huggingface/peft#168]
transformers version - 0.47.0.dev0
peft version 0.2.0.dev0
python 1.13.1 cuda 11.6

When training if gradient checkpoint is True in HF trainer and use_cache is true in model, below error happens
File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1212, in _call_impl
result = forward_call(*input, **kwargs)
File "/usr/local/lib/python3.8/dist-packages/transformers/models/t5/modeling_t5.py", line 693, in forward
self_attention_outputs = self.layer[0](
File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1212, in _call_impl
result = forward_call(*input, **kwargs)
File "/usr/local/lib/python3.8/dist-packages/transformers/models/t5/modeling_t5.py", line 600, in forward
attention_output = self.SelfAttention(
File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1212, in _call_impl
result = forward_call(*input, **kwargs)
File "/usr/local/lib/python3.8/dist-packages/transformers/models/t5/modeling_t5.py", line 550, in forward
position_bias = position_bias + mask # (batch_size, n_heads, seq_length, key_length)
RuntimeError: The size of tensor a (128) must match the size of tensor b (148) at non-singleton dimension 3

ERRORS in inference:

Errors in inference now

File /usr/local/lib/python3.8/dist-packages/peft/peft_model.py:758, in PeftModelForSeq2SeqLM.generate(self, **kwargs)
755 kwargs["token_type_ids"] = None
757 if self.peft_config.peft_type == PeftType.PREFIX_TUNING:
--> 758 return self.base_model.generate(**kwargs)
759 else:
760 raise NotImplementedError

File /usr/local/lib/python3.8/dist-packages/transformers/models/t5/modeling_t5.py:506, in T5Attention.forward..project(hidden_states, proj_layer, key_value_states, past_key_value)
502 if past_key_value is not None:
503 if key_value_states is None:
504 # self-attn
505 # (batch_size, n_heads, key_length, dim_per_head)
--> 506 hidden_states = torch.cat([past_key_value, hidden_states], dim=2)
507 elif past_key_value.shape[2] != key_value_states.shape[1]:
508 # checking that the sequence_length of the past_key_value is the same as
509 # the provided key_value_states to support prefix tuning
510 # cross-attn
511 # (batch_size, n_heads, seq_length, dim_per_head)
512 hidden_states = shape(proj_layer(key_value_states))

RuntimeError: Sizes of tensors must match except in dimension 2. Expected size 16 but got size 32 for tensor number 1 in the list.

These errors are just in prefix tuning, LORA works well.

**Comment by djaym7** [comment]
https://github.com/huggingface/peft/issues/151

**Comment by PanQiWei** [comment]
For my experiencies, you can check for:
1. whether pass `attention_masks` or not, if not the error would be raised
2. initialized multiple peft models that share the same base model, and those peft models have different `num_virtual_tokens`
