### ISSUE TITLE
model merge_and_unload do not support layer_replication

### ISSUE THREAD

**Issue by CrazyBoyM** [huggingface/peft#1707]
### System Info

when you trained a model with layer_replication in LoRAConfig，you will find that can not be merge to the base model in a right way

### Information

- [x] The official example scripts
- [x] My own modified scripts

### Tasks

- [x] An officially supported task in the `examples` folder
- [x] My own task or dataset (give details below)

### Reproduction

just set layer_replication in LoraConfig, train a sample lora and merge it to the base model

### Expected behavior

generate a modeling_config.py script that can work properly with "layer_replication"

**Comment by BenjaminBossan** [comment]
This is not easily possible. The reason is that those replicated layers share the underlying base weights between multiple layers. Therefore, we cannot merge LoRA weights, as different LoRA weights would be merged into the base weights, resulting in incorrect outputs.

**Comment by CrazyBoyM** [comment]
what&nbsp;I&nbsp;mean&nbsp;is&nbsp;when&nbsp;I&nbsp;create&nbsp;a&nbsp;lora&nbsp;with&nbsp;layer_replication&nbsp;for&nbsp;expanding&nbsp;&nbsp;blocks&nbsp;from&nbsp;22&nbsp;to&nbsp;32，I&nbsp;merge&nbsp;and&nbsp;save&nbsp;it，but&nbsp;when&nbsp;I&nbsp;load&nbsp;the&nbsp;output&nbsp;model，I&nbsp;find&nbsp;there&nbsp;are&nbsp;only&nbsp;22&nbsp;blocks&nbsp;in&nbsp;the&nbsp;final&nbsp;model.


---Original---
From: &quot;Benjamin ***@***.***&gt;
Date: Mon, May 6, 2024 17:54 PM
To: ***@***.***&gt;;
Cc: &quot;Xinlu ***@***.******@***.***&gt;;
Subject: Re: [huggingface/peft] model merge_and_unload do not supportlayer_replication (Issue #1707)




 
This is not easily possible. The reason is that those replicated layers share the underlying base weights between multiple layers. Therefore, we cannot merge LoRA weights, as different LoRA weights would be merged into the base weights, resulting in incorrect outputs.
 
&mdash;

**Comment by CrazyBoyM** [comment]
sorry，what&nbsp;I&nbsp;mean&nbsp;is&nbsp;that&nbsp;I&nbsp;want&nbsp;to&nbsp;load&nbsp;the&nbsp;base&nbsp;model&nbsp;and&nbsp;the&nbsp;lora&nbsp;model&nbsp;then&nbsp;merge_and_unload，get&nbsp;a&nbsp;&nbsp;new&nbsp;1.5B&nbsp;model&nbsp;with&nbsp;32block，not&nbsp;a&nbsp;original&nbsp;1B&nbsp;model&nbsp;with&nbsp;22block.


---Original---
From: &quot;Benjamin ***@***.***&gt;
Date: Mon, May 6, 2024 18:27 PM
To: ***@***.***&gt;;
Cc: &quot;Xinlu ***@***.******@***.***&gt;;
Subject: Re: [huggingface/peft] model merge_and_unload do not supportlayer_replication (Issue #1707)




  
What I mean is when I create a lora with layer_replication for expanding blocks from 22 to 32, I merge and save it, but when I load the output model, I find there are only 22 blocks in the final model.
  
As mentioned, merging with layer replication isn't really possible.
 
Also, when you load the model, make sure that you first load the base model, then the LoRA adapter using PeftModel.from_pretrained(...). This should restore the replicated layers.
 
&mdash;

**Comment by BenjaminBossan** [comment]
> what I mean is that I want to load the base model and the lora model then merge_and_unload，get a  new 1.5B model with 32 block，not a original 1B model with 22 block.

This is not really an option right now with PEFT. I guess what you could try is to create clones of the weights that are currently being shared, edit the `adapter_config.json` to remove the `layer_replication` entry, then try to load the LoRA adapter and try if `merge_and_onload` works.
