### ISSUE TITLE
 model.eval()    RuntimeError

### ISSUE THREAD

**Issue by xk503775229** [huggingface/peft#171]
I also have the same problem, could some one help us ?

_Originally posted by @xk503775229 in https://github.com/huggingface/peft/issues/154#issuecomment-1465633335_
 model.eval()           
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [1536, 16, 1, 1], but got 3-dimensional input of size [1, 32, 768] instead

# here is code:
from peft import PeftModel, PeftConfig
import os
from transformers import AutoModelForCausalLM, AutoTokenizer
os.environ["CUDA_VISIBLE_DEVICES"]="2"
peft_model_id = 'outputs'
config = PeftConfig.from_pretrained(peft_model_id)
print(config.base_model_name_or_path)
model = AutoModelForCausalLM.from_pretrained(config.base_model_name_or_path)
model = PeftModel.from_pretrained(model, peft_model_id)
tokenizer = AutoTokenizer.from_pretrained(config.base_model_name_or_path)
model = model.to("cuda")
model.eval()
inputs = tokenizer("hello,", return_tensors="pt")

with torch.no_grad():
    outputs = model.generate(input_ids=inputs["input_ids"].to("cuda"), max_new_tokens=10)
    print(tokenizer.batch_decode(outputs.detach().cpu().numpy(), skip_special_tokens=True)[0])

# all  log

Generate config GenerationConfig {
  "bos_token_id": 50256,
  "eos_token_id": 50256,
  "transformers_version": "4.26.1",
  "use_cache": false
}

/mnt/dl-storage/test-cephfs-0/group/asr/envs/anaconda3/envs/peft/lib/python3.7/site-packages/transformers-4.26.1-py3.7.egg/transformers/generation/utils.py:1187: UserWarning: You have modified the pretrained model configuration to control generation. This is a deprecated strategy to control generation and will be removed soon, in a future version. Please use a generation configuration file (see https://huggingface.co/docs/transformers/main_classes/text_generation)
  "You have modified the pretrained model configuration to control generation. This is a"
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_9244/249180379.py in <module>
      2 
      3 with torch.no_grad():
----> 4     outputs = model.generate(input_ids=inputs["input_ids"].to("cuda"), max_new_tokens=10)
      5     print(tokenizer.batch_decode(outputs.detach().cpu().numpy(), skip_special_tokens=True)[0])

/mnt/dl-storage/test-cephfs-0/group/asr/envs/anaconda3/envs/peft/lib/python3.7/site-packages/peft-0.2.0.dev0-py3.7.egg/peft/peft_model.py in generate(self, **kwargs)
    576     def generate(self, **kwargs):
    577         if not isinstance(self.peft_config, PromptLearningConfig):
--> 578             return self.base_model.generate(**kwargs)
    579         else:
    580             if "input_ids" not in kwargs:

/mnt/dl-storage/test-cephfs-0/group/asr/envs/anaconda3/envs/peft/lib/python3.7/site-packages/peft-0.2.0.dev0-py3.7.egg/peft/peft_model.py in generate(self, **kwargs)
    576     def generate(self, **kwargs):
    577         if not isinstance(self.peft_config, PromptLearningConfig):
--> 578             return self.base_model.generate(**kwargs)
    579         else:
    580             if "input_ids" not in kwargs:

/mnt/dl-storage/test-cephfs-0/group/asr/envs/anaconda3/envs/peft/lib/python3.7/site-packages/torch/autograd/grad_mode.py in decorate_context(*args, **kwargs)
     25         def decorate_context(*args, **kwargs):
     26             with self.clone():
---> 27                 return func(*args, **kwargs)
     28         return cast(F, decorate_context)
     29 

/mnt/dl-storage/test-cephfs-0/group/asr/envs/anaconda3/envs/peft/lib/python3.7/site-packages/transformers-4.26.1-py3.7.egg/transformers/generation/utils.py in generate(self, inputs, generation_config, logits_processor, stopping_criteria, prefix_allowed_tokens_fn, synced_gpus, **kwargs)
   1398                 return_dict_in_generate=generation_config.return_dict_in_generate,
   1399                 synced_gpus=synced_gpus,
-> 1400                 **model_kwargs,
   1401             )
   1402 

/mnt/dl-storage/test-cephfs-0/group/asr/envs/anaconda3/envs/peft/lib/python3.7/site-packages/transformers-4.26.1-py3.7.egg/transformers/generation/utils.py in greedy_search(self, input_ids, logits_processor, stopping_criteria, max_length, pad_token_id, eos_token_id, output_attentions, output_hidden_states, output_scores, return_dict_in_generate, synced_gpus, **model_kwargs)
   2181                 return_dict=True,
   2182                 output_attentions=output_attentions,
-> 2183                 output_hidden_states=output_hidden_states,
   2184             )
   2185 

/mnt/dl-storage/test-cephfs-0/group/asr/envs/anaconda3/envs/peft/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1192         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1193                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1194             return forward_call(*input, **kwargs)
   1195         # Do not call functions when jit is used
   1196         full_backward_hooks, non_full_backward_hooks = [], []

/mnt/dl-storage/test-cephfs-0/group/asr/envs/anaconda3/envs/peft/lib/python3.7/site-packages/transformers-4.26.1-py3.7.egg/transformers/models/gpt2/modeling_gpt2.py in forward(self, input_ids, past_key_values, attention_mask, token_type_ids, position_ids, head_mask, inputs_embeds, encoder_hidden_states, encoder_attention_mask, labels, use_cache, output_attentions, output_hidden_states, return_dict)
   1054             output_attentions=output_attentions,
   1055             output_hidden_states=output_hidden_states,
-> 1056             return_dict=return_dict,
   1057         )
   1058         hidden_states = transformer_outputs[0]

/mnt/dl-storage/test-cephfs-0/group/asr/envs/anaconda3/envs/peft/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1192         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1193                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1194             return forward_call(*input, **kwargs)
   1195         # Do not call functions when jit is used
   1196         full_backward_hooks, non_full_backward_hooks = [], []

/mnt/dl-storage/test-cephfs-0/group/asr/envs/anaconda3/envs/peft/lib/python3.7/site-packages/transformers-4.26.1-py3.7.egg/transformers/models/gpt2/modeling_gpt2.py in forward(self, input_ids, past_key_values, attention_mask, token_type_ids, position_ids, head_mask, inputs_embeds, encoder_hidden_states, encoder_attention_mask, use_cache, output_attentions, output_hidden_states, return_dict)
    893                     encoder_attention_mask=encoder_attention_mask,
    894                     use_cache=use_cache,
--> 895                     output_attentions=output_attentions,
    896                 )
    897 

/mnt/dl-storage/test-cephfs-0/group/asr/envs/anaconda3/envs/peft/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1192         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1193                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1194             return forward_call(*input, **kwargs)
   1195         # Do not call functions when jit is used
   1196         full_backward_hooks, non_full_backward_hooks = [], []

/mnt/dl-storage/test-cephfs-0/group/asr/envs/anaconda3/envs/peft/lib/python3.7/site-packages/transformers-4.26.1-py3.7.egg/transformers/models/gpt2/modeling_gpt2.py in forward(self, hidden_states, layer_past, attention_mask, head_mask, encoder_hidden_states, encoder_attention_mask, use_cache, output_attentions)
    392             head_mask=head_mask,
    393             use_cache=use_cache,
--> 394             output_attentions=output_attentions,
    395         )
    396         attn_output = attn_outputs[0]  # output_attn: a, present, (attentions)

/mnt/dl-storage/test-cephfs-0/group/asr/envs/anaconda3/envs/peft/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1192         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1193                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1194             return forward_call(*input, **kwargs)
   1195         # Do not call functions when jit is used
   1196         full_backward_hooks, non_full_backward_hooks = [], []

/mnt/dl-storage/test-cephfs-0/group/asr/envs/anaconda3/envs/peft/lib/python3.7/site-packages/transformers-4.26.1-py3.7.egg/transformers/models/gpt2/modeling_gpt2.py in forward(self, hidden_states, layer_past, attention_mask, head_mask, encoder_hidden_states, encoder_attention_mask, use_cache, output_attentions)
    308             attention_mask = encoder_attention_mask
    309         else:
--> 310             query, key, value = self.c_attn(hidden_states).split(self.split_size, dim=2)
    311 
    312         query = self._split_heads(query, self.num_heads, self.head_dim)

/mnt/dl-storage/test-cephfs-0/group/asr/envs/anaconda3/envs/peft/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1192         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1193                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1194             return forward_call(*input, **kwargs)
   1195         # Do not call functions when jit is used
   1196         full_backward_hooks, non_full_backward_hooks = [], []

/mnt/dl-storage/test-cephfs-0/group/asr/envs/anaconda3/envs/peft/lib/python3.7/site-packages/peft-0.2.0.dev0-py3.7.egg/peft/tuners/lora.py in forward(self, x)
    446             return F.linear(x, transpose(self.weight, self.fan_in_fan_out), bias=self.bias)
    447         else:
--> 448             result = F.linear(x, transpose(self.weight, self.fan_in_fan_out), bias=self.bias)
    449             if self.r > 0:
    450                 after_A = self.lora_A(self.lora_dropout(x))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (31x768 and 2304x768)

**Comment by pacman100** [comment]
The above PR should resolve the issue, can you please confirm the same?
