### ISSUE TITLE
Unable to Install peft==0.7.0.dev0

### ISSUE THREAD

**Issue by AnonymXXXXX** [huggingface/peft#1718]
### System Info

```bash
ERROR: Could not find a version that satisfies the requirement peft==0.7.0.dev0 (from versions: 0.0.1, 0.0.2, 0.1.0, 0.2.0, 0.3.0, 0.4.0, 0.5.0, 0.6.0, 0.6.1, 0.6.2, 0.7.0, 0.7.1, 0.8.0, 0.8.1, 0.8.2, 0.9.0, 0.10.0)
ERROR: No matching distribution found for peft==0.7.0.dev0
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

I recently worked on a project where I used the peft library version 0.7.0.dev0. (I got this version number from the command `pip list`)

However, when I tried to install version 0.7.0.dev0 of the peft library in a new virtual environment using the command `pip install peft==0.7.0.dev0`, I encountered the error described above.

### Expected behavior

Could you please advise on how I can install peft==0.7.0.dev0? It seems that there are differences between versions 0.7.0, 0.7.1 and 0.7.0.dev0 that affect the results of my model.

**Comment by BenjaminBossan** [comment]
There is a misunderstanding here, `dev` versions are not released versions, they are the version we assign during development on GitHub. If you see a project that uses `0.7.0.dev0`, it means it installed PEFT directly from GitHub. If you want to install this exact version, you would have to figure out the commit hash that was used at the time that this install took place. This can be difficult if you don't have a copy of repo lying around somewhere.

If you can tell us what error exactly you encountered, we may be able to help with that.

**Comment by AnonymXXXXX** [comment]
Thanks for your reply!
