### ISSUE TITLE
Accessing Base model after Lora addition

### ISSUE THREAD

**Issue by agemagician** [huggingface/peft#176]
Hi,

Thanks for your great project.

I have one question, can we somehow access the base model after we add a Lora model adapter?

This is really useful in case we need to apply inference and get the results of the base model and at the same time be able to get the results from the lora adapter model.

**Comment by younesbelkada** [comment]
Hello @agemagician 
I think you can leverage the `disable_adapter` context manager, check an example here: https://github.com/lvwerra/trl/blob/03d98447300efc6bfd14cc271fdbfe175973e9ca/trl/trainer/ppo_trainer.py#L451
cc @pacman100

**Comment by agemagician** [comment]
This is really great and will work for sequential model accessing.
However, if this model is accessed from different threads, results might be overloaded between enabled and disabled.
I think having it as an input to the forward function is better, so it would be independent on each multiple call.

**Comment by agemagician** [comment]
For now, this is a good solution for me :)
Feel free to close it :)

**Comment by edwardelric1202** [comment]
@younesbelkada Hi, is it possible to change lora weights after loading? For instance, I have 2 lora weights, L1 & L2, after merge with L1, I may want to unload L1 and merge with L2 so that I don't need to reload the base model. Is that possible now for peft?

**Comment by younesbelkada** [comment]
hi @edwardelric1202 thanks for the ping! 
You mean merging 2 lora weights on the base model?
If that's the case you can load the first LoRA weight using `load_adapter` method, merge it and save the merged model as a standalone model, then load the L2 weights in that new model. What do you think?

**Comment by edwardelric1202** [comment]
@younesbelkada Thx for your reply. Sry for didn't make it clear, in fact I wonder if it is possible to unmerge L1 after merge with it, so that the model will return to the original one, then I can merge it with L2? It means I can change different Lora adapter without reloading the base model.

**Comment by younesbelkada** [comment]
I see better now thanks for clarifying, as for now i don't think this i supported unfortunately and I am not sure we will support it in the future as it sounds like a very edge usecase

**Comment by edwardelric1202** [comment]
Got it, thanks for your reply!
