### ISSUE TITLE
AdaLora: rank remains constant (to init_r value) across training

### ISSUE THREAD

**Issue by geoffvdr** [huggingface/peft#1801]
### System Info

transformers 4.38.0.dev0
peft 0.11.1
python 3.11.8

### Who can help?

@BenjaminBossan

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

I modified this script [https://github.com/huggingface/transformers/blob/main/examples/pytorch/speech-recognition/run_speech_recognition_ctc.py](url) for finetuning wav2vec2 model with PEFT. This works with Lora. 

My issue: with AdaLora, the rank does not change and stays at the value of `init_r`.
the adaloraconfig I use:
```
peft_config = AdaLoraConfig(
    init_r=12,
    target_r=8,
    tinit=500,
    tfinal=1000,
    total_step=14000,
    deltaT=50,
    lora_alpha=32,
    lora_dropout=0.1,
)
```

I added the following in my training loop (of `trainer.py`), as suggested in [https://github.com/huggingface/peft/issues/432](url) (I was hoping forgetting this line would be the cause of my problem but ranks are still the same):
```
model.base_model.update_and_allocate(total_batched_samples)
```

I tried with higher intial and target ranks (`init_r=128`, `target_r=32`  but the problem remains.

### Expected behavior

Different ranks per layer and transformer module.

**Comment by BenjaminBossan** [comment]
Could you please share the full script and the command to run it?

**Comment by geoffvdr** [comment]
Hello, I figured out that `update_and_allocate()` was not called properly.
Still have another question; I notice that `ranknum` does not correspond to the dimension of `lora_E`, do you know why?

**Comment by BenjaminBossan** [comment]
> Still have another question; I notice that `ranknum` does not correspond to the dimension of `lora_E`, do you know why?

No, not sure. Again, if you can share code, it would help.
