### ISSUE TITLE
Add `save_base_model=True` attribute to `save_pretrained` method

### ISSUE THREAD

**Issue by philschmid** [huggingface/peft#181]
Currently, when calling `model.save_pretrained`, only the adapter weights are stored and not the frozen `base_model`. Would it make sense to add a `kwargs` parameter, .e.g `save_base_model` to also save the `base_model` weights for easier offline usage, e.g. for deployment?

**Comment by philschmid** [comment]
@haofanwang before we have an integration you can add `model.base_model.save_pretrained()` at the end of your training.

**Comment by matthiasdroth** [comment]
I need exactly that feature but from this thread it's not entirely clear to me how to save the full, finetuned model (base_model + adapter_model). Here is my according [colab](https://colab.research.google.com/drive/1AkVgiBQxT7Y69T_ho0NyZQ9O4cp2lSI8?usp=sharing) (saves only the adapter weights).
