### ISSUE TITLE
Lora Training Tab

### ISSUE THREAD

**Issue by ClericerQ** [huggingface/peft#1814]
### System Info

Windows, Linux, RTX4080

### Who can help?

Hey guys,

I loaded a bunch of The Bloke's models, including AWQ, GPTQ, GGUF, as well as LLAMA2, GPT-3, and many more. However, whatever I do, I can't train any LoRA models. I get hundreds of errors when trying to load the models as Transformers in 4 or 8 bit, using AutoAWQ, AutoGPTQ, Transformers, llama.cpp and all other selections.

I get errors about q_proj and v_proj not existing. When I remove the checks for v_proj and q_proj, I encounter the following error: AttributeError: 'NoneType' object has no attribute 'pad_token_id'. When I use AutoAWQ, I get the error: ValueError: Target modules set() not found in the base model.

When I load a GPTQ model as Transformers in 4-bit, it loads but then gives the following error: NotImplementedError: Cannot copy out of meta tensor; no data! and hundreds of other errors. The training never works. (I successfully trained a model at the beginning of the year but can't figure out what I'm doing wrong now.)

Is there any good tutorial, or can anyone explain step-by-step how to train a LoRA model on any existing model? I have already read the oobabooga training documentation and checked the compatibility training table (GGUF is not supported, but all other models do not work either :-( ).

### Expected behavior

Working training.
Or errors messages which tell me which model is loadeable and which is not for training.

**Comment by BenjaminBossan** [comment]
Could you please paste the code you use that results in those errors. Also, could you paste the code used for your fixes? Finally, please paste the full error messages.

**Comment by younesbelkada** [comment]
in addition to what @BenjaminBossan just said, you could also have a look at our gpu examples tests: https://github.com/huggingface/peft/blob/main/tests/test_gpu_examples.py that are tested on daily basis. Here is the docker image we use: https://github.com/huggingface/peft/blob/main/docker/peft-gpu/Dockerfile if you want to repro trainings without any problem

**Comment by ClericerQ** [comment]
I don't use any script, i use the integrated training tab on raw text data.
![training tab](https://github.com/huggingface/peft/assets/106805307/d3c4e8bd-8772-4553-a82b-d7b86797bdd0)
