### ISSUE TITLE
Support XGLM model

### ISSUE THREAD

**Issue by tontan1998** [huggingface/peft#182]
Hello! I want PEFT support XGLM model because my language is very low resource for GPT but my language can work with [XGLM-4.5B (134 languages)](https://huggingface.co/facebook/xglm-4.5B).

Can you add support XGLM model for PEFT?

**Comment by sersh88** [comment]
+1

**Comment by totaltube** [comment]
looks like PEFT works with XGLM.

**Comment by tontan1998** [comment]
> looks like PEFT works with XGLM.

No, I try to use but target_modules is missing in LoraConfig.

**Comment by totaltube** [comment]
> No, I try to use but target_modules is missing in LoraConfig.
Ah, I tried it with prefix tuning. Looks like it works.

**Comment by tontan1998** [comment]
> > No, I try to use but target_modules is missing in LoraConfig.
> 
> Ah, I tried it with prefix tuning. Looks like it works.

I used [trl](https://github.com/lvwerra/trl) and I think it can use LoraConfig only. https://github.com/lvwerra/trl/blob/main/tests/test_peft_models.py
