### ISSUE TITLE
[BugReport] init_lora_weights with pissa is not compatible with deepspeed stage3

### ISSUE THREAD

**Issue by wsp317** [huggingface/peft#1826]
See below:
https://github.com/GraphPKU/PiSSA/issues/11#issue-2299653572

Still exists in the latest release

**Comment by BenjaminBossan** [comment]
If you could provide the code to reproduce the error (including how you call DeepSpeed), we can take a look at the issue, otherwise it's going to be difficult.

Also, it would be nice if you could translate your problem description for us, otherwise we have to rely on machine translation.
