### ISSUE TITLE
Some issues with attributes on custom models

### ISSUE THREAD

**Issue by BenjaminBossan** [huggingface/peft#1827]
### System Info

-

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

As reported by @kashif , it should be possible to use methods like LoRA on custom models that, for instance, wrap the actual model. Here is a reproducer:

```python
import torch
from transformers import AutoModelForCausalLM
from torch import nn
from peft import LoraConfig, get_peft_model

model_id = "facebook/opt-125m"

class MyModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.llm = AutoModelForCausalLM.from_pretrained(model_id)
        # solution 1: explicitly expose missing attributes
        # self.prepare_inputs_for_generation = self.llm.prepare_inputs_for_generation
        # self.config = self.llm.config

    # solution 2: pass through all missing attributes
    # def __getattr__(self, name: str):
    #     """Forward missing attributes to the wrapped module."""
    #     try:
    #         return super().__getattr__(name)  # defer to nn.Module's logic
    #     except AttributeError:
    #         return getattr(self.llm, name)

    def forward(self, *args, **kwargs):
        return self.llm(*args, **kwargs)

config = LoraConfig(task_type="CAUSAL_LM", target_modules=["q_proj", "v_proj"])
model = MyModel()
model = get_peft_model(model, config)
inputs = torch.tensor([[1, 2, 3, 4, 5]])
output = model(inputs)
```

The error is:

```
Traceback (most recent call last):
  File "/home/foo/anaconda3/envs/peft/lib/python3.10/pdb.py", line 1723, in main
    pdb._runscript(mainpyfile)
  File "/home/foo/anaconda3/envs/peft/lib/python3.10/pdb.py", line 1583, in _runscript
    self.run(statement)
  File "/home/foo/anaconda3/envs/peft/lib/python3.10/bdb.py", line 598, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/home/foo/work/forks/peft/foo.py", line 31, in <module>
    model = get_peft_model(model, config)
  File "/home/foo/work/forks/peft/src/peft/mapping.py", line 170, in get_peft_model
    return MODEL_TYPE_TO_PEFT_MODEL_MAPPING[peft_config.task_type](
  File "/home/foo/work/forks/peft/src/peft/peft_model.py", line 1442, in __init__
    self.base_model_prepare_inputs_for_generation = self.base_model.prepare_inputs_for_generation
  File "/home/foo/work/forks/peft/src/peft/tuners/lora/model.py", line 332, in __getattr__
    return getattr(self.model, name)
  File "/home/foo/anaconda3/envs/peft/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1709, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'MyModel' object has no attribute 'prepare_inputs_for_generation'
```

### Expected behavior

This code should work even without one of the two solutions sketched out above.

**Comment by BenjaminBossan** [comment]
I investigated this a bit and I think there is no good solution on the PEFT side here.

The issue is that if we want to accommodate a specific task type, like causal LM in this instance, we need to have specific attributes on the model for it to work. Therefore, we cannot support arbitrary custom models.

For users who come across this, there are 3 potential solutions:

1. Expose the specific needed arguments ("solution 1" in the snippet above). This has the least amount of side effects, but future PEFT versions may require additional parameters, so this solution is not quite as robust as the next.
2. Implement `__getattr__` ("solution 2" in the snippet above). This is more robust to future changes, but can make some errors messages more confusing.
3. Don't pass the `task_type`. When using `config = LoraConfig(target_modules=["q_proj", "v_proj"])`, the code above passes, but some task specific methods may not work correctly, like `model.generate`.

**Comment by KorigamiK** [comment]
> I investigated this a bit and I think there is no good solution on the PEFT side here.
> 
> The issue is that if we want to accommodate a specific task type, like causal LM in this instance, we need to have specific attributes on the model for it to work. Therefore, we cannot support arbitrary custom models.
> 
> For users who come across this, there are 3 potential solutions:
> 
>     1. Expose the specific needed arguments ("solution 1" in the snippet above). This has the least amount of side effects, but future PEFT versions may require additional parameters, so this solution is not quite as robust as the next.
> 
>     2. Implement `__getattr__` ("solution 2" in the snippet above). This is more robust to future changes, but can make some errors messages more confusing.
> 
>     3. Don't pass the `task_type`. When using `config = LoraConfig(target_modules=["q_proj", "v_proj"])`, the code above passes, but some task specific methods may not work correctly, like `model.generate`.

which snippets are you talking about?

**Comment by KorigamiK** [comment]
> In the code I posted above, I have solution 1 and 2 as comments. I'll reproduce it here for you:
> 
> ```python
> class MyModel(nn.Module):
>     def __init__(self):
>         super().__init__()
>         self.llm = AutoModelForCausalLM.from_pretrained(model_id)
>         # solution 1: explicitly expose missing attributes
>         # self.prepare_inputs_for_generation = self.llm.prepare_inputs_for_generation
>         # self.config = self.llm.config
> 
>     # solution 2: pass through all missing attributes
>     # def __getattr__(self, name: str):
>     #     """Forward missing attributes to the wrapped module."""
>     #     try:
>     #         return super().__getattr__(name)  # defer to nn.Module's logic
>     #     except AttributeError:
>     #         return getattr(self.llm, name)
> 
>     def forward(self, *args, **kwargs):
>         return self.llm(*args, **kwargs)
> ```
> 
> You could either uncomment the code beneath "solution 1" or the code beneath "solution 2". The pros and cons are described above. Of course, depending on what your code looks like, the solution may need a bit of tweaking.

Thanks for the great explanation. Just to  confirm, this will only behave as expected if the llm is the first thing that is passed in the forward call right? Are there any caveats to using this approach to fine-tune models?

**Comment by BenjaminBossan** [comment]
> this will only behave as expected if the llm is the first thing that is passed in the forward call right?

Sorry, could you explain further? The llm is not passed to the forward call in this example.

> Are there any caveats to using this approach to fine-tune models?

It depends on your use case. Just to give an example, when you wrap your model like this, checks such as `isinstance(model, transformers.PretrainedModel)` will return `False`b and checks of the signature of `forward` will not find certain arguments if you use `*args, **kwargs`. Furthermore, some methods like `save_pretrained` may not work or at least not fully.

These things can be issues if, for instance, you use some training framework (say, `Trainer` from transformers) which relies on these types of checks. If your training and inference is fully custom and is aware of what the model looks like, you should be able to avoid these issues though.

**Comment by KorigamiK** [comment]
@BenjaminBossan 
> Sorry, could you explain further? The llm is not passed to the forward call in this example.
I mean to say that self.llm is the first thing that the input is passed into in the forward call. Like the first layer of the model, only then it'll work as expected. Is that right?

**Comment by BenjaminBossan** [comment]
Well, for the original issue why I opened the PR, this is not relevant. If your use case requires the model to be called later, that should not be a problem.
