### ISSUE TITLE
Different results when merging LORA weights into the base model vs. when not

### ISSUE THREAD

**Issue by ankur6ue** [huggingface/peft#1836]
### System Info

peft, transformers, pytorch, python (3.8)

### Who can help?

@BenjaminBossan 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

I modified Nvidia's BERT fine-tuning example from [here](https://github.com/NVIDIA/DeepLearningExamples/blob/master/PyTorch/LanguageModeling/BERT/file_utils.py) by adding support for distributed data parallel during finetuning, using Pytorch DDP. 
My code is here:
https://github.com/ankur6ue/distributed_training/tree/master

I'm now trying to add LoRA, which I did as follows.

```python
# load base BERT model:
model = modeling.BertForQuestionAnswering(config)
# Create peft config
peft_config = LoraConfig(
  task_type=TaskType.QUESTION_ANS,
  inference_mode=False,
  r=16,
  lora_alpha=16,
  lora_dropout=0.1,
  bias="all", # will train the bias matrices.
  target_modules=["key", "query", "value"],
  modules_to_save=["qa_outputs"],
)
# Load model from checkpoint and apply LoRA
model.load_state_dict(checkpoint, strict=False)
lora_model = get_peft_model(model, peft_config)
lora_model.print_trainable_parameters()
lora_model.to(device)

# Run training loop. In the forward pass, I'm using the original model (which seems to have been modified in place), rather than the lora_model. If I call the below on the lora_model, I get an error. 
start_logits, end_logits = model(input_ids, segment_ids, input_mask)
```

The training seems to run ok, and I get nearly the same final value of loss as I do without using LoRA.
Now to save the LoRA weights, I can either save them separately like this:
```python
 lora_model.save_pretrained('results/bert_small_lora.bin')
```

or by merging into the base model:
```python
 merged_lora_model = lora_model.merge_and_unload()
output_model_file = os.path.join(args.output_dir, modeling.WEIGHTS_NAME)
torch.save({"model": merged_lora_model.state_dict()}, output_model_file)
```

Now if I run evaluation using the merged model, I get the expected F1 scores. However if I use the saved adaptor weights as follows:
```python
model = modeling.BertForQuestionAnswering(config)
peft_model = PeftModel.from_pretrained(model_, lora_model_location, is_trainable=False)
peft_model.cuda(0)
```
Run evaluation on the model
Then I get terrible results, indicating the LoRA weights are somehow not being applied.. 

What is the right way to do this?? There are so many questions about how to properly save and apply LoRA adapters, that it would be nice to have a proper example that explains how to do it comprehensively (without using the trainer, because that hides too much complexity and only seems to work on hugginsface models.. and when it doesn't work, it is next to impossible to debug..)

### Expected behavior

The evaluation output should be identical for when LoRA weights are merged with the main model vs. when they are not..

**Comment by ankur6ue** [comment]
Another question is that during fine-tuning using LoRA, the GPU memory used is only slight smaller than while doing full-tuning, even though < 1% of the number of parameters are being trained.. I expected the memory consumed to be a lot smaller. Any tips? 

lora_model = get_peft_model(model, peft_config)
lora_model.print_trainable_parameters()
trainable params: 989,186 || all params: 110,374,660 || trainable%: 0.8962

My training code is here: https://github.com/ankur6ue/distributed_training/blob/master/bert_finetuning_squad_peft.py

**Comment by BenjaminBossan** [comment]
> In the forward pass, I'm using the original model (which seems to have been modified in place), rather than the lora_model. If I call the below on the lora_model, I get an error. 

Could you please elaborate on that, what is the error message that you get?


> Now if I run evaluation using the merged model, I get the expected F1 scores. However if I use the saved adaptor weights as follows:
> 
> ```python
> model = modeling.BertForQuestionAnswering(config)
> peft_model = PeftModel.from_pretrained(model_, lora_model_location, is_trainable=False)
> ```

In the code further above, you additionally call `model.load_state_dict(checkpoint, strict=False)` before applying the LoRA adapter. Here, you're not doing that. Could you try what happens when you add this line before calling `PeftModel.from_pretrained`?

> Another question is that during fine-tuning using LoRA, the GPU memory used is only slight smaller than while doing full-tuning, even though < 1% of the number of parameters are being trained.. I expected the memory consumed to be a lot smaller. Any tips?

Hmm, it's hard to tell, as many factors could come into play here. The script you're linking is using FSDP, right? Did you find the same lack of memory savings when not using FSDP?

**Comment by RDXSun** [comment]
> > In the forward pass, I'm using the original model (which seems to have been modified in place), rather than the lora_model. If I call the below on the lora_model, I get an error.
> 
> Could you please elaborate on that, what is the error message that you get?
> 
> > Now if I run evaluation using the merged model, I get the expected F1 scores. However if I use the saved adaptor weights as follows:
> > ```python
> > model = modeling.BertForQuestionAnswering(config)
> > peft_model = PeftModel.from_pretrained(model_, lora_model_location, is_trainable=False)
> > ```
> 
> In the code further above, you additionally call `model.load_state_dict(checkpoint, strict=False)` before applying the LoRA adapter. Here, you're not doing that. Could you try what happens when you add this line before calling `PeftModel.from_pretrained`?
> 
> > Another question is that during fine-tuning using LoRA, the GPU memory used is only slight smaller than while doing full-tuning, even though < 1% of the number of parameters are being trained.. I expected the memory consumed to be a lot smaller. Any tips?
> 
> Hmm, it's hard to tell, as many factors could come into play here. The script you're linking is using FSDP, right? Did you find the same lack of memory savings when not using FSDP?

I also face this problem.
I use this code to save the lora adapter weights
`training_args = TrainingArguments(
    output_dir=args.output_dir,
    evaluation_strategy="epoch", 
    save_strategy="epoch",
    learning_rate=args.learning_rate,
    per_device_train_batch_size=args.per_device_train_batch_size,
    per_device_eval_batch_size=args.per_device_eval_batch_size,
    num_train_epochs=args.num_train_epochs,
    weight_decay=0.01,
    logging_steps=10,
    report_to=[],
    save_total_limit=2, 
    load_best_model_at_end=True, 
    metric_for_best_model="eval_accuracy",  
    gradient_accumulation_steps=args.gradient_accumulation_steps 
)

trainer = Trainer(
    model=model,
    args=training_args,
    tokenizer=tokenizer,
    train_dataset=processed_train_dataset,
    eval_dataset=processed_val_dataset,
    compute_metrics=compute_metrics,
)
trainer.train()
trainer.save_model(args.best_model_path)
tokenizer.save_pretrained(args.best_model_path)`
the eval_accuracy during training is ‘0.965’
but when I use this code to merge the stored lora weights and eval again, I get the '0.496' 
`model = AutoModelForSequenceClassification.from_pretrained(base_model_path)
model = PeftModel.from_pretrained(model, checkpoint_path, is_trainable=True)
model = model.merge_and_unload()  # Merge the LoRA layers and unload the PeftModel wrapper
model.eval()`
I tried so many times and the scores are all different.

**Comment by RDXSun** [comment]
> > In the forward pass, I'm using the original model (which seems to have been modified in place), rather than the lora_model. If I call the below on the lora_model, I get an error.
> 
> Could you please elaborate on that, what is the error message that you get?
> 
> > Now if I run evaluation using the merged model, I get the expected F1 scores. However if I use the saved adaptor weights as follows:
> > ```python
> > model = modeling.BertForQuestionAnswering(config)
> > peft_model = PeftModel.from_pretrained(model_, lora_model_location, is_trainable=False)
> > ```
> 
> In the code further above, you additionally call `model.load_state_dict(checkpoint, strict=False)` before applying the LoRA adapter. Here, you're not doing that. Could you try what happens when you add this line before calling `PeftModel.from_pretrained`?
> 
> > Another question is that during fine-tuning using LoRA, the GPU memory used is only slight smaller than while doing full-tuning, even though < 1% of the number of parameters are being trained.. I expected the memory consumed to be a lot smaller. Any tips?
> 
> Hmm, it's hard to tell, as many factors could come into play here. The script you're linking is using FSDP, right? Did you find the same lack of memory savings when not using FSDP?

I also face this problem.
I use this code to save the lora adapter weights
`training_args = TrainingArguments(
output_dir=args.output_dir,
evaluation_strategy="epoch",
save_strategy="epoch",
learning_rate=args.learning_rate,
per_device_train_batch_size=args.per_device_train_batch_size,
per_device_eval_batch_size=args.per_device_eval_batch_size,
num_train_epochs=args.num_train_epochs,
weight_decay=0.01,
logging_steps=10,
report_to=[],
save_total_limit=2,
load_best_model_at_end=True,
metric_for_best_model="eval_accuracy",
gradient_accumulation_steps=args.gradient_accumulation_steps
)

trainer = Trainer(
model=model,
args=training_args,
tokenizer=tokenizer,
train_dataset=processed_train_dataset,
eval_dataset=processed_val_dataset,
compute_metrics=compute_metrics,
)
trainer.train()
trainer.save_model(args.best_model_path)
tokenizer.save_pretrained(args.best_model_path)the eval_accuracy during training is 0.965 but when I use this code to merge the stored lora weights and eval again, I get the 0.496 model = AutoModelForSequenceClassification.from_pretrained(base_model_path)
model = PeftModel.from_pretrained(model, checkpoint_path, is_trainable=True)
model = model.merge_and_unload() # Merge the LoRA layers and unload the PeftModel wrapper
model.eval()`
I tried so many times and the scores are all different.

**Comment by BenjaminBossan** [comment]
@RDXSun I'm not sure if you are really facing the same issue or if it's something different.

Since you're only showing part of the code, this is hard for me to analyze. Ideally, you could show the whole training code, as well as how you evaluate the model.

As for potential solutions, first of all, could you please ensure that the path you're using to save the model, `args.best_model_path`, is really the same as `checkpoint_path`? Second, do you face the same issue if you remove the line `model = model.merge_and_unload()`?

**Comment by ankur6ue** [comment]
@BenjaminBossan , thanks for looking at this issue.
The errors I get when I run forward pass on the original model are:
(see line 318, here: https://github.com/ankur6ue/distributed_training/blob/master/bert_finetuning_squad_peft.py)

 File "/home/ankur/dev/apps/ML/learn/llms/fsdp/bert/bert_finetuning_squad_peft.py", line 317, in fsdp_main
    start_logits, end_logits = lora_model(input_ids, segment_ids, input_mask)
  File "/home/ankur/miniconda3/envs/dev/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ankur/miniconda3/envs/dev/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ankur/miniconda3/envs/dev/lib/python3.8/site-packages/peft/peft_model.py", line 2132, in forward
    return_dict = return_dict if return_dict is not None else self.config.use_return_dict
AttributeError: 'BertConfig' object has no attribute 'use_return_dict'

**Comment by ankur6ue** [comment]
Regarding memory savings, when I change the r in LoraConfig, the memory is lower by about 10%, so LoraConfig has some effect, just not as big as I expected it to be, given that far fewer gradients are being calculated and stored in the backward pass. I verified that requires_grad = False for all layers other than Lora layers and some bias layers. 
peft_config = LoraConfig(
            task_type=TaskType.QUESTION_ANS,
            inference_mode=False,
            r=8,
            lora_alpha=16,
            lora_dropout=0.1,
            bias="lora_only", # will train the bias matrices.
            target_modules=["key", "query", "value"],
            modules_to_save=["qa_outputs"],
        )

**Comment by ankur6ue** [comment]
@BenjaminBossan Re evaluation, here's what happens.

If I just load the original bert_base checkpoint and don't apply any LORA, as follows:

dllogger.log(step="PARAMETER", data={"loading_checkpoint": True})
checkpoint = torch.load(args.init_checkpoint, map_location='cpu')
checkpoint = checkpoint["model"] if "model" in checkpoint.keys() else checkpoint
model.load_state_dict(checkpoint, strict=False)

and run evaluation, I get very poor F1 score (0.5), as expected

If I apply the LORA adapter saved during training as follows:
lora_model_location = 'results/bert_small_lora.bin'
peft_model = PeftModel.from_pretrained(model, lora_model_location, is_trainable=False)

I get much better F1 score: 6.99

But then if I load the merged model (without applying LORA on top of that), I get better F1 score: 8.42
This is odd, because the result of applying LORA adapter on top of original model should be identical to the merged model?

**Comment by ankur6ue** [comment]
@BenjaminBossan : Also, I'm not using FSDP, just DDP. I took Nvidia's BERT training code and significantly simplified it, as described here:
https://github.com/ankur6ue/distributed_training/tree/master

**Comment by BenjaminBossan** [comment]
> AttributeError: 'BertConfig' object has no attribute 'use_return_dict'

It appears that you're using your own [custom bert model classes](https://github.com/ankur6ue/distributed_training/blob/master/modeling.py), which don't work with classes such as `PeftModelForQuestionAnswering`, which assumes that the model is a transformers model (or at least behaves like one). This is why you get the error. Maybe it would go away if you remove the `task_type=TaskType.QUESTION_ANS` from the config.

> Regarding memory savings, when I change the r in LoraConfig, the memory is lower by about 10%, so LoraConfig has some effect, just not as big as I expected it to be, given that far fewer gradients are being calculated and stored in the backward pass.

This depends on many factors. Bert is a relatively small model and it could be that you find that the memory savings in absolute terms are not that large. Depending on your data and other factors, memory required for activations, which are not reduced by PEFT, could take up a significant amount of space.

> But then if I load the merged model (without applying LORA on top of that), I get better F1 score: 8.42
> This is odd, because the result of applying LORA adapter on top of original model should be identical to the merged model?

Results should be very similar, albeit not exactly the same. There is always a bit of imprecision when merging weights. Maybe you could inspect the outputs of the model directly and check if they are very different are close. Also, F1 scores > 1 should not be possible, so there could also be an issue with how you calculate the scores.

**Comment by TomekPro** [comment]
Hi @ankur6ue, I face the same issue with Mistral model. I fine tune with QLora, then when I do model.merge_and_unload() I get different - worse results. Have you find a solution for that?

**Comment by BenjaminBossan** [comment]
> I fine tune with QLora, then when I do model.merge_and_unload() I get different - worse results

How different are the results? Please compare the logits, not the generated tokens, to get a clear picture. Note that merging will always result in a loss of precision, especially with quantized models.

**Comment by TomekPro** [comment]
Hi, I compared perplexity, it was like 8 vs 11. 
Anyway, finally when I dequantized base model as descibed [here](https://kaitchup.substack.com/p/lora-adapters-when-a-naive-merge) merged model was correct.
