### ISSUE TITLE
`Conv1D` not supported using AdaLora

### ISSUE THREAD

**Issue by bukun46** [huggingface/peft#1846]
### System Info

python = 3.10.11
torch = 2.2.2
peft = 0.11.1

### Who can help?

@pacman100 @younesbelkada @ste

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

`
from peft import get_peft_model, AdaLoraConfig, AdaLoraModel, TaskType

original_whisper = WhisperForConditionalGeneration.from_pretrained('openai/whisper-base')

target_modules = [
    "conv1", "conv2",
    "layers.0.self_attn.k_proj", "layers.0.self_attn.v_proj", "layers.0.self_attn.q_proj", "layers.0.self_attn.out_proj",
    "layers.0.fc1", "layers.0.fc2",
    "layers.1.self_attn.k_proj", "layers.1.self_attn.v_proj", "layers.1.self_attn.q_proj", "layers.1.self_attn.out_proj",
    "layers.1.fc1", "layers.1.fc2",
    "layers.2.self_attn.k_proj", "layers.2.self_attn.v_proj", "layers.2.self_attn.q_proj", "layers.2.self_attn.out_proj",
    "layers.2.fc1", "layers.2.fc2",
    "layers.3.self_attn.k_proj", "layers.3.self_attn.v_proj", "layers.3.self_attn.q_proj", "layers.3.self_attn.out_proj",
    "layers.3.fc1", "layers.3.fc2",
    "layers.4.self_attn.k_proj", "layers.4.self_attn.v_proj", "layers.4.self_attn.q_proj", "layers.4.self_attn.out_proj",
    "layers.4.fc1", "layers.4.fc2",
    "layers.5.self_attn.k_proj", "layers.5.self_attn.v_proj", "layers.5.self_attn.q_proj", "layers.5.self_attn.out_proj",
    "layers.5.fc1", "layers.5.fc2"
]

config = AdaLoraConfig(
peft_type="ADALORA", task_type="SEQ_2_SEQ_LM", r=8, lora_alpha=32, target_modules = target_modules, lora_dropout=0.01)

neuspeech_adalora_model = AdaLoraModel(original_whisper, config, "default")
`

### Expected behavior

Hi guys, I was trying to finetune Whisper-base model implemented from transfomers library using AdaLora, as the code provided. and got: 
ValueError: Target module Conv1d(80, 512, kernel_size=(3,), stride=(1,), padding=(1,)) is not supported. Currently, only `torch.nn.Linear` and `Conv1D` are supported.

Can you help me with this is issue? Thanks a in advance!

**Comment by bukun46** [comment]
Thank you Ben, that explained everything, I will try to substitute conv1d with Conv1D. Many thanks.

**Comment by BenjaminBossan** [comment]
Just know that the two classes are not identical. You cannot use Whisper and replace `Conv1d` with `Conv1D`.

**Comment by BenjaminBossan** [comment]
All right, good luck with that, feel free to re-open the issue if something new comes up.

**Comment by EskildAndersen** [comment]
Could you add support for torch.nn.modules.conv.Conv1d? I would be very interested
