### ISSUE TITLE
Add MoSLoRA

### ISSUE THREAD

**Issue by wutaiqiang** [huggingface/peft#1878]
### Feature request

Paper: Mixture-of-Subspaces in Low-Rank Adaptation

Link: https://arxiv.org/abs/2406.11909

Reference Code: https://github.com/wutaiqiang/MoSLoRA/tree/main/visual_instruction_tuning/peft 

### Motivation

This paper decomposes LoRA into subspaces via structural re-parameterization and proposes a simple yet effective MoSLoRA method, employing a learnable mixer to fuse more subspaces and more flexibly.

MoSLoRA is computationally efficient, easy to implement, and readily applicable to large language, multimodal, and diffusion models.

### Your contribution

I can help to test code or submit a PR

**Comment by BenjaminBossan** [comment]
Thank you for suggesting this new method. For my better understanding, could you point me to where in the linked repo MoSLoRA is implemented?

**Comment by wutaiqiang** [comment]
Thanks~ I am the author of this paper.

This method is simple, that is, to insert a mixer between lora_A and lora_B.

![image](https://github.com/huggingface/peft/assets/28387419/03e14821-069b-4a45-99f3-362d765fd85d)
 
I use the lora_use_mixer, a bool parameter, to control whether to use the mixer.

https://github.com/wutaiqiang/MoSLoRA/blob/ebc05cddace5ce0d10c610f289c2490a03309492/visual_instruction_tuning/peft/tuners/lora/layer.py#L113 and https://github.com/wutaiqiang/MoSLoRA/blob/ebc05cddace5ce0d10c610f289c2490a03309492/visual_instruction_tuning/peft/tuners/lora/layer.py#L166 show the initialization:

> if lora_use_mixer:
>       self.lora_AB[adapter_name] = nn.Linear(r, r, bias=False)

> if self.lora_use_mixer[adapter_name]:
                # nn.init.orthogonal_(self.lora_AB[adapter_name].weight)
                nn.init.kaiming_uniform_(self.lora_AB[adapter_name].weight, a=math.sqrt(5))

There should be two ways~(orthogonal_/kaiming_uniform_) to initialize the lora_AB (the mixer).

For the forward process, please refer to https://github.com/wutaiqiang/MoSLoRA/blob/ebc05cddace5ce0d10c610f289c2490a03309492/visual_instruction_tuning/peft/tuners/lora/layer.py#L346

**Comment by wutaiqiang** [comment]
Got it, thanks.
