### ISSUE TITLE
you cannot fine-tune quantized model with torch.compile

### ISSUE THREAD

**Issue by fengyunflya** [huggingface/peft#1886]
### Feature request

Does peft support torch.compile() for 4bit quantization wih QLora?

### Motivation

run faster

### Your contribution

Don't know

**Comment by BenjaminBossan** [comment]
No, quantization does not work with `torch.compile`. Find a list of what we know does and does not work with `torch.compile` in PEFT [here](https://huggingface.co/docs/peft/main/en/developer_guides/torch_compile).

The reason why some stuff doesn't work can be PEFT related, it can also be missing support on PyTorch side, or, as in this case, that a package we depend on (bitsandbytes) doesn't support `torch.compile`.

**Comment by fengyunflya** [comment]
> No, quantization does not work with `torch.compile`. Find a list of what we know does and does not work with `torch.compile` in PEFT [here](https://huggingface.co/docs/peft/main/en/developer_guides/torch_compile).
> 
> The reason why some stuff doesn't work can be PEFT related, it can also be missing support on PyTorch side, or, as in this case, that a package we depend on (bitsandbytes) doesn't support `torch.compile`.

@BenjaminBossan Thank you for your reply.
