### ISSUE TITLE
local pytest run puts torch.allclose() out of range in test_4bit_lora_mixed_adapter_batches_lora

### ISSUE THREAD

**Issue by kallewoof** [huggingface/peft#1889]
### System Info

peft main branch (7ffa43b16e4625322c9f157db12c9358f2f54cdf)
System is Ubuntu 22.04 with 2x3090 ti cards.

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

Run `pytest -v tests/test_common_gpu.py -k test_4bit_lora_mixed_adapter_batches_lora`

### Expected behavior

Test pass. Instead, the resulting tensors are a tiny bit too different. Adding
```py
        if not torch.allclose(out_adapter0[1::3], out_mixed[1::3], atol=atol, rtol=rtol):
            def compare_tensors(A, B, prefix=""):
                for i, (a, b) in enumerate(zip(A, B)):
                    if len(a.shape) > 1:
                        compare_tensors(a, b, f"{prefix}{i}.")
                    elif not torch.allclose(a, b, atol=atol, rtol=rtol):
                        for j, (c, d) in enumerate(zip(a, b)):
                            if not torch.allclose(c, d, atol=atol, rtol=rtol):
                                print(f"{prefix}{i}.{j}: {c} vs {d}")
            compare_tensors(out_adapter0[1::3], out_mixed[1::3])
```
above the second-to-last (failing) assert produces (1617 out of range cases)

<details>
  <summary>non-comprehensive list of not torch.allclose() scalars</summary>
  
```
0.7.49: 0.03169405832886696 vs 0.03168218210339546
0.7.69: -0.34240224957466125 vs -0.34242019057273865
0.7.78: -0.07967423647642136 vs -0.07969018816947937
0.7.79: 1.0376322269439697 vs 1.037610411643982
...
0.8.49: 0.03169405832886696 vs 0.03168218210339546
0.8.69: -0.34240224957466125 vs -0.34242019057273865
0.8.78: -0.07967423647642136 vs -0.07969018816947937
...
0.9.49: 0.03169405832886696 vs 0.03168218210339546
0.9.69: -0.34240224957466125 vs -0.34242019057273865
0.9.78: -0.07967423647642136 vs -0.07969018816947937
...
0.10.49: 0.03169405832886696 vs 0.03168218210339546
0.10.69: -0.34240224957466125 vs -0.34242019057273865
0.10.78: -0.07967423647642136 vs -0.07969018816947937
...
0.11.49: 0.03169405832886696 vs 0.03168218210339546
0.11.69: -0.34240224957466125 vs -0.34242019057273865
0.11.78: -0.07967423647642136 vs -0.07969018816947937
...
0.12.49: 0.03169405832886696 vs 0.03168218210339546
0.12.69: -0.34240224957466125 vs -0.34242019057273865
0.12.78: -0.07967423647642136 vs -0.07969018816947937
...
0.13.49: 0.03169405832886696 vs 0.03168218210339546
0.13.69: -0.34240224957466125 vs -0.34242019057273865
0.13.78: -0.07967423647642136 vs -0.07969018816947937
...
```
  
</details>

It appears like this test is not failing on github, so if there is something I can do on my side to make it pass please advise.

**Comment by BenjaminBossan** [comment]
Thanks for reporting this. The CI uses CPU, I tested locally with a 4090 and it passed too. It could be something device related, or depend on the PyTorch or CUDA version (I have 2.3.1 and 12.1, respectively). In general, if you don't work on this part of the code, don't worry too much if tests are failing though.

```python
>>> torch.allclose(out_adapter0[1::3], out_mixed[1::3], atol=1e-20, rtol=1e-20)
True
>>> (out_adapter0[1::3] - out_mixed[1::3]).abs().max()
tensor(0., device='cuda:0')
>>> torch.testing.assert_close(out_adapter1[1::3], out_mixed[1::3])
```

Could you tell me what the required tolerance is for you to make `assert torch.allclose(out_adapter0[1::3], out_mixed[1::3], atol=atol, rtol=rtol)` pass? Worst case, we can just increase the tolerance a bit.

**Comment by kallewoof** [comment]
Running with
```
max_dist = torch.max(torch.abs(out_adapter0[1::3] - out_mixed[1::3]))
print(f"max dist: {max_dist}")
```
I got:
```
max dist: 4.673004150390625e-05
```
(exact same output each time). Adjusting would require changing `1e-5` to `6e-5` or so.

As for testing on CPU, this results in the test being skipped on my end.
```
tests/test_common_gpu.py::PeftGPUCommonTests::test_4bit_lora_mixed_adapter_batches_lora
SKIPPED (test requires GPU)                                                                                                                    [100%]
```

**Comment by BenjaminBossan** [comment]
> Adjusting would require changing `1e-5` to `6e-5` or so.

If you could verify that this works for you, feel free to open a PR so that we can fix this. It's still a bit strange why this would happen at all, but oh well.

> As for testing on CPU, this results in the test being skipped on my end.

Ah yes, since this test uses bnb, it has to run on GPU.

**Comment by kallewoof** [comment]
I will open a PR but I'm not convinced yet that changing the tolerance is the right way here, since it works on the CI side. FWIW I have PyTorch 2.3.1 and CUDA 12.1 as well.

**Comment by kallewoof** [comment]
I'm not sure why, but bumping `atol` to `3e-5` was enough to make the tests pass on my end despite the max dist being `4.673e-5`.

**Comment by BenjaminBossan** [comment]
I've seen similar things in the past. Honestly, I'm not sure how exactly `torch.allclose` and `torch.testing.assert_close` really deal with the tolerances, it will always be a great mystery to me.
