### ISSUE TITLE
PeftModel.from_pretrained not load modules_to_save in config file

### ISSUE THREAD

**Issue by double-fire-0** [huggingface/peft#1894]
### System Info

none

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

model = PeftModel.from_pretrained(model, 'a/path/by/model/save_pretrained', is_trainable=True)
model.print_trainable_pramaters()

### Expected behavior

only the parameters in lora is set to train,
module in modules_to_save in lora config file save in the pretrain path is not set to train

**Comment by BenjaminBossan** [comment]
The intent of `modules_to_save` is to designate modules that should be fully fine-tuned, e.g. the classifier head. As such, they need to be trainable. If for some reason you don't want that, you can always manually set `requires_grad` to `False` for whatever module you would like to freeze.

**Comment by double-fire-0** [comment]
Yes. I want it to be trainable when loading with `PeftModel.from_pretrained` API.
For example, when I train a lora model with `modules_to_save` and save it using `model.save_pretrain`, then I need to reload the model using  `PeftModel.from_pretrained`  to resume training. But the module in  `modules_to_save` won't be set to be trainable

**Comment by BenjaminBossan** [comment]
For me, this works correctly:

```python
from transformers import AutoModelForCausalLM
from peft import LoraConfig, PeftModel, get_peft_model

model_id = "facebook/opt-125m"
model = AutoModelForCausalLM.from_pretrained(model_id)
config = LoraConfig(modules_to_save=["lm_head"], target_modules=["q_proj"])
model = get_peft_model(model, config)
model.save_pretrained("/tmp/peft/1894")

del model
model = AutoModelForCausalLM.from_pretrained(model_id)
model = PeftModel.from_pretrained(model, "/tmp/peft/1894", is_trainable=True)
assert model.base_model.model.lm_head.modules_to_save["default"].weight.requires_grad
```

I add `lm_head` to `modules_to_save` and after loading the model, it is trainable. Could you share your code where it does not work?

**Comment by double-fire-0** [comment]
oh! sorry
It's my fault, I forget to use `.modules_to_save` and use the original model
Thanks

**Comment by dengchengxifrank** [comment]
Hi @BenjaminBossan ，I want to know the specific usage of *modules_to_save* and *target_modules*? Because in my code, target_modules will automatically save all lora parameters, but I also want, for example, ‘lm_head’ to be updated during training. Does target_modules need to be added to ‘lm_head’? Finally, if I want to save all trainable parameters, how should I set them?Thanks！

**Comment by BenjaminBossan** [comment]
> I want to know the specific usage of _modules_to_save_ and _target_modules_? Because in my code, target_modules will automatically save all lora parameters, but I also want, for example, ‘lm_head’ to be updated during training.

Adding a layer to `modules_to_save` will fully fine-tune it and also save it when you call `save_pretrained`. Therefore, if you want to fully fine-tune `lm_head`, the correct way is to add it to `modules_to_save`. Only add it to `target_modules` if you want to apply parameter-efficient fine-tuning to it (e.g. LoRA). Don't add it to both `target_modules` and `modules_to_save`.

> if I want to save all trainable parameters, how should I set them?Thanks！

Calling `model.save_pretrained` should do that. If it doesn't work, please let me know.

**Comment by dengchengxifrank** [comment]
@BenjaminBossan  Thanks for your answer. It works. But I want to check the following:
1. If I use e.g. LoRA to finetune the model, I only need to add it (eg 'q_proj') to target_modules instead of modules_to_save, and it will be saved. I only need to add the modules that are not trained using PEFT to the modules_to_save right?

**Comment by BenjaminBossan** [comment]
> 1. If I use e.g. LoRA to finetune the model, I only need to add it (eg 'q_proj') to target_modules instead of modules_to_save, and it will be saved. I only need to add the modules that are not trained using PEFT to the modules_to_save right?

Yes, that is exactly right. In fact, you should never add a layer to `modules_to_save` if it's already in `target_modules`.
