### ISSUE TITLE
fine tuning / prompt tuning dialogue dataset with PEFT

### ISSUE THREAD

**Issue by raihan0824** [huggingface/peft#191]
Hi,

Any recommendations on how to effectively tune the dialogue dataset with PEFT? Would prompt tuning alone suffice or are there other methods you would suggest exploring?

Thanks

**Comment by dukesun99** [comment]
This [repo](https://github.com/tloen/alpaca-lora) fine-tuned a lora of llama with alpaca data. Maybe you may check their performance and configs.
