### ISSUE TITLE
Independently process LoRa adapters and base model

### ISSUE THREAD

**Issue by mtran14** [huggingface/peft#1911]
Hello, 

As I understand, during inference, the current library merges the base model weights with the learned LoRa adapters to avoid increasing in latency, as in h=(W+BA)x. However, I'm wondering if there's a way to process the base model and the learned adapters independently, as in h = Wx+BAx. The Wx computation is easy to implement (just load the original base model and perform inference) but I'm stuck on how to perform the BAx computation. 

For my particular use case, I would like to benchmark the runtime of the BAx computations relative to Wx on the Whisper model.

Thank you for your help!

**Comment by BenjaminBossan** [comment]
Thanks for the question. If you just load the base model and then the LoRA adapter, it is _not merged_ into the base weight. Merging has to be done explicitly by the user. As such, the computation is separate as you described. For instance, for `lora.Linear`, this happens in this line:

https://github.com/huggingface/peft/blob/58afb34ea03ae1166fc331adee0b4646e46db6dc/src/peft/tuners/lora/layer.py#L556

So you should already be able to benchmark this.

**Comment by mtran14** [comment]
Thank you for the explanation!
