### ISSUE TITLE
continue training model in transformers (after LoRA training)

### ISSUE THREAD

**Issue by BigDataMLexplorer** [huggingface/peft#1913]
### System Info

huggingface. transformers, peft, accelerate

### Who can help?

 @BenjaminBossan
@younesbelkada 
@sgugger 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Expected behavior
Hi, could someone please help me?

I have trained an LLM model of Llama3 using the AutoModelForSequenceClassification class. Before training I used LoraConfig and get_peft_model. Now I have saved the checkpoint and want to continue my training. I loaded the model from the checkpoint as follows:

`model = PeftModel.from_pretrained(base_model, path_to_checkpoint, is_trainable=True)
`
I then set the same Training arguments and Trainer and did

`trainer.train(resume_from_checkpoint="path_to_checkpoint")`

After this code I get error:

 `object of type method has no len()
`

**My packages: 
transformers==4.41.2
Peft==0.4.0**

Do you think it could be because I'm using an older version of the Peft package? I can't install a newer version at the moment due to a system error in the company.
Thank you.

.

**Comment by BenjaminBossan** [comment]
Thanks for reporting the error. Please don't ping Sylvain or Younes, who are not at Hugging Face anymore.

Regarding the error, I tried to reproduce it. When I use peft==0.4.0 and transformers==4.41.2, I get an import error

> ImportError: cannot import name 'PeftMixedModel' from 'peft' (/home/vinh/work/forks/peft/src/peft/__init__.py)

I'm not sure how this can work for you but the PEFT version is far too old for the given transformers version.

Switching back to the latest versions of PEFT and transformers, I could successfully resume training from a checkpoint. Here is the script:

```python
import torch
from datasets import load_dataset
from peft import LoraConfig, get_peft_model, PeftModel, TaskType
from transformers import AutoModelForCausalLM, AutoTokenizer, Trainer, TrainingArguments, DataCollatorForLanguageModeling


tmp_dir = "/tmp/peft/1913"
model_id = "facebook/opt-125m"
model = AutoModelForCausalLM.from_pretrained(model_id, device_map=0)
tokenizer = AutoTokenizer.from_pretrained(model_id)

config = LoraConfig(
    r=16,
    lora_alpha=32,
    target_modules=["q_proj", "v_proj"],
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
)

model = get_peft_model(model, config)

data = load_dataset("ybelkada/english_quotes_copy")
data = data.map(lambda samples: tokenizer(samples["quote"]), batched=True)

def get_trainer(model):
    trainer = Trainer(
        model=model,
        train_dataset=data["train"],
        args=TrainingArguments(
            per_device_train_batch_size=4,
            gradient_accumulation_steps=4,
            warmup_steps=2,
            max_steps=3,
            learning_rate=2e-4,
            fp16=True,
            logging_steps=1,
            output_dir=tmp_dir,
        ),
        data_collator=DataCollatorForLanguageModeling(tokenizer, mlm=False),
    )
    return trainer

trainer = get_trainer(model)
trainer.train()
del trainer, model

model = AutoModelForCausalLM.from_pretrained(model_id, device_map=0)
checkpoint_path = tmp_dir + "/checkpoint-3"  # adjust
model = PeftModel.from_pretrained(model, checkpoint_path, is_trainable=True)
trainer = get_trainer(model)
print("resuming training from checkpoint")
trainer.train(resume_from_checkpoint=checkpoint_path)
```

Maybe you could try if it works for. If you still get the same error as reported above, there is probably no solution other than trying to upgrade the versions. You could paste the full error message and perhaps I can spot something, but it's unlikely.

**Comment by BigDataMLexplorer** [comment]
I'm sorry, I didn't know Sylvain or Younes were no longer Huggingface.
Thanks for the help, I finally got to a newer version of the peft package and the code works for me.
