### ISSUE TITLE
problem with pip install peft

### ISSUE THREAD

**Issue by jinge170** [huggingface/peft#1914]
after pip, i cannot import Loraconfig

Traceback (most recent call last):
  File "/home/libj/LBJ/HMEG-main/LLama.py", line 12, in <module>
    from peft import Loraconfig
ImportError: cannot import name 'Loraconfig' from 'peft' (/home/libj/.conda/envs/HMEG/lib/python3.8/site-packages/peft/__init__.py)

**Comment by BenjaminBossan** [comment]
Something must have gone wrong in your Python environment. Could you try to uninstall and reinstall PEFT? If that doesn't help, could you please create a new virtual environment and install PEFT into that env to see if it fixes the issue?

**Comment by jinge170** [comment]
> commented
i havetried both methods and the problem persists

**Comment by jinge170** [comment]
> Something must have gone wrong in your Python environment. Could you try to uninstall and reinstall PEFT? If that doesn't help, could you please create a new virtual environment and install PEFT into that env to see if it fixes the issue?

i havetried both methods and the problem persists

**Comment by jinge170** [comment]
> Something must have gone wrong in your Python environment. Could you try to uninstall and reinstall PEFT? If that doesn't help, could you please create a new virtual environment and install PEFT into that env to see if it fixes the issue?

I found my error，Thanks!!

**Comment by BenjaminBossan** [comment]
Great. Feel free to share it if others have the same problem and stumble upon this issue.
