### ISSUE TITLE
Option to save base model config alongside adapter config

### ISSUE THREAD

**Issue by JohnGiorgi** [huggingface/peft#1916]
### Feature request

`PeftModel.save_pretrained()` only saves the adapter/PEFT models config to disk:

https://github.com/huggingface/peft/blob/e72a96f7cfdb330236c1b6dfe49be398d83f089e/src/peft/peft_model.py#L193-L256

For better reproducibility, I think it should (optionally) also save the base model's config (i.e. `PeftModel.model`)

### Motivation

When training adapters, we sometimes also make changes to a base models configuration. A real example:

- Load a base model
- Modify its config to support e.g. RoPE scaling
- Train an adapter off the base model

For this to be reproducible or loadable in a subsequent process, we would need to:

- Load a base model with the modified config
- Load the trained adapters

However, `PeftModel.save_pretrained` only saves the adapter config. You could argue that its up to the user to save the base model config, but to give just one example where this is tricky: imagine you trained the model using the HuggingFace `Trainer` and were relying on its integration with Weights and Biases to log the model as an artifact. If you used `peft`, the base models config will _not_ be included in this artifact*, because the wandb integration that trainer uses just calls `PeftModel.save_pretrained` under the hood.

My proposal is to offer an option to save the base models config alongside the adapter config. It should be as easy as adding `self.model.config.save_pretrained()` somewhere in `PeftModel.save_pretrained`. It could be made optional, perhaps by adding a flag to `PeftConfig`. I think this would be an easy win for improved reproducibility.

> *Technically it would be included in the artifacts metadata, but this is combined with a bunch of other configurations and its difficult to isolate just the base model's config.

### Your contribution

Assuming this isn't already possible or there is some good reason not to do it, I would be more than happy to open a PR with the proposed change!

**Comment by BenjaminBossan** [comment]
Thanks for suggesting this feature. I agree that adding this would only require a small addition to the code. As such, I'm not strictly opposed to adding it. But I think it would be a bit strange for the `PeftConfig` to contain information about this, so let's also think of other options.

I'm not a wandb user, so I'm not sure if it's possible. But from what I understand, you want to do a one time change to the model config at the very start of the training. Would it be possible to manually call wandb afterwards and store the config as an artifact? It's probably not necessary to store the config each time that a new checkpoint is being made, right?

If we had to change the behavior for each checkpoint though, could we write a small callback that we pass to the `Trainer` that would take the job of storing the model config?

**Comment by JohnGiorgi** [comment]
> Would it be possible to manually call wandb afterwards and store the config as an artifact? 

I think it's possible but quite hacky. You would have to access the `WandbCallback` object of the HF `Trainer`, and from there get to `WandbCallback._wandb.run`. The only way I was able to do that was like this:

```python
trainer.callback_handler.callbacks[trainer.callback_handler.callback_list.split("\n").index("WandbCallback")]._wandb.run
```

Seems... less than desirable. Besides, my goal wasn't to create _another_ artifact with the base model config, but have the base model config _included_ as a file alongside the artifact that the `WandbCallback` is already creating, which includes the adapter config and tokenizer config. See example below:

<img width="2112" alt="image" src="https://github.com/huggingface/peft/assets/8917831/ca3e9a69-b242-45a0-b307-65bd87d4060f">

>  It's probably not necessary to store the config each time that a new checkpoint is being made, right?

I don't think there is a strong argument _not_ to do this. `peft` already saves to disk the `adapter_config.json` for each checkpoint, plus the final model. The base model config (`config.json`) would only add another ~4KB per checkpoint. What ultimately gets uploaded in the W&B artifact is determined by the `WANDB_LOG_MODEL` env var (see the [wandb integration in HF transformers](https://github.com/huggingface/transformers/blob/ab0f050b42d903f34d6eb97f3f8c0c07f0517ad2/src/transformers/integrations/integration_utils.py#L699-L704)).

My proposal would be to add an argument to `PeftConfig`, e.g. `save_base_model_config: bool = False`. By default it would keep behavior unchanged. If `True`, it would call `self.model.config.save_pretrained()` somewhere in `PeftModel.save_pretrained`. Then the `WandbCallback` of the HF Trainer should automatically include it in the resulting artifact. As is already the case, a user can use `WANDB_LOG_MODEL` to determine how many artifacts are created (one per checkpoint, one at the end of training, or none at all), the difference being that, if `save_base_model_config=True`, they will include the base model `config.json`.

What do you think?

**Comment by BenjaminBossan** [comment]
Thanks for further clarifying your goal and your suggestion. As I said earlier, I agree that this could be added rather easily, but my concern still stands that this mixes concerns that are unrelated.

Another suggestion that comes to mind: Would it be possible to subclass `WandbCallback` to do something like this:

```python
class MyWandbCallback(WandbCallback):
    def on_save(self, args, state, control, **kwargs):
        super().on_save(args, state, control, **kwargs)
        if self._log_model == "checkpoint" and self._initialized and state.is_world_process_zero:
            # code to add model.config to wandb artifacts
```

I have no experience with `Trainer` callbacks, so I don't know how exactly one would add the `model.config` to the wandb artifacts. But in the callback code, there is a `combined_dict` which should contain both PEFT and model config and is added to `self._wandb.config`, so that should be the place to look.

https://github.com/huggingface/transformers/blob/6c1d0b069de22d7ed8aa83f733c25045eea0585d/src/transformers/integrations/integration_utils.py#L753-L781

**Comment by JohnGiorgi** [comment]
I don't think this would mix concerns. (1) `transformers` is a requirement of `peft` (2) it looks like the base models `generation_config.json` is already uploaded to the W&B artifact created when training with `peft` (3) the base models config is in the `metadata` already 🤷. This would simply be a matter of making it available as a file and making the W&B artifact's files list look a little more like something you might see on the HF hub.

Anyways, I need this functionality so I went with the `WandbCallback` strategy. It is a little ugly and requires monkey patching `wandb.Artifact`. It also needs to subclass both `WandbCallback.on_save` and `WandbCallback.on_train_end` for full effect. Here is the code in case it benefits any future readers:

```python
import contextlib
import tempfile
from functools import wraps
from pathlib import Path
from typing import Any

from transformers import PreTrainedModel
from transformers.integrations import WandbCallback

from wandb import Artifact


class CustomWandbCallback(WandbCallback):
    def __init__(self, model: PreTrainedModel, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self.model = model

    def _add_configs_artifact(self, artifact: Artifact) -> Artifact:
        with tempfile.TemporaryDirectory() as temp_dir:
            # Save base model config to artifact
            self.model.config.save_pretrained(temp_dir)
            artifact.add_file(Path(temp_dir) / "config.json")
        return artifact

    @contextlib.contextmanager
    def _patch_log_artifact(self, obj: Any, attr: str):
        original_log_artifact = getattr(obj, attr)

        @wraps(original_log_artifact)
        def wrapped_log_artifact(artifact, *args, **kwargs):
            modified_artifact = self._add_configs_artifact(artifact)
            return original_log_artifact(modified_artifact, *args, **kwargs)

        setattr(obj, attr, wrapped_log_artifact)

        try:
            yield
        finally:
            setattr(obj, attr, original_log_artifact)

    def on_train_end(self, *args, **kwargs) -> None:
        with self._patch_log_artifact(self._wandb.run, "log_artifact"):
            super().on_train_end(*args, **kwargs)

    def on_save(self, *args, **kwargs) -> None:
        with self._patch_log_artifact(self._wandb, "log_artifact"):
            super().on_save(*args, **kwargs)
```

Thanks @BenjaminBossan! Closing this for now

**Comment by BenjaminBossan** [comment]
Thanks a lot for sharing the code. It looks quite nice although I agree that the patch is not ideal. Perhaps this is something that could be added to the transformers repo to the original `WandbCallback`.

> I don't think this would mix unrelated concerns.

What I meant is that a PEFT config should only be concerned with how the PEFT adapter is configured. It would be quite surprising if it would control if the base model config is saved or not, which I really want to avoid.
