### ISSUE TITLE
load adapter always infer torch_device

### ISSUE THREAD

**Issue by aiqwe** [huggingface/peft#1918]
### System Info

peft

### Who can help?

@BenjaminBossan @sayakpaul 

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [x] My own task or dataset (give details below)

### Reproduction

https://github.com/huggingface/peft/blob/bc6a99906c09b8ecc6b10b766ef1a3382d8e9630/src/peft/peft_model.py#L960

When I load PeftModel through Mac book, It always use 'mps' device.

I think peft model forcibly [infer device](https://github.com/huggingface/peft/blob/58afb34ea03ae1166fc331adee0b4646e46db6dc/src/peft/utils/other.py#L75) when it works with `load_adapter` method.
So peft always infer my "mps" device not "cpu" even if i pass `device_map="cpu"` parameter.

below is my error code.
(`aiqwe/gemma-2b-it-example-v1` is my own fine-tuned model)

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[14], line 1
----> 1 finetuned_model = AutoPeftModelForCausalLM.from_pretrained(
      2     "aiqwe/gemma-2b-it-example-v1",
      3     torch_dtype=torch.float16,
      4     device_map="cpu"
      5 )

File ~/.base/lib/python3.11/site-packages/peft/auto.py:130, in _BaseAutoPeftModel.from_pretrained(cls, pretrained_model_name_or_path, adapter_name, is_trainable, config, revision, **kwargs)
    125     tokenizer = AutoTokenizer.from_pretrained(
    126         pretrained_model_name_or_path, trust_remote_code=kwargs.get("trust_remote_code", False)
    127     )
    128     base_model.resize_token_embeddings(len(tokenizer))
--> 130 return cls._target_peft_class.from_pretrained(
    131     base_model,
    132     pretrained_model_name_or_path,
    133     adapter_name=adapter_name,
    134     is_trainable=is_trainable,
    135     config=config,
    136     **kwargs,
    137 )

File ~/.base/lib/python3.11/site-packages/peft/peft_model.py:517, in PeftModel.from_pretrained(cls, model, model_id, adapter_name, is_trainable, config, autocast_adapter_dtype, ephemeral_gpu_offload, **kwargs)
    512 else:
    513     model = MODEL_TYPE_TO_PEFT_MODEL_MAPPING[config.task_type](
    514         model, config, adapter_name, autocast_adapter_dtype=autocast_adapter_dtype
    515     )
--> 517 model.load_adapter(
    518     model_id, adapter_name, is_trainable=is_trainable, autocast_adapter_dtype=autocast_adapter_dtype, **kwargs
    519 )
    521 return model

File ~/.base/lib/python3.11/site-packages/peft/peft_model.py:1085, in PeftModel.load_adapter(self, model_id, adapter_name, is_trainable, torch_device, autocast_adapter_dtype, ephemeral_gpu_offload, **kwargs)
   1082         peft_config.inference_mode = not is_trainable
   1083     self.add_adapter(adapter_name, peft_config)
-> 1085 adapters_weights = load_peft_weights(model_id, device=torch_device, **hf_hub_download_kwargs)
   1087 # load the weights into the model
   1088 ignore_mismatched_sizes = kwargs.get("ignore_mismatched_sizes", False)

File ~/.base/lib/python3.11/site-packages/peft/utils/save_and_load.py:479, in load_peft_weights(model_id, device, **hf_hub_download_kwargs)
    477         adapters_weights = safe_load_file(filename, device="cpu")
    478     else:
--> 479         adapters_weights = safe_load_file(filename, device=device)
    480 else:
    481     adapters_weights = torch.load(filename, map_location=torch.device(device))

File ~/.base/lib/python3.11/site-packages/safetensors/torch.py:310, in load_file(filename, device)
    308 with safe_open(filename, framework="pt", device=device) as f:
    309     for k in f.keys():
--> 310         result[k] = f.get_tensor(k)
    311 return result

TypeError: BFloat16 is not supported on MPS
```

### Expected behavior

As i know, when we use `AutoPeftModelForCausalLM.from_pretrained`, code flow would be below:  

1. Users passes `AutoPeftModelForCausalLM.from_pretrained(**parameters)`
2. load base model through `AutoModelForCausalLM.from_pretrained(**parameters)`
3. load adapter through `load_adapter` method

At this point, `**parameters` should be defined on `AutoModelForCausalLM.from_pretrained`.
But `torch_device` parameter is not defined on `AutoModelForCausalLM.from_pretrained` method.
In this reason, `load_adapter` can't get `torch_device` parameter.

`AutoModelForCausalLM.from_pretrained`: `torch_device` parameter not allowed
➡️ `load_adapter` : can't get `torch_device` paramter
➡️ so `load_adapter` always [infer device](https://github.com/huggingface/peft/blob/e72a96f7cfdb330236c1b6dfe49be398d83f089e/src/peft/peft_model.py#L1066)

**Comment by aiqwe** [comment]
Is there any reason we have to infer device by machine environment?

If not, I think there would be some kind of solutions like below:

1. infer device from `device_map`
2. add `torch_device` paramter on `Auto~.from_pretrained` ...

**Comment by BenjaminBossan** [comment]
Thanks for reporting the problem. So IIUC, you would like for `AutoPeftModelForCausalLM.from_pretrained` to correctly take the device from the base model and pass it to `load_adapter`, is that it? I think we can look into that.

As for a solution right now, could you try if this works for you:

```python
from peft import PeftModel

base_model = AutoModelForCausalLM.from_pretrained(..., device_map="cpu")
model = PeftModel.from_pretrained(base_model, <peft-adapter-id>, torch_device="cpu")
```

**Comment by aiqwe** [comment]
ty!
It works well 😀
