### ISSUE TITLE
Save checkpoints with accelerator

### ISSUE THREAD

**Issue by yujianll** [huggingface/peft#192]
When using accelerator for training, how can we only save the additional lora weights for temporary checkpoints?
For example, at [this line](https://github.com/huggingface/transformers/blob/main/examples/pytorch/language-modeling/run_clm_no_trainer.py#L605), how to avoid saving the whole model?

**Comment by samiur** [comment]
Hi, this is still an issue. Please reopen the issue.

**Comment by Aida-yy** [comment]
I have same problem, I use deepspeed, help !
