### ISSUE TITLE
Gradient not appliable to 4-bit quantization. (sft-qlora-fsdp)

### ISSUE THREAD

**Issue by NotTheStallion** [huggingface/peft#1923]
### System Info

accelerate                   0.31.0
peft                              0.11.1
transformers                4.42.4
bitsandbytes                0.41.1

##### The following packages are not related to the error but were given for error reproducibility purposes.
torch                            2.3.1
nvidia-nccl-cu12          2.20.5 # This is used as an accelerate backend

### Who can help?

@BenjaminBossan @sayakpaul

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

# Reproductibility
To reproduce the error run the bash script at `[peft](https://github.com/huggingface/peft/tree/main)/[examples](https://github.com/huggingface/peft/tree/main/examples)/[sft](https://github.com/huggingface/peft/tree/main/examples/sft)

/run_peft_qlora_fsdp.sh`  with the same config end code.

# Error
The following error is the error i get when i try fine-tuning with qlora.
> [rank0]: Traceback (most recent call last):
> [rank0]:   File "/home/ubuntu/PentestLLM/_local_cuisine/train.py", line 163, in <module>
> [rank0]:     main(model_args, data_args, training_args)
> [rank0]:   File "/home/ubuntu/PentestLLM/_local_cuisine/train.py", line 107, in main
> [rank0]:     model, peft_config, tokenizer = create_and_prepare_model(model_args, data_args, training_args)
> [rank0]:   File "/home/ubuntu/PentestLLM/_local_cuisine/utils.py", line 131, in create_and_prepare_model
> [rank0]:     model = AutoModelForCausalLM.from_pretrained(
> [rank0]:   File "/home/ubuntu/Myenv/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 564, in from_pretrained
> [rank0]:     return model_class.from_pretrained(
> [rank0]:   File "/home/ubuntu/Myenv/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3838, in from_pretrained
> [rank0]:     ) = cls._load_pretrained_model(
> [rank0]:   File "/home/ubuntu/Myenv/lib/python3.10/site-packages/transformers/modeling_utils.py", line 4298, in _load_pretrained_model
> [rank0]:     new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(
> [rank0]:   File "/home/ubuntu/Myenv/lib/python3.10/site-packages/transformers/modeling_utils.py", line 904, in _load_state_dict_into_meta_model
> [rank0]:     value = type(value)(value.data.to("cpu"), **value.__dict__)
> [rank0]:   File "/home/ubuntu/Myenv/lib/python3.10/site-packages/bitsandbytes/nn/modules.py", line 147, in __new__
> [rank0]:     self = torch.Tensor._make_subclass(cls, data, requires_grad)
> [rank0]: RuntimeError: Only Tensors of floating point and complex dtype can require gradients
> E0712 21:00:45.048000 136025371594752 torch/distributed/elastic/multiprocessing/api.py:826] failed (exitcode: 1) local_rank: 0 (pid: 37026) of binary: /home/ubuntu/Myenv/bin/python3

# Attempted solutions
I tried : 
- changing from quat 4-bit to 8-bit to test the option tested in this issue https://github.com/hiyouga/LLaMA-Factory/issues/3497.
- using custom config found in a similar problem https://github.com/haotian-liu/LLaVA/issues/783#issuecomment-2105690315.
- excluding linear layer from quant selection https://github.com/huggingface/peft/issues/1720#issuecomment-2104290231.
- + changing the model.
- + changing the number of machines and processes to 1 to test on a local machine.
None of the previous solutions solved the problem.

### Expected behavior

I expected my code not to show any error :stuck_out_tongue_winking_eye: and do peft-sft-qlora-fsdp fine-tuning on any model given to it.

**Comment by BenjaminBossan** [comment]
I just tried this script with some minor modifications and could run it successfully (2x 4090):

```diff
3c3
< --model_name_or_path "meta-llama/Llama-2-70b-hf" \
---
> --model_name_or_path "meta-llama/Llama-2-7b-hf" \
9c9
< --max_seq_len 2048 \
---
> --max_seq_len 256 \
16,18d15
< --push_to_hub \
< --hub_private_repo True \
< --hub_strategy "every_save" \
26,28c23,25
< --output_dir "llama-sft-qlora-fsdp" \
< --per_device_train_batch_size 2 \
< --per_device_eval_batch_size 2 \
---
> --output_dir "/tmp/peft/llama-sft-qlora-fsdp" \
> --per_device_train_batch_size 1 \
> --per_device_eval_batch_size 1 \
```

Could you check if it works for you?

Also, please give more details: What is your `accelerate env`, what machine are you using, what version of relevant libraries (PEFT, accelerate, PyTorch)?

**Comment by NotTheStallion** [comment]
The modification proposed didn't solve the problem.

`Accelerate env` output :
> - `Accelerate` version: 0.31.0
> - Platform: Linux-6.5.0-41-generic-x86_64-with-glibc2.35
> - `accelerate` bash location: /home/ubuntu/Myenv/bin/accelerate
> - Python version: 3.10.12
> - Numpy version: 1.26.4
> - PyTorch version (GPU?): 2.3.1+cu121 (True)
> - PyTorch XPU available: False
> - PyTorch NPU available: False
> - PyTorch MLU available: False
> - System RAM: 31.08 GB
> - GPU type: NVIDIA GeForce RTX 3060
> - `Accelerate` default config:
> 	- compute_environment: LOCAL_MACHINE
> 	- distributed_type: FSDP
> 	- mixed_precision: no
> 	- use_cpu: False
> 	- debug: False
> 	- num_processes: 1
> 	- machine_rank: 0
> 	- num_machines: 1
> 	- main_process_ip: main-node
> 	- main_process_port: 5000
> 	- rdzv_backend: static
> 	- same_network: True
> 	- main_training_function: main
> 	- enable_cpu_affinity: False
> 	- fsdp_config: {'fsdp_auto_wrap_policy': 'TRANSFORMER_BASED_WRAP', 'fsdp_backward_prefetch': 'BACKWARD_PRE', 'fsdp_cpu_ram_efficient_loading': True, 'fsdp_forward_prefetch': False, 'fsdp_offload_params': True, 'fsdp_sharding_strategy': 'FULL_SHARD', 'fsdp_state_dict_type': 'SHARDED_STATE_DICT', 'fsdp_sync_module_states': True, 'fsdp_use_orig_params': False}
> 	- downcast_bf16: no
> 	- tpu_use_cluster: False
> 	- tpu_use_sudo: False
> 	- tpu_env: []

**Comment by BenjaminBossan** [comment]
Hmm, strange that it works on my machine and not yours. Your accelerate env looks fine and is very similar to what I have. Could you try what happens if you deactivate PEFT, i.e. set `--use_peft_lora False`? Of course, we cannot train a quantized model without PEFT but since you mentioned that this is only about the loading step, it should be okay.

**Comment by NotTheStallion** [comment]
I set it to false but that didn't change the error message.
The problem is that i am not sure where the problem is coming from. Is it really a `torch` problem or a silent error in the `Auto` class of `Transformers`.

**Comment by BenjaminBossan** [comment]
Thanks for testing this, I was suspecting it was not PEFT-related. Ideally, you could try to remove all unnecessary code, i.e. everything not related to the model config and loading. That way, you could check if it's really an issue with transformers/bitsandbytes. If you can do that and check if it works, that would be great. Please share the code and I'll also give it a try.

**Comment by BenjaminBossan** [comment]
Great that you could find the issue. Strange why I had no problem. Anyway, I'll close the PR for now, feel free to re-open if something else comes up.
