### ISSUE TITLE
PEFT implementations of adapters are outdated and languishing

### ISSUE THREAD

**Issue by bghira** [huggingface/peft#1931]
### System Info

Latest PEFT, transformers, diffusers codebase.

### Who can help?

@benjaminbossan @sayakpaul 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

The LoKr, LoHa, and other LyCORIS modules are all outdated and missing substantial improvements and fixes from their upstream implementations.

### Expected behavior

Either the upstream implementation should be directly wrapped, or these implementations should be kept up to date by the PEFT team. It doesn't seem like it should be on KohakuBlueleaf to update support for his adapters since the code was hastily copy-pasted into PEFT before being abandoned.

**Comment by bghira** [comment]
full matrix tuning, 1x1 convolutions, quantised LoHa/LoKr, weight-decomposed LoHa/LoKr, fixed rank dropout implementation, fixed maths (not multiplying against the vector, but only the scalar)

**Comment by bghira** [comment]
basically the results are entirely different from upstream to PEFT implementation, with the upstream author recommending peft be avoided at this point in time :[

**Comment by BenjaminBossan** [comment]
Thanks for the info. I reformatted this and put what sounds like bugs to the top, as they are more important. If you have any further references, like GH issues, that would be fantastic.

- [ ] fixed rank dropout implementation
- [ ] fixed maths (not multiplying against the vector, but only the scalar)
- [ ] full matrix tuning
- [ ] 1x1 convolutions
- [ ] quantised LoHa/LoKr
- [ ] weight-decomposed LoHa/LoKr

**Comment by sayakpaul** [comment]
Thanks for making us aware of this, @bghira!

@BenjaminBossan WDYT about also opening this to the community in case someone is interested in collaborating to start with some of these?

**Comment by BenjaminBossan** [comment]
Yes, absolutely @sayakpaul. Do you have a suggestion how to best promote this?

**Comment by sayakpaul** [comment]
@BenjaminBossan https://github.com/huggingface/peft/issues/1935
