### ISSUE TITLE
Check if `past_key_values` is provided when using prefix_tuning in peft_model

### ISSUE THREAD

**Issue by Nidhogg-lyz** [huggingface/peft#1938]
### Feature request

In `peft/peft_model.py`, in `PeftModelForCausalLM.forward() line 1465`, the function call fails to check if key `past_key_values` is in `kwargs`, and this will throw an error when `past_key_values` are provided in the base model's forward call (though in most cases this argument is set to None).
This is a snippet of the source code:
```
    def forward(
        self,
        input_ids=None,
        attention_mask=None,
        inputs_embeds=None,
        labels=None,
        output_attentions=None,
        output_hidden_states=None,
        return_dict=None,
        task_ids=None,
        **kwargs,
    ):
        ......
        if peft_config.peft_type == PeftType.PREFIX_TUNING:
            past_key_values = self.get_prompt(batch_size)
            return self.base_model(
                input_ids=input_ids, inputs_embeds=inputs_embeds, past_key_values=past_key_values, **kwargs
            )
        else:
        ......
```

### Motivation

This error occurs when I try to finetune the language model wrapped in llava. In llava's `forward` function, the language model is called with `past_key_values` argument and this raises TypeError `object got multiple values for keyword argument 'past_key_values'`

### Your contribution

A simple solution is just add `past_key_values` as keyword argument in the peft model's `forward` function and its value can be safely overridden by the inner codes. I'm more than happy to submit a PR.

**Comment by BenjaminBossan** [comment]
Thanks for reporting this error. Indeed it sounds like it should not be too hard to fix. Do you have a code snippet that I can use to reproduce the error?

**Comment by Nidhogg-lyz** [comment]
@BenjaminBossan This is a simple script for reproduction:
```
import requests
from PIL import Image

import torch
from transformers import AutoProcessor, LlavaForConditionalGeneration, LlamaForCausalLM

model_id = "llava-hf/llava-1.5-7b-hf"
prompt = "USER: <image>\nWhat are these?\nASSISTANT:"
image_file = "http://images.cocodataset.org/val2017/000000039769.jpg"

# prepare model and inputs
model = LlavaForConditionalGeneration.from_pretrained(
    model_id, 
    torch_dtype=torch.float16, 
    low_cpu_mem_usage=True, 
)
processor = AutoProcessor.from_pretrained(model_id)
raw_image = Image.open(requests.get(image_file, stream=True).raw)
inputs = processor(prompt, raw_image, return_tensors='pt').to(torch.float16)

# get peft model
from peft import PrefixTuningConfig, get_peft_model
peft_config = PrefixTuningConfig(task_type="CAUSAL_LM", num_virtual_tokens=20)
model.language_model = get_peft_model(model.language_model, peft_config)

output = model(**inputs, output_hidden_states = True)
```

Btw, to find the exact cause of the error, you may need to check `forward` function of llava, in `transformers/models/llava/modeling_llava.py`, `class LlavaForConditionalGeneration` line 476.

**Comment by BenjaminBossan** [comment]
Thanks for providing this example, I could replicate the error. If you want to create the PR to fix this, I'd be happy to accept it.

For this, let's adopt your example as a unit test for this bug. We can substitute the quite big llava model by this tiny variation, which is sufficient to cover the bug: `model_id = "trl-internal-testing/tiny-random-LlavaForConditionalGeneration"`.

**Comment by Nidhogg-lyz** [comment]
To minimize the effect on other codes, I simply check if the `past_key_values` already in `kwargs` and pop it. If there's any potential issues please let me know and I'm glad to participate in this.
