### ISSUE TITLE
Any plans to support multi-task tuning?

### ISSUE THREAD

**Issue by brian-pieces** [huggingface/peft#195]
Some examples of using a single base model for multiple tasks:
- https://github.com/NVIDIA/NeMo/blob/main/tutorials/nlp/Multitask_Prompt_and_PTuning.ipynb
- https://openreview.net/forum?id=Nk2pDtuhTq

**Comment by mayank31398** [comment]
Hey @brian-pieces
check this one out: https://github.com/huggingface/peft/pull/400
Trying to get this in
