### ISSUE TITLE
拉了一个多模态大模型技术交流群，大家可以加入进来进行技术交流

### ISSUE THREAD

**Issue by feihuamantian** [huggingface/peft#1953]
### System Info

请扫微信二维码加群，如果群失效，可以添加我微信加入：yx116169
![20240725-111054](https://github.com/user-attachments/assets/cb500a4a-8008-40f8-bbf6-38472b2dca5b)

### Who can help?

1

### Information

- [X] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

1

### Expected behavior

1

**Comment by BenjaminBossan** [comment]
Closing this, as it looks like advertisement. If this is about a PEFT issue, re-open and explain the issue.
