### ISSUE TITLE
[VeRA] doesn't support different dim when using shared buffer

### ISSUE THREAD

**Issue by AaronZLT** [huggingface/peft#1954]
### System Info

-

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

VeRA doesn't support add lora to all linear layers.

### Expected behavior

-

**Comment by AaronZLT** [comment]
Is it possible to set different shared buffer for different dims? Since there are not so many diff dims in total

**Comment by BenjaminBossan** [comment]
> VeRA doesn't support add lora to all linear layers.

I suspect this is a typo and you mean "add VeRA to all linear layers". In fact, with the latest PEFT release (v0.12.0), this should be possible. Could you give it a try? If it fails, could you show the code and the error?

**Comment by AaronZLT** [comment]
> > VeRA doesn't support add lora to all linear layers.
> 
> I suspect this is a typo and you mean "add VeRA to all linear layers". In fact, with the latest PEFT release (v0.12.0), this should be possible. Could you give it a try? If it fails, could you show the code and the error?

Oh, I haven't tried the latest PEFT yet, on the go...

**Comment by AaronZLT** [comment]
The latest PEFT release (v0.12.0) works, thx @BenjaminBossan
