### ISSUE TITLE
Changing lora_alpha during inference

### ISSUE THREAD

**Issue by SoumiDas** [huggingface/peft#1964]
Hi,

I wanted to know if there's any workaround in peft library, to change the alpha value from that used during training time, for the LoraConfig during inference?

Thanks in advance!

**Comment by BenjaminBossan** [comment]
With the goal of changing the LoRA scaling? There is currently no easy way except to loop through the modules and adjust the `.scaling` argument, but there is a solution in the works in #1951.

**Comment by SoumiDas** [comment]
Thanks @BenjaminBossan! However, importing ```set_adapter_scale``` from ```peft.utils.scaling_utils``` leads to an error. Is the function ```set_adapter_scale``` to be imported from some other class?

**Comment by SoumiDas** [comment]
Thanks a lot! This helps!

**Comment by ariG23498** [comment]
Hi @SoumiDas!

If you end up using the context manager -- do let us know if you run into any errors :smile:
