### ISSUE TITLE
Documentation and optimization of X-LoRA

### ISSUE THREAD

**Issue by EricLBuehler** [huggingface/peft#1966]
Hi all,

Since the merge of #1491, documentation has yet to be added to X-LoRA. I was wondering how I should approach adding this?

Additionally, I also wanted to discuss optimizing X-LoRA. In mistral.rs, we use a dual-KV cache system for optimized inference, and we also implement a variety of tricks to get it to work, such as reducing the granularity of the scalings in the sequence dimension. Would it be possible to implement these here? The dual-KV cache system would likely provide the most impactful improvements for inference times, but I'm not sure if we can overcome a 2x cost during training.

**Comment by BenjaminBossan** [comment]
Thanks for picking up the TODOs for X-LoRA.

> documentation has yet to be added to X-LoRA. I was wondering how I should approach adding this?

Typically, for new methods, we have an entry with a short description (can also be longer if you want), as well as the reference to the paper and a copy of the abstract. Here is an example for a recently added method:

https://github.com/huggingface/peft/pull/1838/files#diff-f8d11c01ce913e667c432a706977515024ba7a974df6ec46556df5a70c6280b0

It would also be great to add an example to the `examples/` directory. Ideally something that trains a real model, maybe replicating an experiment from the paper. If this is too slow, it can also be a dummy example, with some comments on how to go from here.

> I also wanted to discuss optimizing X-LoRA. In mistral.rs, we use a dual-KV cache system for optimized inference, and we also implement a variety of tricks to get it to work, such as reducing the granularity of the scalings in the sequence dimension. Would it be possible to implement these here?

Would this be in Python code or bind Rust code? If the former, I don't see why not. If the latter, it would certainly be possible but require some extra steps, as we don't have Rust bindings at the moment.

**Comment by EricLBuehler** [comment]
> Typically, for new methods, we have an entry with a short description (can also be longer if you want), as well as the reference to the paper and a copy of the abstract. Here is an example for a recently added method:

Ok! I opened #1970 to add docs, I would appreciate it if you could check if it is correct?

> It would also be great to add an example to the examples/ directory. Ideally something that trains a real model, maybe replicating an experiment from the paper. If this is too slow, it can also be a dummy example, with some comments on how to go from here.

Sounds good, I will add that to #1970.

> Would this be in Python code or bind Rust code? If the former, I don't see why not. If the latter, it would certainly be possible but require some extra steps, as we don't have Rust bindings at the moment.

We have a full X-LoRA implementation in mistral.rs, but it is not designed to be compatible with Python. Perhaps we could include a [Python example of inference with mistral.rs](https://github.com/EricLBuehler/mistral.rs/blob/master/examples/python/xlora_zephyr.py)? It shows significant performance improvement over the Python implementation, and there are packages on PyPi.

As for further steps, perhaps we could add this to TGI, or introduce some hooks to power a dual-KV cache mechanism.

**Comment by BenjaminBossan** [comment]
> Perhaps we could include a [Python example of inference with mistral.rs](https://github.com/EricLBuehler/mistral.rs/blob/master/examples/python/xlora_zephyr.py)? It shows significant performance improvement over the Python implementation, and there are packages on PyPi.

Yes, it's a good idea to include a reference to this example. It would be cool to also port the optimizations to PEFT, but I don't know how difficult that would be.
