### ISSUE TITLE
TOWARDS A UNIFIED VIEW OF PARAMETER-EFFICIENT TRANSFER LEARNING

### ISSUE THREAD

**Issue by jc-ryan** [huggingface/peft#197]
Do you have any plan to implement the MAM method proposed in _(He et al., ICLR2022) TOWARDS A UNIFIED VIEW OF PARAMETER-EFFICIENT TRANSFER LEARNING_ ? It is an improvement on the unified level of the Adapter, Prefix-tuning and LoRA methods.
Of course, if you don't have the manpower to implement it at the moment, I can try to submit a PR, but I might need some instructions from you :)

**Comment by pacman100** [comment]
Hello @jc-ryan, this would be a great addition, Thank you for your interest in integrating it 😄. Please let us know how we can enable you to achieve this 🤗
