### ISSUE TITLE
hyper-paramter `r` in adalora_confg and lora_config

### ISSUE THREAD

**Issue by Vincent950129** [huggingface/peft#1971]
It is clear that `r` in lora_config refers to rank. However, in adalora, I noticed that `r` also exists (besides `target_r` and `init_r`) and is used in the example. I am wondering what this `r` represents in adalora? Thanks.

```
from transformers import AutoModelForSeq2SeqLM, LoraConfig >>> from peft import AdaLoraModel, AdaLoraConfig

config = AdaLoraConfig(
peft_type="ADALORA", task_type="SEQ_2_SEQ_LM", r=8, lora_alpha=32, target_modules=["q", "v"],
lora_dropout=0.01,
)
```

**Comment by BenjaminBossan** [comment]
Good point, thanks for bringing this up. AFAICT, `r` does indeed not have any function for AdaLoRA and is just replaced by `init_r`, which is confusing. I'm not sure why back then, it was decided to add this new parameter, it would have been better to just use `r`. At this point, changing this would break existing code. Probably the best action would be to check during the `__post_init__` of the config if a user tried to change `r` and warn them that they probably meant to change `init_r`.
