### ISSUE TITLE
Merging adapters for BF16 model on CPU is very slow

### ISSUE THREAD

**Issue by snarayan21** [huggingface/peft#1977]
### System Info

peft version 0.12.0
AMD EPYC cpu

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

Have a bf16 model on cpu, for a cpu that doesn't have support (or fast support) for bf16 matmuls. Attempt to call `model.merge_and_unload()`

### Expected behavior

We would expect the bf16 layers to be cast to float32 before the matmul, just as in the float16 case:
https://github.com/huggingface/peft/blob/1b16753a6aca2fc9581823c8e2efd628b7d2b676/src/peft/tuners/lora/layer.py#L511

**Comment by BenjaminBossan** [comment]
Solved via #1978.
