### ISSUE TITLE
LoraConfig.__init__() got an unexpected keyword argument 'layer_replication' when using custom model handler

### ISSUE THREAD

**Issue by topher** [huggingface/peft#1979]
### System Info

**Title:**
`LoraConfig.__init__() got an unexpected keyword argument 'layer_replication' when using custom model handler`

**Description:**
I'm encountering an error when trying to deploy a custom model using the Hugging Face Inference Toolkit. The error message indicates that `LoraConfig.__init__()` received an unexpected keyword argument `layer_replication`. This issue persists even after ensuring that all dependencies are up-to-date.

**Error Message:**
```
TypeError: LoraConfig.__init__() got an unexpected keyword argument 'layer_replication'
```

**Steps to Reproduce:**
1. Create a custom model handler with the following configuration:
    ```python
    from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline
    import torch

    class EndpointHandler:
        def __init__(self, model_dir):
            self.model_dir = model_dir
            self.device = 0 if torch.cuda.is_available() else -1  # Use GPU if available, otherwise CPU
            self.tokenizer = AutoTokenizer.from_pretrained(model_dir)
            self.model = AutoModelForCausalLM.from_pretrained(model_dir)

            # Dynamically remove unsupported configuration parameters
            config = self.model.config
            unsupported_params = ['layer_replication']
            for param in unsupported_params:
                if hasattr(config, param):
                    delattr(config, param)

            self.pipeline = pipeline("text-generation", model=self.model, tokenizer=self.tokenizer, device=self.device)

        def __call__(self, inputs):
            return self.pipeline(inputs["text"], max_length=50)

    if __name__ == "__main__":
        handler = EndpointHandler("/repository")
        print(f"Using device: {'cuda' if handler.device == 0 else 'cpu'}")
    ```

2. Ensure the following `requirements.txt` is used:
    ```
    transformers>=4.26.0
    torch>=1.12.1
    bitsandbytes>=0.43.2
    accelerate
    peft
    ```

3. Deploy the model using the Hugging Face Inference Toolkit.

**Expected Behavior:**
The model should load and function without any errors related to `LoraConfig`.

**Actual Behavior:**
The deployment fails with the error:
```
TypeError: LoraConfig.__init__() got an unexpected keyword argument 'layer_replication'
```

**Environment:**
- `transformers` version: 4.38.2
- `torch` version: 2.2.0
- `bitsandbytes` version: 0.43.3
- `accelerate` version: 0.27.2
- `peft` version: 0.9.0
- Python version: 3.10
- Hugging Face Inference Toolkit version: latest

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

import os
import logging
from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline
import torch

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

class EndpointHandler:
    def __init__(self, path=""):
        self.path = path
        self.device = "cuda" if torch.cuda.is_available() else "cpu"
        logger.info(f"Initializing EndpointHandler with device: {self.device}")

        try:
            self.tokenizer = AutoTokenizer.from_pretrained(self.path)
            logger.info("Tokenizer loaded successfully")
        except Exception as e:
            logger.error(f"Failed to load tokenizer: {e}")
            raise

        try:
            # Load model with specific configuration to avoid LoraConfig issues
            self.model = AutoModelForCausalLM.from_pretrained(
                self.path,
                device_map="auto",
                torch_dtype=torch.float16 if self.device == "cuda" else torch.float32,
                low_cpu_mem_usage=True,
            )
            logger.info("Model loaded successfully")
        except Exception as e:
            logger.error(f"Failed to load model: {e}")
            raise

        try:
            self.pipeline = pipeline(
                "text-generation",
                model=self.model,
                tokenizer=self.tokenizer,
                device=0 if self.device == "cuda" else -1
            )
            logger.info("Pipeline created successfully")
        except Exception as e:
            logger.error(f"Failed to create pipeline: {e}")
            raise

    def __call__(self, data):
        try:
            inputs = data.pop("inputs", data)
            parameters = data.pop("parameters", {})
            
            if not isinstance(inputs, list):
                inputs = [inputs]
            
            results = []
            for prompt in inputs:
                output = self.pipeline(prompt, **parameters)
                results.extend(output)
            
            logger.info(f"Generated {len(results)} responses")
            return {"generated_text": [result['generated_text'] for result in results]}
        except Exception as e:
            logger.error(f"Error during inference: {e}")
            return {"error": str(e)}

# For testing the handler
if __name__ == "__main__":
    handler = EndpointHandler()
    test_input = {"inputs": "Hello, how are you?"}
    print(handler(test_input))

### Expected behavior

A successful deployment of Huggingface Dedicated API Inference Endpoint

**Comment by BenjaminBossan** [comment]
This error occurs because you're trying to load a PEFT checkpoint that was trained with a more recent version of PEFT than the one you're using. If possible, please upgrade your PEFT version, as v0.9.0 is quite old at this point. If for some reason that is not an option for you, please edit the `adapter_config.json` file and remove the entry for "layer_replication" (and any other items that cause an error). This should lead to the adapter being correctly loaded.

**Comment by topher** [comment]
Resolved, thank you!
