### ISSUE TITLE
LoftQ init without scaling

### ISSUE THREAD

**Issue by cobbswordsman** [huggingface/peft#1982]
https://github.com/huggingface/peft/blob/f13d860e9f58e908ac85e78ac37528ec8c84eb99/src/peft/tuners/lora/layer.py#L226

I find scaling with pissa and dora，but no scaling with loftq init Lora_A and lora_B.
It's a bug?or no need to do that

**Comment by BenjaminBossan** [comment]
I agree, it looks like it could make sense to consider the scaling factor when applying LoftQ. @fxmeng could you comment on that?

**Comment by BenjaminBossan** [comment]
Another ping @fxmeng.
