### ISSUE TITLE
DoRA with fsdp model cannot work

### ISSUE THREAD

**Issue by Wongboo** [huggingface/peft#1984]
### System Info

- peft 0.12.0
- `transformers` version: 4.43.3
- Platform: Linux-5.15.0-113-generic-x86_64-with-glibc2.35
- Python version: 3.12.4
- Huggingface_hub version: 0.24.2
- Safetensors version: 0.4.3
- Accelerate version: 0.33.0
- Accelerate config: 	- compute_environment: LOCAL_MACHINE
	- distributed_type: MULTI_GPU
	- mixed_precision: fp16
	- use_cpu: False
	- debug: False
	- num_processes: 8
	- machine_rank: 0
	- num_machines: 1
	- rdzv_backend: static
	- same_network: False
	- main_training_function: main
	- enable_cpu_affinity: False
	- downcast_bf16: False
	- tpu_use_cluster: False
	- tpu_use_sudo: False
- PyTorch version (GPU?): 2.4.0 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using distributed or parallel set-up in script?: <fill in>
- Using GPU in script?: <fill in>
- GPU type: NVIDIA A800-SXM4-80GB

### Who can help?

@BenjaminBossan @sayakpaul

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

hugginface trainer with fsdp enabled, with dora peft adapter

### Expected behavior

work fine

**Comment by BenjaminBossan** [comment]
I could successfully train DoRA with FSDP in the past, see #1806. Please provide the full error message and, ideally, a full reproducer, so that we can investigate.

**Comment by austings** [comment]
I am also interested in using DoRA with Peft for inference.
DoRA with deepspeed at inference time has some issues where the adapter layers are not being properly initialized. Reinitializing the model seems to help but negates the benefits of using adapters

**Comment by winglian** [comment]
I also had an issue with bf16 weights + fsdp + dora

[rank0]:   File "/root/miniconda3/envs/py3.11/lib/python3.11/site-packages/peft/tuners/lora/layer.py", line 572, in forward
[rank0]:     result = result + self._apply_dora(x, lora_A, lora_B, scaling, active_adapter)           
[rank0]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/envs/py3.11/lib/python3.11/site-packages/peft/tuners/lora/layer.py", line 265, in _apply_dora
[rank0]:     lora_weight = lora_B.weight @ lora_A.weight     
[rank0]:                   ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~                                                                                      
[rank0]: RuntimeError: inconsistent tensor size, expected tensor [104858] and src [131072] to have the same number of elements, but got 104858 and 131072 elements respectively

**Comment by Wongboo** [comment]
I use stanford alpaca for training
```
torchrun --nproc_per_node=4 --master_port=<your_random_port> train.py \
    --model_name_or_path <your_path_to_hf_converted_llama_ckpt_and_tokenizer> \
    --data_path ./alpaca_data.json \
    --bf16 True \
    --output_dir <your_output_dir> \
    --num_train_epochs 3 \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 8 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 2000 \
    --save_total_limit 1 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --fsdp "full_shard auto_wrap" \
    --fsdp_transformer_layer_cls_to_wrap 'LlamaDecoderLayer' \
    --tf32 True
```
with dora modification
```python
        from peft import LoraConfig, get_peft_model

        loraconfig = LoraConfig(
            r=64,
            lora_alpha=16,
            lora_dropout=0.1,
            use_dora=True,
            bias="none",
            task_type="CAUSAL_LM",
            target_modules="q_proj,k_proj,v_proj,o_proj,down_proj,up_proj,gate_proj".split(","),
        )
        model = get_peft_model(model, loraconfig)
        model.print_trainable_parameters()
```
my error is similar with @winglian

**Comment by Wongboo** [comment]
BTW, anyone knows how to generate `config` parameter in `AdaptionPromptModel` method from peft llama-adapter? The doc seems to be very confusing.

**Comment by BenjaminBossan** [comment]
Thanks for providing more details. I haven't tested bf16 yet. I'll take a closer look and report back.

**Comment by BenjaminBossan** [comment]
Okay, so I managed to successfully train a DoRA model with FSDP and bfloat16. The training script is here:

https://github.com/BenjaminBossan/peft-experiments/blob/main/torchtune/llama3-lora-fsdp/train.py

Run it like so:

`USE_DORA=1 torchrun --nproc_per_node <N> train.py`

Note that this script uses some `torchtune` functionality, as I'm currently working on a comparison between `torchtune` and PEFT and wanted to match `torchtune` as closely as possible. However, the model itself is a transformers+PEFT model, not a `torchtune` model, so this should not make any difference. The dataset is a cleaned version of Alpaca.

You will have to adjust these lines to load the Llama3 tokenizer:

https://github.com/BenjaminBossan/peft-experiments/blob/3b006cb67231d04a8daaaabc340dce2d276c79d7/torchtune/llama3-lora-fsdp/train.py#L32-L33

Regarding the used versions, I have the latest PEFT, transformers, and torchtune (i.e. installed from `main`) and PyTorch 2.3.1.

LMK if you manage, or don't manage, to get the script to run.

**Comment by winglian** [comment]
I also tried this with qdora, and I'm getting the same error, my initial report was for full weights dora+fsdp.

**Comment by BenjaminBossan** [comment]
> my initial report was for full weights dora+fsdp

Note that the provided script is also full weights (non-quantized).

**Comment by winglian** [comment]
Are you able to reproduce the error on your end with accelerate + hf trainer + fsdp?

**Comment by BenjaminBossan** [comment]
@winglian I hacked something together with `Trainer` (actually `SFTTrainer`) + FSDP + DoRA and it works. Note that this is a very rough script and needs improvement for proper training, but it shows that it can work:

```python
# Using trl Trainer and accelerate (trl-0.9.6, accelerate-0.33.0)
# accelerate launch --config_file fsdp_config.yaml train-hf.py
#
# for DoRA:
# USE_DORA=1 accelerate launch --config_file fsdp_config.yaml train-hf.py

import os

import torch
from datasets import load_dataset
from peft import LoraConfig
from transformers import AutoModelForCausalLM, AutoTokenizer
from trl import SFTConfig, SFTTrainer


def train():
    #########
    # SETUP #
    #########

    torch.cuda.manual_seed(0)
    # TODO: template not applied
    tokenizer = AutoTokenizer.from_pretrained(model_id)
    tokenizer.pad_token = tokenizer.eos_token

    ds = load_dataset(ds_name)
    model = AutoModelForCausalLM.from_pretrained(
        model_id,
        torch_dtype=dtype,
    )
    lora_config = LoraConfig(
        r=rank,
        lora_alpha=alpha,
        target_modules=target_modules,
        lora_dropout=dropout,
        use_dora=use_dora,
    )
    training_args = SFTConfig(
        output_dir=output_dir,
        per_device_train_batch_size=batch_size,
        per_device_eval_batch_size=batch_size,
        gradient_accumulation_steps=gradient_accumulation_steps,
        num_train_epochs=total_epochs,
        save_strategy="no",
        bf16=True,
        learning_rate=lr,
        weight_decay=weight_decay,
        lr_scheduler_type="cosine",
        warmup_steps=num_warmup_steps,
        dataset_text_field="input",
        max_seq_length=max_seq_len,
    )

    trainer = SFTTrainer(
        model=model,
        tokenizer=tokenizer,
        args=training_args,
        train_dataset=ds["train"],
        peft_config=lora_config,
        packing=False,
    )
    trainer.train()

if __name__ == "__main__":
    ##############
    # PARAMETERS #
    ##############

    model_id = "meta-llama/Meta-Llama-3-8B-Instruct"
    dtype = torch.bfloat16
    weight_decay = 0.01
    lr = 0.0003
    gradient_accumulation_steps = 4
    num_warmup_steps = 100

    # data
    ds_name = "yahma/alpaca-cleaned"
    max_seq_len = 512
    total_epochs = 1
    batch_size = 2
    # max_steps_per_epoch = None
    output_dir = "/tmp/peft/sft"

    # LoRA
    rank = 8
    alpha = 16
    target_modules = ["q_proj", "v_proj"]
    dropout = 0.05
    use_dora = bool(int(os.environ.get("USE_DORA", "0")))
    if use_dora:
        print("USING DORA")

    train()
```

FSDP config:
```yaml
compute_environment: LOCAL_MACHINE
debug: false
distributed_type: FSDP
downcast_bf16: 'no'
fsdp_config:
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_backward_prefetch: BACKWARD_PRE
  fsdp_cpu_ram_efficient_loading: true
  fsdp_forward_prefetch: false
  fsdp_offload_params: false
  fsdp_sharding_strategy: FULL_SHARD
  fsdp_state_dict_type: SHARDED_STATE_DICT
  fsdp_sync_module_states: true
  fsdp_use_orig_params: false
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```

**Comment by BenjaminBossan** [comment]
I uploaded an adjusted training script for DoRA + FSDP here: https://github.com/BenjaminBossan/peft-experiments/tree/main/torchtune/llama3-lora-fsdp#using-trainer-and-accelerate

It uses `Trainer` and accelerate under the hood and works. I haven't done a long run yet to compare the training progress.

**Comment by winglian** [comment]
@BenjaminBossan I tried your script above on latest releases of bnb and transformers and as well as tried both the latest release 0.32.0 and main on accelerate, w torch==2.3.1 and I get:

```
[rank1]:   File "/root/miniconda3/envs/py3.11/lib/python3.11/site-packages/torch/distributed/fsdp/_init_utils.py", line 610, in _init_param_handle_from_params
[rank1]:     handle = FlatParamHandle(
[rank1]:              ^^^^^^^^^^^^^^^^
[rank1]:   File "/root/miniconda3/envs/py3.11/lib/python3.11/site-packages/torch/distributed/fsdp/_flat_param.py", line 582, in __init__
[rank1]:     self._init_flat_param_and_metadata(
[rank1]:   File "/root/miniconda3/envs/py3.11/lib/python3.11/site-packages/torch/distributed/fsdp/_flat_param.py", line 632, in _init_flat_param_and_metadata
[rank1]:     ) = self._validate_tensors_to_flatten(params)
[rank1]:         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/root/miniconda3/envs/py3.11/lib/python3.11/site-packages/torch/distributed/fsdp/_flat_param.py", line 779, in _validate_tensors_to_flatten
[rank1]:     raise ValueError(
[rank1]: ValueError: Must flatten tensors with uniform `requires_grad` when `use_orig_params=False`
```

**Comment by winglian** [comment]
looks like I needed to update peft. all looks good to me now!

**Comment by jeffchy** [comment]
> I also had an issue with bf16 weights + fsdp + dora
> 
> ```
> [rank0]:   File "/root/miniconda3/envs/py3.11/lib/python3.11/site-packages/peft/tuners/lora/dora.py", line 74, in forward
> [rank0]:     x_eye = torch.eye(lora_A.weight.shape[1], device=lora_A.weight.device, dtype=x.dtype)
> [rank0]:                       ~~~~~~~~~~~~~~~~~~~^^^
> [rank0]: IndexError: tuple index out of range
> ```

I also encountered the same error (peft 0.12.0), did you solve it by upgrading peft? or using the new scripts provided by [BenjaminBossan](https://github.com/BenjaminBossan) ?
