### ISSUE TITLE
QLora with DeepSpeed support

### ISSUE THREAD

**Issue by ysj1173886760** [huggingface/peft#2014]
### System Info

peft: 0.12.1.dev0
accelerate: 0.33.0.dev0
transformers: 4.45.0.dev0
platform: ubuntu22.04 LTS
python 3.10.12
hardward: NVIDIA RTX2080TI * 4

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

https://github.com/pacman100/LLM-Workshop/tree/main/personal_copilot/training

I've been following this [article](https://huggingface.co/blog/personal-copilot) to finetune a model. 

[run_peft.sh](https://github.com/pacman100/LLM-Workshop/blob/main/personal_copilot/training/run_peft.sh) works on my machine but only use single GPU, so i want to use accelerate + deepspeed to split model into multiple GPUs to train larger model.

DeepSpeed with no quantization also works on my machine. But as long as i enabled quantization, it will raise an error: 
ValueError: Model was not initialized with `Zero-3` despite being configured for DeepSpeed Zero-3. Please re-initialize your model via `Model.from_pretrained(...)` or `Model.from_config(...)` after creating your `TrainingArguments`!

So my question is does QLora support deepspeed now, and if so, what is correct way to run it?

### Expected behavior

Expect QLora + DeepSpeed will run on multiple GPUs without error.

**Comment by ysj1173886760** [comment]
btw, i found the same error while trying to run the scripts in examples/sft/run_peft_qlora_deepspeed_stage3.sh.

Do i need to upgrade some package version, or the error is caused by model(since i've changed the model from LLAMA-2-70B to codellama/CodeLlama-7b-Instruct-hf)

**Comment by ysj1173886760** [comment]
Another update, after i inspected the code that triggers this error: 
<img width="850" alt="image" src="https://github.com/user-attachments/assets/c3f3ec74-7b1f-40fd-bb5c-252c327ea65d">

i found transformer lib will not set zero3 when enabled quantization. Let me try to upgrade transformer lib

**Comment by ysj1173886760** [comment]
Nope that won't work, since i found the main branch of transformer also contains this code
<img width="853" alt="image" src="https://github.com/user-attachments/assets/84f40b09-a508-423e-9f9d-c1d36fb6faab">
it will only initialize deepspeed when quantized not configured

**Comment by ysj1173886760** [comment]
I found that was a wrong check introduced from transformer lib. reinstall these dependencies with newest release solved my problem.

**Comment by BenjaminBossan** [comment]
> I found that was a wrong check introduced from transformer lib. reinstall these dependencies with newest release solved my problem.

Glad that you found a solution. Could you be so kind to explain further how you solved it, which dependency needed to be updated?

> I found that was a wrong check introduced from transformer lib.

Do you mean it's a bug in transformers?
