### ISSUE TITLE
Unable to load peft checkpoint

### ISSUE THREAD

**Issue by BigDataMLexplorer** [huggingface/peft#2027]
### System Info

 **- transformers version: 4.44.0**
**-  peft 0.12.0**
- Platform: Linux-4.18.0-477.27.1.el8_8.x86_64-x86_64-with-glibc2.28
**- Python version: 3.9.4**
- Huggingface_hub version: 0.23.2
- Safetensors version: 0.4.3
**- Accelerate version: 0.33.0**
- Accelerate config:    not found
**- PyTorch version (GPU?): 2.4.0+cu121 (True)**
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using distributed or parallel set-up in script?: <fill in>
- Using GPU in script?: <fill in>
- GPU type: Tesla V100-FHHL-16GB

### Who can help?

@BenjaminBossan @saya

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

Hello, I am trying to load peft checkpoint and continue training, but I have this error:

```
site-packages/transformers/trainer.py:3108: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  torch.load(os.path.join(checkpoint, OPTIMIZER_NAME), map_location=map_location)
```

`**ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group**`

I tried google this error, but everyone's problem was, that they changed model's parameters somehow, but I didn't change anything. I use the same code and continue training with same Trainer. I use this:

`model = PeftModel.from_pretrained(model, checkpoint_path, is_trainable=True)`

```
trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=Train_tokenized,
        eval_dataset=Eval_tokenized,
        compute_metrics=compute_metrics,
        callbacks=[MetricsLoggingCallback(log_file),EarlyStoppingCallback(early_stopping_patience=2)]
    )

train_result = trainer.train(resume_from_checkpoint="checkpoint_path")
```

Thanks for any help.

### Expected behavior

----

**Comment by BenjaminBossan** [comment]
Hmm, I haven't seen this error yet and based on the code you provided, it's not possible to determine what went wrong. Would it be possible for you to share enough code that I can try to reproduce the error?

If not, something you could try is to print all parameters with gradients once when you start the first training and then again after loading the model the way you indicated. There could be a difference there that results in the error you showed.

**Comment by BigDataMLexplorer** [comment]
Yes, I will send you the code, thanks.

```
num_labels = 11 
model = AutoModelForSequenceClassification.from_pretrained("Llama3", num_labels=num_labels,device_map="auto")

model.config.pad_token_id = model.config.eos_token_id
model.config.use_cache = False
```

```
from peft import prepare_model_for_kbit_training, get_peft_model
model = prepare_model_for_kbit_training(model)
```

```
from peft import LoraConfig
lora_config = LoraConfig(
    r = 2,
    lora_alpha = 1,
    target_modules = "all-linear"
    lora_dropout = 0.05, 
    bias = 'none', 
    task_type = 'SEQ_CLS'
)

```
`model = get_peft_model(model, lora_config)`

```
import numpy as np
def compute_metrics(p):
    logits, labels = p
    predictions = np.argmax(logits, axis=-1)
    accuracy = (predictions == labels).mean()
    return {"accuracy": accuracy}   
```

```
training_args = TrainingArguments(
    output_dir="xxx",
    save_strategy="steps",
    eval_strategy="steps",
    eval_steps=500,
    save_steps=500,
    learning_rate=2e-4,
    lr_scheduler_type="linear",
    per_device_train_batch_size=2,
    num_train_epochs=1,            
    weight_decay=0.01,
    load_best_model_at_end=True, 
    fp16=True,
    save_total_limit=2,             
)
```

```
from transformers import EarlyStoppingCallback

trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=Train_tokenized,
        eval_dataset=Eval_tokenized,
        compute_metrics=compute_metrics,
        callbacks=[EarlyStoppingCallback(early_stopping_patience=1)]
    )
train_result = trainer.train()
```
### Loading from checkpoint
```
num_labels = 11  
model = AutoModelForSequenceClassification.from_pretrained("Llama3", num_labels=num_labels ,device_map="auto")
```

```
model.config.pad_token_id = model.config.eos_token_id
model.config.use_cache = False
```

```
from peft import prepare_model_for_kbit_training
model = prepare_model_for_kbit_training(model)
```

```
from peft import PeftModel
checkpoint_path ="xxx/checkpoint"
model = PeftModel.from_pretrained(model, checkpoint_path, is_trainable=True)
```

```
from transformers import EarlyStoppingCallback

trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=Train_tokenized,
        eval_dataset=Eval_tokenized,
        compute_metrics=compute_metrics,
        callbacks=[EarlyStoppingCallback(early_stopping_patience=1)]
    )

train_result = trainer.train(resume_from_checkpoint="xxx/checkpoint")
```

**Comment by BenjaminBossan** [comment]
Thank you for the additional code. I could replicate the error but it took quite some to figure out what's going on. However, I think I understand now.

So the main problem is that you use `target_modules="all-linear"` in conjunction with `AutoModelForSequenceClassification`. When using `all-linear`, we don't want to target the final linear layer with LoRA, instead it should by fully fine-tuned (using `ModulesToSaveWrapper` under the hood). To find that layer, we use `model.get_output_embeddings()`, which works fine with `AutoModelForCausalLM` but misses with `AutoModelForSequenceClassification`. As a consequence, the classification layer is falsely targeted with LoRA. I'll have to think of a good solution here.

In the meantime, could you please manually set `target_modules`, making sure to avoid the classification layer, e.g. `["q_proj", "k_proj", "v_proj", "out_proj", "fc1", "fc2"]`, which should target all the actually relevant linear layers. In my testing, this works.

**Comment by BigDataMLexplorer** [comment]
Thank you very much

**Comment by BenjaminBossan** [comment]
Could you confirm that it works?

I created a PR to raise an error in such cases in the future. Moreover, I plan to work on a PR that automatically corrects prevents this error entirely.

**Comment by BigDataMLexplorer** [comment]
Do you think load the checkpoint with only the lora layers you specified from training where I specified "all-linear" in LoraConfig or start new training with only these layers and than resume from checkpoint? Because I am not sure how I should load the checkpoint (after all-linear was applied in previous training) without last linear lora layer without with this:
```
from peft import PeftModel
checkpoint_path ="xxx/checkpoint"
model = PeftModel.from_pretrained(model, checkpoint_path, is_trainable=True)
```

**Comment by BenjaminBossan** [comment]
It is not a good idea to try to convert the existing weights to the new format. Unfortunately, this means you need to retrain your model using the suggested settings.
