### ISSUE TITLE
When using accelerate+deepspeed to accelerate the code does not work

### ISSUE THREAD

**Issue by githubwqj** [huggingface/peft#2060]
### System Info

The classes used are examples/sft/train.py and examples/sft/run_peft_qlora_deepspeed_stage3.sh
When we use fixed parameters ,

Let's comment out the following two lines in def `__main__`
```python
    parser = HfArgumentParser((ModelArguments, DataTrainingArguments, TrainingArguments))

    model_args, data_args, training_args = parser.parse_args_into_dataclasses()
```
![1726037303362](https://github.com/user-attachments/assets/b9526674-7a18-41a5-9db5-061389db6a4d)

or TrainingArguments not use in HfArgumentParser
Then an exception will appear and Parameters should be loaded to both Gpus, but instead all parameters are loaded to the same gpu, causing CUDA to be out of memory
![1726037211812](https://github.com/user-attachments/assets/2e097ef2-a424-4454-b575-02c4a4fb4ef5)

But I added the following two lines to the code. They don't need to be referenced, just added
![1726037431501](https://github.com/user-attachments/assets/06a04d1c-fdb8-43f9-a74c-6e74ee2f2816)
accelerate+deepspeed will also work

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

https://github.com/huggingface/peft/blob/main/examples/sft/train.py
in this file 👍Please comment out,then The main function takes none as an argument,We also need to fix the train.py and untils.py arguments
![1726037303362](https://github.com/user-attachments/assets/b9526674-7a18-41a5-9db5-061389db6a4d)
   `parser = HfArgumentParser((ModelArguments, DataTrainingArguments, TrainingArguments))` in the `__main__` function
https://github.com/huggingface/peft/blob/main/examples/sft/run_peft_qlora_deepspeed_stage3.sh

### Expected behavior

Running code at accelerate+deepspeed incorrectly aggregates operations from multiple Gpus into a single GPU, resulting in OOM
Hopefully this bug will be fixed

**Comment by githubwqj** [comment]
Running code at accelerate+deepspeed incorrectly aggregates operations from multiple Gpus into a single GPU, resulting in OOM
**Expected behavior**:
Hopefully this bug will be fixed

**Comment by githubwqj** [comment]
Annotated all the following lines of code 
before
<img width="661" alt="1726066480392" src="https://github.com/user-attachments/assets/4a5757b6-884b-4558-a367-1afadc1baca6">
after
<img width="692" alt="1726066608575" src="https://github.com/user-attachments/assets/023acbb6-b429-465e-a677-12ac4b077844">

This is to repeat the mistakes I made,

**Comment by githubwqj** [comment]
That is, when all my parameters are fixed in the code, there is no need to pass through the script, that is, there is no need to go through the following two lines of code logic
parser = HfArgumentParser((ModelArguments, DataTrainingArguments, TrainingArguments))
model_args, data_args, training_args = parser.parse_args_into_dataclasses()
Using accelerate+deepspped will cause oom error

**Comment by BenjaminBossan** [comment]
So if I understand you correctly, for your use case, you don't want to use `HfArgumentParser` because all parameters are fixed. However, when you comment it out, you get an error because some initialization within accelerate is missing. Therefore, you want to add the line with `PartialState().process_index`, is my understanding correct?

You are correct that `HfArgumentParser` indirectly initiates the accelerate `PartialState`, which is quite surprising and something that I have encountered in the past too. I don't think that `process_index` is needed. Could you please check if calling just `PartialState()` is sufficient?

Also, this issue no longer happened to me after some time. I think there was a fix in accelerate or bitsandbytes or transformers. So could you please upgrade these libraries and check if the issue disappears?

**Comment by githubwqj** [comment]
Thank you for your suggestion. I will try to adjust the accelerate or bitsandbytes or transformers version

**Comment by BenjaminBossan** [comment]
Great, please report back when you have results.
