### ISSUE TITLE
how to use peft at torch <=1.12.1 and CUDA <= 10.2 envrionment

### ISSUE THREAD

**Issue by cqfxchina** [huggingface/peft#207]
I found the peft  requirement torch >=1.13.0 .
how to use peft at torch <=1.12.1 and CUDA <= 10.2 envrionment

**Comment by chuckhope** [comment]
mmmmmmmmmm also found this problem

**Comment by squall1988** [comment]
same problem

**Comment by mohcineelharras** [comment]
same

**Comment by derrickcyt** [comment]
same

**Comment by armstrong1972** [comment]
pip install peft --no-dependencies

**Comment by armstrong1972** [comment]
> I found the peft requirement torch >=1.13.0 . how to use peft at torch <=1.12.1 and CUDA <= 10.2 envrionment

pip install peft --no-dependencies

**Comment by adeepak7** [comment]
Please re-open the issue

**Comment by JINGTINGSHAN5** [comment]
Have you seccussfullly solved the program?

**Comment by armstrong1972** [comment]
Yes

 

 

Armstrong Li

Founder & CEO , ArtCube VR Co. Ltd.

Mobile : 186-1835-2693

Email :  ***@***.***> ***@***.***

Web :  <http://www.artcubevr.com/> https://www.artcubevr.com

 

 

 

发件人: JINGTINGSHAN5 ***@***.***> 
发送时间: 2023-12-17 14:58
收件人: huggingface/peft ***@***.***>
抄送: Armstrong Li ***@***.***>; Comment ***@***.***>
主题: Re: [huggingface/peft] how to use peft at torch <=1.12.1 and CUDA <= 10.2 envrionment (Issue #207)

 

Have you seccussfullly solved the program?

**Comment by deema-A** [comment]
I am not able to upgrade torch form 1.12.1 and wondering if any got this fixed?

**Comment by Doommmmmmmmmmm** [comment]
> > I found the peft requirement torch >=1.13.0 . how to use peft at torch <=1.12.1 and CUDA <= 10.2 envrionment
> 
> pip install peft --no-dependencies

the RAM cost is same as that I don't use peft

**Comment by lemon1-ui** [comment]
@armstrong1972  how to resolve it ? My python version is 3.7, torch is 1.12.0, cuda is 11.4, is there any other way to fix this besides upgrading the python version?

**Comment by armstrong1972** [comment]
> @armstrong1972 how to resolve it ? My python version is 3.7, torch is 1.12.0, cuda is 11.4, is there any other way to fix this besides upgrading the python version?

pip install peft --no-dependencies 
I runed upper command success in Apr  2023

**Comment by lemon1-ui** [comment]
@armstrong1972  I ran the above command, but I still got the following error：ImportError: cannot import name ‘Literal’ from ‘typing’ (PYTHON_HOME\lib\typing.py

**Comment by armstrong1972** [comment]
> @armstrong1972 I ran the above command, but I still got the following error：ImportError: cannot import name ‘Literal’ from ‘typing’ (PYTHON_HOME\lib\typing.py

https://deepinout.com/python/python-qa/683_python_importerror_cannot_import_name_literal_from_typing.html

**Comment by lemon1-ui** [comment]
@armstrong1972 Thank you very much, I tried this method and still got an error, my code does not directly import Literal, Instead, from peft import LoraConfig,get_peft_model, prepare_model_for_kbit_training, set_peft_model_state_dict

**Comment by armstrong1972** [comment]
> @armstrong1972 Thank you very much, I tried this method and still got an error, my code does not directly import Literal, Instead, from peft import LoraConfig,get_peft_model, prepare_model_for_kbit_training, set_peft_model_state_dict

Upgrade your python to 3.8

**Comment by BenjaminBossan** [comment]
Notice that both Python 3.7 and 3.8 are past their end of life and are thus no longer supported by PEFT. Please upgrade to Python 3.9 or higher (this is also important for security reasons, as the older Python versions don't get any security patches anymore).
