### ISSUE TITLE
contrastive search and do_sampling

### ISSUE THREAD

**Issue by imrankh46** [huggingface/peft#209]
I trained bloom17b but  for inference they not support both _**contrastive search**_ and _**do_sample**_ parameters

The out put are repeating the text 

Here are the code

```
batch = tokenizer(" څوک د زړه ", return_tensors='pt')

max_length = 200
temperature = 0.5
top_k = 10
top_p = 0.95
do_sample = True
with torch.cuda.amp.autocast():
    # Pass the additional parameters to the model.generate() function
    output_tokens = model.generate(input_ids=batch["input_ids"],
                                   attention_mask=batch['attention_mask'],
                                   max_length=max_length,
                                   temperature=temperature,
                                   top_k=top_k,
                                   top_p=top_p,repetition_penalty=1.03,
                                   #penalty_alpha=0.6,
                                   #do_sample=do_sample
                                   )

    print("\n\n", tokenizer.decode(output_tokens[0], skip_special_tokens=True))
```
And the output

![Screenshot_20230323-151456](https://user-images.githubusercontent.com/103720343/227173773-23f553b3-59a2-43e0-a0a5-d9893f9c1376.png)

**Comment by dukesun99** [comment]
Does a non-peft version work? Perhaps the generation parameters are not compatible with each other. You may check different decoing methods [here](https://huggingface.co/docs/transformers/main_classes/text_generation). 

It seems contrastive search has the highest priority (at this moment) according to [this part of code](https://github.com/huggingface/transformers/blob/e8cc02555ee7dce7213e624ab088d8d4d1952064/src/transformers/generation/utils.py#L1333). And `contrastive_search` only takes `top_k` and `penalty_alpha` as in [here](https://github.com/huggingface/transformers/blob/e8cc02555ee7dce7213e624ab088d8d4d1952064/src/transformers/generation/utils.py#L1687).

**Comment by imrankh46** [comment]
> Does a non-peft version work? Perhaps the generation parameters are not compatible with each other. You may check different decoing methods [here](https://huggingface.co/docs/transformers/main_classes/text_generation).
> 
> It seems contrastive search has the highest priority (at this moment) according to [this part of code](https://github.com/huggingface/transformers/blob/e8cc02555ee7dce7213e624ab088d8d4d1952064/src/transformers/generation/utils.py#L1333). And `contrastive_search` only takes `top_k` and `penalty_alpha` as in [here](https://github.com/huggingface/transformers/blob/e8cc02555ee7dce7213e624ab088d8d4d1952064/src/transformers/generation/utils.py#L1687).

Its work for do_sample but not contrastive search. They show me cuda out of memory.
