### ISSUE TITLE
How to use multiple lora at the same time for text generation?

### ISSUE THREAD

**Issue by fangqiang817** [huggingface/peft#211]
I have many lora models,For example: 
funny lora, Ultraman style lora ...
how to use them at the same time, and can adjust the weight between lora.
Similar to stable diffusion.

**Comment by dukesun99** [comment]
It seems #133 is implementing this feature.

**Comment by fangqiang817** [comment]
> It seems #133 is implementing this feature.

Thank you for your reply.😀
#133  is a great job, But I want to use multiple lora when predicting, rather than training, **and can adjust the weights of different LORAs.**
It doesn't seem to have been resolved

**Comment by raihan0824** [comment]
> I have many lora models,For example: funny lora, Ultraman style lora ... how to use them at the same time, and can adjust the weight between lora. Similar to stable diffusion.

did you manage to get the answer for this?

**Comment by NoUnique** [comment]
https://github.com/sabetAI/BLoRA
