### ISSUE TITLE
Request to Include Named Entity Recognition and Relation Extraction Model Finetuning Examples and Guidance Request 

### ISSUE THREAD

**Issue by HarikrishnanK9** [huggingface/peft#2119]
### Feature request

As an NLP enthusiast working on Named Entity Recognition (NER) and Relation Extraction (RE) tasks, I would like to request the inclusion of NER and RE-related  examples, best practices, and **guidance for fine-tuning** models specifically for these tasks on your GitHub page.
The documentation on fine-tuning models for NER and RE would help guide researchers in developing state-of-the-art models without having to reinvent the wheel.Currently Finetuning examples for NER and RE tasks are not available there.These techniques have relevance in identifying technical terms,chemical names,etc from texts and recognize the relationship between identified domain specified technical terms.

### Motivation

ner models are critical in various technologies to identify particular domain related words from an input text,Especially if we are dealing with business terms,chemical names,particle names,and other domain specific technical terms.2nd importance is identify the relation between identified entities.Eg: sentence:Apple acquired Beats for $3 billion in 2014;Entities:Apple, Beats, $3 billion,2014;Relation:acquired

### Pre-requisite

First there must be an appropriate dataset for finetuning, including 1)sentences,2)entities corresponding to that sentence in next column and 3)finally relation between identified entities.Dataset must include diverse domain specific datas like finance,medical,chemical,news,politics,etc then only a general kind of model can identify entities generally.If the purpose is domain specific then particulr domain specific dataset is a must.

**Comment by BenjaminBossan** [comment]
I agree that having such examples could be useful for many users. If you have an existing example that uses full fine-tuning that we can take as a starting point, that would be very helpful. I also added a call for contribution tag so that hopefully someone from the community with expertise on this topic can step in.

**Comment by JINO-ROHIT** [comment]
Hi guys, Im happy to take this up, but do we have any example guidelines? Like should we open a seperate folder and should it be a jupyter notebook or py scripts?

**Comment by BenjaminBossan** [comment]
Thanks a lot for offering to work on this @JINO-ROHIT.

There is no specific template we expect from examples. If you check the `examples` directory, you'll see it's a bit chaotic. I would suggest to add either a script or notebook (whatever you like most) to the `examples/token_classification` directory (as NER would be considered "token classification").

As a dataset, I know that [conll](https://huggingface.co/datasets/eriktks/conll2003) is used for NER but maybe there is a better dataset by now or @HarikrishnanK9 has something else in mind.

As to the PEFT method, probably LoRA would be a good start.

**Comment by JINO-ROHIT** [comment]
gotcha, im on it

**Comment by HarikrishnanK9** [comment]
@JINO-ROHIT @BenjaminBossan Apologies for the delayed response. Over the past few days, I’ve been exploring NER and Relation Extraction (RE), fine-tuning, along with codes and datasets on platforms like Kaggle and various GitHub repositories.Unfortunately, I wasn’t able to complete it as planned ,Anyway I’m happy to hear that @JINO-ROHIT  is also ready to take over the task. If I succeed with any of the codes, I will share it with you immediately.

**Comment by JINO-ROHIT** [comment]
Hey @HarikrishnanK9 have a look at the PR and let us know if this is something along the lines you were looking for.
