### ISSUE TITLE
Very Slow Inference on PEFT-LORA fine-tunned FLAN-UL2

### ISSUE THREAD

**Issue by TejaGollapudi** [huggingface/peft#217]
Thanks to PEFT-LORA I was able to fine-tune a 20B FLAN-UL2 model. 

I'm running inference on 3x v100 GPUs with full precision (not bf16 or fp16)

When I use model.generate() with the PEFT-Model it is about 10 times slower. 

```
BASE_MODEL = google/flan-ul2
model =  T5ForConditionalGeneration.from_pretrained(BASE_MODEL, device_map="auto")

FINE_TUNED_MODEL_PEFT = 'finetunnedmodel-peft-path/' # contains adapter_model.bin, adapter_config.json
model = PeftModel.from_pretrained(model, FINE_TUNED_MODEL_PEFT, device_map="auto")
```

I generate the model outputs for both using: 

` output= model.generate(input_id, max_new_tokens= 256)`

Is it expected to be that much slower? Are there methods for me to improve the inference speed of LORA models? 

Thank you

Edit: 

adapter_config.json

{
  "base_model_name_or_path": "google/flan-ul2",
  "bias": "none",
  "enable_lora": null,
  "fan_in_fan_out": false,
  "inference_mode": true,
  "lora_alpha": 32,
  "lora_dropout": 0.1,
  "merge_weights": false,
  "modules_to_save": null,
  "peft_type": "LORA",
  "r": 8,
  "target_modules": [
    "q",
    "v"
  ],
  "task_type": "SEQ_2_SEQ_LM"
}

**Comment by younesbelkada** [comment]
Hi @TejaGollapudi !
I believe that you can merge the Lora weights into the Flan-UL2 model and load it as a standalone model from `transformers`. Let us know if you need any pointer on this
Here is an example on how it is done for `gpt-neo-20b`: https://github.com/lvwerra/trl/blob/main/examples/sentiment/scripts/gpt-neox-20b_peft/merge_peft_adapter.py

**Comment by johnrobinsn** [comment]
@TejaGollapudi 
any script you can share for fine-tuning Flan-UL2 with peft/lora?  any tips/tricks?

Thanks Much

**Comment by rsilveira79** [comment]
I'm also interested in Finetuning Flan UL2, if we can share results/notebooks here it will be great! 
@TejaGollapudi let us know when you have the script released. 

Just out of curiosity, did you got good results in evaluation with this fine tuning?

**Comment by TejaGollapudi** [comment]
@johnrobinsn @rsilveira79  Sorry for the delay 😅. 

I put the code together at
[Efficient Instruction Fine-tuning of Flan-UL2 (20B LLM) Using LoRA with Limited Compute](https://medium.com/vmware-data-ml-blog/lora-finetunning-of-ul-2-and-t5-models-35a08863593d)

I partition the code into github gist files and put them into that article. Hopefully, it's useful.  I wanted to get the code out sooner in a git repo but that would take me a lot longer to get the clearance. 

Please feel free to reach out if you have any issues with the code. Thanks!

**Comment by younesbelkada** [comment]
Awesome article @TejaGollapudi ! Thanks for bringing this up !

**Comment by daramos** [comment]
FYI to anyone looking at this, #227 added a merge_and_unload function so the above code isn't necessary anymore.

`model = model.merge_and_unload()` should be all you need now to merge the model.

**Comment by rsilveira79** [comment]
Awesome thanks so much @TejaGollapudi 👏

**Comment by dhairyadalal** [comment]
If the base model is loaded in 8-bit model, merge_and_unload() throws an error `merge and unload not supported with 8-bit models`. Any suggestions on how to improve inference speed with this use case where the model has been finetuned with w/t 8-bit?

```
from peft import LoraConfig, TaskType, get_peft_model, PeftModelForSeq2SeqLM
from peft import LoraConfig, get_peft_model, prepare_model_for_int8_training, TaskType

# Load model w/ 8-bit quantization.
model = AutoModelForSeq2SeqLM.from_pretrained(
    config["alias"],
    device_map="auto",
    load_in_8bit=True
)

# Define LoRA Config
lora_config = LoraConfig(
 r=16,
 lora_alpha=32,
 target_modules=["q", "v"],
 lora_dropout=0.05,
 bias="none",
 task_type=TaskType.SEQ_2_SEQ_LM
)

# prepare int-8 model for training
model = prepare_model_for_int8_training(model)

# add LoRA adaptor
model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

.... [training]
model = model.merge_and_unload()
```
`ValueError: Cannot merge LORA layers when the model is loaded in 8-bit mode`

**Comment by younesbelkada** [comment]
Hi @dhairyadalal 
In this case you should load the base model in `float16`, merge the LoRA weights, save the new model somewhere and load it back in 8bit

**Comment by dhairyadalal** [comment]
> Hi @dhairyadalal In this case you should load the base model in `float16`, merge the LoRA weights, save the new model somewhere and load it back in 8bit

@younesbelkada Thanks for the followup. Just so I understand, you're suggesting the following training process right? :
1. Load base model in 8-bit and create LoRA weights
2. Finetune the LoRA weights 
3. Elsewhere load base model in float16 and cache
4. Merge the LoRA weights w/ cached float16 model

Another dumb question. How I do load a HF model in float16? Is there a similar flag to `load_in_8bit`?

Thanks!

**Comment by ereday** [comment]
> Hi @dhairyadalal In this case you should load the base model in `float16`, merge the LoRA weights, save the new model somewhere and load it back in 8bit

Hi @younesbelkada , I've finetuned flan-ul2 model using LoRA ( on 8x v100 GPUs with full precision (not bf16 or fp16)) and I'm having problems with 8bit inference. (I could run inference with Float32 precision both on CPU and GPU, though).  I'm trying to do what you recommended here.

```
## Load base model on float16
base_model_id='google/flan-ul2'
model = AutoModelForSeq2SeqLM.from_pretrained(base_model_id,device_map='auto',torch_dtype=torch.float16)

## Merge lora weights and base model weights
peft_model_id='/home/ubuntu/user/flanul2_lora/alpaca_ul2_lora_v2/2'
model = PeftModel.from_pretrained(model, peft_model_id)

## save it somewhere else. This last operation creates `adapter_config.json` and `adapter_model.pt` files under `flan_ul2_lora_v2_saved_somewhere_else` only. 
model.save_pretrained('flan_ul2_lora_saved_somewhere_else')

```
Now, I open another python interpreter and reload the model and lora adapter weights as follows:

```
## Load base model in 8bit
model = AutoModelForSeq2SeqLM.from_pretrained(base_model_id,load_in_8bit=True,device_map='auto')

## Merge lora weights and base model weights (Note that I load the latest saved model)
peft_model_id='/home/ubuntu/user/flan_ul2_lora_saved_somewhere_else'
model = PeftModel.from_pretrained(model, peft_model_id)
model.eval()
```

Next, I try to model.generate() as follows:

```
prompt_template = "Below is an instruction that describes a task. Write a response that appropriately completes the request.\n\n### Instruction:\n{instruction}\n\n### Response:"
prompt = "Draft me an introduction section of a medium article on the topic 'Efficient Fine-tuning of UL-2 and T5 Models Using LoRA on Limited Compute"
input = prompt_template.format(instruction=prompt)

input_ids = tokenizer(input, return_tensors="pt", truncation=True).input_ids.cuda()
# with torch.inference_mode():
outputs = model.generate(input_ids=input_ids,max_new_tokens=128)
```
Unfortunately, this gives me `'NoneType' object has no attribute 'to'` error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/miniconda3/envs/lora_training/lib/python3.8/site-packages/peft/peft_model.py", line 744, in generate
    return self.base_model.generate(**kwargs)
  File "/home/ubuntu/miniconda3/envs/lora_training/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/lora_training/lib/python3.8/site-packages/transformers/generation/utils.py", line 1268, in generate
    model_kwargs = self._prepare_encoder_decoder_kwargs_for_generation(
  File "/home/ubuntu/miniconda3/envs/lora_training/lib/python3.8/site-packages/transformers/generation/utils.py", line 634, in _prepare_encoder_decoder_kwargs_for_generation
    model_kwargs["encoder_outputs"]: ModelOutput = encoder(**encoder_kwargs)
  File "/home/ubuntu/miniconda3/envs/lora_training/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/lora_training/lib/python3.8/site-packages/transformers/models/t5/modeling_t5.py", line 1074, in forward
    layer_outputs = layer_module(
  File "/home/ubuntu/miniconda3/envs/lora_training/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/lora_training/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/lora_training/lib/python3.8/site-packages/transformers/models/t5/modeling_t5.py", line 693, in forward
    self_attention_outputs = self.layer[0](
  File "/home/ubuntu/miniconda3/envs/lora_training/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/lora_training/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/lora_training/lib/python3.8/site-packages/transformers/models/t5/modeling_t5.py", line 600, in forward
    attention_output = self.SelfAttention(
  File "/home/ubuntu/miniconda3/envs/lora_training/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/lora_training/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/lora_training/lib/python3.8/site-packages/transformers/models/t5/modeling_t5.py", line 519, in forward
    query_states = shape(self.q(hidden_states))  # (batch_size, n_heads, seq_length, dim_per_head)
  File "/home/ubuntu/miniconda3/envs/lora_training/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/lora_training/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/lora_training/lib/python3.8/site-packages/peft/tuners/lora.py", line 502, in forward
    result = super().forward(x)
  File "/home/ubuntu/miniconda3/envs/lora_training/lib/python3.8/site-packages/bitsandbytes/nn/modules.py", line 320, in forward
    out = bnb.matmul(x, self.weight, bias=self.bias, state=self.state)
  File "/home/ubuntu/miniconda3/envs/lora_training/lib/python3.8/site-packages/bitsandbytes/autograd/_functions.py", line 500, in matmul
    return MatMul8bitLt.apply(A, B, out, bias, state)
  File "/home/ubuntu/miniconda3/envs/lora_training/lib/python3.8/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/ubuntu/miniconda3/envs/lora_training/lib/python3.8/site-packages/bitsandbytes/autograd/_functions.py", line 410, in forward
    output = torch.nn.functional.linear(A_wo_outliers, state.CB.to(A.dtype))
AttributeError: 'NoneType' object has no attribute 'to'
```

Do you have any idea how I can do 8bit inference with a lora finetuned model?

**Comment by Praful932** [comment]
> Hi @dhairyadalal In this case you should load the base model in `float16`, merge the LoRA weights, save the new model somewhere and load it back in 8bit

Thanks this is useful

I have finetuned a flan-t5-large model in 8bit and compared predictions and latency number before and after. 
1. There is not a huge delta with the inference before and after merging, after merging the inference is a bit slow but comparable
2. With the same settings, predictions on the test set of both of these model differ by some phrases, Is this expected? - I tested this by loading the base model in both float16 & 32 in the first step

**Comment by vTuanpham** [comment]
So does that mean that if i want to eval every epoch, i would have to merge the lora adapter and run the model.generate ?

**Comment by allanj** [comment]
> So does that mean that if i want to eval every epoch, i would have to merge the lora adapter and then run the model.generate at every epoch?

I have the same concern. But I don't think `merge_and_unload` after each epoch would be the solution as it seems quite expensive.

What I'm doing is to evaluate the loss (but not generation) only during training.

**Comment by vTuanpham** [comment]
> > So does that mean that if i want to eval every epoch, i would have to merge the lora adapter and then run the model.generate at every epoch?
> 
> I have the same concern. But I don't think `merge_and_unload` after each epoch would be the solution as it seems quite expensive.
> 
> What I'm doing is to evaluate the loss (but not generation) only during training. 

What I'm doing is model.generate a small selected samples for manual evaluation (10-20 examples) and a large separate dataloader for perplexity  evaluation. 10-20 examples still very slow though. And you are right, merge_and_unload is not the way to go

**Comment by allanj** [comment]
for PPL, you just need forward, I don't think you need to call the `generate` function

**Comment by StarLooo** [comment]
> for PPL, you just need forward, I don't think you need to call the `generate` function

Thank you. May I explain it like this:
In evaluation, the forward() function is only called once for each eval batch.
But in generation, the forward() function will be called many times for each inference batch, and that means a lot of additional cost for unmerged LoRA weights, and thus we need do merge_and_unload() before generation.
