### ISSUE TITLE
Pipeline 'text-generation' support when?

### ISSUE THREAD

**Issue by gururise** [huggingface/peft#218]
Any plans for adding support to pipeline?

```
pipe = pipeline(
    "text-generation",
    model=model, # model is PeftModel.from_pretrained()
    tokenizer=tokenizer, 
    max_length=256,
    temperature=0.6,
    top_p=0.95,
    repetition_penalty=1.2
)
```

`The model 'PeftModelForCausalLM' is not supported for text-generation. Supported models are ['BartForCausalLM', 'BertLMHeadModel', 'BertGenerationDecoder', 'BigBirdForCausalLM', 'BigBirdPegasusForCausalLM', 'BioGptForCausalLM', 'BlenderbotForCausalLM', 'BlenderbotSmallForCausalLM', 'BloomForCausalLM', 'CamembertForCausalLM', 'CodeGenForCausalLM', 'CTRLLMHeadModel', 'Data2VecTextForCausalLM', 'ElectraForCausalLM', 'ErnieForCausalLM', 'GitForCausalLM', 'GPT2LMHeadModel', 'GPT2LMHeadModel', 'GPTNeoForCausalLM', 'GPTNeoXForCausalLM', 'GPTNeoXJapaneseForCausalLM', 'GPTJForCausalLM', 'LlamaForCausalLM', 'MarianForCausalLM', 'MBartForCausalLM', 'MegatronBertForCausalLM', 'MvpForCausalLM', 'OpenAIGPTLMHeadModel', 'OPTForCausalLM', 'PegasusForCausalLM', 'PLBartForCausalLM', 'ProphetNetForCausalLM', 'QDQBertLMHeadModel', 'ReformerModelWithLMHead', 'RemBertForCausalLM', 'RobertaForCausalLM', 'RobertaPreLayerNormForCausalLM', 'RoCBertForCausalLM', 'RoFormerForCausalLM', 'Speech2Text2ForCausalLM', 'TransfoXLLMHeadModel', 'TrOCRForCausalLM', 'XGLMForCausalLM', 'XLMWithLMHeadModel', 'XLMProphetNetForCausalLM', 'XLMRobertaForCausalLM', 'XLMRobertaXLForCausalLM', 'XLNetLMHeadModel', 'XmodForCausalLM'].`

**Comment by katossky** [comment]
As a work around :

```
pipeline = pipeline(model = base_model)
pipeline.model = PeftModel.from_pretrained(model = base_model, ...)
```

... seems to work.

**Comment by pacman100** [comment]
Hello @katossky, thank you for the neat way of getting this to work, however, that would only work for LoRA method.  

Pipelines should already work, but instead of `pipeline` function, you need to call the corresponding pipeline class. See the example here using the ASR PIpleine: https://github.com/huggingface/peft/blob/main/examples/int8_training/peft_bnb_whisper_large_v2_training.ipynb

<img width="976" alt="Screenshot 2023-04-18 at 3 48 06 PM" src="https://user-images.githubusercontent.com/13534540/232747679-8cb8b0af-3fac-4170-b2bd-433ffade6ff8.png">

**Comment by waterluck** [comment]
@katossky @tuanio Hi, can you provide a sample on this solution?
I have origin llamamodel, and peft-lora finetuned llamamodel , and still get error not support for text generation, when using pipeline.

**Comment by steveepreston** [comment]
Still getting this warning in latest version

**Comment by steveepreston** [comment]
Still getting this warning in latest version

transformers: 4.48.0
peft: 0.14.0
