### ISSUE TITLE
”peft_prefix_tuning_seq2seq.ipynb“RuntimeError Due to Tensor Dimension Mismatch

### ISSUE THREAD

**Issue by 1hb6s7t** [huggingface/peft#2192]
### System Info

System Info
transformers version: 4.46.0
Platform: windows11
Python version: 3.9.
PyTorch version (GPU?): 2.4.0+cu124

Encountered a RuntimeError while trying to perform forward propagation with a BloomForCausalLM model from the transformers library. The error occurs when attempting to concatenate tensors in DynamicCache.update(). Specifically, the error message is: 
RuntimeError: Tensors must have same number of dimensions: got 3 and 4
![屏幕截图 2024-10-31 202640](https://github.com/user-attachments/assets/5081d379-6b14-488f-9301-16dffd354a48)

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

While executing the 'peft_prefix_tuning_seq2seq.ipynb' file, an error occurred in the image. What is the problem?

### Expected behavior

How to solve this problem？

**Comment by JINO-ROHIT** [comment]
Hi @1hb6s7t im not able to replicate your issue. I ran the example notebook on colab and it works fine - https://colab.research.google.com/drive/1m56jHOgFcSSoTiwNns8cdViXwhLmXxvz?usp=sharing

Can you try this maybe?

**Comment by BenjaminBossan** [comment]
To add, please try the latest versions of transformers and PEFT (i.e. installed from source), as we had a couple fixes lately.
