### ISSUE TITLE
Memory Inefficiency for LoRA & DoRA during fine-tuning.

### ISSUE THREAD

**Issue by gslama12** [huggingface/peft#2196]
I applied LoRA and DoRA to a ResNet-50 and noticed, that the memory needed for storing activations during fine-tuning almost doubles compared to full fine-tuning. As this is the main contributor to the memory consumption, this is concerning and it seems unnecessary. What could be done here?

Here are some profiling results from the ResNet-50 under batch size 16 :

**FFT:**
| Device | _MemRefType.PARAM | _MemRefType.BUFFER | _MemRefType.GRAD | _MemRefType.ACT | _MemRefType.TEMP | _MemRefType.OPT | _MemRefType.OTH | Total       |
|--------|--------------------|--------------------|-------------------|-----------------|------------------|-----------------|-----------------|-------------|
| cpu    | 89.68 MiB          | 0.2 MiB           | 89.68 MiB         | 1310.95 MiB     | 12.25 MiB        | 179.37 MiB      | 0.0 MiB         | 1682.14 MiB |

**LORA:**
`trainable params: 317,772 || all params: 23,827,853 || trainable%: 1.3336`
| Device | _MemRefType.PARAM | _MemRefType.BUFFER | _MemRefType.GRAD | _MemRefType.ACT | _MemRefType.TEMP | _MemRefType.OPT | _MemRefType.OTH | Total       |
|--------|--------------------|--------------------|-------------------|-----------------|------------------|-----------------|-----------------|-------------|
| cpu    | 90.9 MiB           | 0.2 MiB           | 1.21 MiB          | 2618.32 MiB     | 12.25 MiB        | 2.42 MiB        | 0.0 MiB         | 2725.3 MiB  |

**DORA:**
`trainable params: 344,332 || all params: 23,854,413 || trainable%: 1.4435`

| Device | _MemRefType.PARAM | _MemRefType.BUFFER | _MemRefType.GRAD | _MemRefType.ACT | _MemRefType.TEMP | _MemRefType.OPT | _MemRefType.OTH | Total       |
|--------|--------------------|--------------------|-------------------|-----------------|------------------|-----------------|-----------------|-------------|
| cpu    | 91.0 MiB           | 0.2 MiB           | 1.31 MiB          | 3963.04 MiB     | 30.63 MiB        | 2.63 MiB        | 0.0 MiB         | 4088.82 MiB |

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

## Requirements
The memory profiler from [here]( https://github.com/pytorch/pytorch/blob/main/torch/distributed/_tools/mem_tracker.py ) (should be available in torch.distributed._tools.mem_tracker in the 2.5.1 release).

## Profiling Code
```
import torch
import argparse
from torch.distributed._tools.mem_tracker import MemTracker
from peft import LoraConfig, get_peft_model

device, dtype = torch.device("cpu"), torch.float32

with torch.device(device):
    # adapt model to 2 output classes
    model = torch.hub.load('pytorch/vision:v0.10.0', 'resnet50', pretrained=True)
    num_features = resnet.fc.in_features
    model.fc = nn.Linear(num_features, 1, bias=True)
    optim = torch.optim.AdamW(self._model.parameters(), lr=0.0001)
    model.train()

    # for lora use this
    #lora_config = LoraConfig(
    #    r=4,
    #    target_modules=get_lora_compatible_layer_names(self._model, 8),
    #    bias="none",
    #    inference_mode=False,
    #    lora_alpha=4,
    #    lora_dropout=0.1
    #)
    #model = get_peft_model(self._model, lora_config)
    #model.print_trainable_parameters()


mem_tracker = MemTracker()
mem_tracker.track_external(model, optim)

with (mem_tracker as mt):
    for i in range(2):
        inp = torch.randn(batch_size, 3, 224, 224, device=device, dtype=dtype)
        out = model(inp)
        loss = out.sum()
        loss.backward()
        optim.step()
        if i == 0:
            mt.reset_mod_stats()  # to account for lazy init of optimizer state

mt.display_snapshot("peak", units="MiB", tabulate=True)
```

### Expected behavior

I would expect the activation memory to be smaller, because the only activations that are actually needed during the backward pass are the ones form the trainable low-rank matrices (in case of LoRA).

**Comment by BenjaminBossan** [comment]
Hi @gslama12 I only skimmed the reported issue. Could you quickly explain why you closed the issue, should this be investigated?

**Comment by gslama12** [comment]
I temporarily closed this as I am currently investigating this further and the results might change. I will re-open it with more concrete results once I am finished. So far it seems like there is a memory overhead during training compared to the original LoRA implementation from [here](https://github.com/microsoft/LoRA) when it comes to activation memory. I will show further evidence once i have tried different models/profilers to verify the results.

**Comment by BenjaminBossan** [comment]
All right, thanks a lot.
