### ISSUE TITLE
Error of watchdog when dreambooth training on multiple GPUs

### ISSUE THREAD

**Issue by THULiusj** [huggingface/peft#220]
Hi, when I tried to train dreambooth lora on two T4, I just made accelerate config default to automatically detect the two GPUs.

And when the training was running, an error occured: **"Watchdog caught collective operation timeout: WorkNCCL(SeqNum=128, OpType=BROADCAST, Timeout(ms)=1800000) ran for 1808160 milliseconds before timing out."**

It seems an error from Accelerate. Anyone knows the reason?

**Comment by Az0nik** [comment]
Your processor calculeit to fast. He give answer, but stil noubady ask...?

**Comment by Az0nik** [comment]
Not innaf calculeit time. Becos reel time more then timeout.
