### ISSUE TITLE
Instruction-FT chatGLM with LORA and Chinese self-instruct data

### ISSUE THREAD

**Issue by vxfla** [huggingface/peft#221]
We have tried fine-tuning chatGLM , an awesome dialogue model aligned with human preference, with LORA.
I think it indeed learns from new datas.

https://github.com/27182812/ChatGLM-chinese-insturct

**Comment by pacman100** [comment]
Hello @vxfla, this is awesome! 🚀✨🤗
Thank you for sharing!
