### ISSUE TITLE
tp_layer.py lora_a,b init_method is different from the method in lora paper

### ISSUE THREAD

**Issue by aeeeeeep** [huggingface/peft#2228]
### System Info

peft: latest

### Who can help?

@zhangsheng37

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

https://github.com/huggingface/peft/blob/main/src/peft/tuners/lora/tp_layer.py#L125-L145

### Expected behavior

I think the init_method of lora a,b layer in tp_layer.py should be as follows

```python
            if self.is_parallel_a:
                lora_a = self.backend.RowParallelLinear(
                    input_size=self.in_features,
                    output_size=r,
                    bias=False,
                    input_is_parallel=input_is_parallel,
                    skip_bias_add=True,
                    init_method=init_method,
                    config=megatron_config,
                )
                lora_b = nn.Linear(in_features=r, out_features=self.out_features, bias=False, dtype=torch.float32)
                torch.nn.init.zeros_(lora_b.weight.data)
            else:
                lora_a = nn.Linear(in_features=self.in_features, out_features=r, bias=False, dtype=torch.float32)
                init_method(lora_a.weight.data)
                lora_b = self.backend.ColumnParallelLinear(
                    input_size=r,
                    output_size=self.out_features,
                    bias=False,
                    gather_output=gather_output,
                    init_method=torch.nn.init.zeros_,
                    config=megatron_config,
                )
```

because it is mentioned in paper
"""
We use a random Gaussian initialization for A and zero for B
"""

the logic should be the same as in the [peft/tuners/lora/layer.py#L157-L166](https://github.com/huggingface/peft/blob/main/src/peft/tuners/lora/layer.py#L157-L166)

**Comment by BenjaminBossan** [comment]
It's not quite clear to me what this change would achieve. Note that the initialization scheme for the weights is determined a few lines further below:

https://github.com/huggingface/peft/blob/d9aa0898e4a184464fe012afbf9af7adf0cf70d8/src/peft/tuners/lora/tp_layer.py#L154-L164

The `reset_lora_parameters` method should take care of initializing the weights in the same way as for normal LoRA layers.

**Comment by aeeeeeep** [comment]
Oh! Im so careless
