### ISSUE TITLE
    active_adapter = model.active_adapters[0] TypeError: 'method' object is not subscriptable

### ISSUE THREAD

**Issue by MAXNORM8650** [huggingface/peft#2249]
### System Info

 trainer = Trainer(
        model=model,
        train_dataset=train_data,
        eval_dataset=val_data,
        args=transformers.TrainingArguments(
            per_device_train_batch_size=micro_batch_size,
            gradient_accumulation_steps=gradient_accumulation_steps,
            warmup_steps=100,
            num_train_epochs=num_epochs,
            learning_rate=learning_rate,
            fp16=True,
            logging_steps=10,
            optim="adamw_torch",
            evaluation_strategy="steps" if val_set_size > 0 else "no",
            save_strategy="steps",
            eval_steps=saving_step if val_set_size > 0 else None,
            save_steps=saving_step,
            output_dir=output_dir,
            save_total_limit=1,
            load_best_model_at_end=True if val_set_size > 0 else False,
            ddp_find_unused_parameters=False if ddp else None,
            group_by_length=group_by_length,
            report_to="wandb" if use_wandb else None,
            run_name=wandb_run_name if use_wandb else None,
            label_names=['labels']
        ),
        data_collator=transformers.DataCollatorForSeq2Seq(
            tokenizer, pad_to_multiple_of=8, return_tensors="pt", padding=True
        ),
    )
    model.config.use_cache = False

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

    trainer.train(resume_from_checkpoint=resume_from_checkpoint)

### Expected behavior

I am currently using **peft-0.3.0** and transformers " Version: 4.46.3"

**Comment by BenjaminBossan** [comment]
Since I don't know the whole code, I can't reproduce the error. But given that you use a very old PEFT version (with a very recent transformers version), the best tip is to install a more recent PEFT version and see if it fixes the error. If you still get it, please show enough code to reproduce the error, or at the very least, paste the whole error message.

**Comment by MAXNORM8650** [comment]
Ahh! Thank you for your response, I upgrade to "transformers version: 4.46.3" and peft-0.13.3. It is working.
