### ISSUE TITLE
Is this the right way to check whether a model has been trained as expected?

### ISSUE THREAD

**Issue by qgallouedec** [huggingface/peft#2255]
I'd like to check whether my PEFT model has been trained as intended, i.e. whether the PEFT weights have changed, but not the base weights. The following code works, but I'm sure a PEFT specialist will suggest a better way.

```python
import tempfile

import torch
from datasets import load_dataset
from peft import LoraConfig, get_peft_model
from transformers import AutoModelForCausalLM

from trl import SFTConfig, SFTTrainer


# Get the base model
model_id = "trl-internal-testing/tiny-Qwen2ForCausalLM-2.5"
model = AutoModelForCausalLM.from_pretrained(model_id)

# Get the base model parameter names
base_param_names = [f"base_model.model.{n}" for n, _ in model.named_parameters()]

# Turn the model into a peft model
lora_config = LoraConfig()
model = get_peft_model(model, lora_config)

# Get the dataset
dataset = load_dataset("trl-internal-testing/zen", "standard_language_modeling", split="train")

with tempfile.TemporaryDirectory() as tmp_dir:
    # Initialize the trainer
    training_args = SFTConfig(output_dir=tmp_dir, report_to="none")
    trainer = SFTTrainer(args=training_args, model=model, train_dataset=dataset)

    # Save the initial parameters to compare them later
    previous_trainable_params = {n: param.clone() for n, param in trainer.model.named_parameters()}

    trainer.train()

    # Check the peft params have changed and the base model params have not changed
    for n, param in previous_trainable_params.items():
        new_param = trainer.model.get_parameter(n)
        if n in base_param_names:  # We expect the base model parameters to be the same
            if not torch.allclose(param, new_param):
                print(f"Parameter {n} has changed, but it should not have changed")
        elif "base_layer" not in n:  # We expect the peft parameters to be different (except for the base layer)
            if torch.allclose(param, new_param):
                print(f"Parameter {n} has not changed, but it should have changed")
```

**Comment by BenjaminBossan** [comment]
There is no convenience method to perform a check as you suggested. In fact, your code appears to be something like a unit test, and in PEFT we have unit tests that look pretty close to what you showed.

Normally, I'd say it's not necessary to make these checks (outside of unit testing) since, as a user, I should assume that this basic functionality is working as expected. Do you have a specific reason why want to check this?

**Comment by d-kleine** [comment]
I personally probably would have done it similarly to your logic, but without the `base_model` string check. I would have gone for `param.requires_grad` to get the trainable params (`True`) to return an error if they have not changed, and with `else` if the frozen params (`False`) return an error if they have changed.

**Comment by qgallouedec** [comment]
Thanks guys for your answers.

> your code appears to be something like a unit test
> Do you have a specific reason why want to check this?

That's precisely for unit testing `trl.SFTTrainer`.

> we have unit tests that look pretty close to what you showed.

Could your share a pointer as example? So that I can take it as reference.

> I personally probably would have done it similarly to your logic, but without the `base_model` string check. I would have gone for `param.requires_grad`

That makes sense, but since this is unit testing, I want to be able to catch the case where SFT would mistakenly enforce that the base model requires grad. In other words, I don't want to trust SFT not to modify the model.

**Comment by BenjaminBossan** [comment]
>  I want to be able to catch the case where SFT would mistakenly enforce that the base model requires grad

Great, feel free to ping me on the PR if it's ready.

> Could your share a pointer as example? So that I can take it as reference.

This test should come closest:

https://github.com/huggingface/peft/blob/c05758989d1a1bc650ab1f41fe1de34c88838731/tests/test_custom_models.py#L1058-L1100

But this test is a bit more generalized than what you need, I see no problem with using the code you pasted.

We also have a testing class which specifically checks `requires_grad`, not if the parameter was actually updated:

https://github.com/huggingface/peft/blob/c05758989d1a1bc650ab1f41fe1de34c88838731/tests/test_custom_models.py#L2071

But maybe that's overkill for your purposes.
