### ISSUE TITLE
Problem with loading PEFT model from checkpoint

### ISSUE THREAD

**Issue by sno-ko** [huggingface/peft#2256]
### System Info

- Python v3.10.15
- torch==2.3.0+cu121
- peft==0.13.2
- transformers==4.46.3

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

I used AI to translate Japanese into English, hoping the translation is accurate.

I am attempting to apply Japanese LLMs to a text classification task using various PEFT methods.
I am using the Trainer from the transformers package for training.
However, I'm encountering an issue with prefix-tuning.

As a prerequisite, in prefix-tuning, an additional module called `prompt_encoder` is placed before the LLM to embed virtual tokens as shown below.

![image](https://github.com/user-attachments/assets/f4bdee73-dc9a-4803-9644-bbe38bb9e2d3)

When I tried to load the best model (the model from the epoch with the lowest validation loss during training) from the checkpoint after training, I encountered the following error:

```
...
File xxx/python3.10/site-packages/peft/peft_model.py:1181, in PeftModel.load_adapter(self, model_id, adapter_name, is_trainable, torch_device, autocast_adapter_dtype, ephemeral_gpu_offload, low_cpu_mem_usage, **kwargs)
   1179 # load the weights into the model
   1180 ignore_mismatched_sizes = kwargs.get("ignore_mismatched_sizes", False)
-> 1181 load_result = set_peft_model_state_dict(
   1182     self,
   1183     adapters_weights,
   1184     adapter_name=adapter_name,
   1185     ignore_mismatched_sizes=ignore_mismatched_sizes,
   1186     low_cpu_mem_usage=low_cpu_mem_usage,
   1187 )
   1188 if (
   1189     (getattr(self, "hf_device_map", None) is not None)
   1190     and (len(set(self.hf_device_map.values()).intersection({"cpu", "disk"})) > 0)
   1191     and len(self.peft_config) == 1
   1192 ):
   1193     device_map = kwargs.get("device_map", "auto")

File xxx/python3.10/site-packages/peft/utils/save_and_load.py:467, in set_peft_model_state_dict(model, peft_model_state_dict, adapter_name, ignore_mismatched_sizes, low_cpu_mem_usage)
    464     load_result = model.load_state_dict(peft_model_state_dict, strict=False)
    466 if config.is_prompt_learning:
--> 467     model.prompt_encoder[adapter_name].embedding.load_state_dict(
    468         {"weight": peft_model_state_dict["prompt_embeddings"]}, strict=True
    469     )
    471 if config.peft_type == PeftType.MULTITASK_PROMPT_TUNING:
    472     model.prompt_encoder[adapter_name].load_state_dict(peft_model_state_dict, strict=False)

File xxx/python3.10/site-packages/torch/nn/modules/module.py:2189, in Module.load_state_dict(self, state_dict, strict, assign)
   2184         error_msgs.insert(
   2185             0, 'Missing key(s) in state_dict: {}. '.format(
   2186                 ', '.join(f'"{k}"' for k in missing_keys)))
   2188 if len(error_msgs) > 0:
-> 2189     raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
   2190                        self.__class__.__name__, "\n\t".join(error_msgs)))
   2191 return _IncompatibleKeys(missing_keys, unexpected_keys)

RuntimeError: Error(s) in loading state_dict for Embedding:
	size mismatch for weight: copying a param with shape torch.Size([10, 172032]) from checkpoint, the shape in current model is torch.Size([10, 3072]).
```

This error indicates that the shape of the weights saved in the checkpoint [10, 172032] does not match the shape of the weights in the target model [10, 3072].
This is a strange phenomenon as these weights with size [10, 172032] do not exist anywhere in the model.

The issue seems to be related to saving and loading the `prompt_encoder`.
The PeftModel calls [get_peft_model_state_dict()](https://github.com/huggingface/peft/blob/v0.13.2/src/peft/utils/save_and_load.py#L154) when creating a checkpoint to save the `prompt_encoder`.
I suspect this function retrieves the output of the `prompt_encoder` (embedding of virtual tokens) and saves it as the weights of the `prompt_encoder`.
Instead of directly saving the `state_dict()` of the `prompt_encoder`, it seems to use the output as weights for saving.
This might be because, during inference, it is assumed that the `prompt_encoder` is initialized with a `torch.nn.Embedding(10, 172032)` layer, and the weights loaded from the checkpoint are set here.
This allows omitting the `transform` layer of the `prompt_encoder` during inference.

However, the Trainer does not anticipate such operations when loading models from checkpoints, and the architecture of the `prompt_encoder` remains the same as during training.
Therefore, an error due to a mismatch in weight shapes occurs as described above.

Moreover, this specification likely affects not only prefix-tuning but also other methods like p-tuning, which add layers behind the `torch.nn.Embedding` layer.

Is this a bug, or is there an error with my code?

For reference, here is a sample code to reproduce this error.

```python
from transformers import (
    AutoModelForSequenceClassification,
    AutoTokenizer,
    EarlyStoppingCallback,
    Trainer,
    TrainingArguments,
)
from peft import PrefixTuningConfig, TaskType
from peft.peft_model import PeftModelForSequenceClassification
from datasets import Dataset, DatasetDict
import pandas as pd


# Temporary fix for the issue (https://github.com/huggingface/peft/issues/2246)
class PatchedPeftModelForSequenceClassification(PeftModelForSequenceClassification):
    def add_adapter(
        self, adapter_name, peft_config, low_cpu_mem_usage: bool = False
    ):
        super().add_adapter(adapter_name, peft_config)


def tokenize_function(examples):
    return tokenizer(examples["text"], max_length=128, truncation=True, padding="max_length")

    
model_name = "llm-jp/llm-jp-3-3.7b"
tokenizer = AutoTokenizer.from_pretrained(model_name, padding_side="left")

base_model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=2,)
base_model.config.pad_token_id = tokenizer.pad_token_id

# Japanese sample datasets for positive/negative classification
train_df = pd.DataFrame([
    ["この商品は期待以上でした。品質がとても良いです。", 1],
    ["デザインは素敵ですが、使い勝手が悪いです。", 0],
    ["購入して大満足です。友人にも勧めたいと思います。", 1],
    ["説明通りの商品でした。特に不満はありません。", 1],
    ["すぐに壊れてしまいました。返品したいです。", 0],
    ["色が写真と違っていてがっかりしました。", 0],
    ["迅速な配送で助かりました。商品も良かったです。", 1],
    ["期待していたよりも性能が低いです。", 0],
    ["とても使いやすく、毎日愛用しています。", 1],
    ["箱が破れて届きました。中身は無事でしたが残念です。", 0],
], columns=["text", "label"])

val_df = pd.DataFrame([
    ["サポートが親切で安心しました。また購入したいです。", 1],
    ["サイズが合わず、返品が面倒でした。", 0],
    ["コストパフォーマンスが良く、満足しています。", 1],
    ["音がうるさくて使えません。", 0],
], columns=["text", "label"])

datasets = DatasetDict({
    "train": Dataset.from_pandas(train_df),
    "val": Dataset.from_pandas(val_df),
})

tokenized_datasets = datasets.map(tokenize_function, batched=True)

peft_config = PrefixTuningConfig(
    task_type=TaskType.SEQ_CLS,
    inference_mode=False,
    prefix_projection=True,
    num_virtual_tokens=10,
)

peft_model = PatchedPeftModelForSequenceClassification(base_model, peft_config)

training_args = TrainingArguments(
    output_dir=f"./results",
    num_train_epochs=3,
    learning_rate=1e-4,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    fp16=True,
    fp16_full_eval=True,
)

trainer = Trainer(
    model=peft_model,
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["val"],
    callbacks=[EarlyStoppingCallback(early_stopping_patience=1)],
)

result = trainer.train()
```

### Expected behavior

I would like the PEFT package to support the trainer's checkpoint function.

**Comment by BenjaminBossan** [comment]
Thanks for reporting this issue. The translation is very good, I could understand the issue you described.

It is indeed not currently possible to load models like prefix tuning automatically from the checkpoint. To give a little bit of context, for these types of models, there is an optimization in PEFT that results in the prompt encoder not being saved in its entirety. Instead, only those weights are saved that are necessary for inference. Since the model architecture is changed, this results in the error of mismatched shapes that you reported.

Unfortunately, I don't think that there is a good way around this. I'd recommend setting `load_best_model_at_end=False` and the manually loading the model when training ends:

```python
from peft import PeftModel

base_model = ...
model = PeftModel.from_pretrained(base_model, <checkpoint-path>)
```

When I tested this, I unfortunately encountered some some issues:

1. I could not use `EarlyStoppingCallback` because `load_best_model_at_end=False`. This doesn't really make sense to me, early stopping should still work.
2. I could not use `trainer.state.best_model_checkpoint` as the checkpoint path, since it was just `None`. However, there were still checkpoints inside the `output_dir`, so it's unclear to me why `trainer.state.best_model_checkpoint` is not set. As is, the correct checkpoint path has to be determined manually (e.g. `checkpoint_path = os.path.join(output_dir, "checkpoint-3")`).

Apart from these stumbling blocks, I believe what we could do is to notice when the PEFT model is a prompt learning method and if the loading fails, give the users a helpful error message.

**Comment by sno-ko** [comment]
Thank you for your comment!

I understand that a perfect fix would be difficult.
For the time being, I plan to modify the source code on my end to forcibly save the entire weights of the `prompt_encoder` as a workaround.

I also appreciate your efforts in creating a pull request regarding an error message.

**Comment by BenjaminBossan** [comment]
> 1. I could not use `EarlyStoppingCallback` because `load_best_model_at_end=False`
> 2. I could not use `trainer.state.best_model_checkpoint` as the checkpoint path, since it was just `None`

@muellerzr informed me that it is possible but we need to set `metric_for_best_model`, e.g. `metric_for_best_model="eval_loss"`. After setting this, the `best_model_checkpoint` was also correctly set.

**Comment by sno-ko** [comment]
> @.muellerzr informed me that it is possible but we need to set metric_for_best_model, e.g. metric_for_best_model="eval_loss". After setting this, the best_model_checkpoint was also correctly set.

I think that method is effective when manually loading the best model. Thank you for sharing.

> If you find a solution that works for you, it would be great to share it here for future users who might run across the same issue.

My solution is just a temporary workaround to achieve my goal, so I don't recommend it, but I'll share it for reference.
I have confirmed that it works for Prefix-tuning and P-tuning in my environment.

First, modify [get_peft_model_state_dict()](https://github.com/huggingface/peft/blob/v0.13.2/src/peft/utils/save_and_load.py#L146C1-L155C59) as follows.

```python
if config.peft_type == PeftType.MULTITASK_PROMPT_TUNING:
    to_return["prefix_task_cols"] = model.prompt_encoder[adapter_name].prefix_task_cols
    to_return["prefix_task_rows"] = model.prompt_encoder[adapter_name].prefix_task_rows
    prompt_embeddings = model.prompt_encoder[adapter_name].embedding.weight
    to_return["prompt_embeddings"] = prompt_embeddings
else:
    to_return.update(model.prompt_encoder[adapter_name].state_dict(prefix="prompt_embeddings."))
```

Next, modify [set_peft_model_state_dict()](https://github.com/huggingface/peft/blob/v0.13.2/src/peft/utils/save_and_load.py#L467C1-L469C10) as follows.

```python
prefix = "prompt_embeddings."
prompt_embeddings = {k.replace(prefix, ""): v for k, v in peft_model_state_dict.items() if k[:len(prefix)] == prefix}
model.prompt_encoder[adapter_name].load_state_dict(prompt_embeddings, strict=True)
```

Please note the following issues with this modification:
- It does not contribute to parameter reduction of `prompt_encoder` during inference.
- It has not been verified whether it negatively affects other features of this PEFT library.

**Comment by BenjaminBossan** [comment]
Thanks a lot for sharing your workaround. I think for some use cases (like continuing the training from a checkpoint), it can be a valid solution. For the final model that is intended to be used only for inference, I would still recommend to go back to the initial PEFT functionality. So if you monkey-patch `get_peft_model_state_dict` and `set_peft_model_state_dict` during the training, for the final save, I'd swap back the original functions.

> * It does not contribute to parameter reduction of `prompt_encoder` during inference.

For other readers, this refers to what I mentioned above:

> there is an optimization in PEFT that results in the prompt encoder not being saved in its entirety. Instead, only those weights are saved that are necessary for inference

**Comment by BenjaminBossan** [comment]
The transformers PR to add a better error message has been merged. Thus I think there are no more todos from this issue and I'll close it. Feel free to re-open if something new comes up.
