### ISSUE TITLE
Make module imports / re-export conforming with typing specs for proper type checker support

### ISSUE THREAD

**Issue by bluenote10** [huggingface/peft#2261]
### Feature request

Make peft's modules type checker friendly.

### Motivation

Currently, using peft with a type checker is somewhat painful, because its module re-exports are not conforming to the [typing specs for library interfaces](https://github.com/python/typing/blob/ad4cbc45f868f47031494694bdb7349119302f59/docs/spec/distributing.rst#library-interface-public-and-private-symbols). This means that very basic things do not type check properly. For instance the following is a type error in both pyright and mypy:

```py
from peft import LoraConfig
```

Mypy error is for instance:
```
example.py:1: error: Module "peft" does not explicitly export attribute "LoraConfig"  [attr-defined]
```

This is obviously not great, because the code works fine as runtime. Suppressing all these type errors causes a lot of noise on user side, and even worse, fails to make any benefit from the type annotations.

### Your contribution

As the specs say: _Imported symbols are considered private by default._

There are basically two ways to get proper library interfaces:
- Using an explicit `__all__` in the modules to mark the re-exports.
- Using the patterns shown in the [Import Conventions](https://github.com/python/typing/blob/ad4cbc45f868f47031494694bdb7349119302f59/docs/spec/distributing.rst#import-conventions) section.

Using an explicit `__all__` would also allow you to remove the linter suppressions like this one

https://github.com/huggingface/peft/blob/f86522e011af21697ef1477da4d232e74de83232/src/peft/__init__.py#L1-L3

because the linter would then understand that the symbol is being used for re-export purposes.

**Comment by BenjaminBossan** [comment]
Thanks for bringing this up. I agree that the type annotation situation in PEFT is lackluster, we don't perform any automatic checks. Could you please tell us which type checker you're using (and which config, if any)?

Regarding your suggestion, I'd be fine with defining an `__all__` with all "public" objects in the `__init__.py`. Using `import X as X` looks terrible though. If you're interested, feel free to create a PR and check if the solution solves your issue.

**Comment by bluenote10** [comment]
> Could you please tell us which type checker you're using (and which config, if any)?

As mentioned, I'm using both pyright and mypy, and it is a type error in both. This is mostly with default configs, but I don't think it depends a lot on the config, because that is just a general convention (of course, you could come up with a config that suppresses these errors). Note that these typing specs are not specific to any type checker, but rather _all_ type checkers in the ecosystem should stick to them -- so if a type checker adheres to the standard, it has to report a type error.

> Regarding your suggestion, I'd be fine with defining an __all__ with all "public" objects in the __init__.py.

Cool! I can look into that once I find some time for it.

**Comment by BenjaminBossan** [comment]
Thanks for the additional info. I'll be looking forward to the PR then.

I searched if there is any possibility to declare that everything imported into a module should be considered "public", but it appears there is no option for that, so using `__all__` seems like the best solution.

**Comment by BenjaminBossan** [comment]
Thanks for your PRs, the issue should now be resolved. Feel free to re-open if anything is still missing.
