### ISSUE TITLE
Question about use lora for mamba2

### ISSUE THREAD

**Issue by Doctor-James** [huggingface/peft#2274]
I am trying to fine-tune the Mamba2 model using LoRA, following the guidance provided by https://huggingface.co/docs/transformers/en/model_doc/mamba2
I set
```
lora_config =  LoraConfig(
        r=8,
        target_modules=["embeddings", "in_proj", "out_proj"],
        task_type="CAUSAL_LM",
        bias="none"
)
````
However, after carefully examining the code, I found that Mamba2 uses its own CUDA algorithms, which directly pass **out_proj.weight** and **out_proj.bias**, bypassing **out_proj.forward**. Given this approach, can LoRA work properly?
```
if self.training and cache_params is None:
    out, ssm_state = mamba_split_conv1d_scan_combined(
        projected_states,
        self.conv1d.weight.squeeze(1),
        self.conv1d.bias,
        self.dt_bias,
        A,
        D=self.D,
        chunk_size=self.chunk_size,
        seq_idx=None,  # was seq_idx
        activation=self.activation,
        rmsnorm_weight=self.norm.weight,
        rmsnorm_eps=self.norm.variance_epsilon,
        outproj_weight=self.out_proj.weight,
        outproj_bias=self.out_proj.bias,
        headdim=self.head_dim,
        ngroups=self.n_groups,
        norm_before_gate=False,
        return_final_states=True,
        **dt_limit_kwargs,
    )

```

**Comment by BenjaminBossan** [comment]
Yes, you are very correct. If the parameters are used directly like in this example, LoRA weights won't be applied to them. The only solution would be to create a specific LoRA layer for this mamba layer and adding the LoRA logic there.
