### ISSUE TITLE
TypeError: TorchaoLoraLinear.__init__() missing 1 required keyword-only argument: 'get_apply_tensor_subclass'

### ISSUE THREAD

**Issue by spezialspezial** [huggingface/peft#2285]
### System Info

peft-0.14.0
diffusers recent
accelerate 1.2.1
torchao 0.7.0

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

  File "site-packages/peft/tuners/lora/torchao.py", line 147, in dispatch_torchao
    new_module = TorchaoLoraLinear(target, adapter_name, **kwargs)
TypeError: TorchaoLoraLinear.__init__() missing 1 required keyword-only argument: 'get_apply_tensor_subclass'

Either init arg is wrongfully mandatory or call is missing an arg. Please check if you find a minute.

### Expected behavior

100% less TypeErrors

**Comment by BenjaminBossan** [comment]
Could you please provide the code to replicate the error?

In torchao 0.7.0, there were a few changes that can break with PEFT, we're working on a fix. However, I haven't encountered the error you just reported. One solution for you could still be to try torchao 0.6.1.

**Comment by spezialspezial** [comment]
Wish I could provide a simple example, unfortunately I can't right now. Maybe validate target and adapter_name to catch errors early. At the moment it just throws a somewhat unhelpful generic python error.

Downgrading peft fixed it, fyi.

**Comment by BenjaminBossan** [comment]
> Wish I could provide a simple example, unfortunately I can't right now.

Could you at least share your LoRA config (especially `target_modules`) and the model architecture?

> Downgrading peft fixed it, fyi.

This may work for some uses cases but e.g. merging will fail.

**Comment by spezialspezial** [comment]
Just so there is no misunderstanding:
- I'm using peft via diffusers and did not change any of diffuser's default settings for peft
- diffusers is currently changing a lot of the code base affecting torchao quantization, especially loading back pre-quantized torch archives 
- TorchaoLoraLinear is a peft class and has an slightly funky __init__ signature that might be error prone

Having said that, if you can hazard a guess where to retrieve data that might help I could go and have a look. Note that I moved on since and wouldn't enjoy having everything implode again.

What I can see in a loaded diffusers pipeline:
![peft](https://github.com/user-attachments/assets/2183e911-46c3-4cf1-98db-30d527eed5c8)


`{'Mall_Portrait_1979_v1_Flux_Lora mllprtrt': LoraConfig(peft_type=<PeftType.LORA: 'LORA'>, auto_mapping=None, base_model_name_or_path=None, revision=None, task_type=None, inference_mode=False, r=42, target_modules={'5.proj_out', 'to_q', '16.proj_out', '12.proj_out', '6.proj_out', '30.proj_out', '15.proj_out', '1.proj_out', '9.proj_out', '36.proj_out', '0.proj_out', '20.proj_out', '37.proj_out', '33.proj_out', '4.proj_out', 'proj', 'proj_mlp', 'to_v', '7.proj_out', '28.proj_out', '14.proj_out', 'add_q_proj', '23.proj_out', 'add_v_proj', 'norm1_context.linear', '2.proj_out', 'net.2', '27.proj_out', '31.proj_out', '21.proj_out', '13.proj_out', '35.proj_out', '17.proj_out', '19.proj_out', '22.proj_out', '8.proj_out', '25.proj_out', '11.proj_out', 'norm.linear', 'to_add_out', 'norm1.linear', '10.proj_out', '32.proj_out', '24.proj_out', 'add_k_proj', 'to_out.0', '29.proj_out', '3.proj_out', 'to_k', '26.proj_out', '34.proj_out', '18.proj_out'}, lora_alpha=42, lora_dropout=0.0, fan_in_fan_out=False, bias='none', use_rslora=False, modules_to_save=None, init_lora_weights=True, layers_to_transform=None, layers_pattern=None, rank_pattern={}, alpha_pattern={}, megatron_config=None, megatron_core='megatron.core', loftq_config={}, use_dora=False, layer_replication=None, runtime_config=LoraRuntimeConfig(ephemeral_gpu_offload=False))}`

**Comment by spezialspezial** [comment]
I think I close this for now and wait until diffusers puts out a stable release. I'll try upgrading peft and report back if I hit it again.

**Comment by BenjaminBossan** [comment]
Okay, sounds good. Just to clarify, the "funky `__init__` signature" of `TorchaoLoraLinear` is on purpose :) We need the `get_apply_tensor_subclass` argument for merging and unmerging. Therefore, I wanted the code to error out early if the argument is missing. Otherwise, people might spend hours training their model and only at the end notice that they can't fully use it for inference.

**Comment by spezialspezial** [comment]
Erroring out did work alright :) If I get this correctly `get_apply_tensor_subclass` is a mandatory argument somewhere in the kwargs if the model is torchao quantized. `dispatch_torchao` is not called for quantized LoRAs, right?

While you're here. Do you think `inference_mode=False` is correct? I noticed the LoRA weights are flagged as requiring grad. Now `torch.no_grad` overrides this but I was wondering where that happens. I also can't use `torch.inference_mode` anymore but this might not relate to peft.

**Comment by BenjaminBossan** [comment]
> If I get this correctly `get_apply_tensor_subclass` is a mandatory argument somewhere in the kwargs if the model is torchao quantized.

Correct.

> `dispatch_torchao` is not called for quantized LoRAs, right?

What do you mean by "quantized LoRAs"? LoRAs are not quantized normally.

> Do you think `inference_mode=False` is correct? I noticed the LoRA weights are flagged as requiring grad. Now `torch.no_grad` overrides this but I was wondering where that happens. I also can't use `torch.inference_mode` anymore but this might not relate to peft.

I'm lacking a bit of context here, could you describe your use case? Ideally show some code of where this goes wrong. Feel free to create a new issue for that.

**Comment by hlnull** [comment]
@BenjaminBossan 
In case a use case is required, I've come across the same issue as detailed in this link (https://github.com/Yuanshi9815/OminiControl/issues/34#issuecomment-2538767336). 

> What do you mean by "quantized LoRAs"? LoRAs are not quantized normally.

It seems the OminiControl uses a quantized LoRAs to support 24G memory graphics cards.

> https://github.com/Yuanshi9815/OminiControl/pull/13/files
![image](https://github.com/user-attachments/assets/6163f45a-50cd-48d0-84fd-f6fb939a3065)

Hope it helps.

**Comment by BenjaminBossan** [comment]
> It seems the OminiControl uses the int8-wo version of [Flux.1-Schnell](https://huggingface.co/black-forest-labs/FLUX.1-schnell) to support 24G memory graphics cards.

The quantization refers to the base model. The shown code does not use any LoRA weights.

**Comment by hlnull** [comment]
> The quantization refers to the base model.

You are right. 

Open the pull request and you will see it load LoRA weights on line 37. 
![Image](https://github.com/user-attachments/assets/37980916-8f08-4ee2-aaa8-d4b9514b82f4)
