### ISSUE TITLE
PeftModelForSeq2SeqLM.generate() does not accept positional arguments

### ISSUE THREAD

**Issue by pminervini** [huggingface/peft#232]
This is easy to fix; I will submit a pull request ASAP.

```bash
Traceback (most recent call last):
[..]
    out = model.generate(
TypeError: PeftModelForSeq2SeqLM.generate() takes 1 positional argument but 2 were given
```

**Comment by younesbelkada** [comment]
@pminervini yes, AFAIK to call generate you need to give explicit kew word arguments; `input_ids=input_ids, attention_mask=attention_mask, ` etc.

**Comment by younesbelkada** [comment]
For reference this is what we do in tests: https://github.com/huggingface/peft/blob/542f2470e7679768f594692fc7f59e83f48585a8/tests/test_peft_model.py#L177

**Comment by pminervini** [comment]
> For reference this is what we do in tests: https://github.com/huggingface/peft/blob/542f2470e7679768f594692fc7f59e83f48585a8/tests/test_peft_model.py#L177

If you folks want things to stay this way, I can close the issue!

**Comment by younesbelkada** [comment]
cc @pacman100 !

**Comment by pacman100** [comment]
Hello, @pminervini, it would be great to support positional args too if that can be done in a clean way. Looking forward to your PR.
