### ISSUE TITLE
Can not retrain peft model 

### ISSUE THREAD

**Issue by khalidnass** [huggingface/peft#234]
Greeting,

I can not load peft model and resume the training. it gives me the following error message 

expected all tensors to be on the same device but found two devices cuda1 and cuda0 

please find my code below 

## First, i load the model and peft model :

import torch
from peft import PeftModel, PeftConfig
from transformers import AutoModelForCausalLM, AutoTokenizer

peft_model_id = "<<my_model>>"
config = PeftConfig.from_pretrained(peft_model_id)
model = AutoModelForCausalLM.from_pretrained(config.base_model_name_or_path, 
                                                                                 return_dict=True,
                                                                                 torch_dtype= torch.float16 ,
                                                                                 device_map='auto')
tokenizer = AutoTokenizer.from_pretrained(config.base_model_name_or_path)

model = PeftModel.from_pretrained(model, peft_model_id)

## then I try to resume my training 
 
trainer = transformers.Trainer(
    model=model, 
    train_dataset=data['train'],
    args=transformers.TrainingArguments(
        per_device_train_batch_size=8, 
        gradient_accumulation_steps=4,
        warmup_steps=100, 
        max_steps=200, 
        learning_rate=2e-4, 
        fp16=True,
        logging_steps=1, 
        output_dir='outputs'
    ),
    data_collator=transformers.DataCollatorForLanguageModeling(tokenizer, mlm=False)
)
model.config.use_cache = False  # silence the warnings. Please re-enable for inference!
trainer.train()

## then it will show the following error 

expected all tensors to be on the same device but found two devices cuda1 and cuda0

**Comment by pacman100** [comment]
Currently, you can only resume training for LoRA method. Could you share minimal code that we can run to reproduce the issue?
