### ISSUE TITLE
Adding Zero-Init Attention Adaptation

### ISSUE THREAD

**Issue by shermansiu** [huggingface/peft#235]
At some point, it may be worthwhile to add Zero-Init Attention Adaptation from the ArXiv preprint [LLaMA-Adapter: Efficient Fine-tuning of Language Models with Zero-init Attention](https://arxiv.org/abs/2303.16199).

This method also supports the addition of multi-modal instructions.

Efficiency Comparison:
|  Model | Parameters | Storage Space | Training Time  
| :-----: | :-----: |:-----:| :-----: |
|  [Alpaca](https://github.com/tatsu-lab/stanford_alpaca) | 7B |13G| 3 Hours|
|  [Alpaca-LoRA](https://github.com/tloen/alpaca-lora) | - |16.8M| - |
|  LLaMA-Adapter | 1.2M |4.7M| 1 Hour|

The training code will be released here: https://github.com/ZrrSkywalker/LLaMA-Adapter

**Comment by pacman100** [comment]
Hello, the paper is interesting and very insightful, we are already evaluating the feasibility of integrating it. Will update this issue accordingly. PRs are welcome for adding this 🤗.

**Comment by yeoedward** [comment]
Took a stab at it!
