### ISSUE TITLE
loss 0 with load_in_8bit = True

### ISSUE THREAD

**Issue by chuckhope** [huggingface/peft#236]
Hello, I came across an issue regarding loss remaining at 0 when using PEFT for the chatglm model. I found that the model works well with fp16. For your reference, my environment consists of a V100 16GB, peft 0.3.0.dev0, and Bitsandbytes 0.37.1. Could you please take a look and provide any insights on how to resolve this issue? Thank you.

**Comment by younesbelkada** [comment]
hi @chuckhope
Can you share a small reproducible script?
Thanks!

**Comment by chuckhope** [comment]
My script is based on the finetune.py of https://github.com/mymusise/ChatGLM-Tuning/tree/master

**Comment by bhavnicksm** [comment]
Encountered the same issue!
Training OPT-125M with bnb on summarization.

**Comment by matrixssy** [comment]
Encountered the same issue!
Training ALPACA_LORA-13B.

**Comment by iMountTai** [comment]
Encountered the same issue!
Training llama-33b.

**Comment by iMountTai** [comment]
@matrixssy @bhavnicksm @chuckhope Sorry to bother you, but have you solved your problem yet?
