### ISSUE TITLE
error while load for inference when call model.eval()

### ISSUE THREAD

**Issue by justdark** [huggingface/peft#237]
After I train on bloomz 7.1B,I load the model for inference
---------------------------------------------------------------------------
---------------------------------------------------------------------------
`RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_2047/358325544.py in <module>
      1 device = torch.device("cuda:0")
      2 
----> 3 model.eval()
      4 

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py in eval(self)
   1928             Module: self
   1929         """
-> 1930         return self.train(False)
   1931 
   1932     def requires_grad_(self: T, requires_grad: bool = True) -> T:

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py in train(self, mode)
   1909         self.training = mode
   1910         for module in self.children():
-> 1911             module.train(mode)
   1912         return self
   1913 

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py in train(self, mode)
   1909         self.training = mode
   1910         for module in self.children():
-> 1911             module.train(mode)
   1912         return self
   1913 

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py in train(self, mode)
   1909         self.training = mode
   1910         for module in self.children():
-> 1911             module.train(mode)
   1912         return self
   1913 

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py in train(self, mode)
   1909         self.training = mode
   1910         for module in self.children():
-> 1911             module.train(mode)
   1912         return self
   1913 

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py in train(self, mode)
   1909         self.training = mode
   1910         for module in self.children():
-> 1911             module.train(mode)
   1912         return self
   1913 

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py in train(self, mode)
   1909         self.training = mode
   1910         for module in self.children():
-> 1911             module.train(mode)
   1912         return self
   1913 

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py in train(self, mode)
   1909         self.training = mode
   1910         for module in self.children():
-> 1911             module.train(mode)
   1912         return self
   1913 

/usr/local/lib/python3.7/dist-packages/peft/tuners/lora.py in train(self, mode)
    418                     self.lora_A.weight.data.unsqueeze(0),
    419                     self.lora_B.weight.data.unsqueeze(-1),
--> 420                     groups=sum(self.enable_lora),
    421                 ).squeeze(0)
    422                 self.weight.data += self.zero_pad(transpose(delta_w * self.scaling, self.fan_in_fan_out))

RuntimeError: Expected 4-dimensional input for 4-dimensional weight [8192, 16, 1, 1], but got 3-dimensional input of size [1, 32, 4096] instead`

**Comment by justdark** [comment]
peft config is :
{
  "base_model_name_or_path": "bigscience/bloomz-7b1",
  "bias": "none",
  "enable_lora": [
    true,
    false,
    true
  ],
  "fan_in_fan_out": false,
  "inference_mode": true,
  "lora_alpha": 32,
  "lora_dropout": 0.1,
  "merge_weights": false,
  "modules_to_save": null,
  "peft_type": "LORA",
  "r": 16,
  "target_modules": [
    "query_key_value"
  ],
  "task_type": "CAUSAL_LM"
}

**Comment by pacman100** [comment]
Hello @justdark, xould you please try the main branch installation and let us know if that solves the issue?

**Comment by justdark** [comment]
> Hello @justdark, xould you please try the main branch installation and let us know if that solves the issue?

thanks, it's ok to use the main branch.
