### ISSUE TITLE
What to use for `model_id` when loading from a model trained locally and not published?

### ISSUE THREAD

**Issue by philharmonikerzzy** [huggingface/peft#251]
Do we have to push the model to hugginface to be able to load a model trained locally?

**Comment by pacman100** [comment]
You need not retrain, it's just that you could have save a lot of storage space with `save_pretrained()`. You can load the whole model weights with `load_pretrained` without any issues

**Comment by philharmonikerzzy** [comment]
could you provide an example of how to pass a path to `PeftModel.from_pretrained()`? when i do `PeftModel.from_pretrained(model, [local-path])` im getting `Repository Not Found for url:`

**Comment by philharmonikerzzy** [comment]
based on the implementation here I don't see how i could load the whole model with the LORA weights using the `from_pretrained` method.
https://github.com/huggingface/peft/blob/main/src/peft/peft_model.py#L148
