### ISSUE TITLE
Why do we need Linear and MergedLinear? 

### ISSUE THREAD

**Issue by hsm1997** [huggingface/peft#258]

**Comment by hsm1997** [comment]
it seems that the key difference is "enable_lora" and "F.Conv1d".

**Comment by sdafkldkfaj** [comment]
Hi @hsm1997 have you figured out why?  I am also curious...

**Comment by clalanliu** [comment]
This is because in some models the multiple module 's weight are processed together.
For example, if there is model on which you want to add 8-rank LoRA to 3 matrices (Q, K, V) of attention layer, you can use 
lora_A = nn.Linear(in_features, 8*3)
lora_B = nn.Conv1d(
    8 * 3
    out_features,
    kernel_size=1,
    groups=3,
    bias=False,
)
