### ISSUE TITLE
How to load weights from a specific checkpoint?

### ISSUE THREAD

**Issue by ruian0** [huggingface/peft#273]
After training,  the `output_directory` looks like: 
```
checkpoint-51/
checkpoint-102/
tokenizer_config.json
adapter_model.bin
adapter_config.json
tokenizer.model
special_tokens_map.json
added_tokens.json
```
and inside checkpoint-51 and checkpoint-102 there are files of 
```
training_args.bin
pytorch_model.bin
trainer_state.json
scheduler.pt
rng_state.pth
optimizer.pt
```

I would like to load the model saved in `checkpoint-51`, with the code below I can get the weights in `checkpoint-102`

```
peft_config = PeftConfig.from_pretrained(output_directory)
model = LlamaForSequenceClassification.from_pretrained(peft_config.base_model_name_or_path) 
model = PeftModel.from_pretrained(model, peft_model_id=output_directory)
```

What should I modify to load from `checkpoint-51`? Thanks

**Comment by younesbelkada** [comment]
How did you defined the rule to save your adapter checkpoints? Can you share with us the way you save the peft model?

**Comment by ruian0** [comment]
> How did you defined the rule to save your adapter checkpoints? Can you share with us the way you save the peft model?

I used a TrainingArguments and trained it with a hugginface Trainer, I think these steps created the files inside each checkpoint folder. I also saved the model and tokenizer after the Trainer finished, this one created files in the top level of the output_directory, adapter_model.bin etc.
```
training_args = TrainingArguments(
    output_dir=output_directory,
    num_train_epochs=2,
    logging_dir=os.path.join(training_dir, './logs'),
    logging_steps=10,
    save_strategy="epoch",
    report_to="wandb",
    ...
)
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    # eval_dataset=valid_dataset,
    callbacks=[SaveTokenizerCallback(tokenizer, os.path.join(training_dir, "tokenizer"))],
)

model.save_pretrained(output_directory)
tokenizer.save_pretrained(output_directory)
```

In the test example I provided above, `checkoutpoint-51` is saved at end of epoch1 `checkoutpoint-102` is saved at the end of epoch2

**Comment by younesbelkada** [comment]
Hi @ruian0 
I think that you need to define a proper callback to save the adapter weights each n-steps, please take a look at the proposed solution in https://github.com/huggingface/peft/issues/96

**Comment by ajsanjoaquin** [comment]
> Hi @ruian0 I think that you need to define a proper callback to save the adapter weights each n-steps, please take a look at the proposed solution in #96

Sorry, I'm having the same problem, and I don't understand how this leads to the solution. Aren't the checkpoint folders that PEFT save already contain the necessary adapter weights & artifacts? 

If so, is there a way to manually load `checkpoint-51` instead of `checkpoint-102`?
