### ISSUE TITLE
Merging adapter error

### ISSUE THREAD

**Issue by Shreyans92** [huggingface/peft#279]
Hi @younesbelkada @pacman100 ,

I am following this script: https://github.com/lvwerra/trl/blob/main/examples/sentiment/scripts/gpt-neox-20b_peft/merge_peft_adapter.py 
for merging adapter of my LORA finetuned flan-t5-xl model. I am getting error while executing this:
for key in key_list:
    parent, target, target_name = model.base_model._get_submodules(key)
    if isinstance(target, peft.tuners.lora.Linear):
        bias = target.bias is not None
        new_module = torch.nn.Linear(target.in_features, target.out_features, bias=bias)
        model.base_model._replace_module(parent, target_name, new_module, target)

Attribute Error: 'LoraModel' object has no attribute _get_submodules(). 

I suspect this might be because of latest changes in peft as previously it was working. Can you suggest some alternative to do this?

i tried doing this merged_model = model.base_model.merge_and_unload() and provided offload_folder param while loading the original model. Is this correct?

**Comment by younesbelkada** [comment]
Hi @Shreyans92 

> i tried doing this merged_model = model.base_model.merge_and_unload() and provided offload_folder param while loading the original model. Is this correct?

Yes you should do something in the following lines! 
Check what we do in the tests: https://github.com/huggingface/peft/blob/445940fb7b5d38390ffb6707e2a989e89fff03b5/tests/testing_common.py#L263

**Comment by Shreyans92** [comment]
@younesbelkada @pacman100 Thanks it worked, but i do observe the change in output with the merged model in comparison to adding adapters to original models separately.

**Comment by pacman100** [comment]
Hello @Shreyans92, are you ensuring `model.eval()` is called before making an evaluation? Please provide us with a script that we can run for further deep dive.
