### ISSUE TITLE
No Trainable Parameters when PeftModel.from_pretrained()

### ISSUE THREAD

**Issue by aced125** [huggingface/peft#282]
Example (using transformers master and peft master):

```python
from peft import PeftModel
from transformers import LlamaForCausalLM
import torch

orig_model = LlamaForCausalLM.from_pretrained(
   'decapoda-research/llama-7b-hf',
    load_in_8bit=True,
    torch_dtype=torch.float16,
    device_map="auto",
)

out = PeftModel.from_pretrained(orig_model, "tloen/alpaca-lora-7b")
print(out.print_trainable_parameters())
# trainable params: 0 || all params: 6755201024 || trainable%: 0.0
```

This issue was not there a few days ago so I'm guessing a recent commit broke it!

**Comment by aced125** [comment]
Can confirm that peft==0.2.0 does not have this issue. The above code snippet gives me 

```
trainable params: 16777216 || all params: 6755192832 || trainable%: 0.24836028248556738
```

**Comment by aced125** [comment]
Using this commit `pip install git+https://github.com/huggingface/peft.git@d5feb8b787624bd9b886a4eb447eabf6d01b8bb2`

gives 
```
trainable params: 262410240 || all params: 6755192832 || trainable%: 3.8845706780854186
```

which is even more worrying...

**Comment by pacman100** [comment]
Hello, thank you for raising the issue. Please let us know if the above PR resolves it.

> trainable params: 0 || all params: 6755201024 || trainable%: 0.0

In a recent PR, `from_pretrained()` is set by default to load the save adapter in frozen mode, i.e., non trainable mode. This is controlled via `is_trainable` boolean. 

Below are example with and without setting `is_trainable` param.

<img width="1124" alt="Screenshot 2023-04-08 at 11 50 50 AM" src="https://user-images.githubusercontent.com/13534540/230706766-6cae9868-7861-4b80-aedf-6a9c9d80fa85.png">

<img width="1104" alt="Screenshot 2023-04-08 at 11 50 42 AM" src="https://user-images.githubusercontent.com/13534540/230706765-7bdfc2c7-c51c-42b6-90f4-949b99730834.png">

**Comment by pacman100** [comment]
> Using this commit `pip install git+https://github.com/huggingface/peft.git@d5feb8b787624bd9b886a4eb447eabf6d01b8bb2`
> 
> gives
> 
> ```
> trainable params: 262410240 || all params: 6755192832 || trainable%: 3.8845706780854186
> ```
> 
> which is even more worrying...

This has been fixed in the above PR

**Comment by aced125** [comment]
Hi @pacman100, can confirm this works. Thank you!
