### ISSUE TITLE
Multi GPU, device_map is not fully respected

### ISSUE THREAD

**Issue by ndvbd** [huggingface/peft#287]
When using:
`PeftModel.from_pretrained`
I am giving a device_map = `{'':7}`
Meaning, that I want only GPU number 7 to be used.
However, it fails on 
`RuntimeError: CUDA error: out of memory`
Since in Accelerate, modeling.py:373 it says:

```
  for i in range(torch.cuda.device_count()):
          _ = torch.tensor([0], device=i)
```

So when peft_model.py:167 is calling:
```
 if device_map != "sequential":
                max_memory = get_balanced_memory(
                    model,
                    max_memory=max_memory,
                    no_split_module_classes=no_split_module_classes,
                    low_zero=(device_map == "balanced_low_0"),
                )
```

It does not respect my device_map.

**Comment by xinyual** [comment]
Hi I meet this problem too. Do you fix this? Or do you know the peft fix this problem? Can we fix this problem by changing peft code?
