### ISSUE TITLE
Implement DyLoRA

### ISSUE THREAD

**Issue by lxe** [huggingface/peft#289]
> Our DyLoRA method trains LoRA blocks for a range of ranks instead of a single rank by sorting out the representation learned by the adapter module at different ranks during training.

>  Our results show that we can train dynamic search-free models with DyLoRA at least 7× faster than LoRA without significantly compromising performance.

https://arxiv.org/pdf/2210.07558.pdf

Example code:

https://github.com/huawei-noah/KD-NLP/tree/main/DyLoRA

**Comment by eware-godaddy** [comment]
This would be amazing. 🙏

**Comment by mojivalipour** [comment]
I just prepared an implementation of DyLoRA on top of PEFT, need further test and some training adjustments. In the meanwhile, let me know what I should consider before making a PR.

https://github.com/mojivalipour/peft

**Comment by mojivalipour** [comment]
> This is amazing. Just started with the original paper, but curious if we can add a non-linear transformation (activation) in-between the two matrix A and B.

The proposed method is not solely for LoRA and it is applicable to any other Adaptation techniques supported in the PEFT. Therefore, it should be possible to add a non-linear transformation in between the two matrices as well. One should however investigate further the dynamic quality of different models using this technique. In any case, some minor modifications might be necessary specifically for the normalization part to achieve the best performance.
