### ISSUE TITLE
There is a problem with the parameters passed in when the example in the example folder calls the LoraModel class

### ISSUE THREAD

**Issue by zhangxixi1993** [huggingface/peft#292]
It seems that version 0.2.0 has modified the input parameters of the init function of the LoraModel class, adding the adapter_name parameter:
`def __init__(self, model, config, adapter_name):
        super().__init__()
        self.model = model
        self.forward = self.model.forward
        self.peft_config = config
        self.add_adapter(adapter_name, self.peft_config[adapter_name])`

But the example call does not pass the adapter_name parameter, you should update these examples：
`if args.use_lora:
        config = LoraConfig(
            r=args.lora_r,
            lora_alpha=args.lora_alpha,
            target_modules=UNET_TARGET_MODULES,
            lora_dropout=args.lora_dropout,
            bias=args.lora_bias,
        )
        unet = LoraModel(config, unet)
        print_trainable_parameters(unet)
        print(unet)`
This will report an error：
Traceback (most recent call last):
  File "test.py", line 33, in <module>
    unet = peft.LoraModel(config, unet)
TypeError: **__init__() missing 1 required positional argument: 'adapter_name'**

**Comment by pacman100** [comment]
Hello @zhangxixi1993, PR #295 should fix this, thank you for bringing this to our notice
