### ISSUE TITLE
ValueError: Target modules ['q_proj', 'v_proj'] not found in the base model. Please check the target modules and  try again.

### ISSUE THREAD

**Issue by satani99** [huggingface/peft#294]
I'm using gtp-neox-20b model, how to solve this? 
Thanks

**Comment by sebastianschramm** [comment]
Hi @satani99, how does your lora config look like - are you setting `target_modules` explicitly?

EleutherAI/gpt-neox-20b is a model of model_type="gpt_neox" as mentioned in their config: https://huggingface.co/EleutherAI/gpt-neox-20b/blob/main/config.json#L15

LoraConfig.target_modules for gpt_neox models is ["query_key_value"].

You have two options to solve your issue:

1. set LoraConfig.target_modules=['query_key_value']
2. set LoraConfig.target_modules=None (then peft will figure out the correct target_modules based on the model_type)

Hope that helps
