### ISSUE TITLE
LoRA for SequenceClassification models do not save output layer weights

### ISSUE THREAD

**Issue by albarji** [huggingface/peft#310]
## Expected behavior

When using PEFT with a `LoraConfig` to train a SequenceClassification model there should be a way to save the adapter weight matrices added by LoRA inside the attention blocks, as well as the classification head added for the classification task, which is also tuned as part of the training process. In this way, one could recover the trained model at a later stage and use it for inference.

## Observed behavior

After training the model, the `save_pretrained` method produces an `adapter_model.bin` that only contains the weight matrices for the attention blocks. The weights for the classification head are not included.

Conversely, if one uses the `save_pretrained`  method of the `base_model`, a `pytorch_model.bin` file is produced , containing the weights for the classification head but not for the adapter layers.

I have been unable to find a way to save both the adapter weights and the classification weights into the same file.

## Environment

```
datasets                  2.10.1
peft                      0.2.0
tokenizers                0.11.4
transformers              4.24.0
Python 3.10.9
```

## Script to reproduce

```python
from datasets import load_dataset
from peft import LoraConfig, TaskType, get_peft_model
import torch
from torch.optim import AdamW
from torch.utils.data import DataLoader
from transformers import AutoModelForSequenceClassification, AutoTokenizer

model_name = "roberta-base"

# Prepare data
dataset = load_dataset("tweet_eval", "emotion")
num_labels = num_labels = len(set(dataset["train"]["label"]))
tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenized_dataset = dataset.map(
    lambda example: tokenizer(example["text"], max_length=60, padding='max_length', truncation=True),
    batched=True
)
tokenized_dataset.set_format(type='torch', columns=['input_ids', 'attention_mask', 'label'])
tokenized_dataset = tokenized_dataset.remove_columns(["text"]).rename_column("label", "labels")
train_dataloader = DataLoader(tokenized_dataset["train"], shuffle=True, batch_size=16)

# Prepare model
peft_config = LoraConfig(TaskType.SEQ_CLS, model_name, r=8, lora_alpha=8, lora_dropout=0.1)
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=num_labels)
if peft_config is not None:
    model = get_peft_model(model, peft_config)
model = model.to("cuda")

# Prepare optimizer
optimizer = AdamW(params=model.parameters(), lr=1e-5)

# Single epoch training loop
for batch in train_dataloader:
    for key in batch:
        batch[key] = batch[key].to("cuda")
    outputs = model(**batch)
    loss = outputs.loss
    loss.backward()
    optimizer.step()
    optimizer.zero_grad()
    
# Save model
model.save_pretrained("tmp/lora_model")
model.base_model.save_pretrained("tmp/base_model")
```

**Comment by pacman100** [comment]
Hello, please use kwargs for LoraConfig as it isn't being properly created in your case. Having `LoraConfig(task_type=TaskType.SEQ_CLS, r=8, lora_alpha=8, lora_dropout=0.1)` should resolve your issue

**Comment by albarji** [comment]
You are totally correcty, I don't know how I ended up with such a configuration. 🤦‍♂️ 

After using your suggestion the classification head is saved perfectly fine. Thanks a lot! And kudos for the great work on PEFT! 👍
