### ISSUE TITLE
Questions about 8-bit finetuning with LORA?

### ISSUE THREAD

**Issue by dhairyadalal** [huggingface/peft#319]
I'm trying to run experiments with the T5 family of models around a combination of pretraining and fine-tuning strategies. I'd like to also explore the scaling effects of these strategies with larger models but I have limited computing resources. So I'm looking into LORA and 8-bit optimization methods. A few questions:

- What is the difference between the Transformers `load_in_8bit` flag and using the bnb 8-bit Adam optimizer in the context of finetuning? Can they be both used at the same time or are they mutually exclusive? 
- Additionally, from the PEFT examples, I notice that all examples use "load_in_8bit". Does that mean the 8-bit optimizer is not supported?
- If I want to finetune an 8-bit model with LORA, can I  merge the LORA layers with the base model? If not, what would be the requirements for future inference?
- Finally, trying to understand what the relative performance differences are between full-finetuning vs finetuning the 8bit models w/ LORA. Is the performance difference minor or significant? Can I make claims that the finetuning w/ 8bit and LORA should be analogous to full finetuning>

**Comment by dhairyadalal** [comment]
Closing this issue. After some research I think I have a better understanding of all these methods. For those who are interested:

8-bit optimizers vs 8-bit model loading
- When you load a model with 8-bit quantization eg:
`model = AutoModelForSeq2SeqLM.from_pretrained("t5-3b", device_map="auto", load_in_8bit=True)`, that model can't be finetuned. 8-bit quantization is meant for inference only. 
- You can, however, use 8-bit loading w/ LoRA, as the base model's weights are frozen and LoRA introduces new trainable parameters. PEFT has a special lora get method to support 8-bit finetuning. The following is an example of loading a model in 8-bit and preparing for finetuning with LoRA
`from peft import LoraConfig, TaskType, get_peft_model, PeftModelForSeq2SeqLM
from peft import LoraConfig, get_peft_model, prepare_model_for_int8_training, TaskType

# Load model w/ 8-bit quantization.
model = AutoModelForSeq2SeqLM.from_pretrained(
    config["alias"],
    device_map="auto",
    load_in_8bit=True
)

# Define LoRA Config
lora_config = LoraConfig(
 r=16,
 lora_alpha=32,
 target_modules=["q", "v"],
 lora_dropout=0.05,
 bias="none",
 task_type=TaskType.SEQ_2_SEQ_LM
)

# prepare int-8 model for training
model = prepare_model_for_int8_training(model)

# add LoRA adaptor
model = get_peft_model(model, lora_config)
model.print_trainable_parameters()
`
- If you are able to load a model fully into memory and don't need 8-bit quantization, then the 8-bit optimizer can be used for more memory-efficient training. 

With respects to my other questions, I'm still running experiments to evaluate the efficacy of these methods for training.

**Comment by dkakaie** [comment]
@dhairyadalal What about merging lora into base model? Any sample code? I'm specially interested in merging weights after finetuning Whisper models.

**Comment by dhairyadalal** [comment]
> @dhairyadalal What about merging lora into base model? Any sample code? I'm specially interested in merging weights after finetuning Whisper models.

@dkakaie Sure. So there are a couple of scenarios for merging. If you loaded the base models with full precision then it's straightforward, just call the merge and unload method, eg 
```
[...  training ... ]
model = model.merge_and_unload() 
```

If you loaded the base model with 8-bit precision, its a bit trickier. You'll need to first save the lora weights. Load another copy of the base model into memory with 16-bit precision. Then reload the LoRA weights using from pretrained model and the half precision base model. Finally you can call merge and unload. Note this method is a bit dicey with larger models (had issues with FLAN-XXL (11B) and FLAN-UL2  (20B). Still trying to figure out the issue. Here's the sample code for what I described above. 
```
[... training ... ]

# 1. save the LoRA weights after finetuning 
model.save_pretrained("testing/lora_weights/")

# 2. Reload the base model with w/ FP16
base_model_half = AutoModelForSeq2SeqLM.from_pretrained(
    config["alias"],
    device_map="auto",
    torch_dtype=torch.float16 # Load model in FP16
)

# 3. Reload LoRA weights w/ the 
model = PeftModelForSeq2SeqLM.from_pretrained(
   base_model_half, 
   model_id="testing/lora_weights/"
)

# 4. Merge and unload 
model = merged_model.merge_and_unload()
```

Hope that helps

**Comment by dkakaie** [comment]
@dhairyadalal Very nice explanation. Thankyou.
