### ISSUE TITLE
Where can I find the documentation of PEFT?

### ISSUE THREAD

**Issue by ZeyiLiao** [huggingface/peft#320]
Where can I find the documentation of PEFT?

**Comment by pacman100** [comment]
Hello @ZeyiLiao, currently all the info is in the README and examples folder. We are working on adding docs, it will be available in the next release.

**Comment by AngledLuffa** [comment]
It would be excellent to have some documentation on what options are available for `LoraConfig` and what the equivalent is for prefix tuning (and the other adapter types).  Thanks!
