### ISSUE TITLE
Unrecognized configuration class  GPT2 

### ISSUE THREAD

**Issue by djaym7** [huggingface/peft#333]
peft                         0.3.0.dev0

ValueError: Unrecognized configuration class <class 'transformers.models.gpt2.configuration_gpt2.GPT2Config'> for this kind of AutoModel: AutoModelForSeq2SeqLM.
Model type should be one of BartConfig, BigBirdPegasusConfig, BlenderbotConfig, BlenderbotSmallConfig, EncoderDecoderConfig, FSMTConfig, GPTSanJapaneseConfig, LEDConfig, LongT5Config, M2M100Config, MarianConfig, MBartConfig, MT5Config, MvpConfig, NllbMoeConfig, PegasusConfig, PegasusXConfig, PLBartConfig, ProphetNetConfig, SwitchTransformersConfig, T5Config, XLMProphetNetConfig.

**Comment by djaym7** [comment]
This seems to be transformers issue

**Comment by dddddjcole** [comment]
How to solve it? bro
