### ISSUE TITLE
How to use PEFT to wrap an encoder?

### ISSUE THREAD

**Issue by AngledLuffa** [huggingface/peft#348]
For the use case of training downstream models which aren't exactly token classification or sequence classification, I have been using Bert, Roberta, etc models as encoders to get context sensitive embeddings.

```
# model is a transformers.models.roberta.modeling_roberta.RobertaModel for roberta-large for example
feature = model(padded_input, attention_mask=attention_mask, output_hidden_states=True)
# from here, use feature as a replacement / another dimension similar to word2vec, glove, etc
```

I cannot use a peft model as a dropin replacement, as far as I can tell, because it is always passing `labels` to the underlying model, even when there are no labels.  So, for example, I just got the stack trace

```
<snip>
/home/john/stanza/stanza/models/common/bert_embedding.py:388 in extract_bert_embeddings
/usr/local/lib64/python3.9/site-packages/torch/nn/modules/module.py:1190 in _call_impl
/usr/local/lib/python3.9/site-packages/peft/peft_model.py:823 in forward
/usr/local/lib64/python3.9/site-packages/torch/nn/modules/module.py:1190 in _call_impl
TypeError: forward() got an unexpected keyword argument 'labels'
```

which goes through here:

```
class PeftModelForTokenClassification(PeftModel):
<snip>
        if not isinstance(self.peft_config, PromptLearningConfig):
            return self.base_model(
                input_ids=input_ids,
                attention_mask=attention_mask,
                inputs_embeds=inputs_embeds,
                labels=labels,
                output_attentions=output_attentions,
                output_hidden_states=output_hidden_states,
                return_dict=return_dict,
                **kwargs,
            )
```

It looks like the same code path is here in the current git repo:

https://github.com/huggingface/peft/blob/2822398fbe896f25d4dac5e468624dc5fd65a51b/src/peft/peft_model.py#L1067

still with the `labels` parameter

I created the peft model as follows:

```
# first, load a RobertaModel into bert_model
peft_config = LoraConfig(task_type=TaskType.TOKEN_CLS, inference_mode=False, r=8, lora_alpha=32, lora_dropout=0.1)            
bert_model = get_peft_model(bert_model, peft_config)
```

All of the forward() calls for the different peft models use a `labels` field, so I don't think there's a different TaskType I could have chosen which would not have this issue.

My approach in the models we built so far is to get the embedding from the model, then backprop into the RobertaModel based on the errors of the downstream task to finetune the roberta.  My hope was to use a PeftModel as a dropin replacement for that.  Is that a reasonable goal?  If so, how would I do that?  If there's no way to currently do that, is that a planned feature for the future?

The version of transformers we used was 4.25.0.dev0, and peft was just installed today, although I do not think the transformers package makes a big difference, as the current version still does not have a `labels` parameter:

https://github.com/huggingface/transformers/blob/8a817e1ecac6a420b1bdc701fcc33535a3b96ff5/src/transformers/models/roberta/modeling_roberta.py#L750

Thanks in advance!

**Comment by AngledLuffa** [comment]
What do you think of #351 as a template for an update?  Currently I only did it for my own personal use case...

**Comment by AngledLuffa** [comment]
I think this is still relevant, at least until there's a way to put a custom model on top of a transformer

**Comment by bvlourenco** [comment]
I'm also with the same problem :point_up_2:

**Comment by pacman100** [comment]
I believe, there needs to be another TaskType called `EMBEDDINGS` which would enable PEFT without a head on top, will put this in backlog. Thank you for your patience

**Comment by AngledLuffa** [comment]
Thanks for the follow-up!  Is this something where you'd want me to start a PR, or will HF take this on?
