### ISSUE TITLE
Training the embedding layer

### ISSUE THREAD

**Issue by SOCSChamp** [huggingface/peft#349]
Hey all,

I've been struggling the past day trying either add the embedding layer as a fully trained layer or use it with LoRA.  

For context, I'm trying this with the new StableLM model but I've also tried it with LLaMA (various sizes).  I'm trying to do int8 LoRA training, but my previous runs have led me to believe that I need to train the embedding layer as well in order to better understand my dataset.

```
model = AutoModelForCausalLM.from_pretrained(
    base_model, 
    cache_dir=hfcache,
    torch_dtype=torch.float16,
    load_in_8bit=True,
    device_map="auto",
    )
```
I first tried casting the layer to float32 and marking it as trainable, then passing it as "modules_to_save:

```
for name, param in model.named_parameters():
    if "embed_in" in name:
        param.data = param.data.to(torch.float32)
        param.requires_grad=True
        print(f"{name}: dtype = {param.dtype}")

lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    target_modules=["query_key_value"],
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
    modules_to_save="embed_in"
)

model = get_peft_model(model, lora_config)

```

In this case, I get the error:
RuntimeError: only Tensors of floating point and complex dtype can require gradients

It's the same error I get whether or not I cast the embedding layer to float32, leave it as is, or mark it as trainable.

If I add "embed_in" to target_modules instead, to train an adapter for it, I get:
AttributeError: 'Embedding' object has no attribute 'bias'

Please tell me if I'm using this wrong, and I'm open to suggestions for alternate ways to do this.  I'm currently writing a workaround for my case, but I feel like this would be a nice thing to have working out of the box for peft if possible.

Thanks!

**Comment by pacman100** [comment]
Hello @SOCSChamp, I got the embedding layer to be trainable, developing on top of https://github.com/huggingface/peft/blob/main/examples/int8_training/Finetune_opt_bnb_peft.ipynb.
Also, note that following changes are to make it work with INT8 training, normal PEFT training with other integrations like DeepSpeed would work without the changes below.

Steps:
1. Embedding layers needs to be casted to FP32 to make it trainable as INT8 loading casts all layers to FP16/INT8. Skip this if you are not doing INT8 based training.
```
from peft import prepare_model_for_int8_training

model = prepare_model_for_int8_training(model)
param = model.model.decoder.embed_tokens.weight
param.data = param.data.to(torch.float32)
``` 

2. Include the layer name in `modules_to_save`:
```
from peft import LoraConfig, get_peft_model

config = LoraConfig(
    r=16, lora_alpha=32, target_modules=["q_proj", "v_proj"], lora_dropout=0.05, bias="none", task_type="CAUSAL_LM",
    modules_to_save=["embed_tokens"]
)

model = get_peft_model(model, config)
model.print_trainable_parameters()
```

3. This increases trainable params by a lot though, in the above case to 6% params:
```
trainable params: 420216832 || all params: 6872776704 || trainable%: 6.114222098259516
```

4. Post training ckpt size and weights:
<img width="1123" alt="Screenshot 2023-04-28 at 12 02 47 PM" src="https://user-images.githubusercontent.com/13534540/235072042-b08ac034-f1ae-416e-9ce3-08e359db58ef.png">

**Comment by iMountTai** [comment]
@pacman100  Can you list the type of GPU you use and the related environment configuration?

**Comment by pacman100** [comment]
Hello @iMountTai, see this comment for end to end working example: https://github.com/huggingface/peft/pull/337#issuecomment-1527412343

**Comment by iMountTai** [comment]
> Hello @iMountTai, see this comment for end to end working example: [#337 (comment)](https://github.com/huggingface/peft/pull/337#issuecomment-1527412343)

Thanks. I'll try

**Comment by xiaoyunwu** [comment]
> Hello @SOCSChamp, I got the embedding layer to be trainable, developing on top of https://github.com/huggingface/peft/blob/main/examples/int8_training/Finetune_opt_bnb_peft.ipynb. Also, note that following changes are to make it work with INT8 training, normal PEFT training with other integrations like DeepSpeed would work without the changes below.
> 
> Steps:
> 
> 1. Embedding layers needs to be casted to FP32 to make it trainable as INT8 loading casts all layers to FP16/INT8. Skip this if you are not doing INT8 based training.
> 
> ```
> from peft import prepare_model_for_int8_training
> 
> model = prepare_model_for_int8_training(model)
> param = model.model.decoder.embed_tokens.weight
> param.data = param.data.to(torch.float32)
> ```
> 
> 2. Include the layer name in `modules_to_save`:
> 
> ```
> from peft import LoraConfig, get_peft_model
> 
> config = LoraConfig(
>     r=16, lora_alpha=32, target_modules=["q_proj", "v_proj"], lora_dropout=0.05, bias="none", task_type="CAUSAL_LM",
>     modules_to_save=["embed_tokens"]
> )
> 
> model = get_peft_model(model, config)
> model.print_trainable_parameters()
> ```
> 
> 3. This increases trainable params by a lot though, in the above case to 6% params:
> 
> ```
> trainable params: 420216832 || all params: 6872776704 || trainable%: 6.114222098259516
> ```
> 
> 4. Post training ckpt size and weights:
> 
> <img alt="Screenshot 2023-04-28 at 12 02 47 PM" width="1123" src="https://user-images.githubusercontent.com/13534540/235072042-b08ac034-f1ae-416e-9ce3-08e359db58ef
@pacman100  what is the easiest way to not not save the embedding for every token, but only for the newly added tokens? Thank.s

**Comment by dougie-r2** [comment]
@pacman100 Hi, I want to do the same thing as @SOCSChamp asked. I tried your answer except no.1 and it didn't work. I skipped no.1 since I do not intend to do quantization right now. I did like the following codes.
```
peft_config = LoraConfig(
    task_type=TaskType.SEQ_CLS,
    target_modules=["query", "key", "value"],
    modules_to_save=["word_embeddings", "classifier"],
    inference_mode=False, 
    r=16,
    lora_alpha=64,
    lora_dropout=0.0, 
    bias="none"
)

lora_model = get_peft_model(base_model, peft_config)
lora_model.print_trainable_parameters()
```
And I checked whether the embedding module can be trained or not.
```
a_token_num = 28696
emb_layer = base_model.roberta.embeddings.word_embeddings
emb_token = emb_layer(torch.tensor(a_token_num))

merged_model = lora_model.merge_and_unload()
emb_layer2 = merged_model2.roberta.embeddings.word_embeddings
emb_token2 = emb_layer2(torch.tensor(a_token_num))

emb_token == emb_token2
```
**emb_token** and **emb_token2** is exactly same. not changed a bit.
What did I miss?
Thx!!
