### ISSUE TITLE
load_in_8bit=True but loss=0.0 when training the llama

### ISSUE THREAD

**Issue by iMountTai** [huggingface/peft#350]
code is:
```
model = LlamaCausalLM.from_pretrained(path, load_in_8bit=True,device_map="auto")
model = prepare_model_for_int8_training(model)
mdoel = get_peft_model(model, peft_config)
model.print_trainable_parameters()
```
![image](https://user-images.githubusercontent.com/35353688/233516123-a96120d7-aac5-4f57-b8ee-074a5fe189e4.png)

![image](https://user-images.githubusercontent.com/35353688/233516243-84c3681b-3126-4de0-b714-fbb718686f7c.png)
platform:
```
torch1.12cu113
python3.8.16
peft=0.3.0.dev0
transformers=4.29.0.dev0
```
And the model works well with fp16.

**Comment by iMountTai** [comment]
This is because `module_to_svae =["embed.tokens", "lm_head"]`,What should I do about it

**Comment by iMountTai** [comment]
@pacman100 Look forward to your help, thank you!

**Comment by huijiawu0** [comment]
same problem, not solved yet.

**Comment by adibMosharrof** [comment]
I am getting the same issue

**Comment by adibMosharrof** [comment]
what GPU are you using @iMountTai 

please take a look into this issue

https://github.com/TimDettmers/bitsandbytes/issues/240

**Comment by iMountTai** [comment]
> what GPU are you using @iMountTai
> 
> please take a look into this issue
> 
> [TimDettmers/bitsandbytes#240](https://github.com/TimDettmers/bitsandbytes/issues/240)

Thank you for your reply. GPU is A40.GPUs detected 8.6.But there are still the same problems

**Comment by DanqingZ** [comment]
Hi, I think this is due to your peft version. Mine is : peft  0.4.0.dev0

You can install this by running
```
pip install git+https://github.com/huggingface/peft.git
```

**Comment by adibMosharrof** [comment]
should it be "embed_tokens" instead of "embed.tokens"
