### ISSUE TITLE
'LoraConfig' object is not subscriptable

### ISSUE THREAD

**Issue by zhouliang-yu** [huggingface/peft#357]
Hey! thx so much for your work!
I am working on using lora to fine-tune Unet in the stable diffusion

The following code is what I did: 
```python
from transformers import AutoTokenizer, AutoConfig, AutoModelForCausalLM
from diffusers import AutoencoderKL, DDPMScheduler, DiffusionPipeline, UNet2DConditionModel
unet = UNet2DConditionModel.from_pretrained(
    "stabilityai/stable-diffusion-2-1", subfolder="unet", torch_dtype=torch.float16
)

from peft import get_peft_config, get_peft_model, LoraConfig, TaskType, LoraModel
peft_config = LoraConfig(
    task_type=TaskType.SEQ_2_SEQ_LM, inference_mode=False, r=8, lora_alpha=32, lora_dropout=0.1
)
unet = LoraModel(model=unet,config=peft_config,adapter_name="unet_adapter")
```
Then it just met an **error** says: **"'LoraConfig' object is not subscriptable"**

the system and package I am using is:
1. python==3.9.16
2. transformers==4.29.0.dev0
3. diffusers==0.15.1
4. peft==0.3.0.dev0

does anyone know how to solve this problem?

**Comment by TalhaSheikh-dev** [comment]
peft expects the model to have a config file with it. so if you are using a custom model other then hugging face model you need to wrap the model with hugging face classes   or somehow add config to your model. below article worked for me 
https://huggingface.co/docs/transformers/custom_models#sharing-custom-models

**Comment by zhouliang-yu** [comment]
> peft expects the model to have a config file with it. so if you are using a custom model other then hugging face model you need to wrap the model with hugging face classes or somehow add config to your model. below article worked for me https://huggingface.co/docs/transformers/custom_models#sharing-custom-models

thx so much @TalhaSheikh-dev
