### ISSUE TITLE
what's the content for   INSTANCE_DIR  and $CLASS_DIR \ in for parameter efficient dreambooth training, any ready-for-use example?

### ISSUE THREAD

**Issue by SeekPoint** [huggingface/peft#369]

**Comment by stevhliu** [comment]
The `INSTANCE_DIR` is a path to the folder containing the images you want to train the model on (you can check out the script [here](https://github.com/huggingface/peft/blob/632997d1fb776c3cf05d8c2537ac9a98a7ce9435/examples/lora_dreambooth/train_dreambooth.py#L96)).

I believe `CLASS_DIR` is used if you're training with prior preservation, and you can use other images from the same class. This is a path to the folder containing these class images.
