### ISSUE TITLE
HuggingFace Inference API Support

### ISSUE THREAD

**Issue by LeVuMinhHuy** [huggingface/peft#370]
Hi all,

I tuned the LLM CodeGen-6B-Mono with LoRA using Peft, and shared that adapter to the hub 

Then I want to try Hosted Inference API of HF on that and config the medata as below

![image](https://user-images.githubusercontent.com/36370320/234548921-3ad69198-dfb3-4c26-836b-2b8135c77b0c.png)

But when I call the api, this error happened

```
 "error": "text-generation is not a valid pipeline for model : mhhmm/codegen-6B-lora"
```

If we click into [Use in Transformers] option:

```
from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("mhhmm/codegen-6B-LoRA")

model = AutoModelForCausalLM.from_pretrained("mhhmm/codegen-6B-LoRA")
```

Any support for this API or any thing I can do? Do I need to create a new lib in [HF API Inference Community](https://github.com/huggingface/api-inference-community) for this ?

Thank you guys in advance !  

My model: https://huggingface.co/mhhmm/codegen-6B-lora

**Comment by younesbelkada** [comment]
THis should be now supported altogether with transformers integration! Closing it

**Comment by coeuskoalemoss** [comment]
> THis should be now supported altogether with transformers integration! Closing it

I'm still getting this error

**Comment by BenjaminBossan** [comment]
@coeuskoalemoss Could you please give a detailed description of the error that you encounter? What model are you using, what are you trying to do, what is the error?
