### ISSUE TITLE
OSError: Token is required (`token=True`), but no token found. 

### ISSUE THREAD

**Issue by SeekPoint** [huggingface/peft#371]
OSError: Token is required (`token=True`), but no token found. You need to provide a token or be logged in to Hugging Face with `huggingface-cli login` or `huggingface_hub.login`. See 
https://huggingface.co/settings/tokens.

**Comment by SeekPoint** [comment]
TBD

**Comment by pacman100** [comment]
Hello, please share clearly the issue, minimal reproducer and expected behaviour.
