### ISSUE TITLE
Hi, for doing Bert or roberta or any automodel class classification task

### ISSUE THREAD

**Issue by shan23chen** [huggingface/peft#377]
```
    lora_config = LoraConfig(
        r=16, 
        lora_alpha=32,
        target_modules=["q", "v"],
        lora_dropout=0.05,
        bias="none",
        task_type=TaskType.TOKEN_CLS
        )
```
do I set the task_type=TaskType.TOKEN_CLS?
Also, why I am hitting ValueError: Target modules ['q', 'v'] not found in the base model. Please check the target modules and try again.

Thanks a bunch!

**Comment by stevhliu** [comment]
> do I set the task_type=TaskType.TOKEN_CLS?

Hi! You can find the available `TaskType`'s [here](https://github.com/huggingface/peft/blob/632997d1fb776c3cf05d8c2537ac9a98a7ce9435/src/peft/utils/config.py#L36). For token classification it is `TOKEN_CLS` and for sequence classification it is `SEQ_CLS`.

> Also, why I am hitting ValueError: Target modules ['q', 'v'] not found in the base model. Please check the target modules and try again.

I think you need to use `target_modules=["query", "value"]` if you're using BERT or RoBERTa (take a look at the Transformers model to LoRA target module [mapping](https://github.com/huggingface/peft/blob/632997d1fb776c3cf05d8c2537ac9a98a7ce9435/src/peft/utils/other.py#L202)).
