### ISSUE TITLE
How to be compatible with the old version of lora?

### ISSUE THREAD

**Issue by ethanyklei** [huggingface/peft#379]
Hi, I pull the repo for the newest version in recently. But I find I can not load my lora adapter weight which is trained on the old version. 

I find in my old version, the lora adapter consists of a linear layer and a Conv1d layer. 
It is different with the newest lora adapter which consists of two linear layer. 

Do you have any way to convert the old weights to be compatible with the new version? 

old version:
```python 
self.lora_A = nn.Linear(in_features, r * sum(enable_lora), bias=False)
self.lora_B = nn.Conv1d(
                r * sum(enable_lora),
                out_features // len(enable_lora) * sum(enable_lora),
                kernel_size=1,
                groups=2,
                bias=False,
            )
```

new version:
```python 
self.lora_A.update(nn.ModuleDict({adapter_name: nn.Linear(self.in_features, r, bias=False)}))
self.lora_B.update(nn.ModuleDict({adapter_name: nn.Linear(r, self.out_features, bias=False)}))
```

**Comment by afalf** [comment]
@ethanyklei Hi, I have met the same problem, are you solved it?

**Comment by J000Z** [comment]
I also have this issue. Do you have any solution to it?

**Comment by pacman100** [comment]
Hello, as mentioned in https://github.com/huggingface/peft/issues/276#issuecomment-1508006734, this is a breaking change unfortunately. Please retrain the model with the latest version
