### ISSUE TITLE
loop decode result from finetuning whisper large v2

### ISSUE THREAD

**Issue by v-yunbin** [huggingface/peft#380]
finetuning on whisper large v2
when test a 9s audio，finetuning model get a loop result：“嗯 嗯 嗯 嗯 嗯 嗯 嗯 嗯 嗯 嗯 嗯 嗯 嗯 嗯 嗯 嗯 嗯 嗯 嗯 嗯” ，but base whisper large v2 get a normal result.
when test a 30s audio，finetuning model and base whisper large v2 all are normal.

**Comment by v-yunbin** [comment]
solved

**Comment by mohblnk** [comment]
> solved

and how did you solve it?
