### ISSUE TITLE
fp16=true, taking more GPU memory on llama

### ISSUE THREAD

**Issue by ruian0** [huggingface/peft#381]
I set fp16=true but I saw that the model is taking more memories, below is my code
model_path is llama weights-13b
```
model = AutoModelForSequenceClassification.from_pretrained(model_path, device_map='auto')
peft_config = LoraConfig(
    task_type=TaskType.SEQ_CLS, 
    inference_mode=False, 
    r=8, 
    lora_alpha=32, 
    lora_dropout=0.1, 
    target_modules=["q_proj", "v_proj"]
)
model = get_peft_model(model, peft_config)


training_args = TrainingArguments(
   ...
    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,
    gradient_accumulation_steps=8, 
    fp16=True,
    tf32=True,
    eval_accumulation_steps=1
    ...
)
```
I do notice that for such classification task with max_sql_length=1024, setting fp16=true takes ~65GB while fp=false takes ~55GB memory. I'm so confused since setting fp16=true should use less GPU memory. Thanks for any suggestions in advance!

**Comment by IMbackK** [comment]
This is expected, in 16bit mode you have another copy of the model in 16bit in vram.
