### ISSUE TITLE
Better warning message or error when target module names are not available

### ISSUE THREAD

**Issue by sayakpaul** [huggingface/peft#40]
If we do:

```py
from peft import LoraConfig, LoraModel
from transformers import AutoModelForImageClassification


model_checkpoint = "google/vit-base-patch32-224-in21k"
label2id = {"dog": 0, "cat": 1, "mouse": 2}
id2label = {v: k for k, v in label2id.items()}
model = AutoModelForImageClassification.from_pretrained(
    model_checkpoint, 
    label2id=label2id,
    id2label=id2label,
    ignore_mismatched_sizes = True, 
)

config = LoraConfig(
    r=16,
    lora_alpha=16,
    target_modules=["q_proj", "v_proj"],
    lora_dropout=0.0,
    bias="none",
)
model = LoraModel(config, model)
```

This wouldn't have any effect and will lead to errors during training because the `target_modules` were incorrectly named inside `LoraConfig`. When this case arises, it would help to throw a warning message so that the users can look into the issue with more information.

**Comment by pacman100** [comment]
Above PR should resolve this issue by raise error. For the example you specified in the issue description, following is the error message that will be raised

<img width="994" alt="Screenshot 2023-02-02 at 1 33 19 PM" src="https://user-images.githubusercontent.com/13534540/216266114-0a48b718-44be-40e0-8a3a-b52ca27f767c.png">

**Comment by nameless0704** [comment]
> Above PR should resolve this issue by raise error. For the example you specified in the issue description, following is the error message that will be raised
> 
> ```
> ValueError: Target modules ['q_proj', 'v_proj'] not found in the base model. Please check the target modules and 
> try again.
> ```

I know maybe it's a different question but how do I solve this if I get this error? How to know what target module name I need?

**Comment by satani99** [comment]
hi @nameless0704, did you get any solution for the error?
My error was solved by changing target module to ["query_key_value"] but I don't know how to find for different models?

**Comment by pacman100** [comment]
Hello, for models that aren't in the https://github.com/huggingface/peft/blob/main/src/peft/utils/other.py#L202, you need to look into the `modeling_*.py` file in transformers https://github.com/huggingface/transformers/tree/main/src/transformers/models

**Comment by panpan0000** [comment]
for example, you can `vim` to view your model layout file like `pytorch_model.bin.index.json`
you can see something like 
`model.layers.3.self_attn.q_proj.weight`

or
`transformer.encoder.layers.5.self_attention.query_key_value.weight`

**Comment by karnikkanojia** [comment]
Can you help me understand what parameter will it be in this model, I can see there is nothing like ```q_proj``` like in the original phi model. The repo id is following: TheBloke/phi-2-GPTQ/modeling_phi.py
