### ISSUE TITLE
Can we fine-tune mpt-7b base model using training script  used for gpt-neo-20b itself

### ISSUE THREAD

**Issue by sujithjoseph** [huggingface/peft#405]
Trying to figure out how to fine-tune mpt-7b model using PEFT itself.

**Comment by DavraYoung** [comment]
I am also very interested in that topic, is there any guide on how to train mpt with PEFT?

**Comment by Taytay** [comment]
This is being discussed in the Mosaic LLM Foundry Repo : https://github.com/mosaicml/llm-foundry/issues/64

**Comment by tirthajyoti** [comment]
This is an important topic
