### ISSUE TITLE
Prefix Tuning Seq Classification tensor size

### ISSUE THREAD

**Issue by ivy2315** [huggingface/peft#407]
I modify **sequence_classification/prefix_tuning.ipynb** to fit my task
my task is a multi-label classification.
 I am getting the following error:
“RuntimeError: The size of tensor a (512) must match the size of tensor b (492) at non-singleton dimension 1”

I don't know why I am getting this.
What is tensor b (492)?

I only put my datasets in, and add "num_labels=3".
`model = AutoModelForSequenceClassification.from_pretrained(model_name_or_path, return_dict=True, num_labels=3)`
model: bert-base-uncased

**Comment by diaoenmao** [comment]
It seems like this example is not working

**Comment by diaoenmao** [comment]
After reading many closed issues, I figured out the issue is the version of transformer is low. After I upgrade to the latest version, there is no error with prefix tuning.

**Comment by suntea233** [comment]
I have upgrade transformer to 4.31.0, but i met the same issue when training for seq2seq with prefix tuning.
