### ISSUE TITLE
Add support for T-Few

### ISSUE THREAD

**Issue by lewtun** [huggingface/peft#42]
T-Few is a PEFT method for few-shot learning that is currently the SOTA on many NLP benchmarks. It uses a nifty technique called (IA)^3 to update a small number of parameters during training and would be an impactful method to include IMO.

Although research code exists, it is tightly bound to the paper and doesn't run easily on hardware that isn't an 80GB A100. The `peft` library could help make this work more accessible to industry practitioners (where few-shot is actually valuable)

cc @craffel

Paper: https://arxiv.org/abs/2205.05638
GitHub: https://github.com/r-three/t-few

**Comment by sayakpaul** [comment]
(IA)^3 is already in the backlog: https://github.com/huggingface/peft#backlog

**Comment by savasy** [comment]
IA^3 is already implemented here
https://github.com/adapter-hub/adapter-transformers

I will give it a try
