### ISSUE TITLE
Deepcopy not copying the LoraConfig

### ISSUE THREAD

**Issue by glerzing** [huggingface/peft#424]
I'm trying to make a deepcopy (using copy.deepcopy) of a LoraModel on the version '0.2.0'. But the values in PeftConfig remain the default ones (e.g. r = 8), not the ones of the copied model. Is it normal ? Am I supposed to do a `model_copy = get_peft_model(model_copy, peft_config)` ?
It is possible to implement `__deepcopy__` and `__copy__` if necessary.

Here is a reproduction example :
``` Python
import copy
from transformers import AutoModelForCausalLM
from peft import get_peft_config, get_peft_model, LoraConfig, TaskType
model_name_or_path = "gpt2"
tokenizer_name_or_path = "gpt2"
peft_config = LoraConfig(task_type=TaskType.CAUSAL_LM, inference_mode=False, r=87, lora_alpha=32, lora_dropout=0.1)
model = AutoModelForCausalLM.from_pretrained(model_name_or_path)
model = get_peft_model(model, peft_config)

model_copy = copy.deepcopy(model)
assert(model.peft_config.r == model_copy.peft_config.r)
```

Moreover, I also get an AssertionError if I continue with :
``` Python
model_copy = get_peft_model(model_copy, peft_config)
assert(model == model_copy)
```

**Comment by glerzing** [comment]
Not stale, still a problem in the current version.

**Comment by pacman100** [comment]
Hello, the issue is because of the following property and methods of dataclass `__dict__` and `to_dict`:

![Screenshot 2023-06-27 at 5 04 30 PM](https://github.com/huggingface/peft/assets/13534540/a5132d0d-0039-47fd-851a-954bed12b014)

**Comment by pacman100** [comment]
I will look int how to resolve this as and when I have time. cc @younesbelkada, @sgugger  and @muellerzr  in case you have ideas and already encountered this before

**Comment by BenjaminBossan** [comment]
Any idea why `__dict__` was overridden in the first place? Messing with `__dict__` is almost always a bad idea. Maybe we could just remove the `property` and replace the instances of `self.__dict__` further below by `asdict(self.__dict__)`?
