### ISSUE TITLE
bits_and_bytes not support windows, how to fine-tune whisper on windows?

### ISSUE THREAD

**Issue by ILG2021** [huggingface/peft#431]
I find that peft + lora + dnd cannot train on windows, even worse, can not run on windows. So how to solve the problem?
If there a method support windows or choose other 8 bit train?

**Comment by ILG2021** [comment]
Solved by [this pip](https://pypi.org/project/bitsandbytes-windows/) But the peft+lora reference is still slow, so it is not that useful

**Comment by phineas-pta** [comment]
https://huggingface.co/docs/bitsandbytes/main/en/installation?OS+system=Windows

**Comment by phineas-pta** [comment]
starting v0.43 there's the official wheel for windows
