### ISSUE TITLE
bug of peft-lora-dreambooth training

### ISSUE THREAD

**Issue by foocker** [huggingface/peft#435]
/train_dreambooth.py", line 692, in main
    unet = LoraModel(config, unet)
TypeError: LoraModel.__init__() missing 1 required positional argument: 'adapter_name' . 

from code , 
```
class LoraModel(torch.nn.Module):
  def __init__(self, model, config, adapter_name):
          super().__init__()
          self.model = model
          self.forward = self.model.forward
          self.peft_config = config
          self.add_adapter(adapter_name, self.peft_config[adapter_name])
```
but the doc example is :
```
model = AutoModelForSeq2SeqLM.from_pretrained("t5-base")
lora_model = LoraModel(config, model).
```

**Comment by louislau1129** [comment]
Maybe you should change the way to call it as follows:
```python
from peft import get_peft_model
lora_model = get_peft_model(model, config)
```
It will call the `PeftModel` class, which has the keyword argument `adapter_name`='default'. Then it will automatically pass to the `LoraModel` according to the `peft_type`=PeftType.LORA.

**Comment by foocker** [comment]
> Maybe you should change the way to call it as follows:
> 
> ```python
> from peft import get_peft_model
> lora_model = get_peft_model(model, config)
> ```
> 
> It will call the `PeftModel` class, which has the keyword argument `adapter_name`='default'. Then it will automatically pass to the `LoraModel` according to the `peft_type`=PeftType.LORA.

my mistake. your newest code is right. but i use the old code  peft-lora-sd-dreambooth from huggingface.
