### ISSUE TITLE
decoder_inputs_embeds not set

### ISSUE THREAD

**Issue by glerzing** [huggingface/peft#439]
On the peft version '0.3.0', in `PeftModelForSeq2SeqLM`, in the function forward and for the type PROMPT_TUNING, I get into an error "TypeError: expected Tensor as element 1 in argument 0, but got NoneType" at the line 937 :
``` Python
decoder_inputs_embeds = torch.cat((prompts[:, peft_config.num_virtual_tokens :], decoder_inputs_embeds), dim=1)
```
In the parameters of forward, I defined `decoder_input_ids`, but not `decoder_inputs_embeds` which is set to None. I suppose the function should have done, maybe :
``` Python
decoder_inputs_embeds = self.word_embeddings(decoder_input_ids)
```

**Comment by glerzing** [comment]
Looks still relevant.

**Comment by pacman100** [comment]
Could you try installing from main branch and let us know if this issue still persists?

**Comment by glerzing** [comment]
I have a different error (`ValueError: You have to specify either decoder_input_ids or decoder_inputs_embeds`). Here is an example that reproduces the problem :
``` Python
from peft import PromptTuningConfig, get_peft_model, TaskType
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer

# You should also check for the other types of config
peft_config = PromptTuningConfig(
    task_type=TaskType.SEQ_2_SEQ_LM,
    num_virtual_tokens=10,
)

tokenizer = AutoTokenizer.from_pretrained("google/t5-efficient-tiny")
model = AutoModelForSeq2SeqLM.from_pretrained("google/t5-efficient-tiny")
model = get_peft_model(model, peft_config)

encoder_text = "Translate to French : Hello world !"
decoder_text = "Bonjour"
encoder_inputs = tokenizer(encoder_text, return_tensors="pt")
decoder_inputs = tokenizer(decoder_text, return_tensors="pt")
inputs = {
    **encoder_inputs,
    "decoder_input_ids": decoder_inputs.input_ids,
    "decoder_attention_mask": decoder_inputs.attention_mask,
}

# If the problem still exists, this should trigger an exception
new_logits = model(**inputs).logits
```

**Comment by glerzing** [comment]
Still relevant : I continue to get the exception

**Comment by XintianHan** [comment]
> Still relevant : I continue to get the exception

I actually got this error when using trlx for int8 training. Then I saw that you are the developer for this : )

**Comment by glerzing** [comment]
Actually, I tried with the current version (0.5.0, not yet released), and the previous problem was solved but I fall into another exception : `RuntimeError: The size of tensor a (2) must match the size of tensor b (12) at non-singleton dimension 3`.
The problem is that the decoder attention mask is extended as if the prompt was in the decoder (whereas it is in the encoder). So the decoder attention mask is too long.

@XintianHan if you want a workaround until the problem is fixed, you should probably install the latest version (`pip install git+https://github.com/huggingface/peft.git`) and remove `decoder_attention_mask` from the arguments given to the model (in the example given above, that means doing `inputs.pop("decoder_attention_mask")` before executing `new_logits = model(**inputs).logits`).
