### ISSUE TITLE
Add an example demoing the use of PEFT for ViT Image Classification

### ISSUE THREAD

**Issue by sayakpaul** [huggingface/peft#44]
PEFT has a lot of practical significance, and the best thing about it is that it's modality-agnostic and just seems to work! 

To this end, I would like to work on an example showing how PEFT can be used for ViT Image Classification (following the structure of [these scripts](https://github.com/huggingface/peft/tree/main/examples)).

I have a demo ready [here](https://github.com/huggingface/peft/pull/39#issuecomment-1406573625) (thanks to @pacman100 for this help).

I believe after #39 is merged, I can start buttoning up the code and create a PR?

@pacman100

**Comment by pacman100** [comment]
Awesome! That PR is merged, you can start with the examples 🚀. Thank you!

**Comment by sayakpaul** [comment]
@pacman100 could you assign the issue to me?
