### ISSUE TITLE
peft 0.3.0 RuntimeError: torch.cat(): expected a non-empty list of Tensors

### ISSUE THREAD

**Issue by zhangzuizui** [huggingface/peft#440]
I defined a bloom based SEQ_CLS model below:
```python
class BloomForCLS(BloomPreTrainedModel):
    def __init__(self, config):
        super().__init__(config)
        self.config = config
        self.transformer = BloomModel(config)
        self.classifier = nn.Linear(config.hidden_size, 1)

        # Initialize weights and apply final processing
        self.post_init()

    def forward(
        self,
        input_ids: torch.LongTensor,
        attention_mask: Optional[torch.Tensor] = None,
        **kwargs
    ):        
        outputs = self.transformer(input_ids, attention_mask=attention_mask)
        # (batch_size, seq_len, hidden_dim)
        last_hidden_state = outputs.last_hidden_state
        # (batch_size, hidden_dim)
        last_token_hidden_state = (
            last_hidden_state[:, -1]
            .view(last_hidden_state.shape[0], -1)
            .contiguous()
        )
        logits = self.classifier(last_token_hidden_state)
        # (batch_size,)
        logits = logits.view(-1)
        return ModelOutput(logits=logits)
```

And bug happened when run self.classifier(last_token_hidden_state).

Error log:

> File "/usr/local/lib/python3.9/dist-packages/deepspeed/runtime/zero/partitioned_param_coordinator.py", line 262, in fetch_sub_module
    self.__inflight_param_registry.pop(param).wait()
  File "/usr/local/lib/python3.9/dist-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/deepspeed/runtime/zero/partition_parameters.py", line 578, in wait
    param.data = instrument_w_nvtx(torch.cat)(partitions).view(param.ds_shape)
  File "/usr/local/lib/python3.9/dist-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
RuntimeError: torch.cat(): expected a non-empty list of Tensors

The code works fine with peft==0.1.0 or 0.2.0

**Comment by zlh1992** [comment]
have you figured out this bug?
I just meet a same one..

**Comment by zhangzuizui** [comment]
> 

I changed deepspeed zero stage to 2（3->2）, and the problem solved.

**Comment by pacman100** [comment]
Please refer https://github.com/microsoft/DeepSpeed/issues/3678
