### ISSUE TITLE
It looks like I cannot have fp16=True, when I have load_in_8bit=True and prepare_model_for_int8_training, why?

### ISSUE THREAD

**Issue by DanqingZ** [huggingface/peft#442]
Hi everyone, I tried to follow the instructions to install the latest version of the code, and I am running the experiments on a 8 x V100, 32G machine
```
pip list | grep -e transformers -e accelerate -e peft -e bitsandbytes -e datasets -e loralib -e 'torch '
accelerate               0.19.0
bitsandbytes             0.38.1
datasets                 2.12.0
loralib                  0.1.1
peft                     0.4.0.dev0
torch                    2.0.1
transformers             4.30.0.dev0
```
when I set fp16=True, I always have this error
```
grad_A = torch.matmul(grad_output, CB).view(ctx.grad_shape).to(ctx.dtype_A), RuntimeError: expected scalar type Half but found Float
```
could someone help me understand why I have this error? 

I am also training the understand the relationship between int8 training and fp16=True. I did some research and found
* INT8 training would mean using 8-bit integers to represent not only weights and activations, but also the gradients and updates during backpropagation.
* FP16 training, also known as mixed-precision training, involves using 16-bit floating point numbers during the training process. Mixed-precision training uses a mix of FP16 and FP32: the forward and backward passes of the model are computed in FP16 for speed and memory efficiency, but the weights are updated in FP32 for accuracy. Many modern GPUs can perform FP16 computations more quickly than FP32 computations, leading to faster training times.

Can int8 training and fp16 be used at the same time? If so, am I having this error because of my instance type? Thanks!

**Comment by DanqingZ** [comment]
I have error message in my log
```
/home/ubuntu/envs/danqinz_alpaca/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: WARNING: Compute capability < 7.5 detected! Only slow 8-bit matmul is supported for your GPU!
  warn(msg)
Overriding torch_dtype=None with `torch_dtype=torch.float16` due to requirements of `bitsandbytes` to enable model loading in mixed int8. Either pass torch_dtype=torch.float16 or don't pass this argument at all to remove this warning.
```

**Comment by getorca** [comment]
running int o the same issue trying to run https://github.com/huggingface/peft/blob/main/examples/int8_training/Finetune_opt_bnb_peft.ipynb

but removing the fp16=True from the `TrainingArguments` works... hesitant to do a pull request to fix as I don't know the exact cause

**Comment by psych0v0yager** [comment]
@getorca, I too have been trying to run the Opt Finetune Jupyter notebook. Try modifying the training loop with the "with torch.autocast("cuda")" parameter before the trainer.train() call. Here is my code for reference

#-------------------------------------------------------------------------------------------------------
import transformers
from datasets import load_dataset
data = load_dataset("Abirate/english_quotes")
data = data.map(lambda samples: tokenizer(samples['quote']), batched=True)

trainer = transformers.Trainer(
    model=model, 
    train_dataset=data['train'],
    args=transformers.TrainingArguments(
        per_device_train_batch_size=4, 
        gradient_accumulation_steps=4,
        warmup_steps=100, 
        max_steps=200, 
        learning_rate=2e-4, 
        fp16=True,
        logging_steps=1, 
        output_dir='outputs'
    ),
    data_collator=transformers.DataCollatorForLanguageModeling(tokenizer, mlm=False)
)
model.config.use_cache = False  # silence the warnings. Please re-enable for inference!
with torch.autocast("cuda"): 
    trainer.train()
   
#-------------------------------------------------------------------------------------------------------

For me this got rid of the current error; however, I got a new error as my training loss was stuck at 0.0000 for most of the iterations. I am not sure what the issue still is.

**Comment by withoutaword** [comment]
> 

I got the same error ,and I add autocast() too. 
As a result, I am facing the same problem that it loss stuck at 0.0000 . 
Seems like it should just cast the fwd part , but backward. 
Any idea how to fix it ?

**Comment by withoutaword** [comment]
hi @sywangyi  , would you pls help to see this issue, thanks in advance :）
