### ISSUE TITLE
Multi Adapter Training

### ISSUE THREAD

**Issue by AIshutin** [huggingface/peft#445]
Hi!

Is it possible to use 2 method configs simultaneously for training in peft library? If it's not, are there any plans for introducing support for it? If it is, how can I do it? 

In theory, it's possible to use LoRA with P-tuning methods. 

I want to do something like this:

```
lora_config = LoraConfig(...)
ptuning_config = PrefixTuningConfig(...)

model = get_peft_model(model, [lora_config, ptuning_config])
```

**Comment by PanQiWei** [comment]
theoretically it's possible, but I think current framework doesn't support such 'multiple adapter fusion'(for now you can use multiple adapters as plug-ins with single base model), to implement this, you may need to customize the code.

I've wrote something similar in #183
