### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for PeftModelForCausalLM: size mismatch for <layer>

### ISSUE THREAD

**Issue by opyate** [huggingface/peft#460]
Hi, thanks for this awesome library.

I posted an initial query here: https://huggingface.co/databricks/dolly-v2-3b/discussions/19

Reposting below.

I'm fine-tuning [dolly-v2-3b](https://huggingface.co/databricks/dolly-v2-3b). Training is invoked with [deepspeed](https://github.com/databrickslabs/dolly/blob/master/train_dolly.py#L161) which uses this [HF module](https://github.com/databrickslabs/dolly/blob/master/training/trainer.py).

Going by [this example](https://github.com/kw2828/Dolly-2.0-Series/blob/main/fine_tuning_dolly_v2_lora_alpaca.ipynb), my changes are:

```python
    model = prepare_model_for_int8_training(model, use_gradient_checkpointing=gradient_checkpointing)

    # The dimension used by the LoRA update matrices
    LORA_R = 4
    # Scaling factor
    LORA_ALPHA = 16
    LORA_DROPOUT = 0.05

    # r and alpha together control the total number of final trainable parameters when using LoRA, giving you the flexibility to balance a trade-off between end performance and compute efficiency.
    config = LoraConfig(
        r=LORA_R,
        lora_alpha=LORA_ALPHA,
        lora_dropout=LORA_DROPOUT,
        bias="none",  # Specifies if the bias parameters should be trained
        task_type="CAUSAL_LM",
        # target_modules=["q", "v"],  # I tried with/without this line
    )
    model = get_peft_model(model, config)
```

It trains successfully, and I end up with a 677kB adapter:

![image](https://github.com/huggingface/peft/assets/96808/d2f77b6b-6c7a-41ed-b710-d810c3ed3f33)

Config looks OK:

```python
from peft import PeftConfig
config = PeftConfig.from_pretrained(repo_name)
```

> Out[19]: PeftConfig(peft_type='LORA', base_model_name_or_path='databricks/dolly-v2-3b', task_type='CAUSAL_LM', inference_mode=True)

But, when I try to use the adapter with the base model, I get an error:

```python
from transformers import AutoModelForCausalLM
from peft import PeftModel
import torch

model = AutoModelForCausalLM.from_pretrained(
    config.base_model_name_or_path,
    device_map="auto",
    torch_dtype=torch.bfloat16,
    trust_remote_code=True,
)
# Load the LoRA model
inference_model = PeftModel.from_pretrained(model, repo_name)  # <-- error here
inference_model.eval()
inference_model
```

Error:

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
File <command-3660940350576262>:12
      5 model = AutoModelForCausalLM.from_pretrained(
      6     config.base_model_name_or_path,
      7     device_map="auto",
      8     torch_dtype=torch.bfloat16,
      9     trust_remote_code=True,
     10 )
     11 # Load the LoRA model
---> 12 inference_model = PeftModel.from_pretrained(model, repo_name)
     13 inference_model.eval()
     14 inference_model

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/peft/peft_model.py:181, in PeftModel.from_pretrained(cls, model, model_id, adapter_name, is_trainable, **kwargs)
    179 else:
    180     model = MODEL_TYPE_TO_PEFT_MODEL_MAPPING[config.task_type](model, config, adapter_name)
--> 181 model.load_adapter(model_id, adapter_name, **kwargs)
    182 return model

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/peft/peft_model.py:384, in PeftModel.load_adapter(self, model_id, adapter_name, is_trainable, **kwargs)
    380 adapters_weights = torch.load(
    381     filename, map_location=torch.device("cuda" if torch.cuda.is_available() else "cpu")
    382 )
    383 # load the weights into the model
--> 384 set_peft_model_state_dict(self, adapters_weights, adapter_name=adapter_name)
    385 if (
    386     (getattr(self, "hf_device_map", None) is not None)
    387     and (len(set(self.hf_device_map.values()).intersection({"cpu", "disk"})) > 0)
    388     and len(self.peft_config) == 1
    389 ):
    390     device_map = kwargs.get("device_map", "auto")

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/peft/utils/save_and_load.py:123, in set_peft_model_state_dict(model, peft_model_state_dict, adapter_name)
    120 else:
    121     raise NotImplementedError
--> 123 model.load_state_dict(peft_model_state_dict, strict=False)
    124 if isinstance(config, PromptLearningConfig):
    125     model.prompt_encoder[adapter_name].embedding.load_state_dict(
    126         {"weight": peft_model_state_dict["prompt_embeddings"]}, strict=True
    127     )

File /databricks/python/lib/python3.9/site-packages/torch/nn/modules/module.py:1671, in Module.load_state_dict(self, state_dict, strict)
   1666         error_msgs.insert(
   1667             0, 'Missing key(s) in state_dict: {}. '.format(
   1668                 ', '.join('"{}"'.format(k) for k in missing_keys)))
   1670 if len(error_msgs) > 0:
-> 1671     raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
   1672                        self.__class__.__name__, "\n\t".join(error_msgs)))
   1673 return _IncompatibleKeys(missing_keys, unexpected_keys)
```

And then this is also printed out for layers 0 to 31.

> RuntimeError: Error(s) in loading state_dict for PeftModelForCausalLM: size mismatch for base_model.model.gpt_neox.layers.0.attention.query_key_value.lora_B.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([7680, 4]).

Any pointers would be appreciated!

**Comment by younesbelkada** [comment]
hi @opyate 
Thanks for the issue, your adapter model looks broken (only few KBs), I tried:

```python
from peft import prepare_model_for_int8_training, LoraConfig, get_peft_model
from transformers import AutoModelForCausalLM, AutoTokenizer

model_id = "databricks/dolly-v2-3b"

model = AutoModelForCausalLM.from_pretrained(model_id, load_in_8bit=True, device_map="auto")
model = prepare_model_for_int8_training(model, use_gradient_checkpointing=True)

# The dimension used by the LoRA update matrices
LORA_R = 4
# Scaling factor
LORA_ALPHA = 16
LORA_DROPOUT = 0.05

# r and alpha together control the total number of final trainable parameters when using LoRA, giving you the flexibility to balance a trade-off between end performance and compute efficiency.
config = LoraConfig(
    r=LORA_R,
    lora_alpha=LORA_ALPHA,
    lora_dropout=LORA_DROPOUT,
    bias="none",  # Specifies if the bias parameters should be trained
    task_type="CAUSAL_LM",
)
model = get_peft_model(model, config)

model.push_to_hub("ybelkada/dolly-adapter-test")


from peft import LoraConfig
from transformers import AutoModelForCausalLM
from peft import PeftModel
import torch

repo_name = "ybelkada/dolly-adapter-test"

config = LoraConfig.from_pretrained(repo_name)


model = AutoModelForCausalLM.from_pretrained(
    config.base_model_name_or_path,
    device_map="auto",
    torch_dtype=torch.bfloat16,
    trust_remote_code=True,
)
# Load the LoRA model
inference_model = PeftModel.from_pretrained(model, repo_name)  # <-- error here
```
And it works without any problem, as you can see from https://huggingface.co/ybelkada/dolly-adapter-test/tree/main / the adapter weight is around 5MB. Probably something wrong went during training which I can't really tell. You may want to re-train the adapter!

**Comment by younesbelkada** [comment]
Awesome thanks! Let us know how it goes

**Comment by opyate** [comment]
The `adapter_model.bin` isn't available when the deepspeed processes exit. I erroneously pushed to hub from within trainer after training, but as it's parallelised, I only got a quarter of the full adapter.

I'll have to dig into deepspeed and see if I can tell it to collate the adapters, and make it available in the output dir after a run.

But meanwhile, I'll try the vanilla approach you proposed.

**Comment by dittops** [comment]
I'm also facing the same issue. Removing deepspeed is solving the issue. But I need to keep deepspeed to fine-tune larger models. If you find any solution, please share.

**Comment by SeanLiaoy** [comment]
Also facing the same issue when using deepspeed ........

**Comment by Whadup** [comment]
Try this, works for me

    trainer.save_model("output")
    model.save_pretrained("output_lora")
    from deepspeed.utils.zero_to_fp32 import get_fp32_state_dict_from_zero_checkpoint
    from peft import get_peft_model_state_dict
    state_dict = get_fp32_state_dict_from_zero_checkpoint("output") # already on cpu
    d = get_peft_model_state_dict(model, state_dict=state_dict)
    torch.save(d, "output_lora/adapter_model.bin")

**Comment by jayden222** [comment]
> Try this, works for me
> 
> ```
> trainer.save_model("output")
> model.save_pretrained("output_lora")
> from deepspeed.utils.zero_to_fp32 import get_fp32_state_dict_from_zero_checkpoint
> from peft import get_peft_model_state_dict
> state_dict = get_fp32_state_dict_from_zero_checkpoint("output") # already on cpu
> d = get_peft_model_state_dict(model, state_dict=state_dict)
> torch.save(d, "output_lora/adapter_model.bin")
> ```
> 
> It uses the trainer to save the full state dict in deepspeeds own format and then deepspeeds utils to gather the weights back on CPU. Then we can store them using torch and pretend all of this never happened :D
> 
> The problem with using just the `peft.save_pretrained` method is that it only stores the weights of a single CUDA device, probably the one corresponding to the first python process. all the other tensors have an empty shape.
> 
> Edit: The above solution works when `"stage3_gather_16bit_weights_on_model_save": false`. Alternatively set `"stage3_gather_16bit_weights_on_model_save": true` in your deepspeed config and that should make the huggingface trainer output a usable state_dict...

---
I set the "stage3_gather_16bit_weights_on_model_save": true, but it still have the same issue. It seems that loRA inference cannot work with deepspeed zero3.

**Comment by Whadup** [comment]
@jayden222 Can you print the saved LoRA state_dict, maybe we can figure out what is wrong from there. Maybe some of the tensors have zero shapes?

**Comment by jayden222** [comment]
> @jayden222 Can you print the saved LoRA state_dict, maybe we can figure out what is wrong from there. Maybe some of the tensors have zero shapes?

I think I have the same issue [here](https://github.com/huggingface/peft/issues/453). The weights saved during training using deepspeed zero stage3 are incomplete. The size of origin `adapter_model.bin` is around 1.3m, but after I modify the code as suggested, it becomes 6m, and it works. It makes sense because I was finetuning on 5*A10 GPU.

But I run into another potentially version issue. When I subclass and overwrite the `_save_checkpoint` function, there is no `self.model.peft_config` in the base class `PeftTrainer`. Therefore, I can only save `adapter_model.bin` (6m) under checkpoint path and replace it with the original one (1m). I don't think this is the good way to the solution. (

**Comment by Whadup** [comment]
I agree, it's not elegant and everything should be handled in the `save_pretrained` method...

My current code is

``` python
    trainer.train() 

    trainer.save_model("output") # will only save from the main process
    from deepspeed.utils.zero_to_fp32 import get_fp32_state_dict_from_zero_checkpoint
    from peft import get_peft_model_state_dict
    if training_args.local_rank == 0:
        print(model.state_dict().keys())
        if trainer.deepspeed and not os.path.exists("output/pytorch_model.bin"):
            print("CONVERT Deepspeed Checkpoint to FP32")
            state_dict = get_fp32_state_dict_from_zero_checkpoint("output") # already on cpu
        else:
            print("TRY to use the model directly")
            state_dict = model.cpu().state_dict()
        print("Number of elements in the state dict", sum(p.numel() for p in state_dict.values()))
        d = get_peft_model_state_dict(model, state_dict=state_dict)

        model.save_pretrained("output_lora")
        torch.save(d, "output_lora/adapter_model.bin")
```

**Comment by jayden222** [comment]
> I agree, it's not elegant and everything should be handled in the `save_pretrained` method...
> 
> My current code is
> 
> ```python
>     trainer.train() 
> 
>     trainer.save_model("output") # will only save from the main process
>     from deepspeed.utils.zero_to_fp32 import get_fp32_state_dict_from_zero_checkpoint
>     from peft import get_peft_model_state_dict
>     if training_args.local_rank == 0:
>         print(model.state_dict().keys())
>         if trainer.deepspeed and not os.path.exists("output/pytorch_model.bin"):
>             print("CONVERT Deepspeed Checkpoint to FP32")
>             state_dict = get_fp32_state_dict_from_zero_checkpoint("output") # already on cpu
>         else:
>             print("TRY to use the model directly")
>             state_dict = model.cpu().state_dict()
>         print("Number of elements in the state dict", sum(p.numel() for p in state_dict.values()))
>         d = get_peft_model_state_dict(model, state_dict=state_dict)
> 
>         model.save_pretrained("output_lora")
>         torch.save(d, "output_lora/adapter_model.bin")
> ```

It works elegantly. Thanks a lot!

**Comment by 1106301825** [comment]
ValueError: Unable to find 'latest' file at output/latest

**Comment by 1106301825** [comment]
ValueError: Unable to find 'latest' file at output/latest @Whadup

**Comment by Whadup** [comment]
> 

what files do you see in output?
If there's no latest, then that probably means that you're writing a `pytorch_model.bin` directly without deepspeed

**Comment by 1106301825** [comment]
output: adapter_config.json, adapter_model.bin, special_tokens_map.json, tokenizer_config.json, tokenizer.model, training_args.bin.     @Whadup

**Comment by Whadup** [comment]
@1106301825 turns out they fixed the issue, you can just use `trainer.save()` and `peft.from_pretrained()` to store and load peft models

**Comment by rounak610** [comment]
@Whadup I am using the code that you have given to save the model.
I am using multi node setup(two machines with 4A10G each).
I am fine-tuning using hugging face SFTT trainer and using deep speed stage3.
Getting this error: ValueError: Unable to find 'latest' file at output/latest
worker: CONVERT Deepspeed Checkpoint to FP32
worker: Traceback (most recent call last):
worker:   File "/home/ubuntu/finetuning/main.py", line 244, in <module>
worker:     run()
worker:   File "/home/ubuntu/finetuning/main.py", line 229, in run
worker:     state_dict = get_fp32_state_dict_from_zero_checkpoint("output") # already on cpu
worker:   File "/home/ubuntu/miniconda3/envs/train/lib/python3.10/site-packages/deepspeed/utils/zero_to_fp32.py", line 502, in get_fp32_state_dict_from_zero_checkpoint
worker:     raise ValueError(f"Unable to find 'latest' file at {latest_path}")

**Comment by Whadup** [comment]
First step in debugging is checking your output folder: does it actually contain a ds checkpoint? Then we can go from there

**Comment by rounak610** [comment]
the output folder was created in the machine with rank=1 instead of 0.
it is working fine.

**Comment by callanwu** [comment]
If I don't use `trainer` but I use deepspeed stage3, how can i fix this?

**Comment by Zuhashaik** [comment]
@Whadup @younesbelkada @opyate help me similar kind of issue in  section #1700
