### ISSUE TITLE
difference between get_peft_model and from_pretrained

### ISSUE THREAD

**Issue by nuoma** [huggingface/peft#470]
Hi, when I'm training LLAMA with Lora, i seem to get different results when loading Lora weights via get_peft_model and from_pretrained. Can't really tell why,both can infer successfully, but with vastly different results.

Could someone be so kind to tell me which is the correct way of doing this. Many thanks!

**Comment by yyqi17** [comment]
Hi nuoma, could you please show me your code in saving & loading checkpoints? I'm finetuning llama with lora, and seem to encounter some issues when infering my checkpoint (saved by `model.save_pretrained()` and loaded by `PeftModel.from_pretrained(base_mode, lora_ckpt_path)`). Thanks a lot!

**Comment by ingo-m** [comment]
Possibly related? #503 🤔
