### ISSUE TITLE
PEFT methods for causal language modeling?

### ISSUE THREAD

**Issue by dcruiz01** [huggingface/peft#471]
Are there any PEFT methods that can be applied to giving a pretrained LLM additional pre-training on domain-specific data through standard causal language modeling (next token prediction)? If so, are there any examples within this library or extensions of it? I have been unable to find any.

**Comment by arshadshk** [comment]
I think you can use the `CAUSAL_LM` task of lora :
```python
# load model in 8bit
model = AutoModelForCausalLM.from_pretrained(
        args.model_path,
        load_in_8bit=True,
        device_map={"": Accelerator().local_process_index}
    )
model = prepare_model_for_int8_training(model)

# add LoRA to model
lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
)

model = get_peft_model(model, config)
```
source : https://huggingface.co/blog/stackllama
