### ISSUE TITLE
Is there a way to unfreeze the embedding layer? 

### ISSUE THREAD

**Issue by ElleLeonne** [huggingface/peft#487]
Basically as the title says, I'd like to unfreeze the embedding layer (or possibly somehow add it to Lora's trained modules).

I'm curious if there's a functionality built in for this

**Comment by adibMosharrof** [comment]
I had expanded the vocabulary size and trained the embedding layer. 
You basically have to add layers to `modules_to_save` option in LoraConfig
Please see https://github.com/huggingface/peft/issues/334#issuecomment-1561727994 for more details.
