### ISSUE TITLE
Is it the right way to use past_key_values in Prefix-tuning for Seq2SeqLM task?

### ISSUE THREAD

**Issue by lemonblocks** [huggingface/peft#491]
In lines 920-924 of the file peft_model.py, pass_key_values is directly passed into self.model for forward.
However, in models such as Bart and T5, the past_key_values will only be passed in when the Decoder is called, so is this inconsistent with the original paper?

**Comment by wangpengabc** [comment]
FYI. If you are skilled in Chinese, I think you can refer to this blog, https://zhuanlan.zhihu.com/p/459305102.
