### ISSUE TITLE
Peft model performance issues.

### ISSUE THREAD

**Issue by imrankh46** [huggingface/peft#497]
I trained a lots of instructions and non instructions base model using peft but after training the model performance are too bad. 

However when I train a small model without using peft so the model performance are good. 

I need suggestion.

**Comment by PanQiWei** [comment]
Do you add the trained adapters back to the base model when you try to use it to inference?

**Comment by imrankh46** [comment]
> Do you add the trained adapters back to the base model when you try to use it to inference?

Yeah, definitely. They generate text but not meaning full. Like a sentence which have no meaning..

**Comment by 3A732038** [comment]
I also encountered the same problem. Could it be that our pre-trained model is too small, and I only use more than 100 million parameters, which makes it impossible to generate a complete model during reasoning.

**Comment by imrankh46** [comment]
> I also encountered the same problem. Could it be that our pre-trained model is too small, and I only use more than 100 million parameters, which makes it impossible to generate a complete model during reasoning.

Why this happened? Or may be due to 8bit ;

**Comment by 3A732038** [comment]
> > 我也遇到了同樣的問題。難道是我們預訓練的模型太小了，我只用了1億多個參數，導致推理時無法生成完整的模型。
> 
> 為什麼會發生這樣的事？或者可能是8bit的原因；
During the solution, have you run the 8bits result yet?
My computer can't run 8bits
