### ISSUE TITLE
How to finetune LLM using DeepSpeed and model parallel under PEFT?

### ISSUE THREAD

**Issue by QinlongHuang** [huggingface/peft#500]
Hi, is that possible to finetune a LLM using DeepSpeed and model parallel under PEFT? 
E.g., I want to finetune a 70B model using LoRA and int8 training, but the model cannot fit in a single A100-40G.

**Comment by submartingales** [comment]
Same question

**Comment by joshuafc** [comment]
+1

**Comment by freckletonj** [comment]
Same question, is there a way of training QLORA across multi GPU?
