### ISSUE TITLE
[Feature Request] - Add support for AdaMix 

### ISSUE THREAD

**Issue by gnovack** [huggingface/peft#504]
The paper [AdaMix: Mixture-of-Adaptations for Parameter-efficient Model Tuning](https://arxiv.org/abs/2205.12410) by Wang, Yaqing, et al. shows good results by applying a Mixture of Experts approach to existing PEFT methods like LoRA. 

It would be great if AdaMix was available as an option in `peft`. Are there any plans to add this in the near future?

**Comment by rishabbala** [comment]
Hi @younesbelkada is this issue still open? If so I can take it up

**Comment by younesbelkada** [comment]
Hi @rishabbala 
Yes this issue is still open, let is know if you want to take it ! You can have some inspiration from the recent work on https://github.com/huggingface/peft/pull/578 to see the required changes to add a new PEFT method 
Thanks !

**Comment by rishabbala** [comment]
Hi @younesbelkada. Is there any way I can run the tests locally to ensure my code is working?

**Comment by younesbelkada** [comment]
Hi @rishabbala 
Thanks for your great work on opening the draft PR ! 
You can try to replicate one of the training examples using AdaMix, for example: https://github.com/huggingface/peft/blob/main/examples/conditional_generation/peft_ia3_seq2seq.ipynb and make sure the model converges; let us know if you need any help !

**Comment by rishabbala** [comment]
Thank! Just to clarify is there also any way I could run the tests from the tests/ folder. I tried using pytest, but it returned 0 tests collected. I'll also try the above example

**Comment by younesbelkada** [comment]
For the tests, to make sure you have not broken the current CI you can run the common tests through `pytest tests/` 
while adding the new adapter model you can design your own tests, make sure to follow what has been done in #578 for adding the tests for new methods
