### ISSUE TITLE
ImportError: cannot import name 'prepare_model_for_kbit_training' from 'peft'

### ISSUE THREAD

**Issue by forkbabu** [huggingface/peft#505]
```
(peft) $ python
Python 3.10.11 | packaged by conda-forge | (main, May 10 2023, 18:58:44) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from peft import prepare_model_for_kbit_training

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/21sd45/miniconda3/envs/peft/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda120.so
/home/21sd45/miniconda3/envs/peft/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: /home/21sd45/miniconda3/envs/peft did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
/home/21sd45/miniconda3/envs/peft/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('//0161-130-15-58-222.ngrok-free.app/proxy/{{port}}'), PosixPath('https')}
  warn(msg)
/home/21sd45/miniconda3/envs/peft/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('FILE'), PosixPath('/tmp/krb5cc_10105_YmAUSb')}
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 7.5
CUDA SETUP: Detected CUDA version 120
CUDA SETUP: Loading binary /home/21sd45/miniconda3/envs/peft/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda120.so...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'prepare_model_for_kbit_training' from 'peft' (/home/21sd45/miniconda3/envs/peft/lib/python3.10/site-packages/peft/__init__.py)
```

Python  - 3.10.11
```
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
```

```
nvidia-smi
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro RTX 8000     On   | 00000000:1A:00.0 Off |                    0 |
| N/A   62C    P0   219W / 250W |  20363MiB / 46080MiB |    100%      Default |
|                               |                      |                  N/A |
```

**Comment by imrankh46** [comment]
> ```
> (peft) $ python
> Python 3.10.11 | packaged by conda-forge | (main, May 10 2023, 18:58:44) [GCC 11.3.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> from peft import prepare_model_for_kbit_training
> 
> ===================================BUG REPORT===================================
> Welcome to bitsandbytes. For bug reports, please run
> 
> python -m bitsandbytes
> 
>  and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
> ================================================================================
> bin /home/21sd45/miniconda3/envs/peft/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda120.so
> /home/21sd45/miniconda3/envs/peft/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: /home/21sd45/miniconda3/envs/peft did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
>   warn(msg)
> /home/21sd45/miniconda3/envs/peft/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('//0161-130-15-58-222.ngrok-free.app/proxy/{{port}}'), PosixPath('https')}
>   warn(msg)
> /home/21sd45/miniconda3/envs/peft/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('FILE'), PosixPath('/tmp/krb5cc_10105_YmAUSb')}
>   warn(msg)
> CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
> CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
> CUDA SETUP: Highest compute capability among GPUs detected: 7.5
> CUDA SETUP: Detected CUDA version 120
> CUDA SETUP: Loading binary /home/21sd45/miniconda3/envs/peft/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda120.so...
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ImportError: cannot import name 'prepare_model_for_kbit_training' from 'peft' (/home/21sd45/miniconda3/envs/peft/lib/python3.10/site-packages/peft/__init__.py)
> ```
> 
> Python - 3.10.11
> 
> ```
> nvcc --version
> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2019 NVIDIA Corporation
> Built on Sun_Jul_28_19:07:16_PDT_2019
> Cuda compilation tools, release 10.1, V10.1.243
> ```
> 
> ```
> nvidia-smi
> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |                               |                      |               MIG M. |
> |===============================+======================+======================|
> |   0  Quadro RTX 8000     On   | 00000000:1A:00.0 Off |                    0 |
> | N/A   62C    P0   219W / 250W |  20363MiB / 46080MiB |    100%      Default |
> |                               |                      |                  N/A |
> ```

Update the peft package.

!pip install -q -U peft

**Comment by SimonKitSangChu** [comment]
Did you install the latest peft from source?
```pip install -I git+https://github.com/huggingface/peft.git```

**Comment by gameveloster** [comment]
Getting the same error on Python 3.10. 

Installed from source using `pip install -q -U git+https://github.com/huggingface/peft.git`. Is this different from `pip install -I`?

**Comment by SimonKitSangChu** [comment]
Indeed. `-U` might be a safer option than `-I`.

**Comment by DylanAlloy** [comment]
Is it unreasonable to expect a CI/CD workflow or something to push to pypi, this seems a little disruptive to workflow and one should be fine installing from `pypi` since it's such a great python registry?

**Comment by younesbelkada** [comment]
hi there!
Do you still face the issue with:
```bash
pip install git+https://github.com/huggingface/peft.git
```

**Comment by DylanAlloy** [comment]
No but... why isn't peft updated in pypi? 

we cannot version control with this method...

**Comment by BenjaminBossan** [comment]
> Could we please request for the repo authors to help update the ver on pypi to that on git?

There have been several releases since this topic was brought up. The function `prepare_model_for_kbit_training` can be imported with the PEFT versions from pypi since a long time.
