### ISSUE TITLE
Target modules for Falcon-40B model ? 

### ISSUE THREAD

**Issue by sanskar-hasija** [huggingface/peft#507]
What target modules should I add in the config for the Falcon-40B model fine-tuning? 
Falcon-40B Model card - [here]( https://huggingface.co/tiiuae/falcon-40b-instruct)

**Comment by psych0v0yager** [comment]
For the LoRA config you will add "query_key_value"

A good way to tell which target module you need is to print the model layers.

print(model)

RWForCausalLM(
  (transformer): RWModel(
    (word_embeddings): Embedding(65024, 8192)
    (h): ModuleList(
      (0-59): 60 x DecoderLayer(
        (ln_attn): LayerNorm((8192,), eps=1e-05, elementwise_affine=True)
        (ln_mlp): LayerNorm((8192,), eps=1e-05, elementwise_affine=True)
        (self_attention): Attention(
          (maybe_rotary): RotaryEmbedding()
          (query_key_value): Linear4bit(in_features=8192, out_features=9216, bias=False)
          (dense): Linear4bit(in_features=8192, out_features=8192, bias=False)
          (attention_dropout): Dropout(p=0.0, inplace=False)
        )
        (mlp): MLP(
          (dense_h_to_4h): Linear4bit(in_features=8192, out_features=32768, bias=False)
          (act): GELU(approximate='none')
          (dense_4h_to_h): Linear4bit(in_features=32768, out_features=8192, bias=False)
        )
      )
    )
    (ln_f): LayerNorm((8192,), eps=1e-05, elementwise_affine=True)
  )
  (lm_head): Linear(in_features=8192, out_features=65024, bias=False)
)


LoRAs always target the attention heads of a transformer. Look for the layer labelled (self attention) and find the query, key, and value layers.

They will typically be named in combinations such as "query, value", "q, v", "query_key_value", etc

**Comment by sanskar-hasija** [comment]
Thanks for the help @psych0v0yager 
I was able to figure out the target_modules. "query_key_value" worked for me.

**Comment by NeonBohdan** [comment]
What pad token used in this model? I don't see it in tokenizer, how to better handle this?
