### ISSUE TITLE
Is QLoRA save and load correct?

### ISSUE THREAD

**Issue by 1049451037** [huggingface/peft#508]
In `bitsandbytes`, the `quant_state` of `Params4bit` is not saved in model state_dict. How to recover these information when loading?

* https://github.com/TimDettmers/bitsandbytes/blob/main/bitsandbytes/nn/modules.py
* https://github.com/huggingface/peft/pull/476

**Comment by orellavie1212** [comment]
is the https://github.com/huggingface/peft/pull/476 even works for you when loading LoRA weights? I get the feelings that the LoRA not actually loading, and I get vanilla like answers from the model.
Older versions of bits, peft, etc works well for 8bit, and I wanted to use the new 4bit.

**Comment by 1049451037** [comment]
@orellavie1212 I think the loading is weird... but works. The trick is that when training with fp16 weights, you need to load pretrained weights first then call `model.cuda()`. But when you do inference with saved 4bit weights, you need to call `model.cuda()` first then load state dict.

This is because the quantization happens when calling `.cuda()`. I think the problem now is the quant_state of saving and loading.
