### ISSUE TITLE
Prefix Tuning - Getting gibberish result

### ISSUE THREAD

**Issue by dittops** [huggingface/peft#516]
I have tried finetuning LLaMa 7B with prefix tuning. Here is the prefix config I used

`PrefixTuningConfig(task_type=TaskType.CAUSAL_LM, num_virtual_tokens=20)`

The inference gives results like below

<img width="760" alt="image" src="https://github.com/huggingface/peft/assets/12937285/da30219b-f360-404e-9bde-ed222dabc2d4">

I have found this message once the training is completed.

<img width="1400" alt="image" src="https://github.com/huggingface/peft/assets/12937285/2f02ff6b-f2de-4704-9144-5e64426bc220">

I tried switching to LoRA with the same setup and it's not giving the warning or the gibberish output.

But If I remove the Prefix layer, the model generates standard text. Any thoughts on what could be the issue?

Versions:

peft==0.3.0
transformers==4.29.2

**Comment by pacman100** [comment]
Hello, how are you loading the saved model during inference?
