### ISSUE TITLE
Is it possible to support multiple GPUs for distributed training at the same time?

### ISSUE THREAD

**Issue by ScottishFold007** [huggingface/peft#52]
Is it possible to support multiple GPUs for distributed training at the same time?

**Comment by mayank31398** [comment]
I think this is already working with accelerate right?

**Comment by pacman100** [comment]
Hello @ScottishFold007, as Mayank mentioned, PEFT methods work seamlessly with 🤗 Accelerate which provides multi-gpu support with no code changes by just using the corresponding config. I'll add an example showcasing it.
