### ISSUE TITLE
Gradient checkpointing error: LongT5 + LoRA

### ISSUE THREAD

**Issue by elieagle** [huggingface/peft#522]
Hi, thanks for your amazing work!

I'm trying to fine-tune a LongT5 model using LoRA and I'm experiencing issues related to gradient checkpointing. Specifically, I’m experiencing the (well known) `RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn` (solved in #137).

The `model.enable_input_require_grads()` did not solve the issue but I managed to narrow down the problem by doing:
```python
def find_tensor_without_grad_fn(model):
    for name, param in model.named_parameters():
        if param.requires_grad and param.grad is None:
            print(f"Tensor without grad_fn: {name}")

try:
    # Instantiating HF's Seq2SeqTrainer
    trainer.train()
except RuntimeError as e:
    if "element 0 of tensors does not require grad and does not have a grad_fn" in str(e):
        find_tensor_without_grad_fn(trainer.model)
    else:
        raise e
  ```
Which returns
```bash
element 0 of tensors does not require grad and does not have a grad_fn
Tensor without grad_fn: base_model.model.encoder.block.0.layer.0.LocalSelfAttention.q.lora_A.default.weight
Tensor without grad_fn: base_model.model.encoder.block.0.layer.0.LocalSelfAttention.q.lora_B.default.weight
Tensor without grad_fn: base_model.model.encoder.block.0.layer.0.LocalSelfAttention.v.lora_A.default.weight
Tensor without grad_fn: base_model.model.encoder.block.0.layer.0.LocalSelfAttention.v.lora_B.default.weight
Tensor without grad_fn: base_model.model.encoder.block.1.layer.0.LocalSelfAttention.q.lora_A.default.weight
Tensor without grad_fn: base_model.model.encoder.block.1.layer.0.LocalSelfAttention.q.lora_B.default.weight
Tensor without grad_fn: base_model.model.encoder.block.1.layer.0.LocalSelfAttention.v.lora_A.default.weight
Tensor without grad_fn: base_model.model.encoder.block.1.layer.0.LocalSelfAttention.v.lora_B.default.weight
...
Tensor without grad_fn: base_model.model.decoder.block.11.layer.0.SelfAttention.q.lora_A.default.weight
Tensor without grad_fn: base_model.model.decoder.block.11.layer.0.SelfAttention.q.lora_B.default.weight
Tensor without grad_fn: base_model.model.decoder.block.11.layer.0.SelfAttention.v.lora_A.default.weight
Tensor without grad_fn: base_model.model.decoder.block.11.layer.0.SelfAttention.v.lora_B.default.weight
Tensor without grad_fn: base_model.model.decoder.block.11.layer.1.EncDecAttention.q.lora_A.default.weight
Tensor without grad_fn: base_model.model.decoder.block.11.layer.1.EncDecAttention.q.lora_B.default.weight
Tensor without grad_fn: base_model.model.decoder.block.11.layer.1.EncDecAttention.v.lora_A.default.weight
Tensor without grad_fn: base_model.model.decoder.block.11.layer.1.EncDecAttention.v.lora_B.default.weight
````
Note that the same code works fine for a T5 model, so I’m thinking that the difference in attention mechanisms between T5 and LongT5 are causing the error. The error occurs for both Transient-Global (google/long-t5-tglobal-base) and Local (google/long-t5-local-base) attention mechanisms.
Also, my code works with LongT5 when disabling gradient checkpointing.

Is there something specific that I need to do to adapt the code to LongT5 architecture? #94 seems to suggest that it should be straightforward.

For reference, here is how I set up LoRA for LongT5 before calling trainer.train():
```python
model = AutoModelForSeq2SeqLM.from_pretrained("google/long-t5-local-base")

# for gradient checkpointing
model.config.use_cache = False
model.enable_input_require_grads()

lora_config = LoraConfig(
        task_type=TaskType.SEQ_2_SEQ_LM,
        inference_mode=False,
        r=4,
        lora_alpha=32,
        lora_dropout=0.1,
        target_modules=["q", "v"]
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    tokenizer=tokenizer,
    data_collator=data_collator,
    callbacks=[
        # save peft adapted model weights
        SavePeftModelCallback,
    ]
)
```

Using:
```
torch 1.13.1
transformers 4.29.2
peft 0.3.0
```

**Comment by cuiyuebing** [comment]
Got a similar issue. Have you found the solution?

**Comment by sujithrs** [comment]
I am also facing  the same issue as described by @elieagle . It works fine with gradient checkpointing disabled.

**Comment by YueChenkkk** [comment]
I am also facing the same issue, it seems to be unable to propagate gradientS from the loss to the LoRA weightS

**Comment by BenjaminBossan** [comment]
I could reproduce the error with `pretrained_model_name_or_path="google/long-t5-local-base"` and `gradient_checkpointing=True`. It occurs neither with `pretrained_model_name_or_path="t5-small"`, nor with `gradient_checkpointing=False`, so it has to be the specific combination of long T5 and gradient checkpointing.

Curiously, both long T5 and small T5 use the same attention module:

https://github.com/huggingface/transformers/blob/c53a6eae74778ad65de9edb0f0bd1eef3674bde3/src/transformers/models/t5/modeling_t5.py#L348
https://github.com/huggingface/transformers/blob/c53a6eae74778ad65de9edb0f0bd1eef3674bde3/src/transformers/models/longt5/modeling_longt5.py#L326

So that can't be the issue, it has to be something else.

**Comment by Legacy107** [comment]
I am facing the same issue with long-t5. Have anyone found the solution to this yet?

**Comment by YueChenkkk** [comment]
I solved the issue by adding the two lines at the end
```
lora_config = LoraConfig(
        r=other_args.lora_r,
        lora_alpha=other_args.lora_alpha,
        target_modules=other_args.lora_target_modules,
        lora_dropout=other_args.lora_dropout,
        bias="none",
        task_type="SEQ_2_SEQ_LM",
)
model = get_peft_model(model, lora_config)

model.base_model.model.encoder.enable_input_require_grads()
model.base_model.model.decoder.enable_input_require_grads()
```
This issue is probably caused by the get_input_embeddings() of long-t5, which cannot actually get the iuput embeddings of long-t5's encoder and decoder

**Comment by Legacy107** [comment]
> I solved the issue by adding the two lines at the end
> 
> ```
> lora_config = LoraConfig(
>         r=other_args.lora_r,
>         lora_alpha=other_args.lora_alpha,
>         target_modules=other_args.lora_target_modules,
>         lora_dropout=other_args.lora_dropout,
>         bias="none",
>         task_type="SEQ_2_SEQ_LM",
> )
> model = get_peft_model(model, lora_config)
> 
> model.base_model.model.encoder.enable_input_require_grads()
> model.base_model.model.decoder.enable_input_require_grads()
> ```
> 
> This issue is probably caused by the get_input_embeddings() method of long-t5, which cannot actually get the iuput embeddings of long-t5's encoder and decoder

This fixed my issue. Thank you so much!

**Comment by andysucao** [comment]
> I solved the issue by adding the two lines at the end
> 
> ```
> lora_config = LoraConfig(
>         r=other_args.lora_r,
>         lora_alpha=other_args.lora_alpha,
>         target_modules=other_args.lora_target_modules,
>         lora_dropout=other_args.lora_dropout,
>         bias="none",
>         task_type="SEQ_2_SEQ_LM",
> )
> model = get_peft_model(model, lora_config)
> 
> model.base_model.model.encoder.enable_input_require_grads()
> model.base_model.model.decoder.enable_input_require_grads()
> ```
> 
> This issue is probably caused by the get_input_embeddings() method of long-t5, which cannot actually get the iuput embeddings of long-t5's encoder and decoder

This fixed my issue too. Thank you so much @YueChenkkk!

**Comment by mariakesa** [comment]
> I solved the issue by adding the two lines at the end
> 
> ```
> lora_config = LoraConfig(
>         r=other_args.lora_r,
>         lora_alpha=other_args.lora_alpha,
>         target_modules=other_args.lora_target_modules,
>         lora_dropout=other_args.lora_dropout,
>         bias="none",
>         task_type="SEQ_2_SEQ_LM",
> )
> model = get_peft_model(model, lora_config)
> 
> model.base_model.model.encoder.enable_input_require_grads()
> model.base_model.model.decoder.enable_input_require_grads()
> ```
> 
> This issue is probably caused by the get_input_embeddings() method of long-t5, which cannot actually get the iuput embeddings of long-t5's encoder and decoder

Yes! Solved it for me!
