### ISSUE TITLE
LoRA not working on latest versions

### ISSUE THREAD

**Issue by dittops** [huggingface/peft#530]
I have tried finetuning LoRA with the latest version, but the layer seems not learning. I'm using LLaMa 7B with a small dataset of 1000 entries. But If I roll back the version to a specific version, it's working as expected.

Latest version (NOT working)

```
peft==0.3.0
transformers==4.29.2
```

Old version (Working)

```
peft @ git+https://github.com/huggingface/peft.git@e536616888d51b453ed354a6f1e243fecb02ea08
transformers @ git+https://github.com/huggingface/transformers.git@390e121fb5233aa553d7a456c40ad5c95a72b7f1
```

Is there version combinations of Transformer and Peft to be followed?

**Comment by 3A732038** [comment]
When I was training a fine-tuned LoRA model myself, I used 100 pieces of data for training, and the effect was also very poor.
But if I use hundreds of thousands of data for training, he runs an epoch and trains for a long time.
 I don’t know if there is a solution.

**Comment by gokulrejith** [comment]
Facing the same issue, LoRA does not seem to be fine-tuning, the models. Getting very unsatisfactory results.

**Comment by LasalJayawardena** [comment]
Any solution you guys found on this. I am also getting similar results
