### ISSUE TITLE
image_classification_peft_lora.ipynb  A problem has occurred in this regard.

### ISSUE THREAD

**Issue by ohchangmin** [huggingface/peft#536]
image_classification_peft_lora.ipynb
Train and evaluate

trainer = Trainer(
    model,
    args,
    train_dataset=train_ds,
    eval_dataset=val_ds,
    tokenizer=image_processor,
    compute_metrics=compute_metrics,
    data_collator=collate_fn,
)
train_results = trainer.train()

Is this part of the description correct?
This will work normally. 

trainer = Trainer(
    lora_model, <<<<<
    args,
    train_dataset=train_ds,
    eval_dataset=val_ds,
    tokenizer=image_processor,
    compute_metrics=compute_metrics,
    data_collator=collate_fn,
)
train_results = trainer.train()

 Shouldn't it be written like this?
When I write this, it seems to be processed normally, but when I look at it, the model is not loaded normally.

**Comment by stevhliu** [comment]
Hi, this has been fixed in #524!
