### ISSUE TITLE
How to use prefix-tuing/prompt-tuning/p-tuning for chatglm-6B?

### ISSUE THREAD

**Issue by ydyjya** [huggingface/peft#544]
I try to use prefix-tuing/prompt-tuning/p-tuning for chatglm-6B, but when I use [examples/causal_language_modeling/peft_prefix_tuning_clm.ipynb], it doesn't work.(https://github.com/huggingface/peft/blob/main/examples/causal_language_modeling/peft_prefix_tuning_clm.ipynb)
I think the problem lies in `preprocess_function(examples)`, the process of this funtion can't match chatglm-6B.
Then, I found [ChatGLM support #180](https://github.com/huggingface/peft/pull/180), I sure peft support Lora. I rephrased `preprocess_function(examples)` with reference to the input in Lora. 
It still doesn't work, so I want to know peft whether support prefix-tuing/prompt-tuning/p-tuning. If it could, please give some examples for chatglm-6B with prefix-tuing/prompt-tuning/p-tuning.
Thanks!

**Comment by cckuailong** [comment]
I got this error to use prefix/prompt/ptuning to finetune ChatGLM.
<img width="1196" alt="image" src="https://github.com/huggingface/peft/assets/10824150/b12296af-6484-4279-866e-371a12f24661">

**Comment by ydyjya** [comment]
> I got this error to use prefix/prompt/ptuning to finetune ChatGLM. <img alt="image" width="1196" src="https://user-images.githubusercontent.com/10824150/243673398-b12296af-6484-4279-866e-371a12f24661.png">

I got similar error when I follow the given example.

**Comment by Dvijesh88** [comment]
Actually I am also receiving same kind of error when tried to finetune falcon. But Error is

RunTimeError: Tensor must have same number of dimensions: get 4 and 3

**Comment by pacman100** [comment]
Hello, please let us know if the issue still persists on the main branch.

**Comment by Dvijesh88** [comment]
> Hello, please let us know if the issue still persists on the main branch.

I just tried today it self. Still it is showing me the same error.

**Comment by Dvijesh88** [comment]
> Hello, please let us know if the issue still persists on the main branch.

Do prefixtuning is support to falcon-7b-instruct model? As I can't solve the error since last few days. But it working fine with LoRA.
