### ISSUE TITLE
Multiple Custom Adapters for Training

### ISSUE THREAD

**Issue by adibMosharrof** [huggingface/peft#550]
Hello, I am trying to implement this paper
[Task-Optimized Adapters for an End-to-End Task-Oriented Dialogue System](https://www.semanticscholar.org/paper/Task-Optimized-Adapters-for-an-End-to-End-Dialogue-Bang-Lee/42eaf025cd52ad668756281b8258a0408e73895b)

They train the model on multiple tasks and for each task they have a separate adapter. The architecture is in the picture below

![TOATOD](https://github.com/huggingface/peft/assets/2650540/da909dfb-8add-4b4c-93e4-3c1e911f184c)

They have also shared their [codebase](https://github.com/sogang-isds/TOATOD), but everything is done manually from scratch.

I wanted to know if it is possible to implement the paper mentioned above using PEFT.

**Comment by younesbelkada** [comment]
Hi @adibMosharrof 
Yes I believe this is possible using PEFT, you just need to play with the arguments [`add_adapter`](https://github.com/huggingface/peft/blob/189a6b8e357ecda05ccde13999e4c35759596a67/src/peft/peft_model.py#LL361C9-L361C20) and [`set_adapter`](https://github.com/huggingface/peft/blob/189a6b8e357ecda05ccde13999e4c35759596a67/src/peft/peft_model.py#L481).
From what i know this is supported only for LoRAs (not sure maybe @pacman100 can confirm). You should define multiple LoRA configs and interatively call `add_adapter` with different adapter name for each adapter. Then before inferring with a given adapter you should call `model.set_adapter(adapter_name)`
Here is an example also on how to do it in the context of RLHF: https://github.com/lvwerra/trl/pull/373
