### ISSUE TITLE
questions about modules_to_save

### ISSUE THREAD

**Issue by iMountTai** [huggingface/peft#551]
First of all thank you for your work. 
At the beginning, lora did not copy the weight of these trainable parameters when setting `modules_to_save`. However, after setting `modules_to_save` in the later update, a weight was copied for these trainable parameters, which led to the increase of VRAM and even OOM.  I would like to ask why this parameter is set and how to modify it so that this part of the weight can not be copied and can be trained normally. Looking forward to your reply, thank you! @pacman100

**Comment by iMountTai** [comment]
Requesting an answer.Thanks！

**Comment by BenjaminBossan** [comment]
Hey, first of all, `modules_to_save` is not really specific to LoRA but a more general mechanism to allow certain modules to be trained independent of the adapter methods (so full fine-tuning).

If I understand your question correctly, you're asking why the `ModulesToSaveWrapper`, which is used when `modules_to_save` are set, creates a copy of the original parameters. The reason for that is that users may want to disable the adapter to get the original outputs from the base model, or they might want to unload the base model. To allow this functionality, we need to keep a copy of the original weights. This will, unfortunately, mean that a bit of extra memory is used.

**Comment by 191220042** [comment]
> Hey, first of all, is not really specific to LoRA but a more general mechanism to allow certain modules to be trained independent of the adapter methods (so full fine-tuning).`modules_to_save`
> 
> If I understand your question correctly, you're asking why the , which is used when are set, creates a copy of the original parameters. The reason for that is that users may want to disable the adapter to get the original outputs from the base model, or they might want to unload the base model. To allow this functionality, we need to keep a copy of the original weights. This will, unfortunately, mean that a bit of extra memory is used.`ModulesToSaveWrapper``modules_to_save`

Hello, i wander if i load the model like this
![image](https://github.com/huggingface/peft/assets/80091648/37a9d372-4300-4234-95d9-2fb0dcddcb92)
how can i merge the model, modules_to_save should be the weight like lora and added to the origin weight ,or modules_to_save should be the new weight replace the origin

**Comment by BenjaminBossan** [comment]
@191220042 I don't quite understand your question. Could you maybe create a new issue and describe, ideally with some code, what you would like to achieve?

> modules_to_save should be the weight like lora and added to the origin weight

This is not possible. With LoRA adapters, the multiplied LoRA weights can be added to the base weight, but with `modules_to_save`, the base weights need to be replaced completely.

**Comment by 191220042** [comment]
> @191220042 I don't quite understand your question. Could you maybe create a new issue and describe, ideally with some code, what you would like to achieve?
> 
> > modules_to_save should be the weight like lora and added to the origin weight
> 
> This is not possible. With LoRA adapters, the multiplied LoRA weights can be added to the base weight, but with `modules_to_save`, the base weights need to be replaced completely.

thank you, You've answered my question，I added output_layer to the modules_to_save when I was fine-tuning ChatGPT with LoRa, but I found that it just copied the original parameters and opened the gradient without actually changing it

**Comment by 191220042** [comment]
> @191220042 I don't quite understand your question. Could you maybe create a new issue and describe, ideally with some code, what you would like to achieve?
> 
> > modules_to_save should be the weight like lora and added to the origin weight
> 
> This is not possible. With LoRA adapters, the multiplied LoRA weights can be added to the base weight, but with `modules_to_save`, the base weights need to be replaced completely.

thank you, You've answered my question，I added output_layer to the modules_to_save when I was fine-tuning ChatGLM with LoRa, but I found that it just copied the original parameters and opened the gradient without actually changing it
