### ISSUE TITLE
The version of P-tuning?

### ISSUE THREAD

**Issue by PhoebusSi** [huggingface/peft#557]
I would like to know if peft supports p-tuning or p-tuning v2 or both? If both methods are available, how should I switch between them?

**Comment by younesbelkada** [comment]
Hi @PhoebusSi 
I believe it is the first version that is used, I think @pacman100 can confirm this information 🙏

**Comment by roki1031** [comment]
any progress?

**Comment by PhoebusSi** [comment]
Thank you for your reply, but there are two papers listed after `Prefix Tuning`, which is confusing. Are these two works essentially the same implementation?

**Comment by pacman100** [comment]
Hello, yes
