### ISSUE TITLE
add support for cache_dir

### ISSUE THREAD

**Issue by katossky** [huggingface/peft#560]
It is not currently possible (as far as I know) to specify where to locate the cache for Peft models.

Regular transformer models now have a `cache_dir` attributes.

Could it possible to use the same mechanism?

**Comment by younesbelkada** [comment]
Hi @katossky 
After https://github.com/huggingface/peft/pull/561 it will be possible to pass `cache_dir` attribute to `PeftModel` as the keyword arguments get directly passed to `hf_hub_download`: https://github.com/huggingface/peft/blob/189a6b8e357ecda05ccde13999e4c35759596a67/src/peft/peft_model.py#L419
