### ISSUE TITLE
TypeError: PeftConfig.init() got an unexpected keyword argument 'device_map'

### ISSUE THREAD

**Issue by FartyPants** [huggingface/peft#564]
After some recent update you are now passing kwargs to PeftConfig from peft_model.py in from_pretrained
line 169 # load the config
        config = PEFT_TYPE_TO_CONFIG_MAPPING[
            PeftConfig.from_pretrained(model_id, subfolder=kwargs.get("subfolder", None), **kwargs).peft_type
        ].from_pretrained(model_id, subfolder=kwargs.get("subfolder", None), **kwargs)

but if the kwargs have 'device_map' or 'dtype' then it will blow in the construct of config.py
line 114:   config = cls(**kwargs)
TypeError: PeftConfig.init() got an unexpected keyword argument 'device_map'

but at the same time you are actually expecting kwargs in from_pretrained to have 'device_map' for example
410:  device_map = kwargs.get("device_map", "auto") in load_adapter perf_model.py is expecting it to have it.

**Comment by younesbelkada** [comment]
Hi @FartyPants 
https://github.com/huggingface/peft/pull/561 should partially solve the issue, I will work on a proper fix right after that PR gets merged
