### ISSUE TITLE
An interesting bug when using Prefix-Tuning on Seq2Seq models

### ISSUE THREAD

**Issue by cunliangkong** [huggingface/peft#565]
I used the prefix-tuning implemented in PEFT, but found a problem when reading the source code. **That is, when the source input is of a certain length, the effectiveness of the model drops dramatically.** The problem may appear in Seq2Seq models, and it was verified on T5 and BART.

Taking T5 model as an example, the prefix vectors are used as the `past_key_values` argument for the base model.
https://github.com/huggingface/peft/blob/189a6b8e357ecda05ccde13999e4c35759596a67/src/peft/peft_model.py#L975

In T5 model, the attention module use the following if-else jugemets to determin what state the code is currently in:
https://github.com/huggingface/transformers/blob/8f093fb799246f7dd9104ff44728da0c53a9f67a/src/transformers/models/t5/modeling_t5.py#L502-L516

The code checkes the sequence length of past_key_values and key_value_states to support prefix-tuning.
In general, the lengths of past_key_value and key_value_state are the same for cross-attention, but different for prefix-tuning.
However, it fails when the length of the source input and the prefix tokens are exactly the same. In this case, the hidden state used in cross-attention whould be past_key_value, which is prefix embeddings and irrelevant with the source input.

A simple solution is to check the source input length and pad an extra dimension if it happens to be equal to the prefix length.

**Comment by diaoenmao** [comment]
Do you know how to fix this?
