### ISSUE TITLE
Object of type ListConfig is not JSON serializable

### ISSUE THREAD

**Issue by khalilRhouma** [huggingface/peft#567]
I am getting `TypeError: Object of type ListConfig is not JSON serializable ` when using `model.save_pretrained("output_dir")` to save the **peft** model after training. the model I used is `"tiiuae/falcon-7b"` 

this is a snippet of code:
```
import torch
from transformers import AutoModelForCausalLM
from peft import (
    LoraConfig,
    get_peft_model,
    get_peft_model_state_dict,
    prepare_model_for_int8_training,
)


model = AutoModelForCausalLM.from_pretrained(
        "tiiuae/falcon-7b",
        trust_remote_code=True,
        load_in_8bit=True,
        device_map="auto",
        torch_dtype=torch.bfloat16,
    )

model.config.use_cache = False
model.gradient_checkpointing_enable()
model = prepare_model_for_int8_training(model)
config = LoraConfig(**config.llm.LoraConfig)
model = get_peft_model(model, config)

old_state_dict = model.state_dict
model.state_dict = (
    lambda self, *_, **__: get_peft_model_state_dict(self, old_state_dict())
).__get__(model, type(model))

model.save_pretrained("output_dir")
```

I got the issue even without using **quantization_config** and I don't know if it is related to this [PR](https://github.com/huggingface/transformers/pull/24137) or not.

this is the traceback:

<img width="898" alt="image" src="https://github.com/huggingface/peft/assets/35801846/41254eb9-4482-4c62-bb1c-2665347fa936">

packages version:
```
transformers==4.30.1
accelerate==0.20.3
peft @ git+https://github.com/huggingface/peft.git
```

**Comment by khalilRhouma** [comment]
Sorry, the issue was from my side. I was passing lora config from hydra and that what cause the issue

**Comment by ziyannchen** [comment]
this issue still occurs in peft==0.13.2

**Comment by BenjaminBossan** [comment]
@ziyannchen Could you provide the code to reproduce the error?
