### ISSUE TITLE
AdaLoRA runtime error: TypeError: eye() missing 1 required positional arguments: "n"

### ISSUE THREAD

**Issue by sineong** [huggingface/peft#569]
I used `peft==0.3.0` to perform adalora finetuning. But I keep getting below error.

Do you have any idea..?

Pytorch version: 2.0.1+cu117
Used GPU Info: NVIDIA A100, Driver Version: 470.82.01, CUDA Version: 11.7

<img width="713" alt="image" src="https://github.com/huggingface/peft/assets/3908484/5d367ab4-5c02-42a4-abad-c318f05c6525">
<img width="713" alt="image" src="https://github.com/huggingface/peft/assets/3908484/7a3531f8-8018-40d9-b602-5a58ef3cef61">
<img width="713" alt="image" src="https://github.com/huggingface/peft/assets/3908484/3a7ff898-e1dd-452e-ab9b-38476dbe13de">

**Comment by cailun01** [comment]
`para_conv.size()` returns empty. Check target module of your `AdaLoraConfig`  may be help.

**Comment by xinghaixu** [comment]
How did you solve it in the end?
