### ISSUE TITLE
[Question] How to resume training for a LoRA training?

### ISSUE THREAD

**Issue by NanoCode012** [huggingface/peft#574]
Hello,

Previously, during saving, `transformers` would save a `pytorch_model.bin` to the `checkpoint-*` folder.

However, I noticed recently this is not done anymore, which would break any `resume_from` functionality for Trainer.

May I ask what is the recommended way to resume the training besides loading from the latest checkpoint's `adapter_model.bin` and start a new training?

**Comment by younesbelkada** [comment]
Hi @NanoCode012 
Thanks for pointing out the issue!
Currently there is an ongoing fix in transformers: https://github.com/huggingface/transformers/pull/24274 therefore once that PR gets merged, you will be able to correctly resume training from a PEFT checkpoint

**Comment by NanoCode012** [comment]
Thank you for the information and clean PR! I will wait for the fix.

**Comment by adityaaryan77** [comment]
Although the training resumes but it doesn't retains the old trained stuff . Can someone please look into this?

**Comment by younesbelkada** [comment]
Hi @adityaaryan77 
I explained how to correctly use that feature here: https://github.com/huggingface/transformers/pull/24274#issuecomment-1596897817

**Comment by younesbelkada** [comment]
Closing as https://github.com/huggingface/transformers/pull/24274 being merged
