### ISSUE TITLE
Peft_config problem when device_map = "auto"

### ISSUE THREAD

**Issue by eleluong** [huggingface/peft#579]
### System Info

Im using mt0_xxl model and trying to use merge_and_unload to save full model.
The problem is i have to use device_map="auto" when load model and offload to some folder. But peft config does not have offload_folder and also i cant use **kwargs.
Please take a look.

### Who can help?

@pacman100 @younesbelkada @sayakpaul

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

# code:
import torch
from peft import PeftModel, PeftConfig
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer
import time 
device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')
print(device)
adapter_path = "path"
peft_model_id = adapter_path

model = AutoModelForSeq2SeqLM.from_pretrained(config.base_model_name_or_path, 
                                              device_map = "auto", 
                                              torch_dtype = torch.bfloat16, 
                                              cache_dir = "cache",
                                              offload_folder  = "offload"
                                             )

tokenizer = AutoTokenizer.from_pretrained(config.base_model_name_or_path)
config = PeftConfig.from_pretrained(peft_model_id)
model = PeftModel.from_pretrained(model, peft_model_id, offload_folder = "offload")

### Expected behavior

cant use offload_folder

**Comment by younesbelkada** [comment]
Hi @eleluong 
Thank you very much for pointing out the issue, https://github.com/huggingface/peft/pull/575 should resolve it
