### ISSUE TITLE
AdaLoRA: can not put ranknum on cuda however  lora_A and lora_B are both on cuda!

### ISSUE THREAD

**Issue by RuSignalFlag** [huggingface/peft#581]
### System Info

cuda 11.7
torch 2.0
peft 0.4.0.dev0
transformers  4.31.0.dev0
accelerate 0.21.0.dev0

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```
model = AutoModel.from_pretrained(
    "THUDM/chatglm-6b",
    trust_remote_code=True,
    device_map='auto',
).half()
```

```
adaloraconfig = AdaLoraConfig(
    task_type=TaskType.CAUSAL_LM,
    init_r=6,
    target_r=4,
    tinit=50,
    tfinal=100,
    deltaT=5,
    beta1=0.3,
    beta2=0.3,
    orth_reg_weight=0.2,
    lora_alpha=32,
    lora_dropout=0.05,
    bias="none",
    target_modules=["query_key_value"]
)
```

```
model = get_peft_model(model, adaloraconfig)
model.base_model.model.transformer.layers[0].attention.query_key_value.lora_A['default'].device
device(type='cuda', index=0)
model.base_model.model.transformer.layers[0].attention.query_key_value.ranknum['default'].device
device(type='cpu')
```
got the  error because self.ranknum[self.active_adapter] is on CPU and other tensors on GPU

but if in AutoModel.from_pretrained add parameter " load_in_8bit"

like this
```
model = AutoModel.from_pretrained(
    "THUDM/chatglm-6b",
    trust_remote_code=True,
    device_map='auto',
    load_in_8bit=True
)
```
the self.ranknum[self.active_adapter] will be put on cuda properly

### Expected behavior

self.ranknum can be put on cuda when loading the model with full precision

**Comment by younesbelkada** [comment]
Hi @RuSignalFlag 
Thank you very much for the handy snippet 
I should have fixed the issue in https://github.com/huggingface/peft/pull/583

**Comment by younesbelkada** [comment]
Awesome thank you very much for the deep dive, yes your explanation makes sense!
