### ISSUE TITLE
Tuned PeftModelForCausalLM generate() function error

### ISSUE THREAD

**Issue by hellorp1990** [huggingface/peft#587]
I tuned the LLaMA 7B model and now is trying to use the tuned model to interact (chat) but the model throws error. My code is following

> import os
 import torch
 from transformers import StoppingCriteria, StoppingCriteriaList,AutoConfig, AutoModel, AutoModelForCausalLM, 
 BitsAndBytesConfig,AutoTokenizer, LlamaForCausalLM
 from peft import PeftConfig,PeftModel
 from transformers import LlamaTokenizer, LlamaForCausalLM,AutoModelForCausalLM
  from peft import (
    LoraConfig,
    get_peft_model,
    get_peft_model_state_dict,
    prepare_model_for_int8_training,
 ` )`
 seed_value= 1
os.environ['PYTHONHASHSEED']=str(seed_value)
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"] = "0,1,2,3"
os.CUDA_LAUNCH_BLOCKING=1

> PATH_TO_CONVERTED_WEIGHTS= '/home/rah/llama-7b/'
PATH_TO_CONVERTED_TOKENIZER='/home/rah/llama-7b/'

model = LlamaForCausalLM.from_pretrained(PATH_TO_CONVERTED_WEIGHTS,
    device_map="auto")

tokenizer = AutoTokenizer.from_pretrained(PATH_TO_CONVERTED_TOKENIZER,
    device_map="auto")

outputdir = "/home/rah/projects/llama_tune/experiment2"
peft_config = PeftConfig.from_pretrained(outputdir)
newmodel = AutoModelForCausalLM.from_pretrained(
        peft_config.base_model_name_or_path,
        load_in_8bit=True,
        return_dict=True,
        device_map="auto",
        torch_dtype=torch.float16,
        low_cpu_mem_usage=True,
)
newmodel = PeftModel.from_pretrained(
        newmodel,
        outputdir,
        torch_dtype=torch.float16,
        device_map={'': 0}
)

class StoppingCriteriaSub(StoppingCriteria):
    def __init__(self):
        super().__init__()

    def __call__(self, input_ids: torch.LongTensor, scores: torch.FloatTensor, stops=[]):
        print('-' * 40)
        print(tokenizer.decode(input_ids[0]))
        if input_ids[0][-1] == 13:
            return True

        return False

ctx = """A dialog, where User interacts with AI. AI is helpful, kind, obedient, honest, and knows its own limits.
User: Hello, AI.
AI: Hello! How can I assist you today?
"""

while True:
    print('-' * 40)
    print(ctx.rstrip("\n"))
    prompt = input(f'User: ')
    if ctx != "":
        ctx = ctx + "User: " + prompt + "\n"
    else:
        ctx = prompt + "\n"

    ctx = (ctx[-1920:]) if len(ctx) >= 2048 else ctx

    if len(ctx.strip()) > 0:
        batch = tokenizer(ctx, return_tensors="pt")
        result = newmodel.generate(batch["input_ids"].to('cuda'),
                                do_sample=True,
                                top_k=50,
                                max_length=6000,
                                top_p=0.95,
                                temperature=1.0,
                                stopping_criteria=StoppingCriteriaList([StoppingCriteriaSub()]),
                                #repetition_penalty=1.0,
                                )
        decoded = tokenizer.decode(result[0])
        ctx = decoded
        print("\n")

 

The error coming is the following: 

> TypeError: PeftModelForCausalLM.generate() takes 1 positional argument but 2 were given

Can anyone help to solve the issue?

**Comment by younesbelkada** [comment]
hi @hellorp1990 
Thanks for the issue
I think the generate method for PEFT models requires explicit positional arguments, can you try to call `generate` as follows:
```python
result = newmodel.generate(input_ids=batch["input_ids"].to('cuda'),
```

**Comment by hellorp1990** [comment]
@younesbelkada Thank you so much. It works.
