### ISSUE TITLE
 AdaLoRA supports the replacement of bnb 4bit quantization layer

### ISSUE THREAD

**Issue by RuSignalFlag** [huggingface/peft#595]
### Feature request

When the model is loaded with 4bit quantization, it is hoped that the adalora layer can be used for replacement

### Motivation

4bit quantized loading model and use adalora for finetuning

### Your contribution

nothing

**Comment by younesbelkada** [comment]
Hi @RuSignalFlag 
Thanks for the issue, I just made https://github.com/huggingface/peft/pull/598 that should add 4bit support for Adalora layers
