### ISSUE TITLE
`modules_to_save` incompatible with `load_in_4bit / load_in_8bit` ?

### ISSUE THREAD

**Issue by linhdvu14** [huggingface/peft#602]
### System Info

Python version: 3.10.8
torch==2.0.1+cu118
transformers @ git+https://github.com/huggingface/transformers.git@17a55534f5e5df10ac4804d4270bf6b8cc24998d
peft @ git+https://github.com/huggingface/peft.git@3714aa2fff158fdfa637b2b65952580801d890b2
accelerate @ git+https://github.com/huggingface/accelerate.git@7d24bdefb5b3252505151d8c1ac0efbed3574857
bitsandbytes==0.39.0

### Who can help?

 @pacman100

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

I'm trying to train a LoRA sequence classification model and found that gradient updates were applied to `original_module` instead of `modules_to_save.default`. This causes issues when loading the trained adapter for inference.

I've tried different combinations of `load_in_{4,8}bit, device_map, resize_token_embeddings, prepare_model_for_kbit_training`, etc. The only combination that behaves as expected was `load_in_4bit=False, device_map=None, should_resize_token_embeddings=True, should_prepare_model_for_kbit_training=False` (i.e. removing `device_map='auto'`). However this is not an option for `load_in_{4,8}bit`.

Thanks for your work and would appreciate any suggestions.

```python
import fire
 
import torch
from peft import LoraConfig, TaskType, get_peft_model, prepare_model_for_kbit_training
from transformers import AutoTokenizer, AutoModelForSequenceClassification, set_seed 

set_seed(123)

PRETRAIN = 'bigscience/bloomz-560m'
tokenizer = AutoTokenizer.from_pretrained(PRETRAIN)


def main(load_in_4bit=False, device_map='auto', should_resize_token_embeddings=False, should_prepare_model_for_kbit_training=False):
    model = AutoModelForSequenceClassification.from_pretrained(
        PRETRAIN,
        load_in_4bit=load_in_4bit,
        torch_dtype=torch.float32,
        device_map=device_map,
    )
    if should_prepare_model_for_kbit_training: model = prepare_model_for_kbit_training(model)

    config = LoraConfig(
        r=16,
        lora_alpha=16,
        lora_dropout=0.05,
        bias="none",
        task_type=TaskType.SEQ_CLS,
    )

    peft_model = get_peft_model(model, config)
    if should_resize_token_embeddings: model.resize_token_embeddings(len(tokenizer))

    lm_head = peft_model.base_model.model.score
    original_module = lm_head.original_module
    modules_to_save = lm_head.modules_to_save.default
    
    inputs = torch.randn((1024))
    o1 = lm_head(inputs)
    o1.mean().backward()
    original_module_has_grad = original_module.weight.grad is not None
    modules_to_save_has_grad = modules_to_save.weight.grad is not None
    print(f'{load_in_4bit=}, {device_map=}, {should_resize_token_embeddings=}, {should_prepare_model_for_kbit_training=} --> {original_module.weight.requires_grad=}, {modules_to_save.weight.requires_grad=}, {original_module_has_grad=}, {modules_to_save_has_grad=}')


if __name__ == '__main__':
    fire.Fire(main)


# load_in_4bit=False, device_map='auto', should_resize_token_embeddings=False, should_prepare_model_for_kbit_training=False --> original_module.weight.requires_grad=True, modules_to_save.weight.requires_grad=True, original_module_has_grad=True, modules_to_save_has_grad=False
# load_in_4bit=False, device_map=None, should_resize_token_embeddings=False, should_prepare_model_for_kbit_training=False --> original_module.weight.requires_grad=True, modules_to_save.weight.requires_grad=True, original_module_has_grad=False, modules_to_save_has_grad=True ***ONLY THIS IS AS EXPECTED***
# load_in_4bit=False, device_map='auto', should_resize_token_embeddings=True, should_prepare_model_for_kbit_training=False --> original_module.weight.requires_grad=True, modules_to_save.weight.requires_grad=True, original_module_has_grad=True, modules_to_save_has_grad=False
# load_in_4bit=True, device_map='auto', should_resize_token_embeddings=False, should_prepare_model_for_kbit_training=True --> original_module.weight.requires_grad=True, modules_to_save.weight.requires_grad=True, original_module_has_grad=True, modules_to_save_has_grad=False
# load_in_4bit=True, device_map='auto', should_resize_token_embeddings=True, should_prepare_model_for_kbit_training=True --> original_module.weight.requires_grad=True, modules_to_save.weight.requires_grad=True, original_module_has_grad=True, modules_to_save_has_grad=False
# load_in_4bit=True, device_map=None, should_resize_token_embeddings=False, should_prepare_model_for_kbit_training=True --> ValueError: A device map needs to be passed to run convert models into 8-bit and 4-bit formats. Please run`.from_pretrained` with `device_map='auto'`
```

### Expected behavior

`modules_to_save.default` should get updated instead of `original_module`

**Comment by 00ber** [comment]
I'm also experiencing something similar! 
Until this is fixed, I'm using the following workaround, which seems to work for me (will need to retrain the classifier again though): 

1. Along with the model, save the classification head's state dict separately
```
..........
model.save_pretrained("my-awesome-model")
torch.save(model.score.state_dict(), 'score-params.pt')
```
2. During inference, after loading the peft model, load the saved params into the model's classification head
```
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from peft import PeftModel, PeftConfig

device_map = "auto"
peft_model_id = "my-awesome-model"
config = PeftConfig.from_pretrained(peft_model_id)
model = AutoModelForSequenceClassification.from_pretrained(
    config.base_model_name_or_path,
    load_in_8bit=True,
    torch_dtype=torch.float16,
    device_map=device_map,
    num_labels=3
)
model = PeftModel.from_pretrained(model, peft_model_id)
tokenizer = AutoTokenizer.from_pretrained(config.base_model_name_or_path)
score_params = torch.load('score-params.pt') 
model.score.load_state_dict(score_params)
```

**Comment by linhdvu14** [comment]
Thanks @00ber for sharing your workaround.

I wonder what is the purpose of `ModulesToSaveWrapper` splitting into `original_module` and `modules_to_save`? Don't you always want to retrain the head i.e. no need for `original_module`?

Aside from this issue, I've also ran into a weird `modules_to_save` error with DeepSpeed zero3. Seems if you initialize DeepSpeed before creating the model (e.g. by using `HfArgumentParser`):
1. `from_pretrained` will partition model params: https://github.com/huggingface/transformers/blob/v4.30.2/src/transformers/modeling_utils.py#L2666
2. `ModulesToSaveWrapper` will copy the (now empty) `original_module`: https://github.com/huggingface/peft/blob/main/src/peft/utils/other.py#L136
3. The forward pass will `RuntimeError: size mismatch, got XX, XXxYYY,0` as the head is empty

Seems this module might need more testing?

**Comment by 00ber** [comment]
@linhdvu14 I'm not sure of the original purpose behind splitting into original_module and modules_to_save either....But yeah, this module definitely needs a bit more testing it seems. I thought it was an issue just with the sequence classification model, but recently when I tried saving the LM Head for a CausalLM model, I faced a similar issue of the weights not being saved correctly.

**Comment by liuyu666-thu** [comment]
> @linhdvu14 I'm not sure of the original purpose behind splitting into original_module and modules_to_save either....But yeah, this module definitely needs a bit more testing it seems. I thought it was an issue just with the sequence classification model, but recently when I tried saving the LM Head for a CausalLM model, I faced a similar issue of the weights not being saved correctly.

@00ber @younesbelkada  I met the same weird problem and had a rough conclusion: it is caused by `dispatch_model` function triggered by `load_in_8bit=True` or 'device_map is not None'. A AlignDeviceHook may be attached to that causes unexpected module forwarding.

**Comment by sjrl** [comment]
I'm also running into the same issue. Thanks for the workaround @00ber, I'll try that out today.

**Comment by BenjaminBossan** [comment]
Hey, thanks everyone here for investigating this bug and providing code to replicate it. We could confirm the error and could pinpoint the issue, the fix is provided in #755. Since this is quite a tricky bug, it would be great if you could help us by checking if the fix solves your original problem.

**Comment by vincentmin** [comment]
@BenjaminBossan Thanks for looking into this issue. For my understanding, could you explain if this fix requires a retraining of our models, or if we can use the adapters from our original training with the old code?

**Comment by vincentmin** [comment]
I just tried running the following code from @younesbelkada new fix branch:
```
import torch
from peft import PeftModel, PeftConfig
from transformers import AutoModelForSequenceClassification, AutoTokenizer

peft_model_id = "vincentmin/llama-2-7b-reward-oasst1"
config = PeftConfig.from_pretrained(peft_model_id)
model = AutoModelForSequenceClassification.from_pretrained(
    config.base_model_name_or_path,
    num_labels=1,
    load_in_8bit=True,
    torch_dtype=torch.float16,
)
model = PeftModel.from_pretrained(model, peft_model_id)
tokenizer = AutoTokenizer.from_pretrained(config.base_model_name_or_path, use_auth_token=True)
model.eval()
with torch.no_grad():
  test = model(**tokenizer("hello world", return_tensors='pt')).logits
test
```
If I run it twice, I get different results.
Note that the adapters that I load here were created from a training run on the old branch.
I guess that answers my question above: "We cannot use adapters from our original training with the old code".
I can try again tomorrow to see if the issue is fixed if we also train on the new branch.

**Comment by vincentmin** [comment]
@BenjaminBossan I managed to confirm that #755 fixes my issue. I trained in 4bit on the branch #755 and can now consistently load the model with the same model output. Thanks @BenjaminBossan  and @younesbelkada !

**Comment by yangjianxin1** [comment]
> I experienced the same problem today. I had 92% accuracy during training but after loading the saved model, my model's accuracy dropped to like 30%. I retrained the model and checked the before-training and after-training weights of both `model.score.modules_to_save` and `model.score.original_module` and found that the `model.score.original_module` was being updated rather than `model.score.modules_to_save` which is causing the model to use the non-optimized weights after it is loaded.
> 
> Until this is fixed, I'm using the following workaround, which seems to work for me (will need to retrain the classifier again though):
> 
> 1. Along with the model, save the classification head's state dict separately
> 
> ```
> ..........
> model.save_pretrained("my-awesome-model")
> torch.save(model.score.state_dict(), 'score-params.pt')
> ```
> 
> 2. During inference, after loading the peft model, load the saved params into the model's classification head
> 
> ```
> import torch
> from transformers import AutoTokenizer, AutoModelForSequenceClassification
> from peft import PeftModel, PeftConfig
> 
> device_map = "auto"
> peft_model_id = "my-awesome-model"
> config = PeftConfig.from_pretrained(peft_model_id)
> model = AutoModelForSequenceClassification.from_pretrained(
>     config.base_model_name_or_path,
>     load_in_8bit=True,
>     torch_dtype=torch.float16,
>     device_map=device_map,
>     num_labels=3
> )
> model = PeftModel.from_pretrained(model, peft_model_id)
> tokenizer = AutoTokenizer.from_pretrained(config.base_model_name_or_path)
> score_params = torch.load('score-params.pt') 
> model.score.load_state_dict(score_params)
> ```

it's a good method.

**Comment by wufeim** [comment]
> Thanks @00ber for sharing your workaround.
> 
> I wonder what is the purpose of `ModulesToSaveWrapper` splitting into `original_module` and `modules_to_save`? Don't you always want to retrain the head i.e. no need for `original_module`?
> 
> Aside from this issue, I've also ran into a weird `modules_to_save` error with DeepSpeed zero3. Seems if you initialize DeepSpeed before creating the model (e.g. by using `HfArgumentParser`):
> 
> 1. `from_pretrained` will partition model params: https://github.com/huggingface/transformers/blob/v4.30.2/src/transformers/modeling_utils.py#L2666
> 2. `ModulesToSaveWrapper` will copy the (now empty) `original_module`: https://github.com/huggingface/peft/blob/main/src/peft/utils/other.py#L136
> 3. The forward pass will `RuntimeError: size mismatch, got XX, XXxYYY,0` as the head is empty
> 
> Seems this module might need more testing?

Hi @linhdvu14 how did u fix this issue?

I'm having this same issue when tuning a LLaVA model with LoRA. I added a customize layer with config `LoraConfig(target_modules=['xxx'], modules_to_save=['customi_layer'])`. It failes on `peft==0.4.0` as specified by LLaVA and upgrading to `peft==0.6.2` or `perf==0.8.0` wouldn't fix this issue either. Is https://github.com/huggingface/peft/pull/755 also fixing this issue or some other workaround is still necessary?
