### ISSUE TITLE
trainer with multi-gpu

### ISSUE THREAD

**Issue by hrdxwandg** [huggingface/peft#607]
I want to use trainer.predict to predict datasets by multi-gpu, but actually I only use single one gpu
when I print Seq2SeqTrainingArguments , I get 
![image](https://github.com/huggingface/peft/assets/2166948/c34b25a7-670a-411a-ab85-23910b98cb92)
It shows 8 gpu

I check my code, when I load model, I find something strange
base_model.device: cpu
peftModel is as follows:
![image](https://github.com/huggingface/peft/assets/2166948/cb30b422-7519-4a76-ba32-fa25afc9d720)
it print cuda

how can i fix?

**Comment by younesbelkada** [comment]
hi @hrdxwandg 
Can you share how do you load the base model so that I have more context about your issue?

**Comment by hrdxwandg** [comment]
> hi @hrdxwandg Can you share how do you load the base model so that I have more context about your issue?

load the base_model code:
```
model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True).half()
print(model.device)
print(model)
```

load the lora adapter model code:
```
from peft import PeftModel
model = PeftModel.from_pretrained(model, "output_exp_v2_model_multi_gpus").half()
print(model.device)
print(model)
```

the seq2seq trainer prediction code:
```data_collator_default = DataCollatorWithPadding(tokenizer=tokenizer)
trainer = Seq2SeqTrainer(model = model,
                  args = eval_args,
                  data_collator=data_collator_default)
predictions = trainer.predict(eval_dataset)
```

**Comment by younesbelkada** [comment]
Hi @hrdxwandg 
thanks for adding more details
I am slightly confused, you are using `Seq2SeqTrainer` but you pass an `AutoModel`, also in the first snippet you pass `device_map` whereas you don't in the second snippet.

```python
model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True).half()
print(model.device)
```
Should give you `"cpu"`, and same for the second snippet:
```python
model = PeftModel.from_pretrained(model, "output_exp_v2_model_multi_gpus").half()
print(model.device)
```

Can you elaborate a bit more? 🙏 Thanks

**Comment by hrdxwandg** [comment]
Hi @younesbelkada  thanks for your quick reply

I don't quite follow your explanation. 
In my code test, the first snippet output "cpu", and the second output "cuda". I think only the second should output "cpu" then the `Seq2SeqTrainer` should work fine. 

the first snippet output
<img width="885" alt="image" src="https://github.com/huggingface/peft/assets/2166948/3b52d128-a207-44e9-ae2e-6ea4a0661a55">


the second snippet output
<img width="818" alt="image" src="https://github.com/huggingface/peft/assets/2166948/36a54ed1-290d-4026-b6c1-814955dd6363">
