### ISSUE TITLE
Expanding the docs of `merge_and_unload`

### ISSUE THREAD

**Issue by Narsil** [huggingface/peft#615]
### Feature request

`merge_and_unload` seems like a super nice gateway to "cast down"  a model into a simpler version usable by other hf tools like optimum, tgi etc..

I linked the doc here: https://github.com/huggingface/text-generation-inference/issues/482 but I think a *more complete* documentation *with examples* and *caveats* would be nice.

### Motivation

It's a very useful method to link back to other parts to the HF ecosystem without putting burden on other libs to reimplement peft logic.

### Your contribution

I'm ok to write a PR, but probably not super knowledgeable about how to use and edge cases.

**Comment by Narsil** [comment]
@younesbelkada

**Comment by younesbelkada** [comment]
Totally agreed! cc @pacman100 as well and @stevhliu @MKhalusova FYI

**Comment by stevhliu** [comment]
I opened #650 to add a basic example usage in the API docs, but we'll also benefit from a more comprehensive doc on it!
