### ISSUE TITLE
LoRA + gradient_accumulation_steps > 1 does not work 

### ISSUE THREAD

**Issue by dardodel** [huggingface/peft#619]
We are finetuning Falcon 40B on 8 GPU A100 (80 gigs memory) and the following setting works well when gradient_accumulation_steps=1 but I get error message when gradient_accumulation_steps is larger than 1 (even 2). The error is not about the OOM (see the message below). Any hint? Thanks!
 
torchrun --nproc_per_node=8 --master_port=8657 trainFalconLoRA.py \
    --model_name_or_path  /PATH_TO_PRETRAINED_MODELS/falcon-40b-instruct \
    --data_path /PATH_TO_TRAINING_SET/FAQs.json \
    --deepspeed /PATH_TO_DEEPSPEED_CONFIGS/deep-learning-pytorch-huggingface/training/configs/ds_flan_t5_z3_offload_bf16.json \
    --output_dir ./FalconCkptInstruct40/ \
    --num_train_epochs 2 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "no" \
    --save_steps 2000 \
    --save_total_limit 1 \
    --learning_rate 2e-5 \
    --weight_decay 0.01 \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \

**Error Message:**

self.__all_gather_params(params_to_prefetch)
  File "/.../llmFalcon/lib/python3.9/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn

    ret_val = func(*args, **kwargs)

  File "/.../llmFalcon/lib/python3.9/site-packages/deepspeed/runtime/zero/partitioned_param_coordinator.py", line 386, in __all_gather_params

    handle = partitioned_params[0].all_gather_coalesced(partitioned_params)

  File "/.../llmFalcon/lib/python3.9/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn

    ret_val = func(*args, **kwargs)

  File "/.../llmFalcon/lib/python3.9/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 942, in all_gather_coalesced

    dtype=get_only_unique_item(p.dtype for p in params),

  File "/.../llmFalcon/lib/python3.9/site-packages/deepspeed/runtime/utils.py", line 824, in get_only_unique_item

    raise RuntimeError(f"expected there to be only one unique element in {items}")

RuntimeError: expected there to be only one unique element in <generator object Init._convert_to_deepspeed_param.<locals>.all_gather_coalesced.<locals>.<genexpr> at 0x7facd8051040>

**Comment by friedriceowl** [comment]
I ran into the same issue. Did you get it working or find a workaround?

**Comment by vecorro** [comment]
I had the same issue. In my case, I had to make the value of `gradient_accumulation_steps`  from `TrainingArguments` match the value of `"gradient_accumulation_steps":` from the deep speed config JSON file.
