### ISSUE TITLE
Cannot import LoraConfig

### ISSUE THREAD

**Issue by xiaohengDa** [huggingface/peft#625]
### System Info

Windows 10

### Who can help?

@pacman100 @younesbelkada @sayakpaul

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

from peft import LoraConfig

[warnings and errors]
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
CUDA SETUP: Loading binary [c:\ProgramData\anaconda3\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...](file:///C:/ProgramData/anaconda3/lib/site-packages/bitsandbytes/libbitsandbytes_cpu.so...)
argument of type 'WindowsPath' is not iterable
-----------------------------------
CUDA Setup failed despite GPU being available.

[Other information]
![image](https://github.com/huggingface/peft/assets/134503417/f388f211-1e23-4c8f-a111-ffa9077901b5)
my system is running normally for LLMs like chatGLM.
Cannot find libcudart.so and libcuda.so in C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\lib\x64
Cannot locate libcudart.so and libcuda.so in my system

[ACTIONS TRIED BUT USELESS]
1. uninstall and reinstall bitesandbytes
2. reinstall CUDA 11.7
3. Copy libcuda.so from a linux environment and paste in C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\lib\x64

### Expected behavior

can import normally

**Comment by younesbelkada** [comment]
Hi @xiaohengDa 
Can you try with:
```bash
pip install git+https://github.com/huggingface/peft.git
```
Thanks

**Comment by xiaohengDa** [comment]
> Hi @xiaohengDa Can you try with:
> 
> ```shell
> pip install git+https://github.com/huggingface/peft.git
> ```
> 
> Thanks

I tried but still the same issue. Does this come from my system? Is this command only for Linux?

**Comment by younesbelkada** [comment]
Hi @xiaohengDa 
I am unable to reproduce, can you try on a fresh new virtual enviornment?

**Comment by tanhm12** [comment]
@xiaohengDa bitsandbytes is not supposed to run on Windows, only Linux distributions are supported. And even on Ubuntu, some servers like mine are not able to install bitsandbytes without some tweaks, like installing from source and specifying Cuda version 
`CUDA_VERSION=120 python setup.py install`

**Comment by jinge170** [comment]
Hi@xiaohengDa, I also meet this issue, did you solve it ?
