### ISSUE TITLE
P-tuning (GPT Understands, too)

### ISSUE THREAD

**Issue by MichelleHS777** [huggingface/peft#627]
### System Info

I was wondering that if I set virtual tokens=10
What’s the input format for p-tuning?

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### Tasks

- [x] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

No

### Expected behavior

P tuning input format

**Comment by pacman100** [comment]
Hello @MichelleHS777, please refer https://github.com/huggingface/peft/blob/main/examples/sequence_classification/P_Tuning.ipynb for an example of how to use P-Tuning along with https://huggingface.co/docs/peft/task_guides/ptuning-seq-classification

Empirically, P-Tuning doesn't lead to good performance. We would suggest trying out Prefix-Tuning or LoRA
