### ISSUE TITLE
How to load GPT model in 8bit in a multi-GPU environment with Trainer class

### ISSUE THREAD

**Issue by yutanozaki1** [huggingface/peft#629]
I saw an earlier issue and added two lines of `setattr` after loading the model with int8 to work around this, as Data Parallel runs by default in the Trainer class.

```
model = AutoModelForCausalLM.from_pretrained(model_name_or_path, load_in_8bit=True, device_map="auto")
model = prepare_model_for_int8_training(model)
setattr(model, 'model_parallel', True)
setattr(model, 'is_parallelizable', True)  

trainer = Trainer(...)
trainer.train()
```
This is done with the following bash command.
`
accelerate launch --gpu_ids 'all' loratune.py
`

Will Model Parallel now work?

This link says this is not recommended.
[https://github.com/huggingface/transformers/pull/22532#issue-1652149748](url)

How can I currently implement Model Parallel?

**Comment by younesbelkada** [comment]
Hi @yutanozaki1 
I think now with the `accelerate` integration of Trainer the hacks,
```
setattr(model, 'model_parallel', True)
setattr(model, 'is_parallelizable', True)  
```
Are probably not needed anymore. You just need to make sure that the model is loaded on a single device (what I do is `device_map={"":Accelerator().process_index}`):
```python
from accelerate import Accelerator

model = AutoModelForCausalLM.from_pretrained(model_name_or_path, load_in_8bit=True, device_map={"":Accelerator().process_index})
model = prepare_model_for_int8_training(model)
...
```
Then make sure you have selected "multi-GPU" in `accelerate` config and run your script with `accelerate launch yourscript.py`. Let us know how it goes

**Comment by yutanozaki1** [comment]
This is my changed codes.

```
model = AutoModelForCausalLM.from_pretrained(
        model_name_or_path, 
        load_in_8bit=True, 
        device_map={"":Accelerator().process_index},
    )
    model = prepare_model_for_int8_training(model,use_gradient_checkpointing=False)

trainer = transformers.Trainer(
    model=model, 
    train_dataset=train_data,
    eval_dataset=val_data,
    data_collator=DataCollatorForLanguageModeling(tokenizer, mlm=False),
    args=transformers.TrainingArguments(
        per_device_train_batch_size=1, 
        gradient_accumulation_steps=16,
        fp16=True,
        num_train_epochs=20, 
        learning_rate=3e-4, 
        output_dir=output_dir,
        evaluation_strategy='epoch',
        save_strategy="epoch",
        load_best_model_at_end=args.load_best_model_at_end,
        optim="adamw_8bit"
    ),
    callbacks=[EarlyStoppingCallback(early_stopping_patience=3)] 
)

trainer.train()
```

**Comment by younesbelkada** [comment]
Great that it worked! 
Currently the paradigm that is in place is pure DDP (Data Parallel), you have a copied replia of the entire training setup in each GPU, and each GPU will receive a different batch, and the gradients and optimizer states are syncronized across all GPUs. 
Currently TP and pure PP are not supported with 8bit / 4bit + PEFT. You can probably use DS + PEFT but without  quantization

**Comment by younesbelkada** [comment]
Note that GPT2 support in 8bit has been recently added: https://github.com/huggingface/transformers/pull/24504 you can use it by installing the main branch of transformers
Closing this issue for now, feel free to re-open if you have more questions

**Comment by ereday** [comment]
Hi @yutanozaki1  . I'm trying to do something similar to what you shared above (i.e. loading an LLM in 8 or 4 bit, an finetuning it with lora using multi-gpu). When I initialise the model as @younesbelkada have shown above I got this error after loading the model:

> Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
> RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 1) Use of a module parameter outside the `forward` function. Please make sure model parameters are not shared across m
> ultiple concurrent forward-backward passes. or try to use _set_static_graph() as a workaround if this module graph does not change during training loop.2) Reused parameters in multiple reentrant backward passes. For example, if you
>  use multiple `checkpoint` functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant backward passes multiple times, and hence marking a variable ready multiple ti
> mes. DDP does not support such use cases in default. You can try to use _set_static_graph() as a workaround if your module graph does not change over iterations.


Did you also get this error? If so, do you know how to fix it? My code is below: 

```
bnb_config = BitsAndBytesConfig(
     load_in_8bit=True,
)

# load model from the hub
model = AutoModelForSeq2SeqLM.from_pretrained(model_id, quantization_config=bnb_config, device_map={"":Accelerator().process_index})
model.gradient_checkpointing_enable()
model = prepare_model_for_kbit_training(model)

# Define LoRA Config
lora_config = LoraConfig(
 r=16,
 lora_alpha=32,
 target_modules=["q", "v"],
 lora_dropout=0.05,
 bias="none",
 task_type=TaskType.SEQ_2_SEQ_LM
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()


data_collator = DataCollatorForSeq2Seq(
    tokenizer,
    model=model,
    label_pad_token_id=label_pad_token_id,
    pad_to_multiple_of=8
)

# Define training args
training_args = Seq2SeqTrainingArguments(
    output_dir=output_dir,
    learning_rate=3e-4,
    num_train_epochs=3,
    #max_steps=10,
    logging_dir=f"{output_dir}/logs",
    logging_strategy="steps",
    logging_steps=400,
    save_strategy="steps",
    save_steps=400,
    report_to="tensorboard",
    evaluation_strategy='steps',
    eval_steps=400,
    per_device_train_batch_size=4,
    load_best_model_at_end=True,
)

# Create Trainer instance
trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    data_collator=data_collator,
    train_dataset=tokenized_dataset["train"],
    eval_dataset=tokenized_dataset["valid"]
)
model.config.use_cache = False

trainer.train()

```

**Comment by yutanozaki1** [comment]
Thanks, @younesbelkada 
> You can probably use DS + PEFT but without quantization

Does this mean that in my GPU environment, LoRA-Tuning with PEFT on the 20B model does not require quantization?
Recently, when I try to LoRA-Tuning to a large model (e.g. Llama-2-70B) using PEFT, fp16 + DDP may cause OOM.
So we are considering LoRA-Tuning of quantized model + DDP + PEFT or LoRA-Tuning of quantized model + DS + PEFT.
Does PEFT not support training of quantized models?
