### ISSUE TITLE
How to switch to P-Tuning v2

### ISSUE THREAD

**Issue by jiahuanluo** [huggingface/peft#630]
We can find the `P-Tuning v2` in 
https://github.com/huggingface/peft/blob/8af8dbd2ec9b4b8f664541e9625f898db7c7c78f/README.md?plain=1#L29
But how can I switch to `P-Tuning v2`?

**Comment by pacman100** [comment]
Hello, those are implemented together. `P-Tuning v2` introduced optional parameterization of prompt tokens which you can specify via `prefix_projection` of `PrefixTuningConfig`. The other contribution was the ability of work without verbalizers using the linear classification head for NLU tasks whereas Prefix-Tuning paper which focused on NLG didn't focus on this.

So, they are supported via the same `PrefixEncoder` PEFT method
