### ISSUE TITLE
Anyone using triton python backend?

### ISSUE THREAD

**Issue by YooSungHyun** [huggingface/peft#633]
### System Info

python 3.10
tritonserver:23.05
torch 2.0.1
peft 0.3.0
transformers 4.29.2

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

check, https://github.com/triton-inference-server/server/issues/5989
i want to use PeftModel in tritonserver:23.05, that is not ocurring error, but don't working on....

Anyone else using it like me?
please, give me some tips 😭

### Expected behavior

set_adapter is work good

**Comment by pacman100** [comment]
Hello @YooSungHyun, as per https://github.com/triton-inference-server/server/issues/5989#issuecomment-1608992718, the issue seems to stem from the fact that `torch.compile` is incompatible with Peft models at present. We will put the deep dive for this in our backlog but this will take time.

**Comment by YooSungHyun** [comment]
@pacman100 thx, if you need something, i will help you. plz just tagging me🤗

**Comment by YooSungHyun** [comment]
if i use like this.
``` python3
model = AutoModelForCausalLM.from_pretrained(
    optional_config["model_path"],
    low_cpu_mem_usage=bool(strtobool(optional_config["low_cpu_mem_usage"])),
    load_in_8bit=bool(strtobool(optional_config["load_in_8bit"])),
    torch_dtype=getattr(torch, optional_config["torch_dtype"], None),
    device_map=device_map,
)

self.model = PeftModel.from_pretrained(
    model,
    optional_config["aa_lora_weights"],
    adapter_name=optional_config["aa_lora_name"],
    device_map=device_map,
)
self.model.load_adapter(
    optional_config["bb_lora_weights"],
    adapter_name=optional_config["bb_lora_name"],
    device_map=device_map,
)
model = torch.compile(model)
self.model.eval()
```

it work fine

**Comment by pacman100** [comment]
Great! So, it works!

**Comment by YooSungHyun** [comment]
@pacman100 but, this is weired... why important `torch.compile`'s implement line number...?

**Comment by pacman100** [comment]
Torch.compile should always be at the end of all the preprocessing of the model. For example, when using DDP too, torch.compile is applied after wrapping the model in DDP.

**Comment by YooSungHyun** [comment]
@pacman100 oh thx

**Comment by YooSungHyun** [comment]
@pacman100 ah.. how about `eval()`?

1. 
``` python3
model.eval()
model = torch.compile(model)
```

2. 
``` python3
model = torch.compile(model)
model.eval()
```

each correct?

**Comment by YooSungHyun** [comment]
@pacman100 hello?

**Comment by YooSungHyun** [comment]
@pacman100
