### ISSUE TITLE
importing peft with an old version of bitsandbytes causes an exception

### ISSUE THREAD

**Issue by glerzing** [huggingface/peft#642]
### System Info

Importing peft with the bitsandbytes version "0.39.1" works. But when importing peft with the version "0.38.1", I get an exception : `AttributeError: module 'bitsandbytes.nn' has no attribute 'Linear4bit'`.

Indeed, the class `SVDLinear4bit` should be defined only if `is_bnb_4bit_available()`, not just if `is_bnb_available()`.

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

in a notebook :
!pip install 'bitsandbytes==0.38.1'
import peft

### Expected behavior

no exception

**Comment by glerzing** [comment]
@younesbelkada This issue seems important if you plan a new release.

**Comment by younesbelkada** [comment]
thanks for the ping @glerzing 
Did https://github.com/huggingface/peft/pull/605 not fixed the issue? can you confirm you get that even with the main branch of PEFT?
That PR introduced a stronger check, and should be using the `is_bnb_4bit_available` method: https://github.com/huggingface/peft/blob/f5352f08c593503a442f4438e1c7e648377b6a4b/src/peft/tuners/adalora.py#L11

**Comment by glerzing** [comment]
Yes, I confirm. And I made a PR here : https://github.com/huggingface/peft/pull/646

**Comment by younesbelkada** [comment]
Thanks a lot @glerzing 
Merged #646
