### ISSUE TITLE
AttributeError: 'T5ForConditionalGeneration' object has no attribute 'disable_adapter_layers'

### ISSUE THREAD

**Issue by TheTahaaa** [huggingface/peft#645]
Hi, and thanks for implementing this amazing library.

I've fine-tuned a T5ForConditionalGeneration model in a supervised manner using PEFT wrapper, and now want to fine-tune it again using TRL. Within the TRL trainer, there is [a piece of code](https://github.com/lvwerra/trl/blob/e1531aa52679082e839c3266ac774662046d9942/trl/trainer/ppo_trainer.py#L616) as follows:

<img width="1078" alt="Screenshot 2023-06-27 at 9 05 00 PM" src="https://github.com/huggingface/peft/assets/30401154/78ea5ec8-f435-42be-a549-e62311b095bb">

However, after entering the first if, I get this error:

<img width="782" alt="Screenshot 2023-06-27 at 9 06 13 PM" src="https://github.com/huggingface/peft/assets/30401154/7c3793d3-c88b-4c23-a544-4e6c098c2824">

I wonder why this is the case, and appreciate any help.

**Comment by pacman100** [comment]
Hello, this seems like a bug. cc @younesbelkada who has more context on TRL

**Comment by TheTahaaa** [comment]
Hey @younesbelkada, I made an effort to gain a bit more understanding of this issue and help in resolving it. Upon examining the [PreTrainedModel class](https://github.com/huggingface/transformers/blob/fe861e578f50dc9c06de33cd361d2f625017e624/src/transformers/modeling_utils.py#L1027) I didn't find a defined method called  'disable_adapter_layers()'. Do you recommend searching for another class that might contain this method? It seems that in the peft_model.py file, 'disable_adapter_layers()' is invoked as a method of self.base_model, which is an instance of the PreTrainedModel class.

**Comment by younesbelkada** [comment]
Hi @TheTahaaa 
Thanks for the heads up !
Can you share a small reproducible snippet ? 🙏 
If you have implemented things correctly, the PPO Trainer should work as expected, there is a check that correctly checks if the model is a peft model. How do you create the PEFT model and pass it to the trainer?

**Comment by TheTahaaa** [comment]
Hey there @younesbelkada , 
I think this bug is for the case of using the Prefix Tuning type in PEFT (at least with the T5 model) since I changed Prefix to LoRA (I only changed `PrefixTuningConfig()` to 'LoraConfig'), and everything seems fine right now. 
I will examine the problem with Prefix-Tuning again and share a small snippet of code if I encounter the bug again.

**Comment by TheTahaaa** [comment]
Hey again @younesbelkada, 
I reproduce the bug again. However, I think it's more related to TRL than PEFT. I think we can continue [here](https://github.com/lvwerra/trl/issues/470).

**Comment by younesbelkada** [comment]
Perfect, let's switch the discussion there, closing this issue
