### ISSUE TITLE
Prototype LoRA/Adapter/Prefix-tuning support - Arxiv

### ISSUE THREAD

**Issue by he20010515** [huggingface/peft#648]
### Feature request

Hello every one. There is a awesome work in arxiv named : [One Network, Many Masks: Towards More Parameter-Efficient Transfer Learning](https://arxiv.org/abs/2305.17682).

I implement a method of it named Prototype LoRA in my repo I forked [here](https://github.com/he20010515/peft), You can see it in prototype_dev branch.  I hope to get everyone's support, thank you. 🙉🙉🙉

PS: this is my first issue and try to contribute. thanks for my poor English.

### Motivation

This work can save disk space by binary mask with different task and different layers. and do better than other LoRA methods.(maybe

### Your contribution

I will try implement tuners in the paper and create a pr try my best, although  I'm NOT author of this paper.

**Comment by younesbelkada** [comment]
This is great ! @he20010515 
Thank you for sharing this, feel free to start opening a PR to add that method. You can take some inspiration from ongoing works such as https://github.com/huggingface/peft/pull/578
