### ISSUE TITLE
Can I give the number of steps to save the model file?

### ISSUE THREAD

**Issue by ScottishFold007** [huggingface/peft#65]
![image](https://user-images.githubusercontent.com/36957508/217777521-ece80a5c-01b7-4bc7-be43-099b8a0441fc.png)
When I am using the code below (red box area), The line 'accelerator.backward(loss) 'will report an error, and displays "**Element 0 of tensors does not require grad and does not have a grad_fn**"

**Comment by pacman100** [comment]
Hello @ScottishFold007 , please let us know if the above PR fixes the issue. Install the branch via `pip install git+https://github.com/huggingface/peft.git@smangrul/fix-save-pretrained`

**Comment by pacman100** [comment]
Please check if the latest main branch fixes the issue

**Comment by ScottishFold007** [comment]
> Please check if the latest main branch fixes the issue

Good, you got it covered with this solution! Thank you very much!
