### ISSUE TITLE
Is it necessary to provide target_modules in LoraConfig?

### ISSUE THREAD

**Issue by siddhsql** [huggingface/peft#659]
as the title states, Is it necessary to provide target_modules in LoraConfig? what happens if i don't? how do i find out what target_modules to provide when using a model whose internals I don't know?

**Comment by younesbelkada** [comment]
Hi @siddhsql 
If the model is correctly present here: https://github.com/huggingface/peft/blob/39ef2546d5d9b8f5f8a7016ec10657887a867041/src/peft/utils/other.py#L220 you don't need to manually pass the target modules to LoraConfig. For architectures that are not present in that dictionary you need to manually pass the target module. Hope this is clear
