### ISSUE TITLE
whisper-peft model to onnx

### ISSUE THREAD

**Issue by marziye-A** [huggingface/peft#660]
@pacman100 
hi,thanks for your excellent work
is there any way to convert a peft model to onnx?
i saw a pull request but it isn't merged.it is in the following link:
[https://github.com/huggingface/peft/blob/smangrul/add-lora-model-to-onnx-conversion-notebook/examples/inference/convert_lora_model_to_onnx.ipynb
](url)
and using the code gives the following error:
`AttributeError: 'str' object has no attribute 'detach'`
any help is really appreciated.

**Comment by ingo-m** [comment]
Using the `bigscience/bloom-560m` base model and finetuning with PEFT / LoRA, I was able to export to ONNX and perform inference, but the model predictions are degraded 🤔 Details: https://github.com/huggingface/peft/issues/670

Not sure whether ONNX export after PEFT / LoRA finetuning is actually supported yet.
