### ISSUE TITLE
Progress bar merge_and_unload

### ISSUE THREAD

**Issue by BramVanroy** [huggingface/peft#667]
### Feature request

Merging adapters takes time, although I must admit that I am not sure whether most time is taken by loading the base model or by the merging itself. If a lot of time is taken by the merging itself, it can be useful for users to see a progressbar. Specifically, a tqdm can be added here:

https://github.com/huggingface/peft/blob/9f7492577ff91c51077308f98dade45bf32c268a/src/peft/tuners/lora.py#L433

which should be disable-able with a function argument `progressbar: bool = True` or similar.

### Motivation

Users benefit when a time-consuming process gets a progressbar

### Your contribution

If you think this is a good idea, I can add it.

**Comment by younesbelkada** [comment]
Hi @BramVanroy 
indeed that would be great! Feel free to open a PR
