### ISSUE TITLE
Is convert_peft_sd_lora_to_kohya_ss.py not quite suitable for SD 2.0?

### ISSUE THREAD

**Issue by Ted-developer** [huggingface/peft#677]
Upon training LoRa through 

peft/examples/lora_dreambooth/train_dreambooth.py,

 the resulting model, when used in webui, generates a large number of unexpected_keys, all originating from the text_encoder-related key.

In debugging the sd-webui-additional-networks plugin, it was found that during the loading of LoRa, it didn't reach https://github.com/kohya-ss/sd-webui-additional-networks/blob/main/scripts/lora_compvis.py#L482 at all.

Could you please tell me whether the convert_peft_sd_lora_to_kohya_ss.py script is supportive of SD 2.0? Or is it solely compatible with SD 1.x. Is there any way to make it compatible with SD 2.0?

Thank you very much for your reply.

**Comment by kovalexal** [comment]
Hi, @Ted-developer!

Thank you for your feedback!

I've written the script [convert_peft_sd_lora_to_kohya_ss.py](examples/lora_dreambooth/convert_peft_sd_lora_to_kohya_ss.py), so basically I've tested it only with SD 1.5.

Could you please provide a sample of the LoRA model you are trying to convert (it can be LoRA model before training, I just need a LoRA structure to investigate this case) or provide LoRA layers you are trying to modify?
I need this info to debug this case and fix it.

**Comment by Ted-developer** [comment]
Hi, @kovalexal 

Have you found the problem yet?

**Comment by kovalexal** [comment]
Hi, @Ted-developer, sorry for late response.

Have just tested the checkpoint you've provided, from my perspective if works just fine with sd-webui-additional-networks plugin and webui (with SD 2.1 checkpoint). However, there is a warning in terminal, that provided converted LoRA has some unexpected keys in text encoder, so probably need more time to investigate what is going on.

It's not quite clear to me, what are you trying to achieve with xformers - are you trying to train a LoRA adapter for SD 2.1 using PEFT? Is your problem related to convert_peft_sd_lora_to_kohya_ss.py? Are you trying to use the converted PEFT model to train using sd-scripts? According to the traceback you've provided - there is a mismatch in tensor dtypes, so you should probably check whether both the base model and LoRA adapter use the same dtype.

Please provide more details for investigating this issue.
