### ISSUE TITLE
add lora bias even if the `target.bias` don't exist

### ISSUE THREAD

**Issue by LZY-the-boys** [huggingface/peft#679]
### Feature request

I set the **lora_bias='lora_only'**, however, the bias logit need bias exist in the module with which lora replaces . Because in the following code 
```
def mark_only_lora_as_trainable(model: nn.Module, bias: str = "none") -> None:
    ...
    elif bias == "lora_only":
        for m in model.modules():
            if isinstance(m, LoraLayer) and hasattr(m, "bias") and m.bias is not None:
                m.bias.requires_grad = True
    ...
```
`m.bias` is depended on `target.bias` , which may not exist. 
```
def _find_and_replace(...):
  ...
  if hasattr(target, "bias"):
      bias = target.bias is not None
 ...
```
I want to add lora bias even if the `target.bias` is not exists.

### Motivation

My motivation come from here https://github.com/huggingface/peft/issues/622: @pacman100 said making biases as trainable via bias config param ('all' or 'lora_only')

### Your contribution

yes

**Comment by BenjaminBossan** [comment]
To clarify, for a given target module that does not have a bias, you want peft to create the bias when setting `lora_bias='lora_only'`?

**Comment by BenjaminBossan** [comment]
@pzdkn I don't fully understand, are you asking me how to enable the biases to be trainable when using LoRA? For this, pass `bias="lora_only"` or `bias="all"` to the `LoraConfig`, depending on your needs. Also note that you can always manually enable or disable which parameters should be updated by setting `requires_grad` _after_ calling `get_peft_model`.

**Comment by pzdkn** [comment]
For my use case, I want to add a separate trainable bias as part of the LoRA adapters (even if the original base model has no bias). 
I was wondering if I can use the mentioned method from OP, but this is not the case. It will only enable the bias of the original model I think. @BenjaminBossan

**Comment by BenjaminBossan** [comment]
> I want to add a separate trainable bias as part of the LoRA adapters (even if the original base model has no bias).

I see, this is not possible like this. Probably it would be best to first load the base model, loop through all relevant layers, register the bias as a new trainable parameter, and then create the PEFT model with the appropriate `bias` argument.
