### ISSUE TITLE
Vision question answering

### ISSUE THREAD

**Issue by ppyt** [huggingface/peft#682]
### Feature request

Would you please add an example about how to fine-tune BLIP2 on a VQA dataset？

### Motivation

VQA IS VERY IMPORANT 

### Your contribution

Sorry.

**Comment by dszpr** [comment]
Hi bro, I am also working on BLIP2-VQA task and want to use LoRA to fine-tune the LLM module. Have you already accomplished this? @ppyt

**Comment by chengjiali** [comment]
Same question here. This is not resolved. Please re-open it.
