### ISSUE TITLE
Can peft support timm style ViT model when using lora?

### ISSUE THREAD

**Issue by double-fire-0** [huggingface/peft#691]
### Feature request

Peft does not support finetune timm style ViT model now (correct me if I'm wrong).

The timm style ViT model uses a trick that makes qkv in one matrix. See code [here](https://github.com/huggingface/pytorch-image-models/blob/394e8145551191ae60f672556936314a20232a35/timm/models/vision_transformer.py#L72)

### Motivation

#

### Your contribution

this project may can help with this issue
https://github.com/JamesQFreeman/LoRA-ViT

**Comment by younesbelkada** [comment]
Hi @double-fire-0 
That might work yes, can you try to run this notebook: https://github.com/huggingface/peft/blob/main/examples/image_classification/image_classification_peft_lora.ipynb with timm models instead of HF models? 

If not https://github.com/huggingface/peft/pull/676 should add general support of LoRA, meaning it would work for any model cc @BenjaminBossan

**Comment by BenjaminBossan** [comment]
Indeed. Please report back any errors you may encounter, so that we could take care of them in #676.

**Comment by double-fire-0** [comment]
Hi @younesbelkada 
I have run this ipynb before, it can't work correctly even if it doesn't throw error after solving the model attribute problem.

First of all, it will throw error because the timm model doesn't have some attributes compared with the hugging face model.
It will throw errors like this:

```python
from peft import LoraConfig, get_peft_model
import timm

model_timm = timm.create_model('vit_base_patch16_224')
print_trainable_parameters(model_timm)

#model_timm.config = None
config = LoraConfig(
    r=16,
    lora_alpha=16,
    target_modules=["qkv"],
    lora_dropout=0.1,
    bias="none",
    modules_to_save=["classifier"],
)
lora_model = get_peft_model(model_timm, config)
``` 
<img width="898" alt="image" src="https://github.com/huggingface/peft/assets/69890917/fd4c5df2-1fc2-4dbb-88ec-5f37a0273176">

Ang more important, LoRA won't work correctly with timm model style even if somehow we solve the problem above. 
Because timm style writes 'qkv' in one matrix instead of 3 matrixes like hugging face model, it will tune the 'value' matrix if we use the code right now.

And also, hope this can help with @BenjaminBossan when doing #676

**Comment by BenjaminBossan** [comment]
> it will tune the 'value' matrix if we use the code right now.

Is this a deal breaker? I think it should still work, but results will not be 100% identical when compared to not tuning `v`.

**Comment by BenjaminBossan** [comment]
> Lora's paper https://arxiv.org/pdf/2106.09685.pdf show this difference in Table 5&6

If I'm not misreading the results, what they show is that tuning `q` & `v`, vs tuning `q` & `v` & `k` & `o` makes very little difference. If your goal is to fine-tune a model for your own use case, I thus think it's safe to go ahead. If your goal is to replicate the paper results, that wouldn't be possible currently.

> Adding a new lora layer class

Unfortunately, I don't see any easy way to achieve that.

**Comment by double-fire-0** [comment]
The final result may not be obvious, the trainable parameters can be the twice of tuning q & v.
can this be an easy solution?
https://github.com/JamesQFreeman/LoRA-ViT/blob/f81340d7511ffb8d4db4380a35503a3bad61de4c/lora.py#L174

**Comment by BenjaminBossan** [comment]
That could work, but it would be a solution very specific to timm. I think a more general issue is that at the moment, peft is not flexible enough to accommodate for different implementations: 

- there is no mechanism to supply user defined layers
- even if there was, right now, vanilla linear is always replaced by LoRA linear (same for other layer types), so it's not possible to have more nuance in the mapping (after all, not all linear layers are used for qkv calculation)

Mid to long term, I would love to see a solution provided to that problem. Meanwhile, we could certainly add the timm-style linear layer and then have an option in the config that toggles between different styles, but I hope you can see that taking this direction is not very future proof.
