### ISSUE TITLE
Add ability to save only selected adapters

### ISSUE THREAD

**Issue by crowsonkb** [huggingface/peft#699]
### Feature request

I would like the ability to save only selected adapters of a model using the `model.save_pretrained()` method, possibly renaming them (saving one selected adapter as "default", for instance).

### Motivation

I am fine-tuning a model using RLAIF and my reward model is a LoRA of the same base model. When I save using the `model.save_pretrained()` method, it saves both the reward model LoRA (which is "default") and the LoRA I am actually tuning (which is "generator"). I want to only save the generator, there is no need to save the same frozen reward model over and over. I would like the fine-tuned generator to be the *default* adapter in the save so I can just load it in easily to try it. Also if I were to push the model to the Hub, it would upload both the generator and the frozen reward model when I only mean to upload the generator.

### Your contribution

I can test implementations of this feature.

**Comment by younesbelkada** [comment]
Hi @crowsonkb 
Thanks for the suggestion, I drafted over https://github.com/huggingface/peft/pull/705 - could you let us know if this fits your needs and possibly test it? Thanks !
