### ISSUE TITLE
PeftModelForCausalLM.generate() takes 1 positional argument and 2 were given

### ISSUE THREAD

**Issue by Bryan-Lavender** [huggingface/peft#708]
### System Info

peft: 0.3.0
accelerate: 0.20.3
transformers: 4.31.0.dev0

Hello! I am having trouble with the following code:

```python
import torch
from transformers import LlamaForCausalLM, GenerationConfig, LlamaTokenizer
from peft import LoraConfig, get_peft_model, TaskType, PeftModel
import time

weight_location = "alpacaFinalWeights"
Lora_Location = "Lora_Weights"
tokenizer = LlamaTokenizer.from_pretrained(weight_location, local_files_only=True, add_eos_toke=False, device_map="cpu")
model = LlamaForCausalLM.from_pretrained(weight_location, device_map="cuda:0", torch_dtype=torch.float16)

#lora_config =  LoraConfig.from_pretrained(Lora_Location)

model = PeftModel.from_pretrained(model, Lora_Location, device_map="cuda:0", torch_dtype = torch.float16)

prompt = "start"


while(prompt != "exit"):
        prompt = input("type and press enter: ")
        start = time.time()
        if( prompt == "exit"):
                exit()
        ## Future: do the thing that GPT3.5 does where it re-inputs the last Prompt and response
        inputs = None
        print("_________________INPUTS_______________")
        inputs = tokenizer(prompt, return_tensors = "pt")
        print(inputs.input_ids)
        print("______________________________________")
        generate_ids = model.generate(inputs.input_ids)
        print(generate_ids)
        returned = tokenizer.batch_decode(generate_ids, skip_special_tokens = False,clean_up_tokenization_spaces=False)[0]
        print(returned)
        print("TIME TAKEN: " + str(time.time() - start))
        print("\n\n")t 
```

when this gets to the model.generate(input.input_ids), it returns 'PeftModelForCausalLM.generate() takes in 1 positional argument, 2 were given.

I am not sure if this is something I am doing wrong or something with the code, any help would be greatly appreciated!

The LlamaModel.generate() works with the same inputs correctly. 

Thank ya thank ya!

### Who can help?

@pacman100 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

generate a Lora finetuning folder using PEFT and have a llama 7b weight folder.
run the following code:

```python
import torch
from transformers import LlamaForCausalLM, GenerationConfig, LlamaTokenizer
from peft import LoraConfig, get_peft_model, TaskType, PeftModel
import time

weight_location = "llamaFinalWeights"
Lora_Location = "Lora_Weights"
tokenizer = LlamaTokenizer.from_pretrained(weight_location, local_files_only=True, add_eos_toke=False, device_map="cpu")
model = LlamaForCausalLM.from_pretrained(weight_location, device_map="cuda:0", torch_dtype=torch.float16)

#lora_config =  LoraConfig.from_pretrained(Lora_Location)

model = PeftModel.from_pretrained(model, Lora_Location, device_map="cuda:0", torch_dtype = torch.float16)

prompt = "start"


while(prompt != "exit"):
        prompt = input("type and press enter: ")
        start = time.time()
        if( prompt == "exit"):
                exit()
        ## Future: do the thing that GPT3.5 does where it re-inputs the last Prompt and response
        inputs = None
        print("_________________INPUTS_______________")
        inputs = tokenizer(prompt, return_tensors = "pt")
        print(inputs.input_ids)
        print("______________________________________")
        generate_ids = model.generate(inputs.input_ids)
        print(generate_ids)
        returned = tokenizer.batch_decode(generate_ids, skip_special_tokens = False,clean_up_tokenization_spaces=False)[0]
        print(returned)
        print("TIME TAKEN: " + str(time.time() - start))
        print("\n\n")t 
```

### Expected behavior

Language generate until 'exit' is typed. what is happening is the error mentioned above.

**Comment by Bryan-Lavender** [comment]
I found a quick fix by using model = model.merge_and_unload() to combine weights before making inferences

**Comment by drdaxxy** [comment]
In your case the workaround would be naming the argument, `model.generate(input_ids=inputs.input_ids)`.

The problem is that [PeftModelForCausalLM.generate currently does not pass along positional arguments](https://github.com/huggingface/peft/blob/e06d94ddeb6c70913593740618df76908b918d66/src/peft/peft_model.py#L995) to the base model (nor does [PeftModelForSeq2SeqLM.generate](https://github.com/huggingface/peft/blob/e06d94ddeb6c70913593740618df76908b918d66/src/peft/peft_model.py#L1209), for that matter).

This looks deliberate as [there's a test case validating it](https://github.com/huggingface/peft/blob/e06d94ddeb6c70913593740618df76908b918d66/tests/testing_common.py#L409), presumably because the seq2seq variant makes use of the arguments by plucking them from the `**kwargs`, which would not work if they're passed as positional arguments.

IMO a better way to handle this would be to move any positional args that appear in `inspect.signature(self.base_model.generate).parameters` into the kwargs, unless I'm overlooking something? `input_ids` is often passed as a positional argument in the Transformers documentation, so the current API contradicts expectations.

**Comment by kopyl** [comment]
> In your case the workaround would be naming the argument, `model.generate(input_ids=inputs.input_ids)`.
> 
> The problem is that [PeftModelForCausalLM.generate currently does not pass along positional arguments](https://github.com/huggingface/peft/blob/e06d94ddeb6c70913593740618df76908b918d66/src/peft/peft_model.py#L995) to the base model (nor does [PeftModelForSeq2SeqLM.generate](https://github.com/huggingface/peft/blob/e06d94ddeb6c70913593740618df76908b918d66/src/peft/peft_model.py#L1209), for that matter).
> 
> This looks deliberate as [there's a test case validating it](https://github.com/huggingface/peft/blob/e06d94ddeb6c70913593740618df76908b918d66/tests/testing_common.py#L409), presumably because the seq2seq variant makes use of the arguments by plucking them from the `**kwargs`, which would not work if they're passed as positional arguments.
> 
> IMO a better way to handle this would be to move any positional args that appear in `inspect.signature(self.base_model.generate).parameters` into the kwargs, unless I'm overlooking something? `input_ids` is often passed as a positional argument in the Transformers documentation, so the current API contradicts expectations.

thank you very much. that helped

**Comment by bxrjmfh** [comment]
By the way, when you attempt to use the peft model with specific configurations (e.g., setting max_new_tokens), you should specify the parameter names. Changing the code from generate_ids = llm.generate(inputs.input_ids, max_new_tokens=max_new_tokens) to generate_ids = llm.generate(input_ids=inputs.input_ids, max_new_tokens=max_new_tokens) can solve the problem.

**Comment by kangzhiheng** [comment]
> By the way, when you attempt to use the peft model with specific configurations (e.g., setting max_new_tokens), you should specify the parameter names. Changing the code from `generate_ids = llm.generate(inputs.input_ids, max_new_tokens=max_new_tokens)` to `generate_ids = llm.generate(input_ids=inputs.input_ids, max_new_tokens=max_new_tokens)` can solve the problem.

That helped!

**Comment by Lins-01** [comment]
> By the way, when you attempt to use the peft model with specific configurations (e.g., setting max_new_tokens), you should specify the parameter names. Changing the code from `generate_ids = llm.generate(inputs.input_ids, max_new_tokens=max_new_tokens)` to `generate_ids = llm.generate(input_ids=inputs.input_ids, max_new_tokens=max_new_tokens)` can solve the problem.

solved by this !!  thks  !!!
