### ISSUE TITLE
How to change the location of soft tokens in prompt tuning

### ISSUE THREAD

**Issue by XueTianci** [huggingface/peft#711]
### Feature request

In fact, when prompt tuning, we will not always add it to the front, it may be in the middle. So I think it's important for us to change the location of soft tokens.

### Motivation

In fact, when prompt tuning, we will not always add it to the front, it may be in the middle. So I think it's important for us to change the location of soft tokens.

### Your contribution

no

**Comment by LokeshJatangi** [comment]
@XueTianci I was interested in knowing if concatenating prompt tokens at suffix position or middle position, does it provide any improvement over prepending it.

**Comment by XueTianci** [comment]
I think the performance is based on tasks. When it's a conditional generation task, the position may influence the performance. A long ago, I remember I read some papers about this. But I forget their name. Recently, I want to proof it with my experiments. But PEFT doesn't support it!!!!!!

**Comment by logisticloon** [comment]
Can someone please tell if there is any update on this? I still don't see any support. Is this something being worked on?
