### ISSUE TITLE
Bug when pass subfolder parameter in peftmodel.load_adapter method!

### ISSUE THREAD

**Issue by RuSignalFlag** [huggingface/peft#718]
### System Info

peft 0.4.0.dev0

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

Given a checkpoint folder as shown below.
```
drwxr-xr-x 2 root root     4096 Jul 16 09:54 LoraAdapter
-rw-r--r-- 1 root root 23443269 Jul 16 09:54 optimizer.pt
-rw-r--r-- 1 root root       27 Jul 16 09:54 README.md
-rw-r--r-- 1 root root    14575 Jul 16 09:54 rng_state.pth
-rw-r--r-- 1 root root      627 Jul 16 09:54 scheduler.pt
-rw-r--r-- 1 root root     7592 Jul 16 09:54 trainer_state.json
-rw-r--r-- 1 root root     3963 Jul 16 09:54 training_args.bin
```
LoraAdapter is the name I specified for the Lora adapter, which is a folder here containing the weight files and configuration files of the adapter.
```
-rw-r--r-- 1 root root      411 Jul 16 09:54 adapter_config.json
-rw-r--r-- 1 root root 11719577 Jul 16 09:54 adapter_model.bin
```
I want to continue training from this checkpoint, so I need to instantiate a PeftModel and load the weights of the Lora adapter into it. However, my adapter weight file is in a subfolder of the checkpoint, so I use the following method.
```
from transformers import AutoModel
from peft import PeftModelForCausalLM, LoraConfig

lora_config = LoraConfig.from_pretrained('ChatGlm2-6B_LoRA/QLora_Adapter_THUDM_chatglm2-6b/checkpoint-2000', subfolder='LoraAdapter')
base_model = AutoModel.from_pretrained('THUDM/chatglm2-6b', trust_remote_code=True, device_map='auto').half()
peftmodel = PeftModelForCausalLM(base_model, lora_config, adapter_name='LoraAdapter')

peftmodel.load_adapter(model_id='ChatGlm2-6B_LoRA/QLora_Adapter_THUDM_chatglm2-6b/checkpoint-2000', adapter_name='LoraAdapter', subfolder='LoraAdapter')
```

But it cannot correctly find my Lora adapter weight file.

I think the problem is here.
https://github.com/huggingface/peft/blob/029f416fced285fe72acd4e1be6c48067f7013d5/src/peft/peft_model.py#L484-L502

This method will put the 'subfolder' keyword argument into 'hf_hub_download_kwargs'.

So here
https://github.com/huggingface/peft/blob/029f416fced285fe72acd4e1be6c48067f7013d5/src/peft/peft_model.py#L519-L522

The 'subfolder' parameter is not present in kwargs anymore.

### Expected behavior

please fix

**Comment by younesbelkada** [comment]
Hi @RuSignalFlag 
https://github.com/huggingface/peft/pull/721 should fix the issue, thanks a lot for noticing!
