### ISSUE TITLE
Use LoRA and prompt tuning at the same time?

### ISSUE THREAD

**Issue by chengyin38** [huggingface/peft#720]
The LoRA paper states that it's a flexible PEFT method that can be combined with any other methods. But in this `peft` library, it seems that we cannot use both at the same time because it only takes in one type of `peft_config`: either `PromptTuningConfig()` or `LoraConfig()` -- is that correct? 

```
peft_model = get_peft_model(base_model, peft_config)
```

**Comment by BenjaminBossan** [comment]
I've never tried it, but perhaps you can nest peft models?

```python
peft_lora = get_peft_model(base_model, peft_config_lora)
peft_prompt_tuning = get_peft_model(peft_lora, peft_config_prompt_tuning)
```

**Comment by Betty1202** [comment]
@chengyin38 May I ask how you eventually resolved this issue?
