### ISSUE TITLE
Add dense layers to TRANSFORMERS_MODELS_TO_LORA_TARGET_MODULES_MAPPING 

### ISSUE THREAD

**Issue by BramVanroy** [huggingface/peft#735]
### Feature request

The `TRANSFORMERS_MODELS_TO_LORA_TARGET_MODULES_MAPPING ` mapping is useful to get a mapping of model_type to target_modules for the peft config but these are restricted to attention-related attributes. It would be great if all linear layers are also included.

### Motivation

For max. performance, the QLoRA paper suggests that LoRA should be applied to _all_ linear layers:

> As shown in Figure 2 for LLaMA 7B finetuning on Alpaca, we find that the most critical LoRA hyper-parameter is how many LoRA adapters are used in total **and that LoRA on all linear transformer block layers are required to match full finetuning performance**.

### Your contribution

Not sure as I do not have the time to manually look for all linear layers within the different architectures.

**Comment by BenjaminBossan** [comment]
Thanks for the suggestion. I think it would be nice to have a mechanism in the future that goes beyond matching the name of the module and could, as you suggest, match by type. This is not so easy to change at the moment.

For the time being, you could print out all modules and filter by type to get their names, and pass those to `target_module`:

```python
model = ...
target_modules = [name for name, layer in model.named_modules() if isinstance(layer, nn.Linear)]
print(target_modules)
```
