### ISSUE TITLE
Method to unload an adapter, to allow the memory to be freed

### ISSUE THREAD

**Issue by uyhcire** [huggingface/peft#738]
### Feature request

Add a `PeftModel.delete_adapter(adapter_id)` method. The method should delete the specified adapter and release all references to the adapter's weights, so that the adapter's weights can be garbage collected.

### Motivation

I am taking advantage of the small size of a PEFT adapter to quickly evaluate many adapter in succession. This can be done quickly even on a single GPU, because loading an adapter is very fast, much faster the loading the full weights of the base model.

I am essentially doing something like this:

```
for adapter_in in adapter_ids:
    peft_model.load_adapter(...)
    evaluate(peft_model)
```

The problem with this naïve implementation is that while adapters are fast to load, they are never garbage collected. A naïve implementation of this loop will quickly exhaust your GPU memory.

### Your contribution

I already have code to do this, complete with unit tests. I am happy to post it here, or submit a PR, if you think this feature is worth having.

**Comment by BenjaminBossan** [comment]
Thanks for investigating. Could you post the main changes, or explain where the memory leak happens and how you solved it? That way, we can check if that would work as a PR.

**Comment by pacman100** [comment]
Hello, `delete_adapter(adapter_id)` is already introduced in PR https://github.com/huggingface/peft/pull/695 and find the related docs here: https://huggingface.co/docs/peft/conceptual_guides/lora#utils-for-lora
