### ISSUE TITLE
Feature for using onnx model as base model when using lora weight

### ISSUE THREAD

**Issue by bohyunshin** [huggingface/peft#748]
### Feature request

Hello, I was wondering if I can make a peft model based on onnx model.
One way to make peft model is to use `from_pretrained` method in [this code](https://github.com/huggingface/peft/blob/main/src/peft/peft_model.py#L211). 
```python
@classmethod
def from_pretrained(
    cls,
    model: PreTrainedModel,
    model_id: Union[str, os.PathLike],
    adapter_name: str = "default",
    is_trainable: bool = False,
    config: Optional[PeftConfig] = None,
    **kwargs: Any,
):
    r"""
    Instantiate a [`LoraModel`] from a pretrained Lora configuration and weights.

    Args:
        model ([`~transformers.PreTrainedModel`]):
            The model to be adapted. The model should be initialized with the
            [`~transformers.PreTrainedModel.from_pretrained`] method from the 🤗 Transformers library.
        model_id (`str` or `os.PathLike`):
            The name of the Lora configuration to use. Can be either:
                - A string, the `model id` of a Lora configuration hosted inside a model repo on the Hugging Face
                  Hub.
                - A path to a directory containing a Lora configuration file saved using the `save_pretrained`
                  method (`./my_lora_config_directory/`).
        adapter_name (`str`, *optional*, defaults to `"default"`):
            The name of the adapter to be loaded. This is useful for loading multiple adapters.
        is_trainable (`bool`, *optional*, defaults to `False`):
            Whether the adapter should be trainable or not. If `False`, the adapter will be frozen and use for
            inference
        config ([`~peft.PeftConfig`], *optional*):
            The configuration object to use instead of an automatically loaded configuation. This configuration
            object is mutually exclusive with `model_id` and `kwargs`. This is useful when configuration is already
            loaded before calling `from_pretrained`.
        kwargs: (`optional`):
            Additional keyword arguments passed along to the specific Lora configuration class.
    """
```

However, the [model argument](https://github.com/huggingface/peft/blob/main/src/peft/peft_model.py#L213) states that it should be `transformers.PreTrainedModel` not onnx.

```python
"""
Args:
    model ([`~transformers.PreTrainedModel`]):
        The model to be adapted. The model should be initialized with the
        [`~transformers.PreTrainedModel.from_pretrained`] method from the 🤗 Transformers library.
"""
```

So, I was curious if there is another method that integrates lora weights to base onnx model.
Thank you!

### Motivation

I am researching how to serve lots of fine-tuned llms efficiently. To do this, onnx converting seems to be necessary because this offers variety of optimization. Because my main focus model is lora fine-tuned model, I was finding how to integrate onnx base model to lora weights

### Your contribution

If necessary, some development related to using onnx model as base model will be done by me

**Comment by BenjaminBossan** [comment]
I'm not an expert on ONNX, but it sounds to me that your suggestion would not be easy to achieve. Just as an alternative, could you load the original model in PyTorch, apply and merge LoRA, then export to ONNX? This takes a few extra steps but might achieve the same final goal.

**Comment by bohyunshin** [comment]
@BenjaminBossan 
I considered the method that you suggested, but in my case multiple fine tuned models should be served. So, I considered saving only one backbone model and apply multiple LoRA weights loading that backbone model to prevent oom or other disk&memory related issue. For this reason, I was considering to export original backbone model to ONNX and save that model, loading it whenever I need to merge LoRA weights.
If my goal is to serve only one fine tune model, your suggestion could be an alternative but my final serving goal is slightly different, so I thought that different approach should be applied

**Comment by BenjaminBossan** [comment]
Yes, for the use case you mentioned, my suggestion would not work. AFAIK, what you suggest wouldn't be possible, but again, I'm not very experienced with ONNX, so someone else might have some ideas.

**Comment by vidhyat98** [comment]
Was a solution identified for this use case? I too am looking to serve multiple lora fine tuned adapters but with onnx support.
