### ISSUE TITLE
specify rank per layer or per tensor type

### ISSUE THREAD

**Issue by MichelNivard** [huggingface/peft#752]
### Feature request

Is it possible to specify the rank (lora_r) per layer, or per tensor type (e.g. give "p_proj" a different r from "v_proj", or steadily increase or decrease r per layer).

### Motivation

My goal would be to study the current rank of various fully trained transformers per layer and tensor type to arrive at reasonable generalisable rules for the approximate rank of these matrices (e.g study distribution of singular values). Id use these observed complexities to assemble an optimally efficient lora, which ideally would allow for base-model training using only (q)lora.

### Your contribution

I am open to suggested ways in which I could help.

**Comment by BenjaminBossan** [comment]
Right now, it is impossible to have different parameters like `r` per layer. We have ideas about exposing a "low level" API that would allow users more fine-grained control, including what you suggest. I cannot say yet if it will really work out and when it's ready, but I'll let you know.

**Comment by Baijiong-Lin** [comment]
thanks @BenjaminBossan
