### ISSUE TITLE
Merging LORA weights and saving safetensors to launch a TGI server

### ISSUE THREAD

**Issue by Mohamedhabi** [huggingface/peft#754]
### System Info

requirements.txt
```
transformers==4.31.0
peft==0.4.0
accelerate==0.21.0
bitsandbytes==0.40.2
safetensors>=0.3.1
```
python3.10

### Who can help?

@pacman100 @younesbelkada @sayakpaul 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

## Problem
I finetuned llama2-7b using LORA.

I want to launch my LORA model on TGI.

Here is an example about how I am saving the weights as safetensors (the format requested by TGI):
```python
peft_config = PeftConfig.from_pretrained(model_dir)

model = AutoModelForCausalLM.from_pretrained(
    peft_config.base_model_name_or_path,
    device_map="cpu",
    trust_remote_code=True,
    use_safetensors=True,
)

model = PeftModel.from_pretrained(model, model_dir)

model = model.merge_and_unload()
model.save_pretrained(save_dir, safe_serialization=True)
```

Then I launch TGI on a docker image
```
docker run gpus 1 shm-size 1g -p 8080:80  -v "{save_dir}":/data  ghcr.io/huggingface/text-generation-inference:latest \
--model-id /data/. \
--max-input-length 500 \
--max-batch-total-tokens 1000 \
--max-total-tokens 1000 \
--max-batch-prefill-tokens 1000 \
--num-shard 1 \
```

But I get: ```RuntimeError: Not enough memory to handle 1000 prefill tokens. You need to decrease `--max-batch-prefill-tokens` ```

I tried to reduce the `--max-batch-prefill-tokens` to 800, it works. But in my usecase I need more tokens than that.

## Side note
When I run the base llama2-7b model, like this:
```python
peft_config = PeftConfig.from_pretrained(model_dir)

model = AutoModelForCausalLM.from_pretrained(
    peft_config.base_model_name_or_path,
    device_map="cpu",
    trust_remote_code=True,
    use_safetensors=True,
)

model.save_pretrained(save_dir, safe_serialization=True)
```
Everything works perfectly. But when merging LORA wights I cant have more than 800 tokens.

### Expected behavior

When merging LORA weights with the base model, we have the same number of parameters.

So, why by merging them, I can not launch a server with the same number of max-tokens as the base model.

What can I do to execute my fine-tuned model with a bigger number of max-tokens on TGI ?

**Comment by BenjaminBossan** [comment]
Hmm, this indeed unexpected. It should not happen that after merging, the model suddenly has more parameters. Could you check if that is really the case by counting the number of parameters using both methods you showed above?

Here is a function that should do the count:

```python
def get_nb_parameters(model):
    all_param = 0
    for param in model.parameters():
        num_params = param.numel()
        if num_params == 0 and hasattr(param, "ds_numel"):
            num_params = param.ds_numel

        if param.__class__.__name__ == "Params4bit":
            num_params = num_params * 2

        all_param += num_params
    return all_param
```
