### ISSUE TITLE
Mixed-task batching

### ISSUE THREAD

**Issue by einarbmag** [huggingface/peft#759]
### Feature request

Ability to load a PEFT model with multiple adapters, and perform mixed-task batch inference. This should be feasible with IA^3 and prompt/prefix tuning, not sure about LoRA.

### Motivation

In the IA^3 paper ([Few-Shot Parameter-Efficient Fine-Tuning is Better and Cheaper than In-Context Learning](https://arxiv.org/abs/2205.05638)),  it is mentioned that one of the requirements for a PEFT method to be compared with few-shot ICL, it should allow for mixed-task batches. 

This would allow for building a very resource-efficient LLM application where we serve a single PEFT model with a large number of adapters to cover different tasks that we want the application to perform, and can handle concurrent requests from multiple users, all performing different tasks. 

### Your contribution

I could possibly get people in my team to look at this if we can get some advice on how to structure the change.

**Comment by einarbmag** [comment]
Thanks, I suspected that it would be a big reactor... I will probably do as you say initially. Might run the base model as one instance and then peft model with changeable adapters as a second instance for specific tasks.

I will ask the IA^3 authors as well, but do you know of any other implementation that supports mixed-task batches?

**Comment by BenjaminBossan** [comment]
> I will ask the IA^3 authors as well, but do you know of any other implementation that supports mixed-task batches?

No, I'm not aware, but please let us know if you find (or build) something.

**Comment by ruirui-zhang** [comment]
Training or serving multiple LoRA modules in a single batch with the following community implementations:
[[https://github.com/S-LoRA/S-LoRA]
](https://github.com/S-LoRA/S-LoRA)[[https://github.com/sabetAI/BLoRA]
](https://github.com/sabetAI/BLoRA)[[https://github.com/TUDB-Labs/multi-lo...](https://github.com/TUDB-Labs/multi-lora-fine-tune)
