### ISSUE TITLE
Size Mismatch Error When Loading Pretrained Model with Expanded Embedding Layer

### ISSUE THREAD

**Issue by hzphzp** [huggingface/peft#762]
### System Info

peft, transformers

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [x] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

I am currently facing an issue when trying to load a pretrained model with an expanded embedding layer. I first expanded the embedding layer, wrapped the model using LoRA, and pass `modules_to_save=["embed_tokens", "lm_head"]` to make the embedding layer trainable. After training, I saved the model using `save_pretrained(path1)`. However, when I try to load the model using AutoModelForCausalLM.from_pretrained(path1), I encounter the following error:
```python
Error(s) in loading state_dict for ModelForCausalLM:  
    size mismatch for base_model.model.model.embed_tokens.modules_to_save.default.weight: copying a param with shape torch.Size([33049, 16]) from checkpoint, the shape in current model is torch.Size([32000, 16])  
 ```

### Expected behavior

I have a rough idea of where the problem lies, but I'm wondering if it would be better to not perform size match checking when loading pretrained models. This could potentially avoid many unnecessary issues.

**Comment by hzphzp** [comment]
waiting for kindly response ...

**Comment by BenjaminBossan** [comment]
We would need a more complete code sample to judge what's going on. One idea: Did you expand the embedding layer of the base model (the same way as the first time) before loading the adapter?

**Comment by adibMosharrof** [comment]
any updates on this? I am having similar issues

**Comment by adibMosharrof** [comment]
I was able to solve it after going through #838
