### ISSUE TITLE
LoRA `Linear4bit` is unmergeable

### ISSUE THREAD

**Issue by SergeyTsimfer** [huggingface/peft#766]
### Feature request

Hi team

Current implementations of `Linear4bit` / `Linear8bitLt` are lacking methods for working with them as adapters: `merge`, `unmerge`, `get_delta_weight`. While it is easy enough to copy-and-paste code for them from `Lora.Linear`, I'm afraid of the unwanted errors of mixing precisions. A ready-to-use implementation would be much appreciated:)

### Motivation

Adapters should have the same API, irregardless of precision and dtypes used

### Your contribution

If there is a confirmation, that the feature can be correctly implemented by re-using the code from existing implementation of `Lora.Linear`, I can contribute that.

**Comment by ddofer** [comment]
I have the same issue - can't use these layers when running lora/qlora.

errorsl ike 
`RuntimeError: only Tensors of floating point dtype can require gradients`

**Comment by BenjaminBossan** [comment]
@ddofer I think your issue may be related to something else. Could you please open a new issue and provide a code sample to reproduce the error?

**Comment by ddofer** [comment]
Problem is prepping sample data (proteins, not a default dataset). 
I'll try to find time to make one; lack of ability to work with QLORA is a shame

**Comment by BenjaminBossan** [comment]
> I'll try to find time to make one; lack of ability to work with QLORA is a shame

As soon as you have something to share, please open a new issue and post it there. Note that the original problem of this issue, not having `merge`/`unmerge`/`get_delta_weight` on `Linear4bit`, has since been resolved.
