### ISSUE TITLE
About layer of Lora

### ISSUE THREAD

**Issue by yumingfan-0219** [huggingface/peft#788]
Hello, I encountered the following issue while fine-tuning my model using Lora:
I trained the A layer of my model using the Lora model (this name is just an example). However, when I merged the Lora model back into the source model, I mistakenly specified another B layer. Surprisingly, the model still merged successfully. Do you have any insights into a possible explanation for this situation?

Thank you for your contributions to the community!

**Comment by BenjaminBossan** [comment]
Could you please provide some code: How you configured your model and how you merged the layers? Otherwise, it's hard to help.
