### ISSUE TITLE
Compute capability < 7.5 detected!

### ISSUE THREAD

**Issue by shon-otmazgin** [huggingface/peft#79]
I trying to run:
```python
from transformers import AutoModelForSeq2SeqLM
from peft import get_peft_model, LoraConfig
model_name_or_path = "facebook/opt-13b"

peft_config = LoraConfig(
    task_type="CAUSAL_LM", inference_mode=False, r=64, lora_alpha=32, lora_dropout=0.1
)

model = AutoModelForSeq2SeqLM.from_pretrained(model_name_or_path)
print(model.print_trainable_parameters())
model = get_peft_model(model, peft_config)
print(model.print_trainable_parameters())
```

but then I getting:
`Compute capability < 7.5 detected! Only slow 8-bit matmul is supported for your GPU!"
`
`NameError: name 'cuda_setup' is not defined
`

I understood that this error comes from `bitsandbytes` so I found this issue:
https://github.com/TimDettmers/bitsandbytes/issues/124

My hardware is `tesla v100-sxm2-32gb` (Volta)

It is possible to run PEFT on my hardware? I don't really need int8, fp16 also should be good.

this is related also to my attempts to FT a large LM on my hardware:
https://discuss.huggingface.co/t/finetune-llm-with-deepspeed/31589

Thanks,
Shon

**Comment by younesbelkada** [comment]
Hi @shon-otmazgin 
I think if you don't need `bnb` you can just uninstall `bitsandbytes` and the error should disappear

**Comment by alfredcs** [comment]
Try install bitsandbytes-cuda112 and see if that helps.

**Comment by djaym7** [comment]
pip install bitsandbytes==0.35.0 should solve your problem

**Comment by djaym7** [comment]
bitsandbytes 0.35.0 solves this but start another issue : 
Traceback (most recent call last):
  File "train_full_csv_int8Training.py", line 463, in <module>
    train(locals(),train_inputs,subtopics_train_targets,val_inputs,subtopics_val_targets)
  File "train_full_csv_int8Training.py", line 400, in train
    trainer = Trainer(
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 382, in __init__
    raise ValueError(
ValueError: The model you want to train is loaded in 8-bit precision.  if you want to fine-tune an 8-bit model, please make sure that you have installed `bitsandbytes>=0.37.0`

**Comment by djaym7** [comment]
https://github.com/TimDettmers/bitsandbytes/issues/179

**Comment by younesbelkada** [comment]
@djaym7 can you try with `bitsandbytes==0.37.0` ?

**Comment by djaym7** [comment]
No can't https://github.com/TimDettmers/bitsandbytes/issues/179
