### ISSUE TITLE
multiple adapter load_model fails when adding bias

### ISSUE THREAD

**Issue by DavidPeleg6** [huggingface/peft#792]
### System Info

peft==0.4.0
transformers==4.31.0
accelerate==0.21.0
torch==2.0.1

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

```
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

model_id = "NousResearch/Nous-Hermes-Llama2-13b"

model = AutoModelForCausalLM.from_pretrained(
    model_id,
    torch_dtype=torch.bfloat16,
    device_map='auto',
)

from peft import PeftModel

# Loading the PEFT model with first adapter
output_dir1 = "nous-hermes2-13b-bf16-lora-r256-with-bias-task1"

model = PeftModel.from_pretrained(model, output_dir1, adapter_name="adapter1",
                                 device_mapping='auto'
                                 )
tokenizer1 = AutoTokenizer.from_pretrained(output_dir1)
print(model.active_adapter)

output_dir2 = "nous-hermes2-13b-bf16-lora-r256-with-bias-task2"
model.load_adapter(output_dir2, adapter_name="adapter2",
                   device_mapping='auto'
                  )
tokenizer2 = AutoTokenizer.from_pretrained(output_dir2)
```

### Expected behavior

both adapters should load. instead im getting the following error:
`ValueError: LoraModel supports only 1 adapter with bias. When using multiple adapters, set bias to 'none' for all adapters.
`

Note that if i catch the exception and try again (meaning the new adapter is already in the peft config) it works fine.

Thanks in advance :)

**Comment by BenjaminBossan** [comment]
As the error message suggests, having multiple LoRA adapters with biases is not supported.

> Note that if i catch the exception and try again (meaning the new adapter is already in the peft config) it works fine.

It will not work completely as expected and depending on what you do later, there could be errors or incorrect outputs, so it's not recommended to continue with the model after the error message comes up.

**Comment by DavidPeleg6** [comment]
thanks!
Is there a plan to support it or a ticket i could follow?
since biased lora adapters yield a notable improvement in performance for my use cases.

**Comment by BenjaminBossan** [comment]
I'm not aware of any plans. In theory, I believe it should be possible to have multiple adapters that each have their own bias. But implementing it in PEFT would require some non-trivial refactoring, not sure if it's planned @pacman100.
