### ISSUE TITLE
Loading the base model and the PEFT model at the same time

### ISSUE THREAD

**Issue by CandyPanda-LS** [huggingface/peft#795]
### System Info
meta/Llama 2. 
Linux OS
RTX A6000

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

I want to load both the PEFT model at the same time as follows and inference using both.
`model1 =LlamaForCausalLM.from_pretrained(model_id, load_in_8bit=True, device_map='auto', torch_dtype=torch.float16)`
`model2 = PeftModel.from_pretrained(model, peft_model)`

But when I do the following, although I call the generate method of the base model as follows,
```python
with torch.no_grad():
    print(tokenizer.decode(model1.generate(**model_input, max_new_tokens=100)[0], skip_special_tokens=True))
```
the finetuned model is generating the answers. Is there something I can do for this. when I just load model 1 only , the code works fine but when I load both models, although Im trying to generate answers from the base model, the answers are being generated from the fine tuned model.

```python
import torch
from transformers import LlamaForCausalLM, LlamaTokenizer
from peft import PeftModel


model_id="./model/Llama-2-7b-chat-hf/"
peft_model = "./model/model-weight/"


tokenizer = LlamaTokenizer.from_pretrained(model_id)
# Function to load the PeftModel for performance optimization
def load_peft_model(model, peft_model):
    peft_model = PeftModel.from_pretrained(model, peft_model)
    return peft_model
user_prompt = """Identify the intent of the user query and only generate the intent label for the last user message. The chat between the user and the AI assistant is provided as context underneath.\n\nchat:\nassistant: Select the date\nuser: 2023-06-26\n\n---\nIntent label:"""
model_input = tokenizer(user_prompt, return_tensors="pt").to("cuda")

model1 =LlamaForCausalLM.from_pretrained(model_id, load_in_8bit=True, device_map='auto', torch_dtype=torch.float16)
model2 = PeftModel.from_pretrained(model, peft_model)

with torch.no_grad():
    print(tokenizer.decode(model1.generate(**model_input, max_new_tokens=100)[0], skip_special_tokens=True))

model2 = load_peft_model(model1, peft_model)
with torch.no_grad():
    print(tokenizer.decode(model2.generate(**model_input, max_new_tokens=100)[0], skip_special_tokens=True))

with torch.no_grad():
    print(tokenizer.decode(model1.generate(**model_input, max_new_tokens=100)[0], skip_special_tokens=True))
```
### Expected behavior

For the answers to be generated from the base model, when the model1.generate method is called and for answers to be generated from the PEFT model when model2 .generate method is called

**Comment by BenjaminBossan** [comment]
Loading the PEFT model may modify the base model in-place, which is why you see the described behavior. What type of fine-tuning did you use?
