### ISSUE TITLE
Add support for Pix2Struct

### ISSUE THREAD

**Issue by NielsRogge** [huggingface/peft#796]
### Feature request

I wanted to apply PEFT to [Pix2Struct](https://huggingface.co/docs/transformers/main/model_doc/pix2struct), however since the model expects `flattened_patches` rather than `input_ids`, I'm getting the following error:

```
[/usr/local/lib/python3.10/dist-packages/peft/peft_model.py](https://localhost:8080/#) in forward(self, input_ids, attention_mask, inputs_embeds, decoder_input_ids, decoder_attention_mask, decoder_inputs_embeds, labels, output_attentions, output_hidden_states, return_dict, **kwargs)
   1078         peft_config = self.active_peft_config
   1079         if not isinstance(peft_config, PromptLearningConfig):
-> 1080             return self.base_model(
   1081                 input_ids=input_ids,
   1082                 attention_mask=attention_mask,

[/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in _call_impl(self, *args, **kwargs)
   1499                 or _global_backward_pre_hooks or _global_backward_hooks
   1500                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1501             return forward_call(*args, **kwargs)
   1502         # Do not call functions when jit is used
   1503         full_backward_hooks, non_full_backward_hooks = [], []

TypeError: Pix2StructForConditionalGeneration.forward() got an unexpected keyword argument 'input_ids'
```
The `flattened_patches` is a pretty unique input name, not sure any other model will ever get that name as input. cc @younesbelkada 

A notebook to reproduce is [here](https://colab.research.google.com/drive/1YlLQqnkanQTlhPIlG34aeQcGLRJxVaGV?usp=sharing).

### Motivation

Pix2Struct is a pretty heavy model, hence leveraging LoRa/QLoRa instead of full fine-tuning would greatly benefit the community.

### Your contribution

Not sure I can help here

**Comment by BenjaminBossan** [comment]
Not sure if this solution would work for you in the grand scheme of things, but at least I got the notebook to train:

```python
from torch import nn

class Pix2StructWrapper(Pix2StructForConditionalGeneration):
    def forward(
        self,
        input_ids,
        attention_mask,
        inputs_embeds,
        decoder_input_ids,
        decoder_attention_mask,
        decoder_inputs_embeds,
        labels,
        output_attentions,
        output_hidden_states,
        return_dict,
        flattened_patches,
        **kwargs
    ):
        # fiddle with arguments
        return super().forward(
            flattened_patches,
            attention_mask=attention_mask,
            decoder_input_ids=decoder_input_ids,
            decoder_inputs_embeds=decoder_inputs_embeds,
            labels=labels,
            output_attentions=output_attentions,
            output_hidden_states=output_hidden_states,
            return_dict=return_dict,
        )

- model = Pix2StructForConditionalGeneration.from_pretrained("google/pix2struct-base")
+ model = Pix2StructWrapper.from_pretrained("google/pix2struct-base")
```

I also had to `model = model.to(device)` before the fit loop.

**Comment by younesbelkada** [comment]
Hi @NielsRogge !
I think with #749 + https://github.com/huggingface/transformers/pull/25077 we should be able to solve the issue. Can you try to install peft from source and transformers from that branch and follow the API that is presented here: https://github.com/huggingface/transformers/pull/25077#issue-1820099126 ? I can also try it on my end and let you know

**Comment by younesbelkada** [comment]
Hi @NielsRogge 
I managed to create a demo that seems to work fine on a Gcolab using the new API for PEFT + transformers: https://colab.research.google.com/drive/1P5CTU7SFuBXwa9o3QOKqvoVzbLEk8AWi?usp=sharing please have a look at that colab and feel free to copy it. I also added instructions on how to save adapters on the Hub and load it back on the model.
Also would like to have your final colab demo if you can share it here it would be great! 
I am closing this issue as I consider the problem as solved ! Feel free to re-open it if you think it is not the case
