### ISSUE TITLE
BERT and LoRA BERT Number of Parameters Mismatch

### ISSUE THREAD

**Issue by uygarkurt** [huggingface/peft#801]
Hi, I load a bert model like this:

`model = BertForQuestionAnswering.from_pretrained(MODEL_PATH).to(device)`

At this point I print the number of parameters of the model with
`print(model.num_parameters())`
which gives me the number: `108893186`

After this I apply LoRA to my model
```
config = LoraConfig(
            task_type = "QUESTION_ANS",
            inference_mode = False,
            r = 16, 
            lora_alpha = 32, 
            lora_dropout = 0.05,
            fan_in_fan_out = False,
            bias = "none",
        )   
model = get_peft_model(model, config
```
I do `model.print_trainable_parameters())`. Gives me `trainable params: 589824 || all params: 109483010 || trainable%: 0.5387356449187869`.

The number of parameters for BERT without LoRA is `108893186`. After I apply LoRA number of parameters is `109483010`. Is this mismatch expected?

**Comment by BenjaminBossan** [comment]
LoRA adds a couple of parameters on top of the existing ones. Therefore, such a change is expected. After you finish the training, you should be able to `.merge_and_unload()` the model to get back a model with the initial number of parameters.
