### ISSUE TITLE
HFValidationError on local PeftModel.from_pretrained 

### ISSUE THREAD

**Issue by LazerJesus** [huggingface/peft#806]
### System Info

Name: transformers
Version: 4.28.1

Name: peft
Version: 0.4.0

Python 3.9.16

### Reproduction

I get a `HFValidationError` when attempting to load a locally stored `PeftModel`

```python
from transformers import AutoModelForCausalLM, BitsAndBytesConfig
import torch

model = AutoModelForCausalLM.from_pretrained(
    BASEPATH,
    torch_dtype=torch.bfloat16,
    device_map="auto",
    quantization_config=bnb_config
).to(device)
```
model is now defined. that part works.

```python
from peft import PeftConfig, PeftModelForCausalLM 

peftmodelpath = "/notebooks/eva/model.bin/"
config = PeftConfig.from_pretrained(peftmodelpath)

model = PeftModelForCausalLM.from_pretrained(
    model, 
    peftmodelpath, 
    cache_dir=peftmodelpath, 
    local_files_only=True
)
```
Results in:
`HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/notebooks/eva/model.bin/'. Use "repo_type" argument if needed.`

### Expected behavior

Dont throw an error and give me my model. what even is "repo type"

**Comment by BenjaminBossan** [comment]
Could you please paste the full stacktrace. Also, could you please show the contents of `/notebooks/eva/model.bin/`?
