### ISSUE TITLE
What is the correct way to apply LoRA on a custom model (not models on HuggingFace)?

### ISSUE THREAD

**Issue by DtYXs** [huggingface/peft#808]
Hi, most models in examples are `transformers` pretrained models.
However, I'm using a custom model and applying LoRA to it:
```
model = MyPytorchModel()
model = PeftModel(model, peft_config)
======= training... ========
model.save_pretrained(save_path)
```
Then, I reload my custom model and merge lora weight:
```
model = MyPytorchModel()
lora_model = PeftModel.from_pretrained(model, save_path)
model = lora_model.merge_and_unload()
```
Is this feasible? When I test the final `model`, its behavior does not differ from before loading LoRA weight, as if `merge_ and_unload()` does not have any effect at all. I want to know where the problem is.

**Comment by BenjaminBossan** [comment]
To clarify, the `lora_model` works correctly, only the final model does not? If possible in any way, could you provide a minimal working example of this potential bug?

**Comment by Garstig** [comment]
Hi, 

I am not sure if this is the same issue or not. But I noticed, that loading LoRA weights with `get_peft_model(model, lora_config) ` does not work for me as it used to last week. Right now the model works correctly after training but if you save it to the disk and load it again, the results are the same. Also 


I trained a model using this [guide ](https://www.kaggle.com/code/hhoang41/llama-2-fine-tuning-using-qlora). 

Last week I was able to load the saved weights. Now it does not seem to work this way. I am not sure what broke it, but since I work on colab I always install everything before running the code and as I unfortunately did not ensure that the same version is installed I guess some update broke the code? 


This [notebook ](https://colab.research.google.com/drive/1e2D_1TPSkxcpX2xyzdvSHdZC3Z5jAMnh?usp=sharing) should be a working minimal example to see the error. Unfortunately I could not test it on a fresh runtime because Colab does not have a free GPU anymore for me for now.
 
 
This [issue ](https://github.com/huggingface/peft/issues/793) might be related.

**Comment by BenjaminBossan** [comment]
@Garstig I didn't have time to look into the code yet, but just to ensure: Are you installing the latest PEFT from main or the stable version from pypi (which is what it looks like in the notebook)? If the latter, it would be strange for this to break because we didn't have a release since last week.

**Comment by Garstig** [comment]
Last week I installed it from git like the guide did. I am pretty sure that it worked then. Now I do not get it to work, neither from git nor from pip. 

When I am home I can check the old notebook again but I think I loaded the model from disk before the inference.

**Comment by Garstig** [comment]
So I checked the old notebook and it also says I used the from_pretrained function to load the model before inferencing. The results there look good.

**Comment by BenjaminBossan** [comment]
In the notebook, you load the model like this:

```python
model = model = AutoModelForCausalLM.from_pretrained(...)
lora_config = LoraConfig.from_pretrained('trained')
peft_model = get_peft_model(model, lora_config)
```

Instead, could you try loading the model like this and see if that works:

```python
from peft import PeftModel

model = AutoModelForCausalLM.from_pretrained(...)
peft_model = PeftModel.from_pretrained(mode, "trained")
```

Another issue could be this: In this notebook, you first load the `model`, then LoRA is applied (via PEFT and trainer), which _modifies `model` inplace_. If you later call `peft_model = get_peft_model(model, lora_config)`, you pass the _modified_ `model` to PEFT again, not the original base model, which might lead to incorrect results (not sure). In reality, you wouldn't load the fine-tuned model in the same notebook, so this problem would not occur, but just be aware of that.

**Comment by Garstig** [comment]
@BenjaminBossan : 
`peft_model = PeftModel.from_pretrained(mode, "trained")` works! Thank you very much!

Is it a bug that `get_peft_model` directly imported from peft does not work here?

Using the model after training does not seem to be a problem.

**Comment by BenjaminBossan** [comment]
> Is it a bug that `get_peft_model` directly imported from peft does not work here?

No, I don't think `get_peft_model` is intended to load a fine-tuned model, it is intended to prepare a base model to be fine-tuned. I think the [Kaggle notebook](https://www.kaggle.com/code/hhoang41/llama-2-fine-tuning-using-qlora) that you linked is just using it wrong. Did you see that pattern elsewhere as well?

In general, we should probably take more care to document how to save and load PEFT models and what that actually entails. For that reason, it would be good to know from users where they got their information from.

**Comment by Garstig** [comment]
I just googled how to finetune a LLAMA 2 model on google colab and this was the first thing I found. Did not see it elsewhere yet. 

Thank you for the fast help!

**Comment by BenjaminBossan** [comment]
> Thank you for the fast help!

I'm glad it worked.

@DtYXs Your problem seems to be a different though. Are you still encountering it?

**Comment by DtYXs** [comment]
> > Thank you for the fast help!
> 
> I'm glad it worked.
> 
> @DtYXs Your problem seems to be a different though. Are you still encountering it?

Thank you for your response. In fact, I haven't resolved the original problem, but I've found another (possibly ugly) way to address it:
I noticed that the parameter names in the LoRA checkpoint (`lora_A`, `lora_B`) seem to be slightly different from those in the model obtained from `PeftModel.from_pretrained` (`lora_A.default`, `lora_B.default`). I wonder if this is the reason why the model's behavior does not differ from before loading the LoRA weight. After applying the above function, the model seems to work properly.

**Comment by BenjaminBossan** [comment]
Thanks for your investigation. It's strange that this doesn't seem to work, at first glance I see nothing wrong with the code.

I tried to reproduce your issue with loading a custom model but there was no issue. Maybe you could check the code and compare it with your own, maybe you can spot a difference that might explain why it doesn't work for you.

```python
import tempfile

import torch
from torch import nn

from peft import LoraConfig, PeftModel, get_peft_model

class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.lin0 = nn.Linear(10, 20)
        self.relu = nn.ReLU()
        self.drop = nn.Dropout(0.5)
        self.lin1 = nn.Linear(20, 2)
        self.sm = nn.LogSoftmax(dim=-1)

    def forward(self, X):
        X = X.float()
        X = self.lin0(X)
        X = self.relu(X)
        X = self.drop(X)
        X = self.lin1(X)
        X = self.sm(X)
        return X

def get_model():
    torch.manual_seed(0)
    return MLP()

X = torch.arange(90).view(9, 10)
config = LoraConfig(target_modules=["lin0"])
model = get_peft_model(get_model(), config)
params_copy = {k: v.clone() for k, v in model.named_parameters()}
optimizer = torch.optim.SGD(model.parameters(), 0.1)

for _ in range(5):
    optimizer.zero_grad()
    output = model(X)
    loss = output.sum()
    loss.backward()
    optimizer.step()

params_trained = {k: v.clone() for k, v in model.named_parameters()}
assert params_trained.keys() == params_copy.keys()

# sanity check that lora params were updated
for k, v in params_trained.items():
    if "lora" in k:
        assert not torch.allclose(v, params_copy[k])
    else:
        assert torch.allclose(v, params_copy[k])

with tempfile.TemporaryDirectory() as tmp_dirname:
    model.save_pretrained(tmp_dirname)
    model_from_pretrained = PeftModel.from_pretrained(get_model(), tmp_dirname)
    params_loaded = {k: v.clone() for k, v in model_from_pretrained.named_parameters()}
    assert params_loaded.keys() == params_copy.keys()

    # check that the loaded params are the same as the saved ones
    for k, v in params_loaded.items():
        assert torch.allclose(v, params_trained[k])
    print("test passed!")
```

**Comment by DtYXs** [comment]
> Thanks for your investigation. It's strange that this doesn't seem to work, at first glance I see nothing wrong with the code.
> 
> I tried to reproduce your issue with loading a custom model but there was no issue. Maybe you could check the code and compare it with your own, maybe you can spot a difference that might explain why it doesn't work for you.
> 
> ```python
> import tempfile
> 
> import torch
> from torch import nn
> 
> from peft import LoraConfig, PeftModel, get_peft_model
> 
> class MLP(nn.Module):
>     def __init__(self):
>         super().__init__()
>         self.lin0 = nn.Linear(10, 20)
>         self.relu = nn.ReLU()
>         self.drop = nn.Dropout(0.5)
>         self.lin1 = nn.Linear(20, 2)
>         self.sm = nn.LogSoftmax(dim=-1)
> 
>     def forward(self, X):
>         X = X.float()
>         X = self.lin0(X)
>         X = self.relu(X)
>         X = self.drop(X)
>         X = self.lin1(X)
>         X = self.sm(X)
>         return X
> 
> def get_model():
>     torch.manual_seed(0)
>     return MLP()
> 
> X = torch.arange(90).view(9, 10)
> config = LoraConfig(target_modules=["lin0"])
> model = get_peft_model(get_model(), config)
> params_copy = {k: v.clone() for k, v in model.named_parameters()}
> optimizer = torch.optim.SGD(model.parameters(), 0.1)
> 
> for _ in range(5):
>     optimizer.zero_grad()
>     output = model(X)
>     loss = output.sum()
>     loss.backward()
>     optimizer.step()
> 
> params_trained = {k: v.clone() for k, v in model.named_parameters()}
> assert params_trained.keys() == params_copy.keys()
> 
> # sanity check that lora params were updated
> for k, v in params_trained.items():
>     if "lora" in k:
>         assert not torch.allclose(v, params_copy[k])
>     else:
>         assert torch.allclose(v, params_copy[k])
> 
> with tempfile.TemporaryDirectory() as tmp_dirname:
>     model.save_pretrained(tmp_dirname)
>     model_from_pretrained = PeftModel.from_pretrained(get_model(), tmp_dirname)
>     params_loaded = {k: v.clone() for k, v in model_from_pretrained.named_parameters()}
>     assert params_loaded.keys() == params_copy.keys()
> 
>     # check that the loaded params are the same as the saved ones
>     for k, v in params_loaded.items():
>         assert torch.allclose(v, params_trained[k])
>     print("test passed!")
> ```

Can you share the name of the keys in `params_loaded` ?
In my code, after `model = PeftModel.from_pretrained(model, '/my/ckpt/path')`, the model has param named `bert.encoder.layer.11.attention.self.value.lora_A.default.weight` and `bert.encoder.layer.11.attention.self.value.lora_B.default.weight`. But the lora ckpt keys are `bert.encoder.layer.11.attention.self.value.lora_A.weight` and `bert.encoder.layer.11.attention.self.value.lora_B.weight`. It seems that `PeftModel.from_pretrained` did not load the lora ckpt successful?

**Comment by BenjaminBossan** [comment]
For me, in both cases, the keys include the `.default` part, which is expected to be there. Not sure why they're missing for your checkpoint. If possible, could you please provide a minimal code example that produces these incorrectly named weights?

**Comment by undercover87** [comment]
Hello, 
I stumbled upon the same issue and compared @BenjaminBossan's custom model code to @DtYXs 's code and my code and found that it was specifying "task_type" that caused the issue. In @DtYXs 's code:
```
peft_config = LoraConfig(
        **task_type=TaskType.FEATURE_EXTRACTION,** inference_mode=False, r=8, lora_alpha=32, lora_dropout=0.1,
        target_modules=['query', 'value']
    )
```

if you remove the task_type argument, it works. It is this argument that triggers the underlying code to look for a "config" attribute in the custom model which is obviously not there since it is a custom model (PreTrained HF models have this attribute).
