### ISSUE TITLE
Question -- is `TaskType` used for anything?

### ISSUE THREAD

**Issue by radekosmulski** [huggingface/peft#812]
I wanted to use `peft` (specifically, LoRA) for a task that is not included as a `TaskType`.

But, seeing the `TaskType` in `PeftConfig` got me thinking -- "mhmmm, I bet this is used for something important, though I have no clue what, let me look at the code"

But reading through the classes and searching for it, it seems it is used only in a single place of the library? 👀
![image](https://github.com/huggingface/peft/assets/2444926/66ad05a5-f25d-43f2-a197-b307f6912896)

Specifically, here in `PeftModel`:
![image](https://github.com/huggingface/peft/assets/2444926/0b2626f9-185a-4220-aa37-3618e7e2442b)

Could I please ask if anything else in the huggingface ecosystem relies on this enum? Would there be value in adding a value of `Other`?

I plan on training a model that wouldn't fall into any of these provided `TaskType`s and the existence of this value in config suggested to me that it actually impacts something, but it seems to be (mostly) for informational purposes only?

Anyhow, will try to train my custom model and see what happens 🙂

**Comment by radekosmulski** [comment]
Thank you very much @BenjaminBossan for the reply, do appreciate it! 🙂

I love the libs by Huggingface and yeah, do consider maybe removing the `TaskType` as right now it is quite misleading to the user.

Why is it there at all?
If I pass it into Lora config (and it is mentioned as one of the first args in the docstrings!) I bet it must be doing something important... what does it do... but it turns out it does absolutely nothing!

And as expected, Lora in no way changes in behavior (or modifications to the arch) depending on what head we stick on the model.

I haven't used the library yet, will do so right now -- but AFAICT you even have to specify yourself which layers you want to modify (which is not clear from the docs) so the whole idea of passing in a TaskType seems very odd.

Anyhow, thank you so much for your response and for the chat 🙏🙂 Came here from the Microsoft Lora repo, very much looking forward to using a library that automates all the changes to my arch and exposes an API for what I want with just a few lines of code 😁 

Will work on the training of my Transformer now! 👋

**Comment by radekosmulski** [comment]
Turns out this is actually being used but you cannot grep for it since `TaskType` is never used, it is used under another var name and it is central to switching what class I get back!

So now have to figure out how to use all this with a custom model, if it is possible at all 😉

![image](https://github.com/huggingface/peft/assets/2444926/66d3ba41-0484-46e3-a179-9f807bfa19f7)

**Comment by BenjaminBossan** [comment]
Oh yeah, good catch. I don't think it should prevent you from using custom models, see [here](https://huggingface.co/docs/peft/developer_guides/custom_models) for instance. But less us know when you run into trouble.
