### ISSUE TITLE
[Bug]: Incompatible with speechbrain: Segmentation fault

### ISSUE THREAD

**Issue by caidongqi** [huggingface/peft#823]
### Describe the bug

I want to use LoRa tuning to fine-tune Whisper, but after I installed peft (parameter-efficient finetuning), it comes to a `segmentation fault` for each speechbrain process (even I didn't import it).

I uninstalled peft, and the code runs normally again.

I have no idea whether this bug derives from Speechbrain or peft, is there anyone meets the same bug?

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

```
import speechbrain as sb
from peft import LoraConfig, get_peft_model
```

### Versions

speechbrain version is 0.5.14
peft version: I tried 0.2.0, 0.4.0, and both of them do not work.

### Relevant log output

```shell
Segmentation fault (core dumped)
```

### Expected behavior

I expected I could import `speechbrain` and `peft` simultaneously.

**Comment by Guralamjyot** [comment]
Does it importing just peft work? or does the issue only come up when when trying to import both simultaneously?

**Comment by caidongqi** [comment]
Importing only peft or speechbrain works normally. It happens when we import them simultaneously.

**Comment by Guralamjyot** [comment]
It has something to do with your installation of Speechbrain. I tried reproducing the error in Colab notebook they provide in tutorial section, but it all worked normally.
Make sure you have all the dependencies installed.

**Comment by caidongqi** [comment]
Could you provide the dependencies and their versions for me plz. I will compare and check my environment.

**Comment by caidongqi** [comment]
Requirements.txt will be perfectly fine if you could.

**Comment by Guralamjyot** [comment]
[Here](https://github.com/speechbrain/speechbrain/blob/develop/requirements.txt)

or alternatively this should do the trick
`!git clone https://github.com/speechbrain/speechbrain/`
`%cd /content/speechbrain/`
`!pip install -r requirements.txt`
`!pip install -e`

**Comment by caidongqi** [comment]
Thank you for your prompt reply. But it seems not have `peft` installed. Could you send me the complete dependence's or the `peft` version please?
