### ISSUE TITLE
Multi label Text classification support

### ISSUE THREAD

**Issue by cassin-edwin** [huggingface/peft#824]
Does PEFT LoRA support multi label classification? If yes what is the  value for task type parameter?

**Comment by BenjaminBossan** [comment]
There is no task type specific to only multi-label classification. Normal sequence classification should do ("SEQ_CLS"). However, there seem to be some extra steps required on the transformers side (in case you're using the trainer):

https://discuss.huggingface.co/t/multilabel-text-classification-trainer-api/11508
