### ISSUE TITLE
increase the size of my peft lora rank after I started training

### ISSUE THREAD

**Issue by LazerJesus** [huggingface/peft#825]
### Feature request

I've setup and trained a peft model for a few epochs. now i would like to increase it's rank. how do i do that, if its possible?

```python
model = get_peft_model(model, config)
model.train()
mode.save_pretrained()
# I continue training 
model = PeftModel.from_pretrained(
    model, 
    EVA_ADAPTER_DIR,
    is_trainable=True
)
```

### Motivation

I want to improve my model.

### Your contribution

By asking.

**Comment by BenjaminBossan** [comment]
PEFT doesn't support that. Although it's not technically impossible, but also not trivial to implement.

What you could do is to [`merge_and_unload`](https://huggingface.co/docs/peft/conceptual_guides/lora#merge-lora-weights-into-the-base-model) the model, i.e. merge the existing LoRA weights into the normal weights. After that, you can add completely new LoRA weights with a different rank on top. However, you cannot unmerge the first LoRA weights anymore.

I haven't seen anyone use that approach though, I'm not sure if it would work better in practice than training new LoRA weights with the higher rank from scratch. If you do try that and it works really well, let us know.

**Comment by LazerJesus** [comment]
thank you. i’ll start from scratch then.

**Comment by PanQiWei** [comment]
One paper you can reference to is ReLoRA, what you need to do is as Ben said using `merge_and_unload` which means you need to customize some training logic

**Comment by PeterL1n** [comment]
Don't be stupid. You can of course expand the rank.

```python
old_rank = 64
new_rank = 128
assert new_rank >= old_rank

new_lora_config = LoraConfig(
    r=new_rank,
    target_modules=["your_module"]
)

model = get_peft_model(model, new_lora_config)

lora_state_old = torch.load("lora.pth")
lora_state_new = get_peft_model_state_dict(model)

for key in lora_state_curr.keys():
    old = lora_state_old[key]
    new = lora_state_new[key]
    new[:old.size(0), :old.size(1)] = old * (new_rank/old_rank)**0.5

torch.save(lora_state_new, "lora_expanded.pth")

```

**Comment by ethansmith2000** [comment]
i believe the above should be division instead of multiplication but otherwise i think this is correct

```python
new[:old.size(0), :old.size(1)] = old / (new_rank/old_rank)**0.5
```
