### ISSUE TITLE
what is alpha ?? alpha not in paper.

### ISSUE THREAD

**Issue by XuJianzhi** [huggingface/peft#826]
### Feature request

https://github.com/huggingface/peft/blob/main/src/peft/tuners/lora.py#L57
this alpha not in paper : 
https://arxiv.org/abs/2106.09685

where can i learn this alpha ??

thank you !!

### Motivation

rt

### Your contribution

rt

**Comment by BenjaminBossan** [comment]
> We then scale ∆W x by α/r, where α is a constant in r

Section 4.1 in the linked paper.
