### ISSUE TITLE
Not Able to Create and Train Multiple LoRA Adapters

### ISSUE THREAD

**Issue by DefinitlyEvil** [huggingface/peft#837]
### System Info

peft: `0.5.0.dev0` (pulled from Github)
transformers: `4.32.0.dev0`

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

```python
peft_model = peft.from_pretrained(base_model, "./path/to/first", is_trainable=False, adapter_name='ADAPTER_1')
peft_model = peft.get_peft_model(peft_model, lora_config, adapter_name='ADAPTER_2')
# or 
peft_model.add_adapter('ADAPTER_2', lora_config) # with inference_model set to False
```

Output: 
```
No inf checks were recorded prior to update. 
```

### Expected behavior

- `ADAPTER_2` should be able to train. 
- `base_model` and `ADAPTER_1` should be frozen.

**Comment by DefinitlyEvil** [comment]
```
PeftModelForCausalLM(
  (base_model): LoraModel(
    (model): PeftModelForCausalLM(
      (base_model): LoraModel(
        (model): LlamaForCausalLM(
          (model): LlamaModel(
            (embed_tokens): Embedding(32000, 5120, padding_idx=0)
            (layers): ModuleList(
              (0-39): 40 x LlamaDecoderLayer(
                (self_attn): LlamaAttention(
                  (q_proj): Linear4bit(
                    in_features=5120, out_features=5120, bias=False
                    (lora_dropout): ModuleDict(
                      (ft_1): Dropout(p=0.01, inplace=False)
                      (ft_2): Dropout(p=0.01, inplace=False)
                    )
                    (lora_A): ModuleDict(
                      (ft_1): Linear(in_features=5120, out_features=16, bias=False)
                      (ft_2): Linear(in_features=5120, out_features=16, bias=False)
                    )
                    (lora_B): ModuleDict(
                      (ft_1): Linear(in_features=16, out_features=5120, bias=False)
                      (ft_2): Linear(in_features=16, out_features=5120, bias=False)
                    )
                    (lora_embedding_A): ParameterDict()
                    (lora_embedding_B): ParameterDict()
                  )
                  (k_proj): Linear4bit(
                    in_features=5120, out_features=5120, bias=False
                    (lora_dropout): ModuleDict(
                      (ft_1): Dropout(p=0.01, inplace=False)
                      (ft_2): Dropout(p=0.01, inplace=False)
                    )
                    (lora_A): ModuleDict(
                      (ft_1): Linear(in_features=5120, out_features=16, bias=False)
                      (ft_2): Linear(in_features=5120, out_features=16, bias=False)
                    )
                    (lora_B): ModuleDict(
                      (ft_1): Linear(in_features=16, out_features=5120, bias=False)
                      (ft_2): Linear(in_features=16, out_features=5120, bias=False)
                    )
                    (lora_embedding_A): ParameterDict()
                    (lora_embedding_B): ParameterDict()
                  )
                  (v_proj): Linear4bit(
                    in_features=5120, out_features=5120, bias=False
                    (lora_dropout): ModuleDict(
                      (ft_1): Dropout(p=0.01, inplace=False)
                      (ft_2): Dropout(p=0.01, inplace=False)
                    )
                    (lora_A): ModuleDict(
                      (ft_1): Linear(in_features=5120, out_features=16, bias=False)
                      (ft_2): Linear(in_features=5120, out_features=16, bias=False)
                    )
                    (lora_B): ModuleDict(
                      (ft_1): Linear(in_features=16, out_features=5120, bias=False)
                      (ft_2): Linear(in_features=16, out_features=5120, bias=False)
                    )
                    (lora_embedding_A): ParameterDict()
                    (lora_embedding_B): ParameterDict()
                  )
                  (o_proj): Linear4bit(in_features=5120, out_features=5120, bias=False)
                  (rotary_emb): LlamaRotaryEmbedding()
                )
                (mlp): LlamaMLP(
                  (gate_proj): Linear4bit(in_features=5120, out_features=13824, bias=False)
                  (up_proj): Linear4bit(in_features=5120, out_features=13824, bias=False)
                  (down_proj): Linear4bit(in_features=13824, out_features=5120, bias=False)
                  (act_fn): SiLUActivation()
                )
                (input_layernorm): LlamaRMSNorm()
                (post_attention_layernorm): LlamaRMSNorm()
              )
            )
            (norm): LlamaRMSNorm()
          )
          (lm_head): Linear(in_features=5120, out_features=32000, bias=False)
        )
      )
    )
  )
)
```

**Comment by DefinitlyEvil** [comment]
This code seemed to work, at least no errors: 
```python
model_ft = peft.get_peft_model(model, peft_config=lc, adapter_name='ADAPTER_2')
model_ft = PeftModel.from_pretrained(model_ft, './path/to/trained/adapter_one', adapter_name='ADAPTER_1', is_trainable=False)
```
Now it will *probably* train `ADAPTER_2` and keep `ADAPTER_1` frozen.

**Comment by BenjaminBossan** [comment]
This looks like it should work as you intend. When you finish training, you could manually check which weights were updated to be 100% sure.

**Comment by DefinitlyEvil** [comment]
> This looks like it should work as you intend. When you finish training, you could manually check which weights were updated to be 100% sure.

@BenjaminBossan 
Hi! Thanks for your kind response. 
But I just read another issue on this. 
Mathematically speaking, if `r` set to be equal, is there still a point to train multiple adapters? 
With previous adapter, the loss seemed to be maintaining around the same value.

**Comment by BenjaminBossan** [comment]
Haha, yes, it's also me.

IIUC, a big difference between the other thread and this one is that here, you want to freeze the first adapter and only train the second, which can make sense in some circumstances.

**Comment by DefinitlyEvil** [comment]
> Haha, yes, it's also me.
> 
> IIUC, a big difference between the other thread and this one is that here, you want to freeze the first adapter and only train the second, which can make sense in some circumstances.

What do you think about this approach than re-creating another larger adapter? 
Can it expand the capacity of a single adapter?

**Comment by Lathashree01** [comment]
> This code seemed to work, at least no errors:
> 
> ```python
> model_ft = peft.get_peft_model(model, peft_config=lc, adapter_name='ADAPTER_2')
> model_ft = PeftModel.from_pretrained(model_ft, './path/to/trained/adapter_one', adapter_name='ADAPTER_1', is_trainable=False)
> ```
> 
> Now it will **probably** train `ADAPTER_2` and keep `ADAPTER_1` frozen.

I wanted to confirm;  I think this needs to be in reverse order like below :
`
model = base_model # Loading base model 
model_ft = PeftModel.from_pretrained(model_ft, './path/to/trained/adapter_one', adapter_name='ADAPTER_1', is_trainable=False)
model_ft = peft.get_peft_model(model, peft_config=lc, adapter_name='ADAPTER_2')
`
When I did as you mentioned, the number of trainable parameters showed 0. Please correct me if I have missed something.


Thanks

**Comment by BenjaminBossan** [comment]
> What do you think about this approach than re-creating another larger adapter?
> Can it expand the capacity of a single adapter?

Hmm, not really sure what you mean. The first adapter could learn some aspects of the dataset, and then the second adapter doesn't have to learn those anymore and can focus on other tasks. But then the second adapter can only work in conjunction with the first adapter, it doesn't really expand its capacity.

> I wanted to confirm; I think this needs to be in reverse order like below :

Yes, that order looks correct, thanks for posting.

**Comment by BenjaminBossan** [comment]
I guess so. Just note that LORA 2 would be tied to LORA 1 and couldn't be used independently. In the end, it's worth giving it a try and see if it works or not.

**Comment by DefinitlyEvil** [comment]
@BenjaminBossan Hah! My computing power is limited so I guess I couldn't test that out... xD
