### ISSUE TITLE
Loading peft model with special tokens

### ISSUE THREAD

**Issue by Lathashree01** [huggingface/peft#838]
### System Info

PEFT

### Who can help?

@younesbelkada @sayakpaul 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

I am trying to train llama with LORA.

LORA training params: 

lora_trainable="q_proj,v_proj,k_proj,o_proj"
modules_to_save="embed_tokens,lm_head"

I add my special tokens and get my peft model. Below is the config that was saved from the checkpoint. 
`
#### checkpoint CONFIG \#####
LlamaConfig {
  "REModelVersion": "0.1",
  "_name_or_path": "llama",
  "architectures": [
    "LlamaForCausalLM"
  ],
  "balance_sample_weights": false,
  "binary_mode": false,
  "bos_token_id": 1,
  "eos_token_id": 2,
  "focal_loss_gamma": 2,
  "hidden_act": "silu",
  "hidden_size": 4096,
  "id2label": {
    "0": "LABEL_0",
    "1": "LABEL_1",
    "2": "LABEL_2",
    "3": "LABEL_3",
    "4": "LABEL_4",
    "5": "LABEL_5",
    "6": "LABEL_6",
    "7": "LABEL_7",
    "8": "LABEL_8"
  },
  "initializer_range": 0.02,
  "intermediate_size": 11008,
  "label2id": {
    "LABEL_0": 0,
    "LABEL_1": 1,
    "LABEL_2": 2,
    "LABEL_3": 3,
    "LABEL_4": 4,
    "LABEL_5": 5,
    "LABEL_6": 6,
    "LABEL_7": 7,
    "LABEL_8": 8
  },
  "max_position_embeddings": 4096,
  "model_type": "llama",
  "num_attention_heads": 32,
  "num_hidden_layers": 32,
  "num_key_value_heads": 32,
  "pad_token_id": 0,
  "pretraining_tp": 1,
  "problem_type": "single_label_classification",
  "rms_norm_eps": 1e-05,
  "rope_scaling": null,
  "scheme": 2,
  "tags": [
    32000,
    32001,
    32002,
    32003
  ],
  "tie_word_embeddings": false,
  "torch_dtype": "bfloat16",
  "transformers_version": "4.31.0",
  "use_cache": true,
  "use_focal_loss": false,
  "vocab_size": 32004
}
`

As we see the vocab size is increased to 32004.

Now when I try to load the peft model as below

`

llamaModel = model.from_pretrained(
                                    PATH_TO_CONVERTED_WEIGHTS,
                                    cache_dir=mycache_dir,
                                    config=self.config,
                        #             output_attentions=False,
                        #             output_hidden_states=False,
                                    torch_dtype=getattr(torch, 'bfloat16'),
                                    low_cpu_mem_usage=True,  
                                )
            print("#### checkpoint CONFIG \#####")
            print(self.config)
            print("####")
            self.model = PeftModel.from_pretrained(llamaModel,latest_ckpt_dir)
            self.model.resize_token_embeddings(len(self.tokenizer))
`

This does not seem to work as expected. I keep getting an error. 

`  
size mismatch for base_model.model.model.embed_tokens.weight: copying a param with shape torch.Size([32004, 4096]) from the checkpoint, the shape in the current model is torch.Size([32000, 4096]).` 

I understood that it is related to the new tokens I am adding. But I have been trying to figure it out. I am passing a new config with the changed vocab size, I am also doing resize token embeddings.

The loaded tokeniser shows the correct vocab size - 32004. I can't seem to figure out the mismatch.

Any help would be greatly appreciated. Thanks

### Expected behavior

peft model should load based on the updated config from PEFT model

**Comment by Lathashree01** [comment]
UPDATE: 

I got it to work. I first resized the original model embeddings to add 4 special tokens and then loaded the checkpoint through
`self.model = PeftModel.from_pretrained(llamaModel,latest_ckpt_dir)`

Initially, I was trying to resize after trying to load peft model.

It works fine now.

I hope it's the right way. Thanks

**Comment by BenjaminBossan** [comment]
Great, thanks for the update, your solution makes sense. I'll close the issue for now, if something comes up again, feel free to re-open.
