### ISSUE TITLE
relora

### ISSUE THREAD

**Issue by thistleknot** [huggingface/peft#841]
### Feature request

https://github.com/Guitaricet/relora

### Motivation

more efficient 'continued pretraining'

### Your contribution

willing to test

**Comment by datalee** [comment]
https://mp.weixin.qq.com/s/1DAvtJ63rYnCcXeBNrgDHA

**Comment by flozi00** [comment]
@pacman100 would be amazing to see that
its democratizing pretraining a lot

**Comment by thistleknot** [comment]
I found this
https://github.com/ElleLeonne/Lightning-ReLoRA/tree/main
