### ISSUE TITLE
Support 4-bit bitsandbytes models

### ISSUE THREAD

**Issue by johnowhitaker** [huggingface/peft#842]
### Feature request

In https://github.com/huggingface/peft/blob/main/src/peft/tuners/lora.py#L893 F.linear is used with self.weight to replace what the normal base model would do. BUT if the model was loaded in 4-bit with bitsandbytes, self.weight is of type bitsandbytes.nn.modules.Params4bit and using it this way means the weights get interpreted as bytes and give only half as many weights as expected. And more generally, F.linear doesn't do the other magic that bnb.Linear4bit layers do. 

I'm not sure how best to address this. I had to patch peft.tuners.lora.Linear's forward method to get my thing working. But maybe I have missed something and this should be handled already? Or should we just avoid using 4-bit bnb with peft LORA for now? 

### Motivation

Just raising this in case someone 1) knows a fix or 2) was looking for motivation to better reconcile BNB with PEFT. Feel free to ignore if this sounds crazy and/or I've just made a mistake somewhere.

### Your contribution

I don't have a good enough overview of PEFT and BNB and Trainer to know where these conflicts are best addressed or if there is an existing fix I'm missing, so can't help besides flagging that in my own experiments getting quantization + LoRA working for training and later loading for eval working was a mission :)

**Comment by BenjaminBossan** [comment]
If you're using 4bit, the model should use the [`Linear4bit`](https://github.com/huggingface/peft/blob/6c44096c7b8d55a2ecf24be9bc68393467e1584a/src/peft/tuners/lora.py#L1177C26-L1177C54) class. It inherits from both `bnb.nn.Linear4bit` and `LoraLayer` but the [super call](https://github.com/huggingface/peft/blob/6c44096c7b8d55a2ecf24be9bc68393467e1584a/src/peft/tuners/lora.py#L1208) should run the `forward` method of `bnb.nn.Linear4bit`, avoiding the problem you mentioned, right?
