### ISSUE TITLE
Are the layers specified in "modules_to_save" not saved in the checkpoints during the training?

### ISSUE THREAD

**Issue by yutanozaki1** [huggingface/peft#845]
The HuggingFace document says that the layers specified in "modules_to_save" are saved at the final checkpoint, but is it possible to save a model with updated weights for the layers specified in modules_to_save at a checkpoint in the middle of training?

I would like to add vocabulary to the Llama2 tokenizer dictionary and update the Embedding layer weights.

Therefore,
```
modules_to_save="embed_tokens,lm_head"
```
but I want to be able to check the model in the middle of training.

**Comment by BenjaminBossan** [comment]
It depends on how you're training and what checkpoint you're using. In general, these modules are considered to be part of those that need to be saved (e.g. when calling `.save_pretrained` or `get_peft_model_state_dict`). If you have code that doesn't save these modules, please show it so that we can take a look.

**Comment by yutanozaki1** [comment]
I used the [Chinese-LLaMA-Alpaca](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/scripts/training/run_clm_pt_with_peft.py) code.

The code for the` SavePeftModelCallback` and Trainer portions is shown below.
```
class SavePeftModelCallback(transformers.TrainerCallback):
    def save_model(self, args, state, kwargs):
        if state.best_model_checkpoint is not None:
            checkpoint_folder = os.path.join(state.best_model_checkpoint, "pt_lora_model")
        else:
            checkpoint_folder = os.path.join(args.output_dir, f"{PREFIX_CHECKPOINT_DIR}-{state.global_step}")

        peft_model_path = os.path.join(checkpoint_folder, "pt_lora_model")
        kwargs["model"].save_pretrained(peft_model_path)
        kwargs["tokenizer"].save_pretrained(peft_model_path)

    def on_save(self, args, state, control, **kwargs):
        self.save_model(args, state, kwargs)
        return control

    def on_train_end(self, args, state, control, **kwargs):
        peft_model_path = os.path.join(args.output_dir, "pt_lora_model")
        kwargs["model"].save_pretrained(peft_model_path)
        kwargs["tokenizer"].save_pretrained(peft_model_path)

trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset if training_args.do_train else None,
        eval_dataset=eval_dataset if training_args.do_eval else None,
        tokenizer=tokenizer,
        data_collator=fault_tolerance_data_collator,
        #【Modified】datacolattorの設定
        #data_collator=transformers.DataCollatorForLanguageModeling(tokenizer, mlm=False),
        compute_metrics=compute_metrics if training_args.do_eval and not is_torch_tpu_available() else None,
        preprocess_logits_for_metrics=preprocess_logits_for_metrics
        if training_args.do_eval and not is_torch_tpu_available()
        else None,
)
trainer.add_callback(SavePeftModelCallback)
# Training
if training_args.do_train:
        checkpoint = None
        if training_args.resume_from_checkpoint is not None:
            checkpoint = training_args.resume_from_checkpoint
        elif last_checkpoint is not None:
            checkpoint = last_checkpoint
        train_result = trainer.train(resume_from_checkpoint=checkpoint)

        metrics = train_result.metrics

        max_train_samples = (
            data_args.max_train_samples if data_args.max_train_samples is not None else len(train_dataset)
        )
        metrics["train_samples"] = min(max_train_samples, len(train_dataset))

        trainer.log_metrics("train", metrics)
        trainer.save_metrics("train", metrics)
        trainer.save_state()
```

According to this code, I think that `adapter_model.bin` is saved under the `pt_lora_model` directory, is this where the modules specified in `modules_to_save` are saved?

**Comment by BenjaminBossan** [comment]
I have no experience with transformers `Trainer`, so I can't be 100% sure, but this line looks like it should be doing its job:

`kwargs["model"].save_pretrained(peft_model_path)`

So as you suggested, all the adapter parameters should be stored in `os.path.join(checkpoint_folder, "pt_lora_model")`.

**Comment by LMXKO** [comment]
I use the same code to run peft，and I found its had been saved in checkpoint，like this
![image](https://github.com/huggingface/peft/assets/35209678/e8ed78ca-4db6-45b5-b3af-ad03564a05e2)
