### ISSUE TITLE
Error in Prefix-tuning

### ISSUE THREAD

**Issue by suntea233** [huggingface/peft#846]
### System Info

When i use prefix tuning with int8,

### Who can help?

@pacman100 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

```
peft_config = PrefixTuningConfig(task_type=TaskType.SEQ_2_SEQ_LM, inference_mode=False, num_virtual_tokens=20)
model = AutoModelForSeq2SeqLM.from_pretrained(model_checkpoint,load_in_8bit=True)
model = prepare_model_for_int8_training(model)

model = get_peft_model(model,peft_config).to(DEVICE)
model.print_trainable_parameters()
```

### Expected behavior

And the error is 
`RuntimeError: The size of tensor a (100) must match the size of tensor b (120) at non-singleton dimension 3`

**Comment by Vincent-Li-9701** [comment]
Got a similar error. Did you manage to find a fix?

**Comment by suntea233** [comment]
Nope, but if you donot set "load_in_8bit=True", it might be worked.
And as the author said that "the effect of prefix tuning is not as good as lora". So i just  change the peft to lora.

**Comment by Vincent-Li-9701** [comment]
I did some debugging and found out that this seems to occur for encoder decoder model. When it's doing decoder forward pass, it seems to concat prefix to decoder tokens too.

**Comment by suntea233** [comment]
Yes, i found that when i use "load_in_8bit", the parameter "gradient_checkpointing" is set to "True". And then the mask mismatch the position_bias. Probably that's the reason.
