### ISSUE TITLE
How to load fine tune IDEFICS model with peft for inference?

### ISSUE THREAD

**Issue by Imran-tech-lab** [huggingface/peft#857]
### Feature request

Request for IDEFICS model. 

### Motivation

I fine tune IDEFICS on custom dataset, but when I load they showing error.

### Your contribution

Add class like AutoPeftModelforVisionTextToText() class, to easily load the model.

**Comment by younesbelkada** [comment]
Hi @imrankh46 
Thanks for the issue, for IDEFICS, consider using the new API: https://huggingface.co/docs/transformers/main/en/peft to inject adapters, please let us know how it goes!

**Comment by dvelho** [comment]
Hi! tried to use the adapters but having this error:

```
Traceback (most recent call last):
  File "/data/evaluate_lora.py", line 16, in <module>
    model.load_adapter(peft_model_id)
  File "/data/envs/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'IdeficsForVisionText2Text' object has no attribute 'load_adapter'

```

Code:

```
checkpoint = "HuggingFaceM4/idefics-9b"

peft_model_id = "diogovelho/idefics-9b-dresses-2"
config = PeftConfig.from_pretrained(peft_model_id)
print("Loading Model")
model = IdeficsForVisionText2Text.from_pretrained(config.base_model_name_or_path, return_dict=True, load_in_8bit=True, device_map='auto')
processor = AutoProcessor.from_pretrained(checkpoint, use_auth_token=False)
model.load_adapter(peft_model_id)
print("Loading PEFT Model")
```

**Comment by dvelho** [comment]
Hi @imrankh46 Thanks for your suggestion, but now i get this error:
```

ValueError: Unrecognized configuration class <class 'transformers.models.idefics.configuration_idefics.IdeficsConfig'> for this kind of AutoModel: AutoModelForCausalLM.
Model type should be one of BartConfig, BertConfig, BertGenerationConfig, BigBirdConfig, BigBirdPegasusConfig, BioGptConfig, BlenderbotConfig, BlenderbotSmallConfig, BloomConfig, CamembertConfig, CodeGenConfig, CpmAntConfig, CTRLConfig, Data2VecTextConfig, ElectraConfig, ErnieConfig, FalconConfig, GitConfig, GPT2Config, GPT2Config, GPTBigCodeConfig, GPTNeoConfig, GPTNeoXConfig, GPTNeoXJapaneseConfig, GPTJConfig, LlamaConfig, MarianConfig, MBartConfig, MegaConfig, MegatronBertConfig, MptConfig, MusicgenConfig, MvpConfig, OpenLlamaConfig, OpenAIGPTConfig, OPTConfig, PegasusConfig, PLBartConfig, ProphetNetConfig, QDQBertConfig, ReformerConfig, RemBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoCBertConfig, RoFormerConfig, RwkvConfig, Speech2Text2Config, TransfoXLConfig, TrOCRConfig, XGLMConfig, XLMConfig, XLMProphetNetConfig, XLMRobertaConfig, XLMRobertaXLConfig, XLNetConfig, XmodConfig.

```

**Comment by dvelho** [comment]
Thanks for the fast replie @imrankh46 getting this error on google colab and also on my machine:
Collecting git+https://github.com/huggingface/transformers.git@add-model-idefics
  Cloning https://github.com/huggingface/transformers.git (to revision add-model-idefics) to /tmp/pip-req-build-lgss5sp_
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/transformers.git /tmp/pip-req-build-lgss5sp_
  WARNING: Did not find branch or tag 'add-model-idefics', assuming revision or ref.
  Running command git checkout -q add-model-idefics
  error: pathspec 'add-model-idefics' did not match any file(s) known to git
  error: subprocess-exited-with-error
  
  × git checkout -q add-model-idefics did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git checkout -q add-model-idefics did not run successfully.
│ exit code: 1
╰─> See above for output.

**Comment by dvelho** [comment]
Same error :( :

note: This error originates from a subprocess, and is likely not a problem with pip.
$ pip install -q -U git+https://github.com/huggingface/transformers.git@add-model-idefics
  WARNING: Did not find branch or tag 'add-model-idefics', assuming revision or ref.
  error: subprocess-exited-with-error
  
  × git checkout -q add-model-idefics did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error: pathspec 'add-model-idefics' did not match any file(s) known to git
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git checkout -q add-model-idefics did not run successfully.
│ exit code: 1
╰─> See above for output.

**Comment by dvelho** [comment]
Yes, already tried with pip install -q -U transformers but then I can't load LoRA. The model trains fine and if i don't unload it it works as expected. Only when I try to load LoRA from Huggingface repo it does not apply the weights :(
I can apply LoRA on other LLM but not on this new idefics model

**Comment by dvelho** [comment]
Thanks a lot for your support. already opened a bug report on transformers repo
