### ISSUE TITLE
Unable to load optimizer checkpoint when using resume_from_checkpoint

### ISSUE THREAD

**Issue by activatedgeek** [huggingface/peft#859]
### System Info

`pytorch`: 2.0.1+cu118
`peft`: 0.5.0
`transformers`: 4.32.0
`accelerate`: 0.21.0
`platform`: Ubuntu 22.04.2 LTS
`python`: 3.10.12

### Who can help?

@younesbelkada @pacman100

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

Here is a rough sketch of the code I use. The code is exactly this, except I skip some arguments and bookkeeping steps. The training setup is standard `LoRA` adapter fine-tuning for a `CausalLM` class. The dataset is also formatted as usual for a `CausalLM` task with `input_ids` and `attention_mask`.

```python
    tokenizer = LlamaTokenizer.from_pretrained(...)
    special_token_count = tokenizer.add_special_tokens(get_special_tokens(tokenizer))

    model = LlamaForCausalLM.from_pretrained(
        ...,
        device_map={"": accelerator.local_process_index},
        load_in_8bit=True,
        ...
    )

    model.resize_token_embeddings(len(tokenizer))
    ## ... update embeddings init.

    model = prepare_model_for_kbit_training(model)

    if peft_dir is not None:
        model = get_peft_model(model, PeftConfig.from_pretrained(peft_dir))

        set_peft_model_state_dict(
            model, 
            torch.load(os.path.join(peft_dir, PEFT_WEIGHTS_NAME)))
    else:
        peft_config = LoraConfig(
            task_type=TaskType.CAUSAL_LM,
            bias="none",
            r=lora_rank,
            lora_alpha=lora_alpha,
            lora_dropout=lora_dropout,
        )
        model = get_peft_model(model, peft_config)

    model.config.use_cache = False

    with accelerator.main_process_first():
        train_data, val_data, test_data = get_dataset(...)

    trainer = Trainer(
        model=model,
        args=TrainingArguments(
            fsdp=False,
            fp16=False,
            bf16=False,
            gradient_checkpointing=False,
            ddp_find_unused_parameters=False,
            max_steps=max_steps,
            eval_steps=1000,
            save_steps=save_steps,
            logging_steps=100,
            log_on_each_node=False,
            evaluation_strategy="steps",
            per_device_train_batch_size=batch_size,
            per_device_eval_batch_size=batch_size,
            loss_mode=loss_mode,
            optim="adamw_torch",
            learning_rate=learning_rate,
            lr_scheduler_type="cosine",
            warmup_steps=warmup_steps,
            weight_decay=weight_decay,
            gradient_accumulation_steps=grad_acc,
            output_dir=log_dir,
            report_to="wandb",
            dataloader_num_workers=4,            
        ),
        train_dataset=train_data,
        eval_dataset=val_data,
        test_dataset=test_data,
        tokenizer=tokenizer,
    )

    trainer.train(resume_from_checkpoint=peft_dir)
    trainer.save_state()
```

Now here are the steps I take:
- I first use this training code without the `peft_dir` variable above. This leads to a checkpoint folder with the following files:
    ```shell
    README.md            added_tokens.json  rng_state_1.pth  scheduler.pt             tokenizer_config.json
    adapter_config.json  optimizer.pt       rng_state_2.pth  special_tokens_map.json  trainer_state.json
    adapter_model.bin    rng_state_0.pth    rng_state_3.pth  tokenizer.model          training_args.bin
    ```
- Now, send in exactly the same arguments, except this time passing `peft_dir` to the directory containing the above files.
   - In terms of evaluating the checkpoint, I can confirm that the adapter weights are loading correctly, since I am able to see performance improvement in test from the checkpoint (that exactly matches what I see during my training logs)
   - But, when loading this checkpoint for training, I get the following error:
      ```shell
      File "finetune.py", line 169, in main
        trainer.train(resume_from_checkpoint=peft_dir)
      File "/ext3/.conda/envs/overlayfs/lib/python3.10/site-packages/transformers/trainer.py", line 1555, in train
        return inner_training_loop(
      File "/ext3/.conda/envs/overlayfs/lib/python3.10/site-packages/transformers/trainer.py", line 1707, in _inner_training_loop
        self._load_optimizer_and_scheduler(resume_from_checkpoint)
      File "/ext3/.conda/envs/overlayfs/lib/python3.10/site-packages/transformers/trainer.py", line 2499, in _load_optimizer_and_scheduler
        self.optimizer.load_state_dict(
      File "/ext3/.conda/envs/overlayfs/lib/python3.10/site-packages/accelerate/optimizer.py", line 103, in load_state_dict
        self.optimizer.load_state_dict(state_dict)
      File "/ext3/.conda/envs/overlayfs/lib/python3.10/site-packages/torch/optim/optimizer.py", line 390, in load_state_dict
        raise ValueError("loaded state dict contains a parameter group "
      ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group
      ```
   - One way I've worked around this issue is to simply not load the `optimizer.pt`. I change what the `transformers` library looks for as:
      ```python
       import transformers.trainer as TrainerModule
       optimizer_path = os.path.join(peft_dir, TrainerModule.OPTIMIZER_NAME)
       TrainerModule.OPTIMIZER_NAME = f"_{TrainerModule.OPTIMIZER_NAME}"
      ```
      Consequently, all the code works as usual, and I know the trainer state is set correctly, because the training resumes only for the remainder of the steps. e.g. if I load a `checkpoint-10000` folder, it resumes from step `10001`, which I verified using the `on_train_begin` callback and checking `state.global_step`.

On manual inspection of the `trainer.optimizer.state_dict()`, I am able to see that the state is very different from what is stored at initialization, and therefore the conflict in loading.

However, after the first step of the optimizer, the `trainer.optimizer.state_dict()` looks fairly similar to the checkpoint. I believe the `AdamW` optimizer lazily creates the required state after the first gradient step. Since, the optimizer checkpoint is large, I was only able to verify the keys manually by traversing the `state_dict`. Although, by then using `torch.load` after the first gradient step (using a custom trainer callback), it still fails with the same error.

Loading the optimizer state is fairly important for continuing the training, since the moving averages affect subsequent training dynamics.

Could someone help with what is going wrong here, either in the API usage or otherwise?

### Expected behavior

The`trainer.train(resume_from_checkpoint=peft_dir)` works by loading the optimizer state as well.

**Comment by activatedgeek** [comment]
Hi @younesbelkada @pacman100, cc'ing you here again, since I did not put it in the first time (and assuming from your roles in #593). Thank you!

**Comment by activatedgeek** [comment]
I tried one other thing. It turns out just cherry-picking the pretrained config works. i.e. I selectively pick the pretrained `PeftConfig` from the checkpoint, and then create the `PeftModel` as I was doing without the checkpoint.

```python
    if peft_dir is not None:
        peft_config = PeftConfig.from_pretrained(peft_dir)
        lora_rank = peft_config.r
        lora_alpha = peft_config.lora_alpha
        lora_dropout = peft_config.lora_dropout

        if accelerator.is_main_process:
            print(f"[INFO]: Loaded PEFT config from '{peft_dir}'.")

    peft_config = LoraConfig(
        task_type=TaskType.CAUSAL_LM,
        bias="none",
        r=lora_rank,
        lora_alpha=lora_alpha,
        lora_dropout=lora_dropout,
    )
    model = get_peft_model(model, peft_config)
```

This seems to resume training without errors. In the `trainer._load_from_checkpoint` method, I see that it already loads the model adapter from checkpoint.

Could you please confirm if this is the right way to resume training correctly?

**Comment by mjsteele12** [comment]
same issue here

**Comment by activatedgeek** [comment]
I think I've figured out the cleanest solution:

```python
model = PeftModel.from_pretrained(model, peft_dir, is_trainable=True)
```

```python
trainer.train(resume_from_checkpoint=peft_dir)
```

These two lines should be enough to resume training from a checkpoint.

**Comment by mjsteele12** [comment]
@activatedgeek how are you saving your peft adapter? I tried setting to the same versions as you for every library but I am getting the same error

**Comment by activatedgeek** [comment]
I am not doing anything different to save. I use `save_steps` as usual for the checkpoints to be saved, create the base model and the LoRA adapter as above.

If you are not seeing checkpoints in your `output_dir`, perhaps you will need to reduce `save_steps`. Try `save_steps=1` for a quick check.
