### ISSUE TITLE
ImportError: cannot import name 'is_npu_available' from 'accelerate.utils'

### ISSUE THREAD

**Issue by mahbubur-87** [huggingface/peft#860]
### System Info

peft-0.5.0
accelerate-0.22.0

My kaggle code worked well before 22 Aug 2023 but from 23 Aug 2023 the import statement "from peft import PeftModel, PeftConfig" throws the following error:

_ImportError: cannot import name 'is_npu_available' from 'accelerate.utils' 
(/opt/conda/lib/python3.10/site-packages/accelerate/utils/__init__.py)_

I would request for a solution, thanks in advance.

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

!pip install accelerate
!pip install peft
!pip install transformers
!pip install -U bitsandbytes

from peft import PeftModel, PeftConfig

### Expected behavior

successful import of PeftModel, PeftConfig classes

**Comment by younesbelkada** [comment]
Hi @mahbubur-87 
Thanks for the issue, I did not managed to reproduce the issue, can you try:
```bash
!pip install -U accelerate peft transformers
```
Then import 
```python
from peft import PeftModel, PeftConfig
```

**Comment by mahbubur-87** [comment]
Hello @younesbelkada thanks for your answer, I do according to your guideline and it works.
