### ISSUE TITLE
An error in code comments (peft_model.py)

### ISSUE THREAD

**Issue by houx15** [huggingface/peft#881]
### System Info

the newest peft code in this repo

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

line 137 in `peft_model.py`:

```python
    def save_pretrained(
        self,
        save_directory: str,
        safe_serialization: bool = False,
        selected_adapters: Optional[List[str]] = None,
        **kwargs: Any,
    ):
        r"""
        This function saves the adapter model and the adapter configuration files to a directory, so that it can be
        reloaded using the [`LoraModel.from_pretrained`] class method, and also used by the [`LoraModel.push_to_hub`]
        method.
```

wrote that "reloaded using the `LoraModel.from_pretrained`"

However, the class `LoraModel` doesn't have a function named `from_pretrained()`

### Expected behavior

It should be `PeftModel.from_pretrained()`

**Comment by BenjaminBossan** [comment]
Thanks for reporting this, it is indeed an error in the docs. Same goes for `LoraModel.push_to_hub`, which should be `PeftModel.push_to_hub`. Do you want to create a PR to fix it? Otherwise, I'll do it.
