### ISSUE TITLE
How to make “Finetune_opt_bnb_peft.ipynb” distributed?

### ISSUE THREAD

**Issue by ScottishFold007** [huggingface/peft#89]
How can I make the code here distributed? Support multiple card operations on one machine?
https://github.com/huggingface/peft/blob/main/examples/int8_training/Finetune_opt_bnb_peft.ipynb

**Comment by pacman100** [comment]
cc @younesbelkada for question regarding DDP with INT8 training.
Although from use case point of view, INT8 is for low resource training on single GPUs such as  Colab.

For full scale distributed training of LLMs with PEFT, I would suggest PEFT + Accelerate's DeepSpeed ZeRO3 integration. Example script: https://github.com/huggingface/peft/blob/main/examples/conditional_generation/peft_lora_seq2seq_accelerate_ds_zero3_offload.py

**Comment by ScottishFold007** [comment]
> cc @younesbelkada for question regarding DDP with INT8 training. Although from use case point of view, INT8 is for low resource training on single GPUs such as Colab.
> 
> For full scale distributed training of LLMs with PEFT, I would suggest PEFT + Accelerate's DeepSpeed ZeRO3 integration. Example script: https://github.com/huggingface/peft/blob/main/examples/conditional_generation/peft_lora_seq2seq_accelerate_ds_zero3_offload.py

I have tried this method you mentioned, and although it can run, it is not as significant as in8 in terms of memory savings. So, see if it's possible to make int8 distributed as well and use multiple gpu's at the same time to speed up training.

**Comment by younesbelkada** [comment]
Hi @ScottishFold007 
I need to double check that, but my feeling is that it should work out of the box as the 8-bit parameters are frozen and DDP should just take care of syncronizing the weights that are inside the optimizer states. You can use `accelerate`'s `Accelerator` to prepare your models & optimizer states.
Do you have a simple handy script that you want to use for DDP?

**Comment by ScottishFold007** [comment]
I've tried the method you mentioned, but it doesn't work, the script has been sent to your email.Looking forward to your answer, thanks!

**Comment by younesbelkada** [comment]
Well received, will have a look!

**Comment by ScottishFold007** [comment]
> Well received, will have a look!

Hello! Is there any progress on this so far, please? Running int8 in multi-gpu mode via the script I emailed you

**Comment by prajdabre** [comment]
Int8 optimizer does not work with FSDP because FSDP does not know how to handle sharding of the statistics needed by 8 bit optimizers. https://github.com/TimDettmers/bitsandbytes/issues/89
