### ISSUE TITLE
Model size after fine-tuning

### ISSUE THREAD

**Issue by sergej-d** [huggingface/peft#890]
Hallo, can someone please explain the model size differences to me? When I load the Llama-2-7b-hf, which has a size of ~13.5GB, after fine-tuning with LoRa and running merge_and_unload and save_pretrained, the model size is twice as large, approximately 27GB. Is this the expected behavior?

Thanks!

Edit: Sorry, I believe I've figured it out on my own. The original model is FP16, but the fine-tuned model is unexpectedly FP32. How is this possible?

**Comment by BenjaminBossan** [comment]
Could you please paste the code you use to get this result?
