### ISSUE TITLE
transformers.Trainer with torch_compile=True errors inside peft

### ISSUE THREAD

**Issue by tmm1** [huggingface/peft#893]
### System Info

transformers              4.33.0.dev0
peft                      0.6.0.dev0
accelerate                0.22.0.dev0

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

Running HF transformers trainer with peft for lora and torch compiler, on llama2, results in:

```
  File "/home/tmm1/micromamba/envs/dev/lib/python3.10/site-
packages/torch/_dynamo/variables/builtin.py", line 931, in 
call_getattr                                               
    return obj.var_getattr(tx, name).add_options(options)    File "/home/tmm1/micromamba/envs/dev/lib/python3.10/site-
packages/torch/_dynamo/variables/nn_module.py", line 124, i
n var_getattr                                              
    subobj = inspect.getattr_static(base, name)              File "/home/tmm1/micromamba/envs/dev/lib/python3.10/inspe
ct.py", line 1769, in getattr_static                       
    raise AttributeError(attr)                             
AttributeError: config                                     
                                                           
from user code:                                               File "/mnt/ml/peft/src/peft/peft_model.py", line 918, in forward                                                   
    if self.base_model.config.model_type == "mpt":         
    
```

### Expected behavior

No error

**Comment by tmm1** [comment]
Actually this is probably a dynamo error and it should not react to AttributeError so violently?

**Comment by passaglia** [comment]
Upgrading PyTorch to 2.1.0-rc2 worked, thank you @tmm1 !

**Comment by kxzxvbk** [comment]
I'm wondering how to install PyTorch to 2.1.0-rc2. Do I have to compile from source here: https://github.com/pytorch/pytorch/archive/v2.1.0-rc2.tar.gz. Is there any binary files? For examples, if versions here work ?https://download.pytorch.org/whl/nightly/cu118

**Comment by passaglia** [comment]
hi @kxzxvbk , the pytorch release candidates are stored in the [pytorch-test](https://anaconda.org/pytorch-test/pytorch/files) conda repository. 

I then used conda to install the version I wanted:
```bash
conda install pytorch-test::pytorch=2.1.0=py3.10_cuda11.8_cudnn8.7.0_0
```

hope this helps
