### ISSUE TITLE
merged model size not right, some data not existed after use merge_and_unload

### ISSUE THREAD

**Issue by zhurui-xiaozhuzaizai** [huggingface/peft#894]
### System Info

I load the Llama-2-13b-hf, which has a size of ~26GB, 
after fine-tuning with LoRa and running merge_and_unload and save_pretrained, 
the lora is ～1.4G,  after merge_and_unload it is only 9GB 
when i use the new merged model , it tells me that many layers data not exist!!
origin layer is 40, but merged model data not existed when layer >= 14
such as:

While copying the parameter named "model.layers.24.post_attention_layernorm.weight", whose dimensions in the model are torch.Size([5120]) and whose dimensions in the checkpoint are torch.Size([5120]), an exception occurred : ('Cannot copy out of meta tensor; no data!',).

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

File "hf_decoder_model.py", line 211, in __init__
model = AutoModelForCausalLM.from_pretrained(
 File "envs/lmflow/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 491, in from_pretrained
return model_class.from_pretrained(
File "envs/lmflow/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2883, in from_pretrained
 ) = cls._load_pretrained_model(
 File "envs/lmflow/lib/python3.9/site-packages/transformers/modeling_utils.py", line 3279, in _load_pretrained_model
 raise RuntimeError(f"Error(s) in loading state_dict for {model.__class__.__name__}:\n\t{error_msg}")
RuntimeError: Error(s) in loading state_dict for LlamaForCausalLM:
 While copying the parameter named "model.layers.14.self_attn.q_proj.weight", whose dimensions in the model are torch.Size([5120, 5120]) and whose dimensions in the checkpoint are torch.Size([5120, 5120]), an exception occurred : ('Cannot copy out of meta tensor; no data!',).

### Expected behavior

No error

**Comment by BenjaminBossan** [comment]
Is it possible that you face the same issue as in #868, i.e. some weights being on meta device?
