### ISSUE TITLE
About "task-specific" prefix in Prefix tuning

### ISSUE THREAD

**Issue by dydxdt** [huggingface/peft#897]
### Feature request

Thanks for your great job.
I wonder in prefix training, the virtual tokens seem to be initialized like this:

self.prompt_tokens[adapter_name] = torch.arange(
            config.num_virtual_tokens * config.num_transformer_submodules
        ).long()

Does this corresponds to random initialization? Have you offered the "task-specific" prefix code?
Looking forward to your reply! @tmm1 @hotchpotch @kashif @srush Thanks!

### Motivation

Try to figure out the principle of prefix tuning. Thanks!

### Your contribution

Not sure.

**Comment by visionary-pony** [comment]
Does anyone know this? Does prefix tuning implementation in Hugging Face use random initialization? 
I read in the paper that :
`In particular, initializing with task relevant words such as “summarization” and “table-to-text” obtains slightly better performance than task irrelevant words such as “elephant” and “divide”, but using real words is still better than random. `

**Comment by vikram71198** [comment]
First off, HF has chosen to implement two variants of Prefix Tuning depending on the value of ```prefix_projection``` passed to ```PrefixTuningConfig```:

a. Use a ```torch.nn.Embedding()``` lookup table for the prefix tokens. Then project that into the same feature dimensionality as the input to a transformer submodule using two linear layers and a tanh in between.
b. Only use a ```torch.nn.Embedding()``` for the prefix tokens & make sure the dimensionality is already compatible with that of the input for concatenation.

If you look at the code for ```PrefixEncoder``` [here](https://github.com/huggingface/peft/blob/v0.8.2/src/peft/tuners/prefix_tuning/model.py#L57), yes, it does seem like random (well, standard Gaussian for the embedding layers atleast) for everything.

This is unlike Soft Prompt tuning, where they use some text your provide to initialize the soft prompt tokens.
