### ISSUE TITLE
LoRA/PEFT model export to ONNX fails

### ISSUE THREAD

**Issue by sh0tcall3r** [huggingface/peft#901]
Hi, I'm struggling to resolve a strange error while exporting my model to ONNX format.
A little intro: I have downloaded mt0-xxl model from huggingface in 8bit precision and finetuned it on my downstream task with LoRa/PEFT.
Now I want to convert the final model to ONNX, but it's seems that I can't.
I used save_pretrained method for saving my final model locally and then executed the command
```
model = ORTModelForSeq2SeqLM.from_pretrained(
    "mt0_peft", from_transformers=True, provider="CUDAExecutionProvide)
```
But have the following error:
`AttributeError: 'str' object has no attribute 'detach'`

Please help me to resolve that!

torch 2.0.1+cu117
optimum 1.12.0
transformers 4.32.1
bitsandbytes 0.41.1
peft 0.5.0

**Comment by J-Douglas** [comment]
Can you link the pretrained model you are trying to use?

Also, you have a small bug in your provider input. It should be `provider="CUDAExecutionProvider"`

**Comment by sh0tcall3r** [comment]
Sure, here it is: https://huggingface.co/bigscience/mt0-xxl-mt
Yeap, this is a typo in provider variable, thanks. It's correct in the notebook i'm using.

**Comment by sh0tcall3r** [comment]
Any suggestions?)

**Comment by younesbelkada** [comment]
Hi everyone, I suggest to first merge the LoRA weights into the base model then use the merged standalone transformers model to convert it to ONNX
