### ISSUE TITLE
Corrupted model when saving checkpoints

### ISSUE THREAD

**Issue by ToddMorrill** [huggingface/peft#907]
### System Info

- peft version: 0.4.0
- `transformers` version: 4.31.0
- Platform: Linux-5.15.0-1040-gcp-x86_64-with-glibc2.31
- Python version: 3.11.4
- Huggingface_hub version: 0.16.4
- Safetensors version: 0.3.2
- Accelerate version: 0.21.0
- Accelerate config:    not found
- PyTorch version (GPU?): 2.1.0.dev20230820 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: yes, FSDP

### Who can help?

@pacman100 @younesbelkada 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

This may not be trivial to reproduce but I'm wondering if there is a race condition when saving PEFT (particularly LoRA) parameters in a distributed training setup, particularly with FSDP. In particular, if you look at [this line](https://github.com/facebookresearch/llama-recipes/blob/322522e9a272c60df7c07ff738a464676ba4c086/utils/train_utils.py#L157) from the llama-recipes repo, you'll see that all workers in a distributed setup are calling `model.save_pretrained()`. So if PEFT isn't handling race conditions internally, I need to figure out how to save the LoRA weights in a multi-GPU environment with FSDP with 16 or more GPUs.

In my testing, this seems to work when there are relatively few GPUs (e.g. <10). But with say 16 GPUs, I've seen the saved `adapter_model.bin` get corrupted, which results in the following error when reading the model weights: 
`RuntimeError: PytorchStreamReader failed reading zip archive: invalid header or archive is corrupted`

I've also seen see the following type of error in `adapater_config.json`. You can see the issue with the last few lines of the JSON file:
```
  "task_type": "CAUSAL_LM"
}  "task_type": "CAUSAL_LM"
}
```
and the corresponding error message:
```
File "/opt/conda/envs/llm/lib/python3.11/site-packages/peft/utils/config.py", line 143, in from_json_file
    json_object = json.load(file)
                  ^^^^^^^^^^^^^^^
  File "/opt/conda/envs/llm/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/llm/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/llm/lib/python3.11/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 21 column 4 (char 426)
```

There's also a possibility that this has something to do with the divisibility of the parameter count by the number of workers in the FSDP setting, but seeing the JSON error makes me think this is more of a race condition in a parallel environment rather than an issue with divisibility of parameter counts or model architecture.

Here's the first time this issue appeared: https://github.com/facebookresearch/llama-recipes/issues/113

### Expected behavior

I am looking to train LoRA models in highly distributed environments and be able to successfully save and reload the parameters.

**Comment by BenjaminBossan** [comment]
I don't have experience with FSDP, but from your description, it seems very possible that a corruption could happen in those situations. In PEFT, we are agnostic with regard to the training process, so we cannot really avoid the problem you described (or at least I don't see a way). Instead, you would have to use the tools given by the training framework to ensure that at the time of saving, the model is synced and only the main process stores the model. Maybe in your case, it would be sufficient to move the `save_pretrained` call inside the `if` conditions you have above:

```python
                    if train_config.enable_fsdp:
                        if rank==0:
                            print(f"we are about to save the PEFT modules")
                            + model.save_pretrained(train_config.output_dir)
                    else:
                        print(f"we are about to save the PEFT modules")
                        + model.save_pretrained(train_config.output_dir)
                    - model.save_pretrained(train_config.output_dir)
```

**Comment by ToddMorrill** [comment]
I tried this and the code would hang. Nevertheless, thank you for confirming that there is a race condition unless properly handled and luckily, another user had a solution in the original issue: https://github.com/facebookresearch/llama-recipes/issues/113
