### ISSUE TITLE
Add Late Prompt Tuning

### ISSUE THREAD

**Issue by jackapbutler** [huggingface/peft#91]
# Overview
[Late Prompt Tuning: A Late Prompt Could Be Better Than Many Prompts](https://arxiv.org/pdf/2210.11292.pdf) has shown that prompt tuning can sometimes be more effective if the prompt generation is placed closer to the output signal in the later layers of the transformer architecture.

I think this would be a nice addition to the existing techniques in `peft`.

# Task
1. Understand [Late Prompt Tuning: A Late Prompt Could Be Better Than Many Prompts](https://arxiv.org/pdf/2210.11292.pdf)
2. Integrate the method into `peft`
3. Benchmark and test it against other methods in the repository

(happy to consider doing this issue myself if possible)

**Comment by pacman100** [comment]
Hello @jackapbutler, PR for integrating `Late Prompt Tuning` is welcome. Looking forward to it 😄.
