### ISSUE TITLE
Can't find config.json

### ISSUE THREAD

**Issue by betterfly123** [huggingface/peft#910]
### System Info

I save adapter_model.bin and adapter_config.json locally and when I reload these parameters I get an error：

Traceback (most recent call last):
  File "test.py", line 69, in <module>
    inference_model = PeftModel.from_pretrained(inference_model, save_path)
  File "/data/xxl/.conda/envs/lora/lib/python3.8/site-packages/peft/peft_model.py", line 135, in from_pretrained
    config = PEFT_TYPE_TO_CONFIG_MAPPING[PeftConfig.from_pretrained(model_id).peft_type].from_pretrained(model_id)
  File "/data/xxl/.conda/envs/lora/lib/python3.8/site-packages/peft/utils/config.py", line 101, in from_pretrained
    raise ValueError(f"Can't find config.json at '{pretrained_model_name_or_path}'")
ValueError: Can't find config.json at './sst2_lora'

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

model.save_pretrained("./sst2_lora_lora")
model_name_or_path = "./Roberta_base"
save_path = "./sst2_lora"
inference_model = AutoModelForSequenceClassification.from_pretrained(model_name_or_path)
inference_model = PeftModel.from_pretrained(inference_model, save_path)

### Expected behavior

I'd like to be able to load adapters locally rather than from hub

**Comment by BenjaminBossan** [comment]
Could you please show the content of `./sst2_lora`? Also, in the code you pasted, you save the (I presume) PEFT model to `./sst2_lora_lora`, which is a different directory.

**Comment by betterfly123** [comment]
![image](https://github.com/huggingface/peft/assets/51893117/c3720217-3cd1-4e2f-9b27-6ce8f3eca96d)
There is a small error in the code I showed above, the model storage path and read path are the same in my project

**Comment by BenjaminBossan** [comment]
Hmm, is it possible that the current code and the one used to save the model were using different versions of PEFT? Could you try updating to the latest version and see if it fixes the issue?
