### ISSUE TITLE
Shall we have enable_adapter in PeftModel attributions?

### ISSUE THREAD

**Issue by timboilermaker** [huggingface/peft#912]
### Feature request

PeftModel supports [disable_adapter](https://github.com/huggingface/peft/blob/0c9354bda98eb7f5348699e23ab752e8dca1e60e/src/peft/peft_model.py#L464), which disables the adapter modules; but I didn't see an enable_adapter func to revert this.

However, the base model implementation supports both disable_adapter_layers and enable_adapter_layers (taking [lora](https://github.com/huggingface/peft/blob/0c9354bda98eb7f5348699e23ab752e8dca1e60e/src/peft/tuners/lora/model.py) as an example); and it seems to me that enable_adapter_layers is not called by any funcs.

May I ask why PeftModel does not support enable_adapter?  Is it intended?  Thanks!

### Motivation

Try to have the flexibility to apply adapter or not.

### Your contribution

NA

**Comment by BenjaminBossan** [comment]
The `disable_adapter` function is a context manager. Within the context, adapters are disabled, but as soon as you leave it, it is enabled again. Therefore, there is no need for a separate function to enable the adapter.

**Comment by timboilermaker** [comment]
Thanks for the explanation!
