### ISSUE TITLE
Do Hyperparameter Search using Trainer API with PEFT?

### ISSUE THREAD

**Issue by VanHoang85** [huggingface/peft#914]
Hi, 
Do we have a workaround way to do a Hyperparameter Search using Trainer API as stated on here (https://huggingface.co/docs/transformers/hpo_train) with a PEFTModel? As I understand, to do hyperparameter search with Trainer, you need to define a model_init function and pass it to Trainer instead of the model itself. However, the PEFTModel requires us to have a model first before casting it to PEFTModel.

**Comment by BenjaminBossan** [comment]
I haven't worked with HF Trainer HPO, but I think something along these lines should work:

```python
def model_init(trial):
    base_model = AutoModelForXxx.from_pretrained(...)
    peft_config = ...
    model = get_peft_model(base_model, peft_config)
    return model
