### ISSUE TITLE
RuntimeError: Failed to import transformers.models.gpt_bigcode.modeling_gpt_bigcode because of the following error (look up to see its traceback): No module named 'torch._six'

### ISSUE THREAD

**Issue by Marvinmw** [huggingface/peft#917]
### System Info

deepspeed 0.8.0

```
self.tokenizer = AutoTokenizer.from_pretrained("HuggingFaceH4/starchat-alpha")
self.model = AutoModelForCausalLM.from_pretrained("HuggingFaceH4/starchat-alpha", torch_dtype=torch.float16, device_map=config.device_map )
```
I had the error 
```
RuntimeError: Failed to import transformers.models.gpt_bigcode.modeling_gpt_bigcode because of the following error (look up to see its traceback):
No module named 'torch._six'
```

After I upgrade deepspeed, everything is fine. Could we upgrade deep speed supported version?

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

```
self.tokenizer = AutoTokenizer.from_pretrained("HuggingFaceH4/starchat-alpha")
self.model = AutoModelForCausalLM.from_pretrained("HuggingFaceH4/starchat-alpha", torch_dtype=torch.float16, device_map=config.device_map )
```

RuntimeError: Failed to import transformers.models.gpt_bigcode.modeling_gpt_bigcode because of the following error (look up to see its traceback):
No module named 'torch._six'

### Expected behavior

After I upgrade deepspeed, everything is fine. Could we upgrade deep speed supported version?

**Comment by BenjaminBossan** [comment]
I don't think that PEFT restricts the deepspeed version in its requirements. Or do you mean this line from the README?

https://github.com/huggingface/peft/blob/f5aae1b47d19c5d3528a5580db8f48aa7fdd3431/README.md#L164

**Comment by Marvinmw** [comment]
yes.

**Comment by BenjaminBossan** [comment]
I see. If you know which is the actual minimum required version for deepspeed, please let me know or feel free to open a PR.

**Comment by Marvinmw** [comment]
Thanks
