### ISSUE TITLE
chatGLM-6b prefix-tuning The size of tensor a (194) must match the size of tensor b (321) at non-singleton dimension 2

### ISSUE THREAD

**Issue by sxl1993** [huggingface/peft#919]
### System Info

peft: 0.5.0
transformers: 4.31.0

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

peft/peft_model.py: 383
get_prompt() 

`past_key_values = past_key_values.permute([2, 0, 3, 1, 4]).split(
                peft_config.num_transformer_submodules * 2
            )` is error

this correct is 
`past_key_values = past_key_values.permute([2, 1, 0, 3, 4]).split(
                peft_config.num_transformer_submodules * 2
            )`

ref: [https://huggingface.co/THUDM/chatglm-6b/blob/main/modeling_chatglm.py](url) :879

### Expected behavior

please fix this issue

**Comment by BenjaminBossan** [comment]
Thanks for bringing this to our notice. Maybe @pacman100 can comment on it?

The link you provided did not work for me, so here it is again:

https://huggingface.co/THUDM/chatglm-6b/blob/8b7d33596d18c5e83e2da052d05ca4db02e60620/modeling_chatglm.py#L879

**Comment by sxl1993** [comment]
@pacman100

**Comment by vikram71198** [comment]
@pacman100 @BenjaminBossan has this issue been fixed? I'm facing the same issue currently & so are other users.

**Comment by BenjaminBossan** [comment]
If you change the permutation order as suggested above, does this resolve the issue for you? I just want to be sure that this is the core issue.
