### ISSUE TITLE
Degree of Cooperation with Adapter Hub?

### ISSUE THREAD

**Issue by xloem** [huggingface/peft#92]
Was [Adapter Hub](https://adapterhub.ml/) involved in this work? I know they put so much energy in to implement something similar and tried to contribute their work back to you all. I just found your exciting blog post and was surprised to not see this mentioned.

**Comment by pacman100** [comment]
Hello, this work was independent and done from the ground up with no collaboration from Adapterhub.

With respect to co-existence with Adapterhub: We are focusing on a subset of performant PEFT methods driven by use cases that users want, e.g., tuning large LLMs on low resource hardware while being seamlessly integrated out of the box with 🤗 ecosystem of Transformers, Accelerate and Hub.

**Comment by xloem** [comment]
Thank you.

AdapterHub’s adapter-transformers work meets the exact same goal. I imagine you both would enjoy working together.

**Comment by calpt** [comment]
Hey, one of the maintainers of AdapterHub here (just accidentally came across this issue).
Great to see all the recent developments at Hugging Face in embracing adapter/ PEFT methods and building this library. I think this helps giving adapters/ PEFT a lot more visibility in the community.

While there has been no cooperation between our team and the team here so far, we're happy to exchange ideas and collaborate in the future if there's interest in this 🙂
