### ISSUE TITLE
AdaLoRA runtime error: TypeError: eye() missing 1 required positional arguments: "n"

### ISSUE THREAD

**Issue by xinghaixu** [huggingface/peft#927]
### System Info

I used peft==0.4.0 to perform adalora finetuning. But I keep getting below error.

![image](https://github.com/huggingface/peft/assets/21352017/d2f15802-e86a-4112-a34e-d8e4ce8d3a32)

How to fix it？

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

    for epoch in range(args.num_train_epochs):
        model.train()
        for step, batch in tqdm(enumerate(train_dataloader), total=len(train_dataloader), unit="batch"):
            batch = {k: v.to(device) for k, v in batch.items()}
            outputs = model(**batch, use_cache=False)     # here, error
            loss = outputs.loss
            tr_loss += loss.item()
            model.backward(loss)

### Expected behavior

TypeError: eye() missing 1 required positional arguments: "n"

debug信息：
para_cov = tensor(0., device='cuda:1', dtype=torch.float16, grad_fn=<DotBackward0>)
n = 'transformer.encoder.layers.0.self_attention.query_key_value.lora_A.defau…

**Comment by younesbelkada** [comment]
Hi @xinghaixu 
Can you try with PEFT == 0.5.0 and let us know if the issue still persists?

```bash
pip install -U peft
```

**Comment by xinghaixu** [comment]
@younesbelkada  update PEFT == 0.5.0 , same error
<img width="807" alt="image" src="https://github.com/huggingface/peft/assets/21352017/5d332e6b-0167-4035-95dc-d3d1feb2f836">

<img width="342" alt="image" src="https://github.com/huggingface/peft/assets/21352017/a2c88196-58e3-49b3-9114-fee9ffe2760c">

**Comment by BenjaminBossan** [comment]
I think this means that `para_cov` is an empty tensor (i.e. `Size([])`), which should only happen if the `model` has empty AdaLora parameters. Could you please check if you have any empty parameters in your model?
