### ISSUE TITLE
Dtype error while doing qlora training with gptq quantized model.

### ISSUE THREAD

**Issue by monksgoyal** [huggingface/peft#929]
### System Info

A10 GPU Server

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

While doing qlora training with GPTQ quantized model using peft, getting below error:
TypeError: nn.Module.to only accepts floating point or complex dtypes, but got desired dtype=torch.int32

I understand that model in itself in 4 bit so is that an issue? but is this expected? cannot we do further tuning of GPTQ models?

`
pretrained_model_name_or_path = "4bit/Qwen-VL-Chat-Int4"
config = AutoConfig.from_pretrained(
    pretrained_model_name_or_path,
    trust_remote_code=True,
)
model = AutoModelForCausalLM.from_pretrained(pretrained_model_name_or_path,
                                             config=config,
                                                trust_remote_code=True,
                                                device_map="auto",
                                                quantization_config= GPTQConfig(bits=4, disable_exllama=True)

modules = ["c_attn", "attn.c_proj", "w1", "w2"]

config = LoraConfig(
r=16,
lora_alpha=32,
target_modules=modules,
lora_dropout=0.05,
bias="none",
task_type="CAUSAL_LM",
modules_to_save=["wte", "lm_head"]
)

model = prepare_model_for_kbit_training(model, use_gradient_checkpointing=gradient_checkpointing)
model = get_peft_model(model, config)
`

### Expected behavior

Training should not cause any error

**Comment by younesbelkada** [comment]
Hi @monksgoyal 
Thanks for the issue, this should be fixed with https://github.com/huggingface/peft/pull/928

**Comment by younesbelkada** [comment]
Closing as should be fixed with #928
