### ISSUE TITLE
Add `base_model` metadata to the automatically generated model card 

### ISSUE THREAD

**Issue by davanstrien** [huggingface/peft#938]
### Feature request

Currently, the `base_model` information is stored in the config for the model when pushing to the hub e.g. https://huggingface.co/Sudhee1997/Llama-2-7b-Custom-Recruit/blob/e9ddbc5e8f4d41b1bbbd65ce16d1ece78b3f5125/config.json#L3. It would be nice if this could also be exposed in the YAML of the README metadata i.e. https://huggingface.co/kensvin/emotion_classification/blob/5f71a143a0639e4286dc5c2d01cc965a8a69f2b3/README.md?code=true#L3. 

I can make PRs for existing models to add this metadata see internal slack [thread](https://huggingface.slack.com/archives/C01BWJU0YKW/p1687766681122359) but it would be cool to add this information upfront for new models shared to the Hub. 

### Motivation

Improve the quality of metadata on the hub. This `base_model` info also gives quite a bit of extra visibility into how models are being used e.g. which models are being fine-tuned most often. 

### Your contribution

I am happy to make a PR for this if it is helpful.

**Comment by julien-c** [comment]
maybe point to the existing `transformers` implementation of that feature for reference?

**Comment by davanstrien** [comment]
Adding link to `transformers` implementation of this https://github.com/huggingface/transformers/blob/bc7ce1808f6c30df87fd9dff871a53ef510ccf77/src/transformers/modelcard.py#L463. From taking a quick look at PEFT I think the relevant function to update on the PEFT side would be `create_or_update_model_card`:  https://github.com/huggingface/peft/blob/6b4554e6437a372177d16a7800df8cfd03fbd16f/src/peft/peft_model.py#L648

**Comment by BenjaminBossan** [comment]
Sounds good to me. We just need to keep in mind that the base model does not necessarily have to be a transformers model.

**Comment by davanstrien** [comment]
> Sounds good to me. We just need to keep in mind that the base model does not necessarily have to be a transformers model.

Some potential way of trying to reduce the number of these

- Perform a regex check to see if the `base_model` matches potential hub IDs i.e. max one `/` character. This would remove a fair few examples where the `base_model` would point to a local path. 
- Add a function `is_valid_hub_id`, before adding a `base_model` to the model card. This could pass the `base_model` ID to the Hub API and check for a valid response. This would require an API call so might be less desirable.
