### ISSUE TITLE
[Feature] Add support for LongT5 and LongFormer

### ISSUE THREAD

**Issue by jordancole21** [huggingface/peft#94]
Before the feature request I just wanted to say great work on this library everyone, I've been looking forward to the release of this for a while now! 

I just wanted to hop in to ask, if there are any plans to support fine-tuning of models with large context windows like LongT5, Pegasus X, and LongFormer?

Or is it just a matter of using PEFT with those models? If so would it be possible to add that example in the examples folder?

Great job and thanks so much again for releasing this!

**Comment by pacman100** [comment]
Hello @jordancole21, yes, it is a matter if using PEFT with those models. I'll add an example in the next couple weeks, thank you for your kind words and happy that you like the library! Alternately, feel free to open PR if you have gotten PEFT to work with long range Transformer models.
