### ISSUE TITLE
The Gradio Space demo in the diffusion section is closed.

### ISSUE THREAD

**Issue by Inkyl** [huggingface/peft#942]
### System Info

This peft is simply an amazing project and has been a huge help in fine-tuning my stablediffusion.
But when I wanted to access the Gradio Space in the fine-tuning diffusion method, I found that the space  was closed.
Do you plan to open up this part of the content in the future? I wish you a happy life, thank you.
> Try out the 🤗 Gradio Space which should run seamlessly on a T4 instance: [smangrul/peft-lora-sd-dreambooth](https://huggingface.co/spaces/smangrul/peft-lora-sd-dreambooth).

### Who can help?

 @stevhliu

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

none

### Expected behavior

Reopen Gradio Space.

**Comment by BenjaminBossan** [comment]
It seems like @pacman100 has paused the space. Did you try cloning the space and running it on your own?

**Comment by Inkyl** [comment]
> It seems like @pacman100 has paused the space. Did you try cloning the space and running it on your own?

Thank you so much for your advice! This problem has been bothering me all day. While I'm new to Computer Vision and not very familiar with HuggingFace's space functionality, your suggestion helped me resolve it. Can I open a pull request to add this solution to the readme for other beginners?

**Comment by BenjaminBossan** [comment]
Glad that it worked for you. If you want, you can create a PR to update the README.
