### ISSUE TITLE
i^3A with llama and hit errors

### ISSUE THREAD

**Issue by ChaoGaoUCR** [huggingface/peft#950]
Dear Authors,

Thanks for this great project.
I was trying to fine-tune with different peft algorithms, everything works fine until I use IA^3.
Here is the code I use for model setting and trainer arguments.
![image](https://github.com/huggingface/peft/assets/86901408/75ce5a37-d7bb-4e92-849f-f5031a75b5ff)
![image](https://github.com/huggingface/peft/assets/86901408/8136a0d1-4056-418e-9426-d1d2c8595658)
And here are the error messages I received
![image](https://github.com/huggingface/peft/assets/86901408/c438ba5f-72f8-4078-8513-d5a065a86c1d)
I wondered if there are any hints on how should I resolve this.

Thanks
Chao

**Comment by SumanthRH** [comment]
Hello,

Looking at the traceback, the error seems to be in the dataloading stage. Are you sure your dataset preprocessing is correct?  Each column in your dataset should have values that are integers or integer sequences. Make sure to remove columns that are not needed (You can also get this error if you have a column with strings, for example).

**Comment by ChaoGaoUCR** [comment]
Thank you for your reply.
I was switching the (IA)^3 config and LoRA config
The LoRA config runs perfectly fine, but the (IA)^3 not working...
![image](https://github.com/huggingface/peft/assets/86901408/a0fdc0c9-1e92-4860-9a81-394138322157)
I will try to debug the data loading part

**Comment by SumanthRH** [comment]
Hi @ChaoGaoUCR , the dataloading fix resolved the issue I believe?
