### ISSUE TITLE
How can I turn off wandb training?

### ISSUE THREAD

**Issue by nameless0704** [huggingface/peft#955]
I want to train the model offline but wandb needs network.

**Comment by BenjaminBossan** [comment]
There is nothing in PEFT that requires wandb. This must come from something else in your code.

**Comment by SauravMaheshkar** [comment]
> > I want to train the model offline but wandb needs network.
> 
> @nameless0704 Can you share more details about your environment ? `wandb` shouldn't be required by default.
> 
> Nevertheless a simple fix can be to run `wandb offline` before running your script, which will store the metadata locally.

Did this help @nameless0704 ?

**Comment by nameless0704** [comment]
Sorry, I didn't respond. I end up installed wandb and set
`os.environ["WANDB_DISABLED"]='true'` and `wandb.disabled=True` then it works fine w/o wandb.

But is there a way not install wandb at all?
