### ISSUE TITLE
Cannot make several adapters active through PeftModel interface

### ISSUE THREAD

**Issue by kovalexal** [huggingface/peft#967]
### System Info

Full environment could be reproduced with provided [Dockerfile](https://github.com/huggingface/peft/blob/69665f24e98dc5f20a430637a31f196158b6e0da/docker/peft-gpu/Dockerfile). I used peft from main branch.

### Who can help?

@pacman100 @younesbelkada @BenjaminBossan

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

https://colab.research.google.com/drive/1Re3n9Tbi5-CVVidiMVV7CNWCAk89TZsy?usp=share_link

### Expected behavior

Hi!

I am not sure, whether the interface for enabling multiple adapters during inference is still under construction, but I've tried to use it and found out that it does not work as expected.

I left some comments in the colab notebook code to demonstrate what I faced with.

**Comment by BenjaminBossan** [comment]
@younesbelkada

**Comment by BenjaminBossan** [comment]
This issue is still relevant, we have yet to implement this and document it properly. It shouldn't be too hard, the main challenge is that not all methods allow to set multiple active adapters.

**Comment by BenjaminBossan** [comment]
This will be supported via #1069 but I'll probably spin it off into a separate PR (since the base-layer refactor of that PR is merged now).
