### ISSUE TITLE
Wrong file read in test_save_pretrained_selected_adapters

### ISSUE THREAD

**Issue by dzonesasaki** [huggingface/peft#968]
Another adapter file is loaded on this line.

https://github.com/huggingface/peft/blob/634bd197f211c8c5cbbcc9f85e98856a1e3a9d24/tests/testing_common.py#L308C11-L308C75

Should the following be changed?
```
model_from_pretrained.load_adapter(tmp_dirname+"/new_adapter", "new_adapter")
```

**Comment by BenjaminBossan** [comment]
Thanks for reporting the issue in the test. There is a PR for this now (#969).

**Comment by dzonesasaki** [comment]
Thank you very much too.
