### ISSUE TITLE
Adding LoRA adapters gets slower and slower with more adapters

### ISSUE THREAD

**Issue by BenjaminBossan** [huggingface/peft#981]
### System Info

Tested on current PEFT `main`, but problem persists for some time now.

### Information

- [ ] The official example scripts
- [x] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [x] My own task or dataset (give details below)

### Reproduction

This is a follow up from the discussion [here](https://github.com/huggingface/peft/issues/957#issuecomment-1734546320).

Loading more and more LoRA adapters becomes slower and slower. Here is a script to reproduce:

```python
import time
from contextlib import contextmanager
import peft
from transformers import AutoModelForCausalLM

model = AutoModelForCausalLM.from_pretrained("facebook/opt-125m")
config = peft.LoraConfig(peft_type=peft.TaskType.CAUSAL_LM, init_lora_weights=False)
peft_model = peft.get_peft_model(model, config)
path = "./notebooks/save/issue-957"
peft_model.save_pretrained(path)
model = AutoModelForCausalLM.from_pretrained("facebook/opt-125m")

@contextmanager
def timed(msg):
    start = time.perf_counter()
    yield
    end = time.perf_counter()
    print(f"{msg} took {1000 * (end - start):.2f} ms")

with timed("loading 1st adapter (initial load)"):
    peft_model = peft.PeftModel.from_pretrained(model, path)

for i in range(2, 51):
    with timed(f"loading {i}th adapter"):
        peft_model.load_adapter(path, adapter_name=f"adapter-{i}")
```

Results on my machine:

```
loading 1st adapter (initial load) took 901.32 ms
loading 2th adapter took 23.20 ms
loading 3th adapter took 22.93 ms
loading 4th adapter took 24.31 ms
loading 5th adapter took 27.34 ms
loading 6th adapter took 26.87 ms
loading 7th adapter took 27.84 ms
loading 8th adapter took 29.23 ms
loading 9th adapter took 30.64 ms
loading 10th adapter took 32.42 ms
loading 11th adapter took 33.60 ms
loading 12th adapter took 35.04 ms
loading 13th adapter took 38.28 ms
loading 14th adapter took 37.69 ms
loading 15th adapter took 38.84 ms
loading 16th adapter took 40.55 ms
loading 17th adapter took 43.78 ms
loading 18th adapter took 42.86 ms
loading 19th adapter took 44.24 ms
loading 20th adapter took 45.83 ms
loading 21th adapter took 46.82 ms
loading 22th adapter took 49.40 ms
loading 23th adapter took 120.13 ms
loading 24th adapter took 58.81 ms
loading 25th adapter took 57.50 ms
loading 26th adapter took 58.75 ms
loading 27th adapter took 58.31 ms
loading 28th adapter took 60.10 ms
loading 29th adapter took 61.20 ms
loading 30th adapter took 61.46 ms
loading 31th adapter took 63.55 ms
loading 32th adapter took 64.52 ms
loading 33th adapter took 66.29 ms
loading 34th adapter took 66.28 ms
loading 35th adapter took 69.04 ms
loading 36th adapter took 69.59 ms
loading 37th adapter took 71.61 ms
loading 38th adapter took 72.38 ms
loading 39th adapter took 74.41 ms
loading 40th adapter took 75.09 ms
loading 41th adapter took 79.09 ms
loading 42th adapter took 79.20 ms
loading 43th adapter took 79.83 ms
loading 44th adapter took 81.26 ms
loading 45th adapter took 82.92 ms
loading 46th adapter took 83.29 ms
loading 47th adapter took 85.25 ms
loading 48th adapter took 86.69 ms
loading 49th adapter took 87.14 ms
loading 50th adapter took 92.14 ms
```

We can see a steady increase from ~23ms for the 2nd adapter to ~90ms for the 50th.

Note that there is a spike for adapter 23. This is reproducible! Not sure what happens there, if someone else could try the script, that would be nice.

I could track down the source of the slowdown to the `update_layer` method: https://github.com/huggingface/peft/blob/52ff0cde9f2cc64059e171c2cfd94512914c85df/src/peft/tuners/lora/layer.py#L62-L88

When I comment out all the lines that add to the `nn.ModuleDict`s, the slowdown vanishes completely. Similarly, when I replace all instances of `self.module_dict[adapter_name] = ...` with `self.foo = ...` (i.e. still creating and assigning the new modules but not using `nn.ModuleDict`), the slowdown also vanishes.

Therefore, I thought it could be an issue with `nn.ModuleDict`. However, it is not generally true that `nn.ModuleDict` slows down over time, as this script demonstrates:

```python
import torch
from torch import nn
import time
from contextlib import contextmanager

@contextmanager
def timed(msg):
    start = time.perf_counter()
    yield
    end = time.perf_counter()
    print(f"{msg} took {1000 * (end - start):.2f} ms")

class MyModule(nn.Module):
    def __init__(self):
        super().__init__()
        self.md = nn.ModuleDict()

    def update(self, name):
        self.md[name] = nn.Linear(2000, 2000)

mod = MyModule()
for i in range(1, 101):
    with timed(f"adding adapter {i}"):
        mod.update(f"adapter-{i}")
```

Here the timing remained stable:

```
adding adapter 1 took 31.17 ms
adding adapter 2 took 25.76 ms
adding adapter 3 took 25.42 ms
adding adapter 4 took 26.11 ms
adding adapter 5 took 29.27 ms
adding adapter 6 took 25.33 ms
adding adapter 7 took 28.58 ms
adding adapter 8 took 26.11 ms
adding adapter 9 took 27.66 ms
adding adapter 10 took 26.77 ms
...
adding adapter 90 took 27.02 ms
adding adapter 91 took 25.19 ms
adding adapter 92 took 25.86 ms
adding adapter 93 took 26.84 ms
adding adapter 94 took 25.05 ms
adding adapter 95 took 25.03 ms
adding adapter 96 took 26.14 ms
adding adapter 97 took 25.64 ms
adding adapter 98 took 26.30 ms
adding adapter 99 took 25.10 ms
adding adapter 100 took 26.99 ms
```

So the slowdown must somehow relate to the way we use `nn.ModuleDict` in PEFT.

### Expected behavior

Adding more and more adapters should not lead to such a strong slowdown.

**Comment by ChrisHayduk** [comment]
@BenjaminBossan I would guess it's in set_adapter:

`def set_adapter(self, adapter_names: str | list[str]):
        """Set the active adapter

        Args:
            adapter_name (str): The name of the adapter to set as active
        """
        if isinstance(adapter_names, str):
            adapter_names = [adapter_names]

        # Deactivate grads on the inactive adapter and activate grads on the active adapter
        for layer_name in self.adapter_layer_names:
            module_dict = getattr(self, layer_name)
            for key, layer in module_dict.items():
                if key in adapter_names:
                    # Note: It is possible that not a single layer is called with requires_grad_(True) here. This may
                    # happen if a completely different adapter layer is being activated.
                    layer.requires_grad_(True)
                else:
                    layer.requires_grad_(False)

        self._active_adapter = adapter_names`

Since set_adapter always loops through all of the ModuleDicts and we add new entries for each adapter name, the lenght of the loop in set_adapter will grow as we add more and more adapters. I will test with overwriting the same adapter name to confirm.

**Comment by ChrisHayduk** [comment]
@BenjaminBossan I was able to confirm that the growing size of the ModuleDicts is causing this behavior:

With different adapter names (making the ModuleDicts grow in size):
`loading 1st adapter (initial load) took 4758.99 ms
loading 2th adapter took 28.62 ms
loading 3th adapter took 30.26 ms
loading 4th adapter took 31.11 ms
loading 5th adapter took 32.49 ms
loading 6th adapter took 32.52 ms
loading 7th adapter took 41.41 ms
loading 8th adapter took 38.13 ms
loading 9th adapter took 36.57 ms
loading 10th adapter took 41.38 ms
loading 11th adapter took 95.65 ms
loading 12th adapter took 174.25 ms
loading 13th adapter took 107.95 ms
loading 14th adapter took 82.94 ms
loading 15th adapter took 84.68 ms
loading 16th adapter took 96.36 ms
loading 17th adapter took 89.34 ms
loading 18th adapter took 93.44 ms
loading 19th adapter took 99.01 ms
loading 20th adapter took 95.76 ms
loading 21th adapter took 126.43 ms
loading 22th adapter took 109.35 ms
loading 23th adapter took 121.40 ms
loading 24th adapter took 127.43 ms
loading 25th adapter took 149.49 ms
loading 26th adapter took 241.02 ms
loading 27th adapter took 245.36 ms
loading 28th adapter took 257.20 ms
loading 29th adapter took 249.96 ms
loading 30th adapter took 270.35 ms
loading 31th adapter took 269.33 ms
loading 32th adapter took 267.03 ms
loading 33th adapter took 365.87 ms
loading 34th adapter took 296.07 ms
loading 35th adapter took 303.29 ms
loading 36th adapter took 821.84 ms
loading 37th adapter took 352.70 ms
loading 38th adapter took 281.58 ms
loading 39th adapter took 157.82 ms
loading 40th adapter took 167.62 ms
loading 41th adapter took 183.42 ms
loading 42th adapter took 183.61 ms
loading 43th adapter took 176.42 ms
loading 44th adapter took 193.20 ms
loading 45th adapter took 331.52 ms
loading 46th adapter took 151.81 ms
loading 47th adapter took 105.48 ms
loading 48th adapter took 102.72 ms
loading 49th adapter took 111.77 ms
loading 50th adapter took 191.02 ms`

With same adapter name (making the ModuleDicts not grow in size):
`loading 1st adapter (initial load) took 210.32 ms
loading 2th adapter took 32.75 ms
loading 3th adapter took 10.90 ms
loading 4th adapter took 11.05 ms
loading 5th adapter took 10.76 ms
loading 6th adapter took 10.67 ms
loading 7th adapter took 10.69 ms
loading 8th adapter took 10.88 ms
loading 9th adapter took 10.81 ms
loading 10th adapter took 10.69 ms
loading 11th adapter took 10.95 ms
loading 12th adapter took 24.85 ms
loading 13th adapter took 10.76 ms
loading 14th adapter took 10.83 ms
loading 15th adapter took 10.77 ms
loading 16th adapter took 11.03 ms
loading 17th adapter took 14.52 ms
loading 18th adapter took 15.00 ms
loading 19th adapter took 16.06 ms
loading 20th adapter took 16.93 ms
loading 21th adapter took 12.06 ms
loading 22th adapter took 11.20 ms
loading 23th adapter took 14.10 ms
loading 24th adapter took 11.82 ms
loading 25th adapter took 11.05 ms
loading 26th adapter took 12.52 ms
loading 27th adapter took 14.48 ms
loading 28th adapter took 13.23 ms
loading 29th adapter took 14.80 ms
loading 30th adapter took 12.42 ms
loading 31th adapter took 12.81 ms
loading 32th adapter took 15.39 ms
loading 33th adapter took 17.49 ms
loading 34th adapter took 12.55 ms
loading 35th adapter took 13.23 ms
loading 36th adapter took 12.41 ms
loading 37th adapter took 16.22 ms
loading 38th adapter took 16.03 ms
loading 39th adapter took 16.57 ms
loading 40th adapter took 13.40 ms
loading 41th adapter took 13.08 ms
loading 42th adapter took 13.64 ms
loading 43th adapter took 13.01 ms
loading 44th adapter took 15.55 ms
loading 45th adapter took 12.51 ms
loading 46th adapter took 12.49 ms
loading 47th adapter took 16.18 ms
loading 48th adapter took 12.73 ms
loading 49th adapter took 13.27 ms
loading 50th adapter took 14.31 ms`

**Comment by BenjaminBossan** [comment]
Thanks for investigating. However, changing `set_adapter` to immediately `return` did not solve the problem:

```
loading 1st adapter (initial load) took 27.32 ms
loading 2th adapter took 24.29 ms
loading 3th adapter took 25.84 ms
loading 4th adapter took 26.57 ms
loading 5th adapter took 27.79 ms
loading 6th adapter took 29.52 ms
loading 7th adapter took 30.49 ms
loading 8th adapter took 32.14 ms
loading 9th adapter took 32.00 ms
loading 10th adapter took 33.70 ms
loading 11th adapter took 35.67 ms
loading 12th adapter took 38.27 ms
loading 13th adapter took 39.14 ms
loading 14th adapter took 41.18 ms
loading 15th adapter took 41.32 ms
loading 16th adapter took 43.10 ms
loading 17th adapter took 44.65 ms
loading 18th adapter took 44.22 ms
loading 19th adapter took 46.11 ms
loading 20th adapter took 48.18 ms
loading 21th adapter took 47.43 ms
loading 22th adapter took 122.29 ms
loading 23th adapter took 49.90 ms
loading 24th adapter took 51.39 ms
loading 25th adapter took 53.85 ms
loading 26th adapter took 54.60 ms
loading 27th adapter took 54.88 ms
loading 28th adapter took 55.60 ms
loading 29th adapter took 57.85 ms
loading 30th adapter took 58.24 ms
loading 31th adapter took 61.09 ms
loading 32th adapter took 64.17 ms
loading 33th adapter took 65.37 ms
loading 34th adapter took 68.28 ms
loading 35th adapter took 69.74 ms
loading 36th adapter took 70.15 ms
loading 37th adapter took 68.17 ms
loading 38th adapter took 70.06 ms
loading 39th adapter took 72.41 ms
loading 40th adapter took 76.22 ms
loading 41th adapter took 75.64 ms
loading 42th adapter took 77.57 ms
loading 43th adapter took 76.92 ms
loading 44th adapter took 78.52 ms
loading 45th adapter took 81.19 ms
loading 46th adapter took 85.80 ms
loading 47th adapter took 88.20 ms
loading 48th adapter took 86.47 ms
loading 49th adapter took 87.51 ms
loading 50th adapter took 88.61 ms

```
