### ISSUE TITLE
QaLora

### ISSUE THREAD

**Issue by thistleknot** [huggingface/peft#986]
### Feature request

This came out
https://github.com/yuhuixu1993/qa-lora/blob/main/qalora.py

would like to use it with transformers

btw, I also got mezo integrated with transformers.  Maybe we can swap notes to get that integrated.

### Motivation

more efficient

### Your contribution

I'll test, contribute code if necessary

**Comment by BenjaminBossan** [comment]
Yes, this is something we surely want to integrate into PEFT. The linked repo already uses PEFT, so hopefully this should not be too difficult to add. Let us know if you want to work on adding the feature.

Also, feel free to share your notes on MeZO, though I assume this is for the transformers `Trainer`, so please share them with the transformers folks.

**Comment by thistleknot** [comment]
mezo:
https://github.com/thistleknot/TrainLLMv3/blob/main/functions.py#L1284

transformers suggested I submit mezo here
https://github.com/huggingface/transformers/issues/24264

**Comment by datavistics** [comment]
Id definitely be interested in this. It seems just as promising as LoftQ if not better.

**Comment by gapsong** [comment]
Does someone have an update on that one?

**Comment by gapsong** [comment]
Here is the PR for QA-Lora with GPTQ:

https://github.com/huggingface/peft/pull/2571

**Comment by thistleknot** [comment]
Omg

**Comment by thistleknot** [comment]
thank you!

now training with qa-lora =D
