### ISSUE TITLE
the test of get_peft_model_state_dict

### ISSUE THREAD

**Issue by dzonesasaki** [huggingface/peft#988]
I have concerns about this changes of a test script.
https://github.com/huggingface/peft/blob/52ff0cde9f2cc64059e171c2cfd94512914c85df/tests/testing_common.py#L334

The `get_peft_model_state_dict` was only tested under particular conditions.
I think `get_peft_model_state_dict` needs to be changeed like https://github.com/huggingface/peft/pull/931 in order to pass the test under any conditions.

This line:
https://github.com/huggingface/peft/blob/52ff0cde9f2cc64059e171c2cfd94512914c85df/src/peft/utils/save_and_load.py#L67

to changeed like this:
```
if adapter_name in to_return.items():
    to_return = {k: v for k, v in to_return.items() if (("lora_" in k and adapter_name in k) or ("bias" in k))}
```

This issue also seem to be related to https://github.com/huggingface/peft/issues/970 .

**Comment by BenjaminBossan** [comment]
Sorry, I'm a bit confused now. So in #931 you said the issue was fixed but here you say it is not fixed after all? Could you please clarify this for me, thanks.

And as I said there, the check should be `if adapter_name in to_return.keys():`, not `if adapter_name in to_return.items():`.

**Comment by dzonesasaki** [comment]
Sorry for the confusion .It was my mistake.
I re-ran the test without the change and it passed.
I understand that you have almost fixed these issues, thank you.

However, I cannot explain why the adapter weights are missing.

1. insert this routine.

in https://github.com/huggingface/peft/blob/52ff0cde9f2cc64059e171c2cfd94512914c85df/tests/testing_common.py#L343

```python
if 'lora' in model.peft_type.lower():
    if any(k.find("new_adapter")>0 for k in model.state_dict().keys()):
        if any(k.find("new_adapter")>0 for k in get_peft_model_state_dict(model, unwrap_compiled=True).keys()) is False:
            raise ErrorForDebug
```

2. run the test

```sh
python3 -m pytest -x --pdb ./tests/test_decoder_models.py
```

3. check the keys when NameError (ErrorForDebug) was occurred.

To print in pdb
```
p model.state_dict().keys()
```

it will show this
```
:
'base_model.model.model.decoder.layers.0.self_attn.v_proj.lora_A.default.weight', 'base_model.model.model.decoder.layers.0.self_attn.v_proj.lora_A.new_adapter.weight',
:
```
To print in pdb
```
p get_peft_model_state_dict(model, unwrap_compiled=True).keys()
```

it will show this
```
:
'base_model.model.model.decoder.layers.0.self_attn.v_proj.lora_A.weight',
:
```

I think `default.weight` are replaced by `weight`. 
But `new_adapter.weight` are missing.

**Comment by dzonesasaki** [comment]
I am so Sorry. This issue was due to my misunderstanding.
And I understood that `get_peft_model_state_dict` returns single adapter weight of selected it, which is the correct behaviour.
There are still a few things I don't understand, but I'll read more about them later.
Your kindness is much appreciated.
