### ISSUE TITLE
Loading multiple adapters fails when quantized

### ISSUE THREAD

**Issue by bhperry** [huggingface/peft#990]
### System Info

```
Python                        3.9.18
accelerate                    0.22.0
peft                          0.6.0.dev0
transformers                  4.33.1
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

Wanted to load mulitple PEFT adapters onto a Llama2 base to be able to hotswap them. I have to load Llama2 quantized in order to fit it on the graphics card I'm using, and that works fine with one adapter. However as soon as I attempt to load a second adapter, I get an error about the dtype

```
from transformers import AutoModelForCausalLM

model = AutoModelForCausalLM.from_pretrained("meta-llama/Llama-2-7b-chat-hf", device_map="cuda:0", load_in_8bit=True)

# Succeeds
model.load_adapter("/path/to/adapter1", "adapter1")
# Fails
model.load_adapter("/path/to/adapter2", "adapter2")
```

Error message is:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/saturncloud/envs/saturn/lib/python3.9/site-packages/peft/peft_model.py", line 578, in load_adapter
    self.add_adapter(adapter_name, peft_config)
  File "/opt/saturncloud/envs/saturn/lib/python3.9/site-packages/peft/peft_model.py", line 527, in add_adapter
    self.base_model.inject_adapter(self, adapter_name)
  File "/opt/saturncloud/envs/saturn/lib/python3.9/site-packages/peft/tuners/tuners_utils.py", line 219, in inject_adapter
    self._create_and_replace(peft_config, adapter_name, target, target_name, parent, **optionnal_kwargs)
  File "/opt/saturncloud/envs/saturn/lib/python3.9/site-packages/peft/tuners/lora/model.py", line 199, in _create_and_replace
    target.update_layer(
  File "/opt/saturncloud/envs/saturn/lib/python3.9/site-packages/peft/tuners/lora/layer.py", line 78, in update_layer
    self.to(weight.device, dtype=weight.dtype)
  File "/opt/saturncloud/envs/saturn/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in to
    raise TypeError('nn.Module.to only accepts floating point or complex '
TypeError: nn.Module.to only accepts floating point or complex dtypes, but got desired dtype=torch.int8
```

### Expected behavior

Expected to be able to load multiple peft adapters with quantization.

**Comment by younesbelkada** [comment]
Hi @bhperry 
Thanks for the issue, I have just ran:

``python
from transformers import AutoModelForCausalLM

model = AutoModelForCausalLM.from_pretrained("hf-internal-testing/tiny-random-OPTForCausalLM", device_map="cuda:0", load_in_8bit=True)

# Succeeds
model.load_adapter("peft-internal-testing/tiny-OPTForCausalLM-lora", "adapter1")
# Fails
model.load_adapter("peft-internal-testing/tiny-OPTForCausalLM-lora", "adapter2")
```

Then I have suspected that it is somehow related to llama-2 - So I have tried:

```python
from transformers import AutoModelForCausalLM
from peft import LoraConfig

model = AutoModelForCausalLM.from_pretrained("meta-llama/Llama-2-7b-chat-hf", device_map="cuda:0", load_in_8bit=True)

lora_config = LoraConfig(r=8)

# Succeeds
# model.load_adapter("peft-internal-testing/tiny-OPTForCausalLM-lora", "adapter1")
model.add_adapter(lora_config, "adapter1")
# Fails
# model.load_adapter("peft-internal-testing/tiny-OPTForCausalLM-lora", "adapter2")
model.add_adapter(lora_config, "adapter2")
```

And both scripts seems to work fine on my end - I think your bug has been silently fixed on the latest transformers release - can you try again with `transformers==4.34.0` ?

**Comment by bhperry** [comment]
Transformers 4.34.0 didn't do it on its own, but after also re-installing peft from source it works. Thanks!

**Comment by younesbelkada** [comment]
Thanks a lot for double checking!
